efeone/beams

beams/beams/doctype/item_type/item_type.js
beams/beams/doctype/item_type/item_type.json
beams/beams/doctype/item_type/item_type.py
beams/beams/doctype/item_type/test_item_type.py

-Create Doctype Item Type.
-Created Doctype Item Type.
-No

feat: create Doctype Item Type

---

beams/beams/doctype/bureau/bureau.js
beams/beams/doctype/bureau/bureau.json
beams/beams/doctype/bureau/bureau.py
beams/beams/doctype/bureau/test_bureau.py

-Create Doctype Bureau.
Created Doctype Bureau.
-No

feat: Create Doctype Bureau

---

beams/beams/doctype/adhoc_budget/adhoc_budget.json
beams/fixtures/workflow.json
beams/fixtures/workflow_action_master.json
beams/fixtures/workflow_state.json
beams/hooks.py

- Fix
- Changed the state and action performed
[Screencast from 21-08-24 10:28:35 AM IST.webm](https://github.com/user-attachments/assets/e4817d34-849e-414c-ada8-84d04aece083)
- Adhoc Budget
- New Data

fix : Rework on Workflow Adhoc Budget

---

beams/beams/doctype/adhoc_budget/adhoc_budget.py

-Create a Budget On the Approval of Adhoc Budget.
-Automatically Created budget On the Approval of Adhoc Budget.
-No

feat: Create a Budget On the Approval of the Adhoc Budget

---

beams/beams/doctype/beams_accounts_settings/beams_accounts_settings.json
beams/beams/doctype/driver_batta_claim/driver_batta_claim.js
beams/beams/doctype/driver_batta_claim/driver_batta_claim.json
beams/beams/doctype/driver_batta_claim/driver_batta_claim.py
beams/beams/doctype/driver_batta_claim/test_driver_batta_claim.py
beams/beams/doctype/work_details/work_details.json
beams/beams/doctype/work_details/work_details.py

- Feature
-This feature introduces validation and calculation functionality for the Driver Batta Claim doctype and its child table Work Details. 
-It ensures that date ranges do not overlap and calculates total hours, overtime hours, and batta values, updating totals on the form accordingly.
-A new doctype named Driver Batta Claim was created, including a child table called Work Details. 
-The solution then added event handlers and functions to validate date ranges, calculate total hours, and update batta values.
-New Feature
- New Data

feat:Create doctype Driver Batta Claim.

---

beams/beams/doctype/date/date.json
beams/beams/doctype/date/date.py
beams/beams/doctype/stringer_bill/stringer_bill.js
beams/beams/doctype/stringer_bill/stringer_bill.json
beams/beams/doctype/stringer_bill/stringer_bill.py
beams/beams/doctype/stringer_bill/test_stringer_bill.py
beams/setup.py

Create doctype Stringer Bill.Add a new child table Date to this doctype.Calculate number of days and Total wages from childtable.
Add a new field to Employee doctype.
Created the Doctype Stringer Bill and Child Table Date and Added New Field in the  Employee  also
Calculated  the No of days from the Date Child Table and Calculated the Total Wage from the Daily Wage and No of Days
and Validated the Duplicate Date .
-New Feature
-No

feat: Created Doctype Stringer Bill and child Doctype Date

---

beams/beams/doctype/adhoc_budget/adhoc_budget.py

-Update Budget Creation From Adhoc Budget
-Updated Budget creaton From Adhoc Budget
-No
-Mozilla

fix: Update Creation Of Budget From Adhoc Budget

---

beams/beams/doctype/stringer_bill/stringer_bill.py

Create  Purchase Invoice on Approval of Stringer Bill.Purchase invoice must be created against the Supplier given in Stringer Bill.
On approval of Stringer Bill a Purchase Invoice is now created against the supplier and also the items child table is populated with Item fetched from Stringer Type doctype.
-No

feat:Created Purchase Invoice on Approval of Stringer Bill.

---

beams/beams/doctype/adhoc_budget/adhoc_budget.js

- Add intro message update on form load and refresh to ensure visibility after save.
- Added intro message update on form load and refresh to ensure visibility after save.
-No
-Mozilla

fix: Ensure intro message persists after save and optimize field updates

---

beams/beams/workspace/beams/beams.json

Change doc-type Batta Claim instead of Driver Batta Claim in workspace beams
Changed doc-type Batta Claim in workspace

fix : Added doctype Batta claim instead of Driver Batta Claim

---

beams/beams/custom_scripts/purchase_order/purchase_order.py
beams/beams/overrides/budget.py
beams/beams/workspace/beams/beams.json
beams/hooks.py
beams/setup.py

Budget Exceed button should automatically check in purchase order and material request when the total amount exceed the corresponding budget of the same account and cost centre or project
Budget Exceed button is automatically checked in purchase order and material request when the total amount exceed the corresponding budget of the same account and cost centre or project
[Screencast from 04-09-24 01:23:59 PM IST.webm](https://github.com/user-attachments/assets/3b859281-6420-49d0-948d-fc9dd3c4f897)

Budget final

---

beams/beams/doctype/batta_claim/batta_claim.js
beams/beams/doctype/batta_claim/batta_claim.json

- Syntax error in doctype batta claim
- Fixed the function

fix : Syntax Error Resolved

---

beams/beams/doctype/room_criteria/room_criteria.js
beams/beams/doctype/room_criteria/room_criteria.json
beams/beams/doctype/room_criteria/room_criteria.py
beams/beams/doctype/room_criteria/test_room_criteria.py

-Create Room Criteria Doctype 
-Add  Field and Naming Series
-- Created new Doctype: Room Criteria
- Added field: Room Criteria 
- Configured Naming Series based on the Room Criteria field
-no

feat:Create Doctype Room Criteria

---

beams/fixtures/workflow.json
beams/hooks.py

- Create a workflow for doctype Substitute Booking
- Created a workflow Substitute booking with action :
- Submit For Approval
- Reopen
- Approve
- Reject
[Screencast from 13-09-24 10:37:39 AM IST.webm](https://github.com/user-attachments/assets/8bbb1b51-a56c-4b3d-a00f-d94317e56fbf)
put

feat : Created a Workflow on doctype substitute booking

---

beams/beams/custom_scripts/sales_invoice/sales_invoice.py

-Need to Fix the  Capitailisation on the messages in Sales Invoice Doctype.
Fixed the Capitailisation on the messages in Sales Invoice Doctype.
Sales invocie doctype
-No

Fixed the Capitailisation on the messages 

---

beams/beams/doctype/voucher_entry_type/test_voucher_entry_type.py
beams/beams/doctype/voucher_entry_type/voucher_entry_type.js
beams/beams/doctype/voucher_entry_type/voucher_entry_type.json
beams/beams/doctype/voucher_entry_type/voucher_entry_type.py

- Feat.
- Created Doctype Voucher Entry Type with fields voucher entry type,description,attachment and Accounts table.
- Applied filters for company field in Accounts table.
- Added naming series for doctype Voucher Entry Type.
Voucher Entry Type-Doctype.
- New Data

feat: Create doctype Voucher Entry Type

---

beams/beams/doctype/batta_policy/batta_policy.js
beams/beams/doctype/batta_policy/batta_policy.json
beams/beams/doctype/batta_policy/batta_policy.py
beams/beams/doctype/batta_policy/test_batta_policy.py
beams/beams/doctype/mode_of_travel/mode_of_travel.js
beams/beams/doctype/mode_of_travel/mode_of_travel.json
beams/beams/doctype/mode_of_travel/mode_of_travel.py
beams/beams/doctype/mode_of_travel/test_mode_of_travel.py

Need to Create Doctypes Mode of Travel and Batta Policy 
Created Doctype Mode of travel with one field Mode of Travel and added naming series as field name for doctype.
Created Doctype Batta Policy 
-New feature
-No

feat: Created a  two Doctype Mode of travel and Batta policy

---

beams/beams/doctype/region/region.js
beams/beams/doctype/region/region.json
beams/beams/doctype/region/region.py
beams/beams/doctype/region/test_region.py

- Feat.
- Created Doctype Region with field 'Region'.
Region-Doctype
- New Data

feat: Create doctype Region

---

beams/beams/doctype/stringer_bill/stringer_bill.json

-Update Stringer Bill Doctype.
-Removed number of days and total wage from stringer bill doctype.
-Updated Company Field
-Added Purchase Invoice connection in Stringer Bill
-No

feat: Add Connections in Stringer Bill Doctype

---

beams/beams/doctype/substitute_booking/substitute_booking.js
beams/beams/doctype/substitute_booking/substitute_booking.json
beams/beams/doctype/substitution_bill_date/substitution_bill_date.json

- Feature
- Add fields expense account,mode of payment,paid amount and necessary section breaks in substitute booking doctype.
- Added fields.
Substitute Booking
- New Data

feat: Update substitute booking doctype

---

beams/hooks.py

-Need to Add Workflow Name in Contract Doctype.
Added to workflow Name in Contract Doctype via hooks.py
added Workflow Name
no

fix: Fixed the workflow Name of Contract Doctype

---

beams/beams/workspace/beams/beams.json

-Add "Beams Accounts Settings" shortcut and update dashboard layout
- Added "Beams Accounts Settings" shortcut
-no.

feat:Add Shortcut

---

beams/beams/custom_scripts/contract/contract.py
beams/beams/doctype/services/services.json
beams/hooks.py
beams/public/js/contract.js

- Create child doc-type Service
- Calculate amount as the product of rate and quantity
- Generate purchase order on approval of contract
- Service child table created and set the calculation of amount as product of rate and quantity
- Generated purchase order automatically on the approval of corresponding contract and fetched the datas from it 
[Screencast from 24-09-24 01:43:44 PM IST.webm](https://github.com/user-attachments/assets/aa0ace34-3789-406a-a6c3-e93bee9c0bd8)

feat : Created Purchase Order On The Approval of Contract

---

beams/beams/api/api.py

- Fix
- The fix updates the create_release_order function to remove hardcoded tax values and instead use a Sales Taxes and Charges Template.
Release Order.
- New Data

feat: Create release order API

---

beams/beams/doctype/batta_claim/batta_claim.js
beams/beams/doctype/batta_claim/batta_claim.json
beams/beams/doctype/batta_claim/batta_claim.py
beams/beams/doctype/batta_policy/batta_policy.json
beams/hooks.py

-Update batta Policy Doctype
-Update Batta Claim Doctype
-Applied Batta Policy In Batta Claim based on Designation.
-No

feat : Batta Policy

---

beams/setup.py

- Wanted to Automate the creation of Role
In setup.py file created a method to create role , when the argument is passed
When argument is passed the role will be created
-No
- Chrome

feat: Automate creation of Role

---

beams/beams/doctype/language_proficiency/language_proficiency.json
beams/beams/doctype/language_proficiency/language_proficiency.py
beams/beams/doctype/skill_proficiency/skill_proficiency.json
beams/beams/doctype/skill_proficiency/skill_proficiency.py
beams/setup.py

- Feature
**1.  Add a Work Details section with the following fields:**
**2.  Add a Education and Qualification Details section with the following fields:**
**3. Create Language Proficiency Child Table with the following fields:**
**4. Create Skill Proficiency Child Table with the following fields:**
**1. Work Details Section:**
**2. Education and Qualification Section:**
**3. Child Tables:**
[Screencast from 10-03-2024 11:29:39 AM.webm](https://github.com/user-attachments/assets/d5c878d3-a569-4db7-aec1-4e3a473c78a4)
- `beams/setup.py`
- `beams/beams/doctype/language_proficiency/`
- `beams/beams/doctype/skill_proficiency/`
- No
- New Data
- No

feat : Customise Job Requisition Doctype.

---

beams/setup.py

Implement some strategy to avoid the error while bench migration
commented the method to create 
-migration happens without error
-No
- chrome

fix: commented the function to create Role

---

beams/beams/doctype/batta_claim/batta_claim.json
beams/beams/doctype/batta_policy/batta_policy.json
beams/beams/doctype/mode_of_travel_table/mode_of_travel_table.json
beams/beams/doctype/mode_of_travel_table/mode_of_travel_table.py
beams/beams/doctype/room_criteria/room_criteria.json
beams/beams/doctype/room_criteria_table/room_criteria_table.json
beams/beams/doctype/room_criteria_table/room_criteria_table.py

- implement multiple selection for fields in Batta Claim  and Batta Policy Doctype
1.  Created new Child Doctypes Room Criteria Table 
Room Criteria (Link,Option - Room Criteria )
2.  Created New Child Doctype Mode of Travel Table 
Mode of travel (link-Option- Mode of Travel )
3. checked in list view  and added mandatory in Room Criteria
4. implement multiple selection for fields in Batta Claim Doctype.
-    Changed the link Fields Mode of Travelling ( Table Multiselect ,Option- Mode of Travel Table)
-    Changed the Link Field Room Criteria (  Table Multiselect , Option- Room Criteria Table)
5. implement multiple selection for fields in Batta Policy Doctype.
-    Changed the link Fields Mode of Travel ( Table Multiselect ,Option- Mode of Travel Table)
-    Changed the Link Field Room …

feat: Enabled multiselect fields for Batta cliam and Batta Policy

---

beams/beams/doctype/employees_left/employees_left.json
beams/beams/doctype/employees_left/employees_left.py

Create Child Table Employees Left
Created a new Child Table -> Employees Left
New Child Table is created
-No
- chrome

feat: Created Employees Left Child doctype

---

beams/beams/doctype/local_enquiry_report/local_enquiry_report.json
beams/setup.py

- Chore
- This update improves the user experience in the Job Requisition Doctype by reorganizing field positions and enhancing field description.
- Moved the department field above the no of positions field in Job Requisition
- Changed the description of  Number of Days Off' field.
- Changed the field type of 'Applicant Name','Information Given By' in Local Enquiry Report.
- Job Requisition.
- Local Enquiry Report.
- No
- New Data

chore:update Job Requisition

---

beams/beams/custom_scripts/job_applicant/job_applicant.py
beams/public/js/job_applicant.js
beams/setup.py

Need to Modify the Job Applicant doctype with specific field changes and validation rules.
-Modify the validation Message in job Applicant Doctype.
-Need to change label and Field type in job Applicant Doctype.
-Update and remove the validation in job Applicant Doctype.
-Add the New field in job applicant doctype.
1. Changed the name of Minimum Educational Qualification to Educational Qualification via setup.py
2. Modified the field type of Educational Qualification from 'Multi select' to 'Link' (option: Educational Qualification).setup.py
3. Renamed Minimum Experience Required to Work Experience (in years) in Via setup.py
4. Removed validation for the Proficiency field in the Skill Proficiency child table.in via job applicant.py and job applicant.js
5. Added validation for Educational …

fix: Modified Validation for Job Applicant in Job Requisition.

---

beams/beams/custom_scripts/job_requisition/job_requisition.py
beams/public/js/job_requisition.js

Feature
Implement Jinja Templating in Job Description Template.
Implemented the logic to render the template , onload .
Dynamically fetch and display the job description from a selected Job Description Template in the Job Requisition form. The template content is rendered using the details from the job requisition
beams/beams/custom_scripts/job_requisition/job_requisition.py
beams/public/js/job_requisition.js
No
Existing Data
New Data
No

feat: Applied Template rendering logic

---

beams/beams/custom_scripts/job_applicant/job_applicant.py
beams/beams/doctype/interview_question_result/interview_question_result.json
beams/beams/doctype/local_enquiry_checklist/local_enquiry_checklist.json
beams/beams/doctype/local_enquiry_report/local_enquiry_report.json
beams/setup.py

- Fix
- required fields were not correctly added to skill assessment table In Interview Feedback doctype.
- Rearrangement of fields in Local enquiry report,interview question result and local enquiry checklist doctypes
- Required fields are added and rearranged fields appropriately.
- local enquiry Checklist
- interview question result
- Interview feedback
No
Existing Data
New Data
No

fix: Update Interview Feedback doctype

---

beams/beams/custom_scripts/department/department.py
beams/beams/report/budget_report/budget_report.js
beams/beams/report/budget_report/budget_report.json
beams/beams/report/budget_report/budget_report.py
beams/public/js/budget.js
beams/public/js/department.js

-Create Budget Report
-Update Budget Doctype
-Created Report of Budget based on monthly distribution.
-Added default current fiscal year filters in Budget Report.
-Fetched department and cost center based on cost subhead.
-Applied filters in department based on cost center.
[Screencast from 29-10-24 03:11:03 PM IST.webm](https://github.com/user-attachments/assets/7bad442e-8709-4bae-af07-b39baca114a4)
[Screencast from 29-10-24 03:13:15 PM IST.webm](https://github.com/user-attachments/assets/9517d3b0-4ee1-410e-a4a5-cb7324d3a800)
[Screencast from 29-10-24 03:14:08 PM IST.webm](https://github.com/user-attachments/assets/77f1f224-bc8e-431b-b2a3-0520e15ce2a9)
-No

feat : Create Budget Report and Update Budget Doctype

---

beams/beams/custom_scripts/job_requisition/job_requisition.py

Feature
Fix indendation error in job requisition.
Fixed indendation error in function make job opening.
beams/beams/custom_scripts/job_requsition/job_requsition
No
Existing Data
New Data
No

fix:fixed indendation error

---

beams/beams/custom_scripts/interview/interview.py
beams/beams/custom_scripts/interview_round/interview_round.py
beams/hooks.py
beams/public/js/interview.js

- Create a dialog on clicking a button Interview feedback to create interview feedback
- Fetch questions assessment from interview round
- Score converted to rating
- Created a dialog on clicking a button Interview feedback to create interview feedback
- Fetched questions assessment from interview round
- Score converted to rating
[Screencast from 30-10-24 04:32:19 PM IST.webm](https://github.com/user-attachments/assets/96421100-afe8-4feb-912d-e280101b4a6a)

feat : Dialog box in interview for submitting interview feedback

---

beams/beams/doctype/substitute_booking/substitute_booking.js
beams/beams/doctype/substitute_booking/substitute_booking.py

-Update Substitute Booking Doctype
-Applied filters in Leave Application of Substitute Booking.
[Screencast from 30-10-24 05:08:12 PM IST.webm](https://github.com/user-attachments/assets/19e4e998-75d5-4154-9926-e6930a26a3c1)
-No

fix : Update Substitute Booking Doctype (TASK-2024-00906)

---

beams/beams/custom_scripts/contract/contract.py

-Update contract doctype.
-Fixed '_' errors in contract.
-No

fix : Update Contract doctype

---

beams/public/js/interview.js

- No submit and cancel button
- If the form is dirty it shows save if not then submit and to cancel

fix : Submit & cancel updated

---

beams/beams/custom_scripts/purchase_order/purchase_order.py

-Update contract doctype.
-Fixed '_' errors in purchase order.
-No

fix : Fixed the Error in Contract

---

beams/public/js/job_applicant.js

1. Removed Client Side Validations from Job Applicant
2. Removed Interview round fetching from client side
1. job_applicant.js
No
- Chrome

refactor: Optimised and removed unwanted codes from Job Applicant

---

beams/api/api.py

Address info will be returned along with customer info with customer list API
Added a method to fetch addresses of the customers
- Fixed the issue with agency list APIs fetching non agents by fixing the filter
- Agency List API: ![image](https://github.com/user-attachments/assets/a46792d6-11a2-44de-ad9d-c0f3eece3877)
- Client List API:  ![image](https://github.com/user-attachments/assets/70830566-3fa7-4bb9-8705-c83ed3493ac6)
API
- get_client_list
- get_agency_list
No
- Chrome - Yes
- Opera Mini
- Safari

feat: added address keys in customer list API

---

beams/beams/doctype/local_enquiry_report/local_enquiry_report.json
beams/fixtures/workflow.json
beams/fixtures/workflow_action_master.json
beams/hooks.py
beams/setup.py

1.Make the doctype as submittable in local enquiry report
2.change the workflow state and workflow action in local enquiry report
3.create the new roles for local enquiry report
1.Modified the Local Enquiry Report Type doctype to be submittable
Added  submittable from the doctype
2.added the action enquiry complted via hooks.py
-Changed doc_status from "1" to "0" in rejected state 
-Modified the role for the Assign to Enquiry Officer action from HR Manager to Enquiry Manager inworkflow
-Replaced duplicate "Enquiry Completed" actions with a single "Approve" action for HR Manager .
3 .Created new role Enquiry Officer and Enquiry Managerin via setup.py
[Screencast from 05-11-24 11:27:27 AM IST.webm](https://github.com/user-attachments/assets/12649504-df20-4f51-b484-a389f1e26e0c)
[Screencast …

TASK-2024-00946: Updated workflow in local enquiry report

---

beams/beams/custom_scripts/job_applicant/job_applicant.js
beams/beams/custom_scripts/job_applicant/job_applicant.py
beams/beams/doctype/applicant_interview_round/applicant_interview_round.json
beams/hooks.py

-Fetch Interview Reference and Interview Status from Created Interview In Job Applicant.
-Mark Checkbox Interview Completed as Checked when the interview is completed.
-Once Created the interview against the interview round through Create/view button in Job Applicant Child table,then cannot create the interview against that interview Round.
- Create/View button should not work if the form is dirty. 
- Interview round might be read-only and also Interview Status.
-Make Interview Round as Mandatory 
-Show "Selected" button inside the Set Status Group Button in Job Applicant if the status is "Local Enquiry Approved."
-On clicking "Selected" update the status to "Selected."
-Updated Interview Reference and Interview Status from Created Interview In Job Applicant.
-Marked Checkbox Interview …

TASK-2024-00963 : Fetch Interview Reference and Interview Status from Created Interview

---

beams/beams/custom_scripts/job_applicant/job_applicant_list.js
beams/beams/doctype/local_enquiry_report/local_enquiry_report.py
beams/hooks.py

-Update Job Applicant Status to "Local Enquiry Approved" when the Local Enquiry Report is Approved.
-Set Job Applicant Status Indicators.
-Updated Job Applicant Status to "Local Enquiry Approved" when the Local Enquiry Report is Approved.
-Set Job Applicant Status Indicators.
[Screencast from 05-11-24 04:23:17 PM IST.webm](https://github.com/user-attachments/assets/bf394287-836b-48bf-b7f1-1dc9785543dd)
[Screencast from 05-11-24 04:25:22 PM IST.webm](https://github.com/user-attachments/assets/018bb4ce-2b67-4b12-b00f-db1abaf3773e)
No.

    TASK-2024-01011 : Update Job Applicant Status to Local Enquiry Approved

---

beams/setup.py

-Add Custom Fields in Job Applicant
-Added Willing to Work On the Selected Location Checkbox in Job Applicant.
No.

feat : Add Custom Fields In Job Applicant

---

beams/beams/custom_scripts/job_applicant/job_applicant.js
beams/beams/custom_scripts/job_applicant/job_applicant.py
beams/setup.py

-Update location in Job Applicant from Job opening when the checkbox is checked.
-Hide fields in Release Order
-Updated location in Job Applicant from Job opening when the checkbox is checked.
-Hid scan barcode,shipping rule and incoterm fields in release Order.
-Arranged custom fields in Release Order.
[Screencast from 08-11-24 02:02:14 PM IST.webm](https://github.com/user-attachments/assets/a037ebfb-13e6-49c7-8c73-419cc7b9eaa7)
No.

    TASK-2024-00958 : Update Location In Job Applicant from Job Opening when the checkbox is checked.

---

beams/beams/doctype/job_proposal/job_proposal.py
beams/setup.py

1.Need to Add the  new status in job applicant
2.  update the status of job applicant on creation of job proposal doctype .
3. update the status of the job applicant when the job proposal accepted 
1.Added  the  new status in job applicant
-added new status Job Proposal Created and Job Proposal Accepted in job applicant via setup.py
2.updated the status of job applicant on creation of job proposal doctype 
.   -updated the status in to ' Job Proposal Created ' job applicant after creation of job proposal via job proposal.py
3.updated  the status of the job applicant when the job proposal accepted 
-updated the status in to 'Job Proposal Accepted' job applicant when the  job proposal status become 'Applicant Accepted'
via job proposal.py 
[Screencast from 11-11-24 12:56:49 PM …

TASK-2024-01030: updated  the status of Job Applicant according to Job Proposal

---

beams/beams/doctype/job_proposal/job_proposal.js

- Apply a filter in the field job applicant in doctype job proposal
- In doctype job proposal the field job applicant only shows employees that are selected

TASK-2024-01059 : Filter applied for job applicant in job proposal

---

beams/beams/doctype/job_proposal/job_proposal.py

-Create ToDo for CEO and HR Manager based on Job Proposal Status.
-Created ToDo for CEO when the Job Proposal is created.
-Created ToDo For HR Manager when the job Proposal is verified by CEO.
[Screencast from 12-11-24 10:46:39 AM IST.webm](https://github.com/user-attachments/assets/d8334605-e3a6-49a9-ae99-de8c427e115a)
No.

    TASK-2024-01033 : Create ToDo for CEO and HR Manager based on Job Proposal status

---

beams/beams/custom_scripts/employee/employee.js
beams/beams/custom_scripts/employee_dashboard/employee_dashboard.py
beams/beams/custom_scripts/event/event.js
beams/hooks.py

- Create a group button with option training request in doctype employee
- Create a group button with option training request in doctype event
- Both button should only visible for the user with HOD role
- Add connection to training request from employee
- Created a group button named Create with option Training Request in both Doctype Employee and Event
- Both Button are Only Visible for the Role HOD
- Added Connection to Training Request From Employee
[Screencast from 13-11-24 02:39:05 PM IST.webm](https://github.com/user-attachments/assets/1f7db4d7-f9ee-40fc-823d-c4dd7d64e3f5)

 TASK-2024-01069 : Button added and connection given in Employee to Training request

---

beams/beams/custom_scripts/employee/employee.js
beams/beams/custom_scripts/employee/employee.py

1. Add a custom "Event" button in the Employee doctype
2. Implement functionality to map the selected Employee and the HOD user as participants in the created Event.
1. Created a custom "Event" button in the Employee doctype.
visible to users with the HOD user  with employee id via employe.py and employee.js
2. implemented functionality to map the selected Employee and the HOD user as participants in the created Event.
-implemented logic to map the  participants in event via employee.js and employee.py
3. Added new file for emloyee via hooks.py
[Screencast from 13-11-24 04:53:26 PM IST.webm](https://github.com/user-attachments/assets/ed6b15d8-0c4a-476d-acb5-fa092de117a3)
employee doctype
event doctype
No

TASK-2024-01031: created a button event in employee doctype

---

beams/beams/custom_scripts/training_event/training_event.js
beams/beams/custom_scripts/training_event/training_event.py
beams/hooks.py

-Add a button "Get Employees from " in Training Event.
-Show a dialog in Trianing event when the button is clicked .
-Display Training Request with status "Open" in dialog.
-Fetch employees and corresponding training request in Training Event.
-Added a button "Get Employees from " in Training Event.
-Displayed a dialog in Trianing event when the button is clicked .
-Displayed Training Request with status "Open" in dialog.
-Fetch employees and corresponding training request in Training Event.
[Screencast from 13-11-24 05:23:38 PM IST.webm](https://github.com/user-attachments/assets/6aeabcbb-2854-47ed-94f3-a1c3866e8042)
No.

    TASK-2024-01057 : Add a button Get Employees from in Training Event

---

beams/beams/custom_scripts/employee/employee.js
beams/beams/custom_scripts/event/event.js
beams/beams/doctype/training_request/training_request.py

- Sent a Notification to the users with role Hr Manager on Creation of Training Request
- On creation of Training Request , A Todo is generated to all users with role Hr Manager
[Screencast from 14-11-24 11:36:15 AM IST.webm](https://github.com/user-attachments/assets/a72d4bdf-affa-4bd3-a3ff-3a85624d7505)

TASK-2024-01058 : Todo Created for Hr On Creation Of Training Request

---

beams/beams/doctype/education_qualification/education_qualification.json
beams/beams/doctype/professional_certification/professional_certification.json
beams/www/job_application_upload/upload_doc.css
beams/www/job_application_upload/upload_doc.html
beams/www/job_application_upload/upload_doc.js
beams/www/job_application_upload/upload_doc.py

- Initializes context details for applicants upon validation.
- Authenticates applicant links to ensure valid, non-expired access.
- Updates applicant details, including qualifications, certifications, and employment history.
- Manages file uploads and links attachments to the applicant’s profile.
- Authorization: **authorize_applicant_id** decrypts and validates applicant IDs.
- Applicant Update: **update_register_form** loads and validates form data for updating applicant details.
- File Management: **update_file** handles file uploads, linking files to applicant records if they exist.
`beams/www/`
No
- Chrome

feat : TASK-2024-00926 -Document Upload Webpage.

---

beams/beams/custom_scripts/employee/employee.js
beams/beams/custom_scripts/event/event.js
beams/beams/doctype/training_request/training_request.py

- Button visible before the form is saved
- Description of todo change
- Button is hided if the form is new
- Description chnaged as need

fix : Issue in button visibility

---

beams/beams/custom_scripts/job_requisition/job_requisition.js
beams/beams/custom_scripts/job_requisition/job_requisition.py
beams/patches.txt
beams/patches/delete_custom_fields.py
beams/setup.py

Refactored Job Requisition
Job Requisition
No
- Chrome

refactor: Job Requisition

---

beams/beams/custom_scripts/interview/interview.py
beams/beams/custom_scripts/job_applicant/job_applicant.js
beams/beams/custom_scripts/job_applicant/job_applicant.py
beams/hooks.py
beams/patches.txt
beams/patches/delete_custom_fields.py
beams/setup.py

optimised and refactored Job Applicant fields
Job Applicant files
Interview creation/updation
No
- Chrome

refactor: optimised and refactored Job Applicant fields

---

beams/setup.py

- Translate doctype name Attendance Request to Attendance Regularisation
- Add Custom fields and options
- Translated the name of doctype
- Created the custom field reports to
- Added option to the field reason
[Screencast from 16-11-24 11:03:38 AM IST.webm](https://github.com/user-attachments/assets/f581de49-6a52-4e4a-b4f4-1627506c3806)

TASK-2024-01085 : Updated the doctype attendance request

---

beams/beams/custom_scripts/event/event.js

- Update Training Request
- Fetched employee from Event in to Training Request.
[Screencast from 16-11-24 03:12:05 PM IST.webm](https://github.com/user-attachments/assets/5cf42fe7-29de-4ec9-8cc5-877f3bbf9f67)
No.

fix : Fetch employee in to Training Request from Event

---

beams/beams/custom_scripts/attendance/attendance.py
beams/hooks.py

1.implement a reminder email to the "Reports To" check for employees with absent attendance created 2 days back.
1.sented the reminder email to the "Reports To" check for employees with absent attendance created 2 days back.
- added teh schedular event for send reminder via hooks.py 
- implemented the logic to send email to reports to employee where check employees with absent attendance created 2 days back.  and also no leave application on attendance day via attendance.py 
[Screencast from 18-11-24 10:27:06 AM IST.webm](https://github.com/user-attachments/assets/32c209e8-2a0b-4096-b7c8-27bc069c59bb)
0fe30)
attendance 
No..

  TASK-2024-01095 : sented a reminder to notify absent attendance without leave application

---

beams/www/job_portal/index.css
beams/www/job_portal/index.html
beams/www/job_portal/index.js
beams/www/job_portal/index.py
beams/www/job_portal/job.html
beams/www/job_portal/job.py

feat: Job Portal

---

beams/beams/custom_scripts/interview_feedback/interview_feedback.js
beams/beams/custom_scripts/interview_feedback/interview_feedback.py

- interview feedback skills and questions are not being fetched.
- Fetched Skills , Questions and weights  in Interview feedback from specified interview Round.
[Screencast from 18-11-24 02:15:45 PM IST.webm](https://github.com/user-attachments/assets/a0a4ba6e-d5e9-439c-a14e-a24bdf0bac27)
No.

    TASK-2024-00942 : Fetches Skills and Questions from Interview Round

---

beams/beams/custom_scripts/job_requisition/job_requisition.py
beams/www/job_application_form/index.js
beams/www/job_application_form/index.py

minor changes in application form and creation
No
- Chrome

chore: minor changes in application form and creation

---

beams/beams/custom_scripts/job_applicant/job_applicant_dashboard.py
beams/hooks.py

Connections in Job Applicant
Added connections in Job Applicant doctype . 
To visit multiple doctype
Job applicant doctype
No
- Chrome

TASK-2024-00987:  Added connections in job applicant

---

beams/beams/custom_scripts/interview/interview.js
beams/beams/custom_scripts/interview/interview.py
beams/beams/doctype/interview_question_result/interview_question_result.json
beams/beams/doctype/interview_questions/interview_questions.json
beams/beams/doctype/interview_questions/interview_questions.py
beams/patches.txt
beams/patches/delete_custom_fields.py
beams/setup.py

optimised Interview Feedback added fixes
[https://www.youtube.com/watch?v=5JTVUsLjm3M](url)
Interview
Interview Round
Interview Feedback
No
- Chrome

refactor: optimised Interview Feedback added fixes

---

beams/beams/custom_scripts/interview_feedback/interview_feedback.js
beams/beams/custom_scripts/interview_feedback/interview_feedback.py
beams/hooks.py
beams/setup.py

Score based rating calculation in Interview Feedback
No
- Chrome

feat: Score based rating calculation in Interview Feedback

---

beams/www/job_application_form/index.html
beams/www/job_application_form/index.js
beams/www/job_application_form/index.py

updated Job Application Webform
No
- Chrome

fix: updated Job Application Webform

---

beams/www/job_application_form/index.html
beams/www/job_portal/job.html
beams/www/job_portal/job.py

validate fields in Job Application form
No
- Chrome

feat: validate fields in Job Application form

---

beams/beams/custom_scripts/attendance_request/attendance_request.py
beams/beams/custom_scripts/shift_type/shift_type.py
beams/hooks.py

Set/update missing values in Attendance
Override Shift Type Class
Override Attendance Request Class
`Attendance Request Doctype`
`Shift Type Doctype`
No
- Chrome

feat: Set/update missing values in Attendance

---

beams/beams/workspace/accounts/accounts.json
beams/beams/workspace/hr/hr.json

Add HR and Accounts workspace
Added HR and Accounts Workspace 
workspace/accounts
workspace/hr
No
- Chrome

TASK-2024-01125: Added HR and Accounts Workspace

---

beams/beams/custom_scripts/job_applicant/job_applicant.py
beams/beams/custom_scripts/job_requisition/job_requisition.js
beams/beams/custom_scripts/job_requisition/job_requisition.py
beams/hooks.py
beams/setup.py

1.Need to hide the + icon  in connection in job opening from the cancel of job requisition doctype
2. Need to change the label to Field  Minimum Educational Qualification in job requisition doctype.
3. Need to fetch post time in the job opening .
4. implement the validation in job applicant Validate Applicant email with Job Opening
1.hidden the + icon  in connection in job opening from the cancel of job requisition doctype
- while cancelled the job requsition the job opening in connection hidden the + icon using via job requisition.js
2.changed the label to Field  Minimum Educational Qualification in  job requisition doctype.
-changed the label Minimum Educational Qualification to Preferred Educational Qualification via setup.py
3.fetched post time in the job opening in approval of job …

    TASK-2024-01133: Validate Applicant email with Job Opening

---

beams/beams/custom_scripts/leave_application/leave_application.js
beams/beams/custom_scripts/leave_application/leave_application.py
beams/hooks.py
beams/setup.py

Add Minimum Advance Days Field and Validation for Leave Applications
Field Label: Minimum Advance Days
Field Type: Float
Description: Specifies the minimum number of days required to apply for this leave.
Add Validation in Leave Application
Implement a validation in the Leave Application DocType to ensure the From Date is at least the specified number of days from the current date, as defined in the selected Leave Type.
- Added Custom Field in Leave Type doctype labelled  Minimum Advance Days(int).
- 
- Implemented a validation function in the backend to ensure that the from_date in the Leave Application is at least the configured minimum number of days from the current date.
- 
- Triggered validation when the leave_type or from_date field is changed in the Leave Application form.
- …

TASK-2024-01141:Validated Leave Application based on minimum advance days.

---

beams/beams/custom_scripts/leave_application/leave_application.js
beams/beams/custom_scripts/leave_application/leave_application.py
beams/hooks.py
beams/setup.py

1. Need to add new fields in Leave Type doctype
2. Need to add new field in Leave Application doctype.
3. Implement logic to  show or hide the 'medical_certificate' field based on leave type and duration.
4. implement  validation for medical certificate requirements for sick leave exceeding 2 days
1. Added new fields in Leave Type doctype
-Is Sick Leave(checkbox)
-Is Proof Document Required(checkbox) show this checkbox only if Is Sick Leave checkbox is checked
-Medical Leave Required for Days"(float) show this field only if Is Proof Document Required checkbox checked.
2. Added new fields in leave application doctype
-Medical Certificate(Attach) This field is displayed when The leave type is marked as sick leave.and the duration of the leave      exceeds 2 days in leave application doctype …

TASK-2024-01142 : Add Proof Document Requirement for Sick Leave

---

beams/api/api.py
beams/patches.txt
beams/patches/delete_custom_fields.py
beams/setup.py

Create Release Order API
Get Employees API
Get Currency API
No
- Chrome

feat: Create Release Order APIs

---

beams/beams/custom_scripts/leave_allocation/leave_allocation.py
beams/beams/doctype/gender_leave_type_mapping/gender_leave_type_mapping.js
beams/beams/doctype/gender_leave_type_mapping/gender_leave_type_mapping.json
beams/beams/doctype/gender_leave_type_mapping/gender_leave_type_mapping.py
beams/beams/doctype/gender_leave_type_mapping/test_gender_leave_type_mapping.py
beams/beams/workspace/hr/hr.json
beams/hooks.py

create new doctype "Gender Leave Type Mapping" and apply validation in leave allocation doctype for selected gender has leave type or not 
Created a new doctype "Gender Leave Type Mapping" and applied the validation in leave allocation doctype whether the selected employee has leave allocated or not based on gender and leave type
[Gender Leave Type Mapping]
[Leave Allocation]
No
- Chrome

TASK-2024-01147: Create Doctype Gender Leave Type Mapping

---

beams/api/api.py

API to create Sales Order
No
- Chrome

feat: Create Sales Order API

---

beams/beams/doctype/family_details/family_details.json
beams/beams/doctype/family_details/family_details.py
beams/beams/doctype/nominee_details/nominee_details.json
beams/beams/doctype/nominee_details/nominee_details.py
beams/setup.py

- Add Custom Fields in Employee Doctype.
- Added Custom Fields in Employee Doctype.
- Created Child table Nominee Details and Family Details.
[Screencast from 26-11-24 04:36:27 PM IST.webm](https://github.com/user-attachments/assets/072fad4b-4d59-4d94-8bae-3643181dfb03)
No.

    TASK-2024-01145 : Added Custom Fields in Employee Doctype

---

beams/setup.py

Enhance Employee Doctype with new fields and label modifications
Added height and weight fields to employee custom fields and update label for father/spouse name
No. 

feat:Modify Employee Doctype

---

beams/beams/doctype/kyc_details/kyc_details.json
beams/beams/doctype/kyc_details/kyc_details.py
beams/beams/doctype/provident_fund/provident_fund.js
beams/beams/doctype/provident_fund/provident_fund.json
beams/beams/doctype/provident_fund/provident_fund.py
beams/beams/doctype/provident_fund/test_provident_fund.py

1. Need to create the doctype Provident Fund 
2. Need to create the child  doctype KYC Details
3. Add naming series to  doctype Provident Fund 
1.Created the Doctype Provident Fund 
-fields are Whether earlier a member of the employee's Provident Fund scheme,1952?(Check),whether earlier a member of the   employee's pension scheme,1995?(check) if this check box checked added mandatory in the below tab break fields in Previous Employment Details
-Added tab break Previous Employment Details
field are added section break The details of the Universal Account Number(UAN) or previous PF member ID' and add following fields into it
-UAN(Data),Previous Member ID(Data),Date of Exit for previous member Id(DD/MM/YYYY)(Date),If scheme certificate issued for previous employment,then scheme Certificate …

    TASK-2024-01152:Created Provident Fund Doctype and KYC details child doctype.

---

beams/beams/custom_scripts/employee/employee.py

The feature is designed to handle cases where these settings are missing, ensuring the employee creation process is not disrupted.
- If valid settings are available,  fetch leave period details and create  a Leave Policy Assignment.
- If configurations or details are missing, skip the assignment without throwing errors.
Enhanced the after_insert_employee function to validate and handle missing or incomplete leave configurations.
[Screencast from 2024-11-28 11-08-37.webm](https://github.com/user-attachments/assets/d564ef12-db7b-4619-993c-68e5ca7e364f)
employee 
No. 
- Chrome

fix:The process of employee creation was made functional even if leave settings were misconfigured.

---

beams/beams/custom_scripts/employee/employee.js

- Fetch the common details from job applicant to employee
- While triggering job applicant field in employee all the corresponding details of employee is fetched to the doctype employee
[Screencast from 28-11-24 09:55:31 AM IST.webm](https://github.com/user-attachments/assets/c9551901-1ab8-4b54-9208-25f7925d56ad)
(optional)

TASK-2024-01172 : Fetching all the details from job applicant to employee

---

beams/setup.py

-Enhance employee form fields
- Added "Additional Information" section with related fields for travel preferences and personal details.
- Rearranged and renamed fields like "Father's Name" and "Spouse's Name" for clarity.
- Introduced conditional dependencies and column breaks to enhance form layout.
- Adjusted labels and insert positions for better user experience.
- Removed redundant 'Height' and 'Weight' fields from the employee form
No. 

    TASK-2024-01154:Updated employee custom fields configuration

---

beams/www/job_application_upload/upload_doc.html

Change the required text field to select field
changed the text field to Select field
[upload_doc.html]
No
- Chrome

fix: changed text to select field

---

beams/beams/custom_scripts/job_applicant/job_applicant.py
beams/hooks.py
beams/www/job_application_upload/upload_doc.html

- Traverse Designation to job applicant from job opening
- Correct the spelling mistake in position applied
- Change the period from and to year field
- Fetch the mobile number to the application 
- Designation fetched to job applicant from job opening
- Spelling mistake corrected
- Mobile number fetched
- Year as given that 4 digit can be given within 0-9

fix : Adjusted some fields and designation fetched to job applicant

---

beams/www/job_application_upload/upload_doc.html
beams/www/job_application_upload/upload_doc.js

Need to correct the submit button submittion issue and change text to select 
Corrected the issue the submit button and changed the text issue to select issue.
[ upload_doc.html ]
[ upload_doc.js ]
No
- Chrome

Aju dev nov

---

beams/beams/doctype/bank_details/bank_details.json
beams/beams/doctype/bank_details/bank_details.py
beams/beams/doctype/esi/esi.js
beams/beams/doctype/esi/esi.json
beams/beams/doctype/esi/esi.py
beams/beams/doctype/esi/test_esi.py

Create ESI Doctype with personal details
- Include child tables for Family Details, Nominee Details, and Bank Details
Created ESI Doctype with the following fields:
-Personal details
-Added section breaks for Date and Signature.
Created child tables:
- Family Details with fields: Name , Relationship with Employee, Date of Birth , Whether   Residing with Employee, State, and District.
- Nominee Details with fields: Name of Nominee, Relationship with Employee, Percentage, and Address of Nominee.
- Bank Details with fields: Account No, Name of Bank, Type of Account, Branch, and IFSC Code.
added a naming series for the ESI Doctype.
[Screencast from 02-12-24 09:46:11 AM IST.webm](https://github.com/user-attachments/assets/9d83b815-fff9-4c82-8f43-b62a4bc42d0c)
No. 

    TASK-2024-01145:Created ESI Doctype with fields

---

beams/beams/custom_scripts/job_applicant/job_applicant.py
beams/hooks.py

- Fetch department in job applicant
- Fetched department from job opening in job applicant

feat : Fetched Department

---

beams/www/job_application_upload/upload_doc.html

- Date format should be dd-mm-yy instead dd/mm/yy
- Date format changed to dd-mm-yy

fix : Date format changed from dd/mm/yy to dd-mm-yy

---

beams/beams/doctype/shift_swap_request/shift_swap_request.js
beams/beams/doctype/shift_swap_request/shift_swap_request.json
beams/beams/doctype/shift_swap_request/shift_swap_request.py
beams/beams/doctype/shift_swap_request/test_shift_swap_request.py

- Create a doctype shift swap request
- Filter should be applied to the field swap with employee that with department
- Created a doctype shift swap request with employee , department and shift date details
- A filter applied in field swap with employee that only shows employee in selected department in field department
[Screencast from 02-12-24 01:14:47 PM IST.webm](https://github.com/user-attachments/assets/36fa76d0-ba70-4906-b448-4b883a56a767)

TASK-2024-01189 : Created doctype shift swap request

---

beams/beams/doctype/shift_swap_request/shift_swap_request.py

- Validate the start and end date should be future date
- Validate the swap employee and employee are in same department
- Validate both employee and swap employee should have shift assignment
- Start  date and end date are checked whether it is future date
- Checks the employee and swap employee belong to same department
- Check both employee has a shift assignment to swap
[Screencast from 02-12-24 04:39:37 PM IST.webm](https://github.com/user-attachments/assets/dc3145a9-675e-450b-9533-d06b1eba1aa4)
(optional)

TASK-2024-01190 : Added validation for shift assignment , date and department

---

beams/setup.py

-Enhance Employee Custom Fields: Updated Defaults and Dependencies
-Replaced ambiguous fields with clear and descriptive labels.
-Added default values for select fields for consistency.
-Implemented conditional dependencies for better form logic.
-Reorganized field placement for improved user experience.
-Employee Doctype
- No. 

Task_Fix:Updated Employee Custom Fields

---

beams/beams/doctype/shift_swap_request/shift_swap_request.json

- Change the field alignment in doc-type shift swap request
- Changed the field alignment

TASK-2024-01189 : Field alignment changed in doctype

---

beams/beams/custom_scripts/attendance_request/attendance_request.py

Enhance the Attendance Request functionality to calculate and update the first check-in and last checkout times for an employee based on attendance date and records.
- Introduced the `get_checkin_checkout_time` method to compute the first check-in and last checkout times.
- Added  methods:
- `get_checkout_time`: Retrieves the last checkout time after a specified check-in.
- `get_checkin_time`: Retrieves the first check-in time before a specified checkout.
- Updated the `create_or_update_attendance` method to integrate these calculations, ensuring the attendance records are accurate and consistent.
`Attendance Request Doctype`
No
- Chrome

feat : Enhance Attendance Request with Check-in/Checkout Time Calculation

---

beams/beams/custom_scripts/job_offer/job_offer.py

Fetche current address to from job applicant to employee when creating create employee button clicked
Fetche current address to from job applicant to employee when creating create employee button clicked
[job_offer]
No
- Chrome

feat: fetched current address too

---

beams/beams/custom_scripts/job_offer/job_offer.py

Correct the json parsing error in job offer 
corrected the logic to handle the error
[Job Offer]
No
- Chrome

fix: refactored the code and corrected the json parsing error

---

beams/beams/doctype/shift_swap_request/shift_swap_request.py

Remove the code for creating todo
Removed the code
[Shift Swap Request]
No

fix: Remove code for creating todo

---

beams/beams/doctype/company_kra/company_kra.json
beams/beams/doctype/company_kra/company_kra.py
beams/beams/doctype/department_kra/department_kra.json
beams/beams/doctype/department_kra/department_kra.py
beams/beams/doctype/employee_kra/employee_kra.json
beams/beams/doctype/employee_kra/employee_kra.py
beams/beams/doctype/performance_appraisal/performance_appraisal.js
beams/beams/doctype/performance_appraisal/performance_appraisal.json
beams/beams/doctype/performance_appraisal/performance_appraisal.py
beams/setup.py

Create doctype Performance Appraisal.
Create child table Employee KRA,Company KRA and Department KRA and add to this doctype.
Add fields Employee Appraisal Template,Company Appraisal Template Department Appraisal Template.
Populate child table by fetching data from these templates.
Create doctype Performance Appraisal and add following fields to it:
- Employee(Link,option-Employee,Mandatory)
- Name of Employee(Data,read-only,fetch from employee)
- Designation(Link,option-Designation,read-only)
- Department(Link,option-Department,read-only)
- Location(Link,option-Location)
- Date of Joining(Date)
- Mode of Employment(Link,option-Employment Type)
- Date of Last Promotion(Date)
- Appraisal Cycle(Link,option-Appraisal Cycle)
Create Child table Employee KRA and add fields into it:
- …

feat:Created doctype Performance Appraisal and customised Employee Performance Feedback doctype.

---

beams/beams/doctype/employee_clearance/employee_clearance.json
beams/beams/doctype/employee_clearance/employee_clearance.py
beams/beams/doctype/employee_exit_clearance/employee_exit_clearance.js
beams/beams/doctype/employee_exit_clearance/employee_exit_clearance.json
beams/beams/doctype/employee_exit_clearance/employee_exit_clearance.py
beams/beams/doctype/employee_exit_clearance/test_employee_exit_clearance.py

Create  doctype  Employee Exit Clearance and child table Employee Clearance.
Create  doctype  Employee Exit Clearance with following fields:
- Role Permission-HR Manager,HOD
- It should be Submittable doctype
- Employee(Link,option-Employee,mandatory)
- Employee Name(Read-only,fetch from employee)
- Department(link to Department,fetch from employee)
- Designation(link to designation,fetch from employee)
- Employee Separation Begins on(Date)
- Relieving Date(Date,fetch from employee)
- Notice Period(Int,fetch from employee)
- Pending Dues(check)
- Amount(Currency,show this field only if Pending Dues is checked)
Create childtable  Employee Clearance :
-Department(link,option-department)
- Employee Exit Clearance(link,option-Employee Exit Clearance)
- …

feat:Created doctype Employee Exit Clearance and child table Employee Clearance.

---

beams/beams/custom_scripts/employee_separation/employee_separation.py
beams/beams/doctype/employee_clearance/employee_clearance.json
beams/beams/doctype/employee_exit_clearance/employee_exit_clearance.json
beams/beams/doctype/employee_exit_clearance/employee_exit_clearance.py
beams/hooks.py
beams/setup.py

This feature automates the exit clearance process for employees, ensuring all clearance tasks are tracked and completed efficiently. It also marks the overall Employee Separation status as "Completed" once all clearance tasks are done.
- In Employee Separation doctype,under Employee clearance child table,add field 'Employee Clearance Status'(select,options-pending,completed)
- An Employee Exit Clearance is automatically created from an Employee Separation and assigned to the respective department Heads as specified in the Employee Clearance child table of the Employee Separation.
- On Submit:When Employee Separation is submitted Employee Exit Clearance document is created.
- When an Employee Exit Clearance document is submitted, the related row in the Employee Clearance child table of the …

TASK-2024-01277:Created Employee Exit Clearance from Employee Separation.

---

beams/beams/custom_scripts/task/task.py
beams/hooks.py

- A Todo should generate to Hr Manager on Completion of Employee Separation
- Checks on updation of task completed checks whether it is related to employee separation if yes check all the task is completed or not if completed then the todo is sent 
[Screencast from 19-12-24 01:25:47 PM IST.webm](https://github.com/user-attachments/assets/818a1bf6-721b-46a1-ad87-87f590eb0f4e)

TASK-2024-01284 : A todo sent to hr on completion of employee separation

---

beams/beams/custom_scripts/attendance/attendance.py

-- create a leave application for employees absent without submission within 48 hours.
--Fetched the Penalty Leave Type from the Employment Type of the employee. 
--Set Leave Without Pay (LWOP) as the default if no penalty leave type was configured
--Automatically created a leave application for the absent employee
[Screencast from 24-12-24 03:02:35 PM IST.webm](https://github.com/user-attachments/assets/4dba74cd-ee56-45a9-b32e-95e2ed697122)
--Leave Application Doctype
--Yes 

    TASK-2024-01310:create leave application for absent employees

---

beams/beams/custom_scripts/attendance/attendance.py

--Enhance absence reminder to approve and submit auto-created Leave Applications
--Set Leave Application status to 'Approved' and submitted during absence reminder process
[Screencast from 26-12-24 03:53:16 PM IST.webm](https://github.com/user-attachments/assets/e3a42df0-cc49-4d35-903b-6e7bf1bf7c28)
--Leave Application Doctype
-- Yes 

fix:Updated absence reminder to approve and submit Leave Applications

---

beams/beams/custom_scripts/appraisal_template/appraisal_template.py
beams/hooks.py

The feature aims to create and manage Employee Feedback Criteria for performance goals, linked to existing KRA (Key Result Areas).
Create Criterias for each KRA up on their creation.
When a kra is selected,set the corresponding criterias in Criteria table
This code  ensures that  feedback criteria are populated based on the employee’s goals and their respective KRAs.
- It iterates over the goals child table  and  creates a new Employee Feedback Criteria if one does not exist.
- The new Employee Feedback Criteria is appended   to the rating criteria child table.
Employee Feedback Criteria Doctype:
No. 
- Chrome

TASK-2024-01314:Created Employee Feedback Criteria from KRA

---

beams/www/application_success/success.html

--Create a success page to confirm application submission
--Added a success page that displays a message
--redirects the user to the job portal after 3 seconds
[Screencast from 09-01-25 10:21:04 AM IST.webm](https://github.com/user-attachments/assets/f99b5be8-ce54-43a9-846c-54771137492e)
-- No. 

Create success page for job application submission 

---

beams/beams/custom_scripts/appraisal/appraisal.js
beams/beams/custom_scripts/appraisal/appraisal.py
beams/beams/doctype/assessment_officer/assessment_officer.json
beams/beams/doctype/assessment_officer/assessment_officer.py
beams/hooks.py
beams/setup.py

This feature automates the task assignment process by sequentially assigning tasks to Assessment Officers based on their designations. 
Add Childtable Assessment Officers with field Designation.
Added Childtable Assessment Officers with field Designation. in Appraisal Template doctype.
Tasks are assigned  sequentially to Assessment Officers listed in an Appraisal Template. The task assignment is made based on the employees' designation defined in the template. The function ensures that tasks are not reassigned to officers who have already completed their designated tasks, and it only assigns tasks to active employees with valid user IDs.
The code implements the assign_tasks_sequentially function which:
-     Fetches the Appraisal document.
-     Verifies if the event reference exists to …

feat:Notication to Assessment officers to add Category.

---

beams/beams/doctype/appraisal_category/appraisal_category.js
beams/beams/doctype/appraisal_category/appraisal_category.json
beams/beams/doctype/appraisal_category/appraisal_category.py
beams/beams/doctype/appraisal_category/test_appraisal_category.py
beams/beams/doctype/category/category.js
beams/beams/doctype/category/category.json
beams/beams/doctype/category_details/category_details.json

This feature introduces several key updates to the "Category" doctype, including renaming, adding new fields, and implementing validation logic.
- Added  field 'Appraisal Threshold' in Category doctype
- Added a validation to the "Category" doctype to ensure that the "Appraisal Threshold" field falls within the acceptable range of 0 to 5.
- Renamed Category doctype to Appraisal Category
[Screencast from 01-10-2025 11:08:48 AM.webm](https://github.com/user-attachments/assets/9bc5c018-e8e3-465a-a96e-35c471a540dd)
Category doctype-Renaming and validation logic
- Chrome
- Opera Mini
- Safari

feat: Customize Category Doctype

---

beams/www/job_application_upload/upload_doc.css
beams/www/job_application_upload/upload_doc.html

Update Job Application Upload Webpage.
- Added new section with heading General Details.
- Added styles for fields :  Gender,Country,Location, Tables.
- Removed fields : `current_period_To` and `mobile number` from Current Address section and removed `permanent_period_to` from Permanent Address section.
- Added a `checkbox` in Permanent Address section , by checking it will copy the address from current address.
- Fixed the alignment issue in the tab `Current Employment Details`.
- Added a script that will allow the job applicant who is a fresher to view only tabs : Personal Information and More Details.
- Added a script that will change the color of the submit button when submit button is clicked by checking the checkbox and also while clicking on submit button,redirect to another page. …

fix : Updated Job Application Upload Webpage.

---

beams/beams/doctype/program_request/program_request.js
beams/beams/doctype/program_request/program_request.json
beams/beams/doctype/program_request/program_request.py
beams/beams/doctype/program_request/test_program_request.py
beams/beams/doctype/program_type/program_type.js
beams/beams/doctype/program_type/program_type.json
beams/beams/doctype/program_type/program_type.py
beams/beams/doctype/program_type/test_program_type.py

Add new Doctypes for Program Request and Program Type
Program Request DocType
- Is Submittable
- Fields:
-- Posting Date (Date)(Default: Today)*
-- Program Details (Section Break)
-- Program Name (Data)*
-- Start Date (Date)*
-- End Date (Date)*
-- Description (small text)
-- Program Type (Link) - Program Type*
-- Generates Revenue (Check|Fetch From Program Type|Read Only)
-- Location (Link/Location)
-- Requirements (Text Editor)
Program Type DocType
- Master DocType
- Fields
-- Program Type (Data)*
-- Generates Revenue (Check)*
- Naming Series by fieldname Program Type
- Introduced new Doctype: Program Request
- Introduced new Doctype: Program Type
- These additions aim to support enhanced functionality and data structuring within the system.
Database Schema:Two new tables are added to …

feat:Add new Doctypes for Program Request and Program Type

---

beams/beams/doctype/program_request/program_request.json

Modified Program Request Form Layout so that:
- Tabbing is easier
- Cursor goes to Program Name field on New
- General Appearance
DocType
- Program Request
No
- Chrome
- Opera Mini
- Safari

chore: modified program request form layout

---

beams/beams/doctype/program_request/program_request.js

add validation for start date and end date
validation added in program request.j
program request
new feature
- Chrome
- Opera Mini
- Safari

fix:added validation in program request

---

beams/beams/doctype/bureau/bureau.json
beams/setup.py

--Introduce Location in Bureau and Bureau in Asset
--Added Location field to Bureau and Bureau field to Asset Doctype
--Asset Doctype
-- Bureau Doctype
--No. 

    TASK-2025-00072:Modify Bureau and Customize Asset

---

beams/beams/doctype/vehicle_type/test_vehicle_type.py
beams/beams/doctype/vehicle_type/vehicle_type.js
beams/beams/doctype/vehicle_type/vehicle_type.json
beams/beams/doctype/vehicle_type/vehicle_type.py

Create DocType Vehicle Type
Created Master  DocType Vehicle Type, add field Vehicle Type and Naming Series is by field name Vehicle Type
[Screencast from 18-01-25 11:11:17 AM IST.webm](https://github.com/user-attachments/assets/868e489d-f7ba-45f0-b3cb-9e13123d1ab6)
No

TASK-2025-00066:Created DocType Vehicle Type

---

beams/beams/doctype/equipment_hire_request/equipment_hire_request.js
beams/beams/doctype/equipment_hire_request/equipment_hire_request.json
beams/beams/doctype/equipment_hire_request/equipment_hire_request.py
beams/beams/doctype/equipment_hire_request/test_equipment_hire_request.py
beams/beams/doctype/required_hire_items_detail/required_hire_items_detail.json
beams/beams/doctype/required_hire_items_detail/required_hire_items_detail.py

Created doctype Equipment Hire Request with fields:
- Project (Link/Project)
- Bureau (Link)
- Posting Date (Date)
- Required From (Datetime)
- Required To (Datetime)
- Required Items (Table/Required Hire Item Detail)
This is a Submittable doctype.
Equipment Hire Request doctype.     
No
- Chrome

TASK-2025-00071:Created doctype Equipment Hire Request and child table Required  Hire Items  Detail.

---

beams/beams/doctype/required_hired_vehicle_detail/required_hired_vehicle_detail.js
beams/beams/doctype/required_hired_vehicle_detail/required_hired_vehicle_detail.json
beams/beams/doctype/required_hired_vehicle_detail/required_hired_vehicle_detail.py
beams/beams/doctype/required_hired_vehicle_detail/test_required_hired_vehicle_detail.py
beams/beams/doctype/transportation_request/test_transportation_request.py
beams/beams/doctype/transportation_request/transportation_request.js
beams/beams/doctype/transportation_request/transportation_request.json
beams/beams/doctype/transportation_request/transportation_request.py
beams/beams/doctype/vehicle_detail/vehicle_detail.json
beams/beams/doctype/vehicle_detail/vehicle_detail.py
beams/beams/doctype/vehicle_hire_request/test_vehicle_hire_request.py
beams/beams/doctype/vehicle_hire_request/vehicle_hire_request.js
beams/beams/doctype/vehicle_hire_request/vehicle_hire_request.json
beams/beams/doctype/vehicle_hire_request/vehicle_hire_request.py

Create Doctype named as Vehicle hire request with custom fields,add child table  named Required Hired Vehicle Detail 
Create Doctype Transportation Request with custom fields ,add child table Required Hired Vehicle Detail it shows only after saving
Doctype created named as Vehicle hire request with custom fields,child table added named  Required Hired Vehicle Detail
Created Doctype Transportation Request with custom fields ,added child table Required Hired Vehicle Detail it shows only after saved
No

TASK-2025-00065:Created  Vehicle Hire Request Doctype and Transportation Request Doctype

---

beams/beams/doctype/transportation_request/transportation_request.js
beams/beams/doctype/transportation_request/transportation_request.py

Need to: Create Vehicle Hire Request from Transportation Request
Mapped the fields like project,bureau and required_on in Vehicle Hire Request from Transportation Request
[Screencast from 21-01-25 01:04:46 PM IST.webm](https://github.com/user-attachments/assets/95c7034e-d218-496c-947c-6cb2a39a3636)
Transportation Request DocType
No. 

TASK-2025-00074:Created Vehicle Hire Request from Transportation Request

---

beams/beams/custom_scripts/project/project.js
beams/beams/custom_scripts/project/project.py
beams/beams/doctype/equipment_hire_request/equipment_hire_request.json

- Create a custom button in group create of doctype project
- Map necessary fields to the doctype 
- Created a custom  button equipment hire request in project
- Maps project name , bureau , start date and end date to the doctype
- Setting posting date as today
[Screencast from 20-01-25 05:24:58 PM IST.webm](https://github.com/user-attachments/assets/ab159ced-486c-4998-9258-55e9d1f5669d)

TASK-2025-00083 : Created equipment hire request from project

---

beams/beams/doctype/employee_travel_request/employee_travel_request.js
beams/beams/doctype/employee_travel_request/employee_travel_request.json
beams/beams/doctype/employee_travel_request/employee_travel_request.py
beams/beams/doctype/employee_travel_request/test_employee_travel_request.py
beams/beams/doctype/reference_document/reference_document.json
beams/beams/doctype/reference_document/reference_document.py
beams/beams/doctype/traveller/traveller.json
beams/beams/doctype/traveller/traveller.py

Implement a new DocType "Employee Travel Request" to manage travel requests with necessary  fields.
- Requested By: Link (Employee), Mandatory
- Posting Date: Date, Default Today, Mandatory
- Is Group: Check
- Travellers: Table Multiselect (Depends on "Is Group")
-  Added Travel Details: Section Break
- -     Is Unplanned: Check
- -     Travel Type: Link (Purpose of Travel), Mandatory
- -     Start Date / End Date: Datetime, Mandatory
- -     Total Days: Float
- -     Source: Link (Location), Mandatory
- -     Destination: Link (Location)
- -     Batta Policy: Link (Depends on "Is Group")
- -     Mode of Travel: Link (Filtered by Batta Policy if single)
- -     Inside Kerala: Check
- -     Accommodation Required: Check
- -     Room Criteria: Link (Filtered by Batta Policy if single)
- - …

TASK-2025-00108:Created doctype Employee Travel Request.

---

beams/__init__.py
beams/beams/custom_scripts/purchase_order/purchase_order.py
beams/beams/overrides/budget.py

- update monthly distribution in Budget.
- Added monthly distribution in Budget.
[Screencast from 21-01-25 11:55:03 PM IST.webm](https://github.com/user-attachments/assets/66d11fbd-d8cd-42b4-b104-eab6a32ba932)
No.

feat: Update Monthly distribution in Budget

---

beams/beams/doctype/award_expense_detail/award_expense_detail.json
beams/beams/doctype/award_expense_detail/award_expense_detail.py
beams/beams/doctype/award_record/award_record.js
beams/beams/doctype/award_record/award_record.json
beams/beams/doctype/award_record/award_record.py
beams/beams/doctype/award_record/test_award_record.py

Create a child table named "Award Expense Detail" 
-  Create a child table named "Award Expense Detail" with fields for **Remarks** (Small Text) and **Amount** (Currency).  
-  Create a DocType named "Award Record" with the following fields: **Employee** (Link to Employee), **Full Name** (Data, fetched from Employee), **Posting Date** (Date, default to Today), **Award Detail** (Small Text), and **Expenses** (Table referencing "Award Expense Detail").  
-  Add a field for **Total Amount** (Currency) in the "Award Record" DocType.
- Chrome
- Opera Mini
- Safari

feat:TASK-2025-00103

---

beams/beams/doctype/vehicle_document/test_vehicle_document.py
beams/beams/doctype/vehicle_document/vehicle_document.js
beams/beams/doctype/vehicle_document/vehicle_document.json
beams/beams/doctype/vehicle_document/vehicle_document.py

Create Doctype Vehicle Document with custom fields
Created Doctype Vehicle Document with custom fields
No

TASK-2025-00117: Vehicle Document Created

---

beams/beams/doctype/digital_library_request/digital_library_request.js
beams/beams/doctype/digital_library_request/digital_library_request.json
beams/beams/doctype/digital_library_request/digital_library_request.py
beams/beams/doctype/digital_library_request/test_digital_library_request.py

Create DocType Digital Library Request
Create a DocType for "Digital Library Request" with the following fields:  
- **Requested By**: A mandatory link field to the Employee making the request.  
- **Employee Full Name**: A read-only data field fetched automatically from the Employee record.  
- **Requirements**: A mandatory small text field to specify the request details.
new feature 
- Chrome
- Opera Mini
- Safari

feat: TASK-2025-00101-Create DocType Digital Library Request

---

beams/beams/doctype/makeup_consumption_entry/makeup_consumption_entry.py

- Create a stock entry on submitting the makeup consumption entry
- On submitting the makeup consumption entry a corresponding stock entry is created with the data in makeup consumption entry
[Screencast from 23-01-25 09:56:06 AM IST.webm](https://github.com/user-attachments/assets/f249cc72-be3e-471c-a648-ec54f781bf0a)
hots (optional)

TASK-2025-00097 : Create a stock entry on submission of makeup consumption entry

---

beams/beams/doctype/trip_sheet/trip_sheet.js

Need to: Create a button in Tripsheet to create Vehicle Incident Record
Created the button in Tripsheet to create Vehicle Incident Record.
[Screencast from 23-01-25 12:17:51 PM IST.webm](https://github.com/user-attachments/assets/08b85538-d09d-4a29-b78c-f511907e4d0a)
No. 

TASK-2025-00115:Add button in Tripsheet to create Vehicle Incident Record

---

beams/beams/doctype/vehicle_documents/vehicle_documents.json
beams/beams/doctype/vehicle_documents/vehicle_documents.py
beams/setup.py

Customize Vehicle Doctype ,Create child table Vehicle Documents
Customized Vehicle Doctype ,Created child table Vehicle Documents
Vehicle Doctype
No

TASK-2025-00118: Vehicle Doctype Customization

---

beams/beams/doctype/offense_type/offense_type.js
beams/beams/doctype/offense_type/offense_type.json
beams/beams/doctype/offense_type/offense_type.py
beams/beams/doctype/offense_type/test_offense_type.py
beams/beams/doctype/vehicle_incident_record/test_vehicle_incident_record.py
beams/beams/doctype/vehicle_incident_record/vehicle_incident_record.js
beams/beams/doctype/vehicle_incident_record/vehicle_incident_record.json
beams/beams/doctype/vehicle_incident_record/vehicle_incident_record.py

Need to:Create Vehicle Incident Record DocType and Offense Type DocType
Created Vehicle Incident Record Doctype with fields like:
Trip Sheet (Link/Trip Sheet)*
- Offense Type (Link/Create offense type master)*
- Posting Date (Date)*
- Offense Date and Time (Datetime)*
- Employee (Link/Employee)*
- Employee Name (fetch from employee/ro)
Vehicle Incident Record DocType
No. 

TASK-2025-00114:Create DocType Vehicle Incident Record

---

beams/beams/doctype/fuel_card/fuel_card.js
beams/beams/doctype/fuel_card/fuel_card.json
beams/beams/doctype/fuel_card/fuel_card.py
beams/beams/doctype/fuel_card/test_fuel_card.py
beams/beams/doctype/fuel_card_provider/fuel_card_provider.js
beams/beams/doctype/fuel_card_provider/fuel_card_provider.json
beams/beams/doctype/fuel_card_provider/fuel_card_provider.py
beams/beams/doctype/fuel_card_provider/test_fuel_card_provider.py
beams/beams/doctype/recharge_history/recharge_history.json
beams/beams/doctype/recharge_history/recharge_history.py

Create Doctype Fuel Card ,Create Master Doctype Fuel Card Provider linked field in Fuel Card, Create child table Recharge History with fields
Created Doctype Fuel Card ,Created Master Doctype Fuel Card Provider linked field in Fuel Card, Created child table Recharge History with fields
No

TASK-2025-00120: Fuel Card doctype Created

---

beams/beams/doctype/trip_sheet/trip_sheet.js
beams/beams/doctype/trip_sheet/trip_sheet.py

Need to:Implement the calculations in Distance Traveled and Fuel Consmption per Km in Trip Sheet
Implemented the calculations in Distance Traveled and Fuel Consmption per Km in Trip Sheet
[Screencast from 24-01-25 09:21:07 AM IST.webm](https://github.com/user-attachments/assets/54808206-d097-47ce-bc13-c08902a97fa3)
Trip Sheet
No. 

Implemented the calculations in Distance Traveled and Fuel Consmption per Km in Trip Sheet

---

beams/beams/doctype/service_unit/service_unit.js
beams/beams/doctype/service_unit/service_unit.json
beams/beams/doctype/service_unit/service_unit.py
beams/beams/doctype/service_unit/test_service_unit.py

- Create a doctype Service unit 
- Created a doctype Service Unit with fields :  
. Service unit name
. Type - Meeting room , Guest room
. Allow appointments
. Allow multiple appointments (depends on : Allow appointments)

TASK-2025-00152 : Created a new doctype Service unit

---

beams/beams/custom_scripts/leave_application/leave_application.js
beams/beams/custom_scripts/leave_application/leave_application.py
beams/beams/doctype/guest_appointment/guest_appointment.js
beams/beams/doctype/guest_appointment/guest_appointment.json
beams/beams/doctype/guest_appointment/guest_appointment.py
beams/beams/doctype/guest_appointment/test_guest_appointment.py

- Guest Type (Link/Guest Type)*
- Guest Name (Data)*
- Posting Date (Date)* Default Today
- Appointment Date(Date)*
- Appointment Time (Time)* Default Now
- Purpose of Visit (Small Text)*
- Received By (Link/Employee)*
- Remarks (Small Text)
Created doctype Guest Appointment.
Added Validation by checking if an approved Leave Application exists against that employee for the specified dates.
Guest Appointment doctype.
No
- Chrome

TASK-2025-00150:Created Doctype Guest Appointment.

---

beams/beams/doctype/patrol_log_detail/patrol_log_detail.json
beams/beams/doctype/patrol_log_detail/patrol_log_detail.py
beams/beams/doctype/security_patrol_log/security_patrol_log.js
beams/beams/doctype/security_patrol_log/security_patrol_log.json
beams/beams/doctype/security_patrol_log/security_patrol_log.py
beams/beams/doctype/security_patrol_log/test_security_patrol_log.py

Create Child Table Patrol Log Detail , Add Child Table Named Patrol Log Detail
Created Child Table Patrol Log Detail , Added Child Table Named Patrol Log Detail
No

TASK-2025-00156: Security Patrol Log doctype Created

---

beams/beams/doctype/outward_pass/outward_pass.js
beams/beams/doctype/outward_pass/outward_pass.json
beams/beams/doctype/outward_pass/outward_pass.py
beams/beams/doctype/outward_pass/test_outward_pass.py

Create Outward Pass Doctype with Custom Fields
Created Outward Pass Doctype with Custom Fields
No

TASK-2025-00156: Outward Pass Doctype Created

---

beams/beams/doctype/employee_travel_request_details/employee_travel_request_details.json
beams/beams/doctype/inward_register/inward_register.json
beams/beams/doctype/outward_register/outward_register.json
beams/beams/doctype/transportation_request_details/transportation_request_details.json

Need to :Correct the some spelling issues
Corrected the some spelling issues like Vistor Type to Visitor Type and Vistor Name to Visitor Name.
In Employee Travel Request  Details  Doctype and Transportation Request Details whose fields are changed to Mandatory
Inward Register Doctype,Outward Register Doctype, Employee Travel Request  Details  Doctype and Transportation Request Details
No. 

Fix:Corrected the some spelling issues

---

beams/beams/custom_scripts/vehicle/vehicle.py
beams/beams/doctype/beams_admin_settings/beams_admin_settings.json
beams/beams/doctype/vehicle_document/vehicle_document.json
beams/hooks.py

Send Notification Based On Vehicle Documents in Vehicle Doctype
Notification Sending Based On Vehicle Documents in Vehicle Doctype, When the Vehicle Expiry Date is Overdue or Expiring Soon
No

TASK-2025-00119: Sending Notification Based on Vehicle Documents in Vehicle Doctype

---

beams/setup.py

--Add department thresholds and CEO approval.
--Added department thresholds and modified workflow for CEO approval
--Now, if a department’s threshold is crossed, CEO approval is required before proceeding.
--Purchase Order Doctype

    TASK-2025-00142:modify Purchase Order workflow

---

beams/beams/doctype/guest_appointment/guest_appointment.js
beams/beams/doctype/guest_appointment/guest_appointment.json
beams/beams/doctype/guest_appointment/guest_appointment.py

- Created DocType Guest Appointment with fields:
- - Guest Name (Data)*
- - Posting Date (Date)* Default Today
- - Appointment Date(Date)
- - Appointment Time (Time)
- - Purpose of Visit (Small Text)*
- - Received By (Link/Employee)*
- - Remarks (Small Text)
- Workflow transitions:
- - Draft -> Pending (Employee)
- - Pending -> Approved (Admin)
- - Pending -> Rejected (Admin)
- Validated Attendance of Recieved by on Appointment date by checking if an approved leave exists for that employee on   the given date.
-   Notified  Received By (in guest appointment) Once Guest Appointment is Approved by creating aToDo task for that employee.
-  Added button in Guest Appointment to  to create Inward Register.
Guest Appointment Doctype.
No.
- Chrome

TASK-2025-00144:Created doctype Guest Appointment

---

beams/beams/doctype/vehicle_documents/vehicle_documents.json

Set Expiry Date Mandatory
Expiry Date Set to Mandatory
No

 Expiry Date Set to Mandatory

---

beams/beams/doctype/trip_sheet/trip_sheet.js
beams/beams/doctype/trip_sheet/trip_sheet.json
beams/beams/doctype/trip_sheet/trip_sheet.py

Need to : Filter the Multiselect fields in Trip Sheet Doctype.  
Change the field name Fuel Consumption Per Km changed to "Mileage"
Filtered the Multiselect fields like Travel Requests and Transportation Requests in Trip Sheet Doctype.
Changed the field name Fuel Consumption Per Km changed to "Mileage"
[Screencast from 27-01-25 04:50:23 PM IST.webm](https://github.com/user-attachments/assets/8fa29af9-8458-4919-868c-b85818d06bbd)
Trip Sheet Doctype 
No. 

Feat:Filtered the Multiselect fields in Trip Sheet Doctype

---

beams/beams/doctype/vehicle_hire_request/vehicle_hire_request.json

Make Fields change to Mandatory in Vehicle Hire Request
Fields change to Mandatory in Vehicle Hire Request
No

 Fields change to Mandatory in Vehicle Hire Request

---

beams/beams/doctype/required_hired_vehicle_detail/required_hired_vehicle_detail.json

Change Required Hired Vehicle Detail Doctype Fields to Mandatory
Required Hired Vehicle Detail Doctype Fields change to Mandatory
No

 Required Hired Vehicle Detail Doctype Fields change to Mandatory

---

beams/beams/custom_scripts/project_dashboard/project_dashboard.py
beams/hooks.py

- Add connection in doctype project
- Added connection with label Request and in it :  
- Adhoc Budget
- Equipment Hire Request
- Equipment Request
- Transportation Request
- Technical Request

feat :  Added new connection in doctype project

---

beams/beams/custom_scripts/project_dashboard/project_dashboard.py

- Rename and Rearrange the connection
- Renamed the connection all requests under Programs
- Renamed the all budgets under Budgets

chore : Renamed the connection names

---

beams/beams/doctype/equipment_request/equipment_request.js
beams/beams/doctype/equipment_request/equipment_request.json
beams/beams/doctype/equipment_request/equipment_request.py

Need to: Fix the issues in Equipment Request Doctype
Fixed the issues in Equipment Request Doctype:
Validated the required_from and required_to
Equipment Request Doctype
No. 

Fix:Fixed the issues in Equipment Request Doctype

---

beams/beams/doctype/inward_register/inward_register.py
beams/beams/doctype/visitor_pass/visitor_pass.js
beams/beams/doctype/visitor_pass/visitor_pass.py

Need to: Validate the Time field in Visitor Pass Doctype.
Change the field name Vistor Name to Visitor Name in Inward Register Doctype.  
Validated the Time field in Visitor Pass Doctype
Changed the field name Vistor Name to Visitor Name in Inward Register Doctype.  
Visitor Pass Doctype.
No. 

Feat:Validated the Time field in Visitor Pass Doctype

---

beams/beams/doctype/guest_appointment/guest_appointment.js

Need to: Fetch the form page instead of list view from Guest Appointment Doctype
Fetched the form page instead of list view from Guest Appointment Doctype
No. 

Fix:Fetched the form page instead of list view from Guest Appointment Doctype

---

beams/beams/custom_scripts/project/project.js
beams/beams/custom_scripts/project/project.py
beams/beams/doctype/equipment_request/equipment_request.js
beams/beams/doctype/required_items_detail/required_items_detail.json

The feature introduces a button called Assign Equipments that allows users to assign equipment for a project with the ability to view available quantities and request missing equipment either from internal stock or via hire.
A custom button Assign Equipments is added to a form.Upon clicking the button, a dialog is triggered that includes:
Fields to specify the required dates (From and To). A table to select items and specify required quantities for equipment.
The dialog fetches available quantities for each item, based on the current bureau and available assets.
The user can then submit the form, which results in creating:
Equipment Request (for available stock items).
Equipment Hire Request (for items that are in short supply and need to be hired).
The dialog filters available items …

feat:Assignment of equipments done from project

---

beams/beams/doctype/adhoc_budget/adhoc_budget.py

Fixed
- Chrome
- Opera Mini
- Safari

fix:Fixed adhoc budget amount

---

beams/beams/doctype/adhoc_budget/adhoc_budget.py

Revert "fix:Fixed adhoc budget amount"

---

beams/beams/custom_scripts/budget/budget.js
beams/beams/doctype/budget_tool/budget_tool.css
beams/beams/doctype/budget_tool/budget_tool.html
beams/beams/doctype/budget_tool/budget_tool.js
beams/beams/doctype/budget_tool/budget_tool.json
beams/beams/doctype/budget_tool/budget_tool.py
beams/beams/doctype/budget_tool/test_budget_tool.py

feat: Budget Tool

---

beams/beams/custom_scripts/department/department_dashboard.py
beams/hooks.py

Add connection Division in Department doctype.
Added connection Division in Department doctype.

feat: Add connection Divion in Department doctype

---

beams/beams/doctype/revenue/revenue.js
beams/beams/doctype/revenue/revenue.json
beams/beams/doctype/revenue/revenue.py
beams/beams/doctype/revenue/test_revenue.py
beams/beams/doctype/revenue_account/revenue_account.json
beams/beams/doctype/revenue_account/revenue_account.py

- Create New Doctype Revenue.
- Created New Doctype Revenue and its child table Revenue Account.
- Calculated Revenue amount based on Monthly amount distribution.
[Screencast from 31-01-25 03:21:07 PM IST.webm](https://github.com/user-attachments/assets/7f9da0f0-1255-4d69-a881-5b0eae517a17)
No.

feat: Create New Doctype Revenue

---

beams/beams/doctype/vehicle_hire_request/vehicle_hire_request.js

RemovePurchase Invoice Button from Vehicle Hire Request Button
Removed Purchase Invoice Button from Vehicle Hire Request Button
No

 Removed Purchase Invoice Button from Vehicle Hire Request Doctype

---

beams/hooks.py

Clearly and concisely describe the feature.
- Chrome
- Opera Mini
- Safari

fix: migration issue

---

beams/beams/doctype/makeup_consumption_entry/makeup_consumption_entry.py

- Validate Posting date must be today
- Validation given to posting date

fix : Validate posting date

---

beams/beams/doctype/award_expense_detail/award_expense_detail.json
beams/beams/doctype/award_record/award_record.js
beams/beams/doctype/award_record/award_record.json
beams/beams/doctype/award_record/award_record.py
beams/beams/doctype/equipment_hire_request/equipment_hire_request.js
beams/beams/doctype/equipment_hire_request/equipment_hire_request.json
beams/beams/doctype/equipment_hire_request/equipment_hire_request.py
beams/beams/doctype/equipment_request/equipment_request.js
beams/beams/doctype/equipment_request/equipment_request.json
beams/beams/doctype/equipment_request/equipment_request.py
beams/beams/doctype/guest_appointment/guest_appointment.js
beams/beams/doctype/guest_appointment/guest_appointment.py

validation for Award Request doctype
- change button name **action** to **create** and **create Journal Voucher** to **Journal Voucher**
- added validation for posting date , Posting Date cannot be set after today's date
- A function was added to update the total amount when a row is deleted from the Expense child table.
- Remarks  field changed to Expense Description
- The **total amount** and **employee name**  set to **read-only**
- **Full name** changed to **employee name**
- A button "Travel Request" appears in the "Award Request" form when workflow_state = "Awarded"
- Clicking the button creates a new "Travel Request" with pre-filled data from "Award Request".
Award Request doctype
- Chrome
- Opera …

fix:validation for Award Record doctype

---

beams/beams/doctype/digital_library_request/digital_library_request.json
beams/beams/doctype/employee_travel_request/employee_travel_request.js
beams/beams/doctype/employee_travel_request/employee_travel_request.json
beams/beams/doctype/employee_travel_request/employee_travel_request.py

1. Need to change the label name  of a field in digital library request doctype
2. Need to change the label name of field and position of the fields in the employee travel request doctype
3. Need to create attendance request from mark attendance in employee travel request doctype 
4. Need to Add validation for posting date in the employee travel request doctype
5.Need to add  a condition to check not filter the room criteria if employee which have not batta policy
6.Need to refresh the filed in employee travel request  
1.changed the label name  of a field in digital library request doctype
employe full name in to employee name
2.changed the label name of field and position of the fields in the employee travel request doctype
3. after checked the checkbox mark attendance created …

feat: Created Attendance Request on Mark Attendance in Employee Travel Request 

---

beams/beams/custom_scripts/budget/budget.js
beams/beams/doctype/budget_template/budget_template.js
beams/beams/doctype/budget_template/budget_template.json
beams/beams/doctype/budget_template/budget_template.py

filters on Budget and Budget Template
No
- Chrome

feat: filters on Budget and Budget Template

---

beams/beams/doctype/vehicle_hire_request/vehicle_hire_request.js
beams/beams/doctype/vehicle_hire_request/vehicle_hire_request.py

Add Posting date validation in Vehicle Hire Request Doctype
Added Posting date validation in Vehicle Hire Request Doctype
No

fix: Posting Date Validation

---

beams/beams/doctype/division/division.py

- Update Division Naming Series.
- Updated Division field in Division when we rename the division document.
[Screencast from 04-02-25 03:48:47 PM IST.webm](https://github.com/user-attachments/assets/f3f16a8d-57f2-4899-bf92-00b0ac53e4da)
No.

fix: Update Division Naming Series

---

beams/beams/custom_scripts/interview/interview.js

✅ Fix issue where interview feedback result was cleared after saving
✅ Included functionality to fetch and display existing feedback for the job applicant.
[Screencast from 05-02-25 12:26:22 PM IST.webm](https://github.com/user-attachments/assets/c3617e85-1b2e-4f9d-b4ce-c796c7aa605a)
✅ Interview Feedback Doctype
✅ Yes 
✅ Mozilla Firefox

ISS-2025-00015:issue where interview feedback result was clearing after save

---

beams/beams/doctype/budget_tool/budget_tool.py

Fixed Error in Budget Tool
- Chrome
- Opera Mini
- Safari

fix:fixed budget tool error

---

beams/beams/doctype/award_record/award_record.json
beams/beams/doctype/provident_fund/provident_fund.json
beams/beams/doctype/shift_swap_request/shift_swap_request.json

- Fetching first name on fetching employee instead of full name 
- Fetching of name is given as his/her name(Full Name) instead of first name

fix : Fetching of employee name changed to his/her name

---

beams/beams/doctype/equipment_acquiral_request/equipment_acquiral_request.js
beams/beams/doctype/equipment_request/equipment_request.js
beams/beams/doctype/required_acquiral_items_detail/required_acquiral_items_detail.json

Need to: Create Service Purchase Order Button from Equipment Acquiral Request Doctype  to Purchase Order Doctype
Created Service Purchase Order Button from Equipment Acquiral Request Doctype  to Purchase Order Doctype
[Screencast from 05-02-25 05:28:48 PM IST.webm](https://github.com/user-attachments/assets/e28e0552-35a1-46b6-a2a3-9e4d6d3e2026)
Equipment Acquiral Request Doctype
No.

Feat:Created Service Purchase Order Button from Equipment Acquiral Request Doctype  to Purchase Order Doctype

---

beams/beams/doctype/program_request/program_request.json
beams/setup.py

Need to: 
- Add Location field in Project Doctype.
- Add Location field as mandatory in Program Request Doctype.
- Added Location field in Project Doctype
- Added Location field as mandatory in Program Request Doctype.
Project Doctype 
Program Request Doctype
No. 

Feat:Added Location field in Project Doctype

---

beams/beams/custom_scripts/appraisal/appraisal.js
beams/beams/custom_scripts/appraisal/appraisal.py

✅ Validate 'marks' field in 'employee_self_kra_rating' table
✅ Added check to prevent 'marks' from being greater than 5 in the 'employee_self_kra_rating' table.
✅  Included form-level validation to prevent submission if any 'marks' value exceeds 5.
[Screencast from 06-02-25 01:55:56 PM IST.webm](https://github.com/user-attachments/assets/147b51e2-c0bc-49e9-be5a-4afd85418467)
✅ Appraisal Doctype
✅ No
✅ Mozilla Firefox

feat:Add validation for 'marks' field in 'employee_self_kra_rating' table

---

beams/beams/doctype/equipment_acquiral_request/equipment_acquiral_request.json
beams/beams/doctype/equipment_request/equipment_request.json
beams/beams/doctype/external_resource_request/external_resource_request.json
beams/beams/doctype/technical_request/technical_request.json
beams/beams/doctype/transportation_request/transportation_request.json
beams/beams/doctype/vehicle_hire_request/vehicle_hire_request.json

Need to: Add Location fields in Doctypes like Equipment Request , Equipment Acquiral Request , Technical Request, Transportation Request , External Resource Request , Vehicle Hire Request . 
Add Location fields in Doctypes like Equipment Request , Equipment Acquiral Request , Technical Request, Transportation Request , External Resource Request , Vehicle Hire Request . 
Equipment Request , Equipment Acquiral Request , Technical Request, Transportation Request , External Resource Request Vehicle Hire Request Doctypes 
No

Feat:Added Location fields in Doctypes

---

beams/beams/custom_scripts/project/project.py
beams/beams/doctype/equipment_request/equipment_request.py

add location in doctype through code
add a location when mapping the project to Equipment Acquiral Request, Transportation Request, Technical Request, and 
Equipment Request to Equipment Acquiral Request
project , Equipment Acquiral Request, Transportation Request, Technical Request, and 
Equipment Request , Equipment Acquiral Request
- Chrome
- Mozilla Firefox-yes 
- Opera Mini
- Safari

feat:add location in doctype through code

---

beams/beams/doctype/employee_travel_request/employee_travel_request.js
beams/beams/doctype/external_resource_request/external_resource_request.py
beams/beams/doctype/transportation_request/transportation_request.py
beams/beams/doctype/vehicle_hire_request/vehicle_hire_request.json

Need to: 
- Fix the TypeError issue in External Resource Request Doctype.  
- Map the location field from  Transportation Request Doctype to Vehicle Hire Request Doctype.
- Remove the Purchase Invoice Button in Employee Travel Request Doctype.  
- Fixed the TypeError issue in External Resource Request Doctype.
- Mapped the location field from  Transportation Request Doctype to Vehicle Hire Request Doctype.
- Remove the Purchase Invoice Button in Employee Travel Request Doctype. 
[Screencast from 07-02-25 02:22:41 PM IST.webm](https://github.com/user-attachments/assets/2f4515f2-866e-468d-9ba6-40832f1ec131)
- External Resource Request Doctype.
- Vehicle Hire Request Doctype.
- Employee Travel Request Doctype. 
No. 

Fix:fixed the TypeError issue in External Resource Request Doctype

---

beams/beams/custom_scripts/project/project.js

- Apply dynamic Employee filtering based on Designation in the Allocated Resource Detail.
- I implemented dynamic filtering for the employee field based on the selected designation in the allocated resource detail child table.  
- Ensured the filter is applied both when the form loads and when the Designation field is changed.  
- Cleared the Employee field whenever the Designation is modified or cleared to prevent incorrect selections.  
- Refreshed the child table to reflect updated filters dynamically.  
project doctype
- Chrome
- Opera Mini
- Safari

feat:Apply dynamic Employee filtering based on Designation in Allocated Resource Detail

---

beams/beams/custom_scripts/purchase_order/purchase_order.py
beams/beams/doctype/equipment_request/equipment_request.js
beams/beams/doctype/equipment_request/equipment_request.py
beams/beams/doctype/required_items_detail/required_items_detail.json

1.need to optimize the code condition to prevent duplicate updates
1.optimize the code condition to prevent duplicate updates
- add condition to check  prevent updates when Purchase Order is per_billed 100 
purchase order 
No.

fix: Optimize code condition to prevent duplicate updates

---

beams/beams/custom_scripts/project/project.js

- Remove the existing filter in the child table of dialog in equipment request 
- Removed the code for filter in child table

feat : Remove the existing filter

---

beams/beams/doctype/technical_request/technical_request.json

Remove Mandatory
Mandatory Removed
No

feat: Mandatory Removed

---

beams/beams/custom_scripts/employee/employee.py
beams/hooks.py
beams/setup.py

Employee naming series based on Department
No
- Chrome

feat: Employee naming series based on Department

---

beams/beams/custom_scripts/budget/budget.js

Fixed issue in budget template auto-fetching based on division
- Chrome

fix:fixed issue in budget template auto-fetching

---

beams/beams/custom_scripts/leave_allocation/leave_allocation.py

The permission issue occurs for an employee with a double shift assignment when attempting to perform an employee checkout.This Restricts creation of Compensatory Leave Log.
- Chrome
- Opera Mini
- Safari

fix: Permission issue occurs while employee checkout

---

beams/www/job_portal/index.py

-Update job portal to display newest listings first.
-Changed job listings order to show newest first
[Screencast from 21-02-25 01:02:51 PM IST.webm](https://github.com/user-attachments/assets/2c04ac06-5221-420b-9d04-a098d8edceab)
-No. 

feat:Sort job listings from newest to oldest in the job portal

---

beams/beams/doctype/budget_template/budget_template.js

- Update Budget Template Item Child table.
- Updated Budget Template Item Child Table.
[Screencast from 24-02-25 10:17:58 AM IST.webm](https://github.com/user-attachments/assets/b320267c-bafb-421f-b59d-2f283c64ed19)
No.

fix: update Budget Template Items

---

beams/beams/custom_scripts/employee_dashboard/employee_dashboard.py

Add asset in connections of employee
Added asset in connections of employee
List out the areas affected by your code changes.( employee doctype)
- Chrome

feat: add asset in connections of employee

---

beams/beams/report/damage_history_report_for_assets/damage_history_report_for_assets.js
beams/beams/report/damage_history_report_for_assets/damage_history_report_for_assets.json
beams/beams/report/damage_history_report_for_assets/damage_history_report_for_assets.py

Added fields in Asset Damage History Report
- Added fields in Item Code,Total Asset Cost .
- added filters for   Item Code
[Screencast from 24-02-25 02:43:20 PM IST.webm](https://github.com/user-attachments/assets/aa8e9437-0f4e-4fd2-9c8a-576ee6804b48)
- Asset 
- Asset Repair 
- Asset Auditing
- Chrome
- Mozilla Firefox - YES
- Opera Mini
- Safari

feat:Added fields in Asset Damage History Report

---

beams/setup.py

Correct spelling in Attendance Request reason options ("Forget" → "Forgot")
- Chrome
- Opera Mini
- Safari

fix: change the option names in Attendance Request

---

beams/beams/doctype/cost_subhead/cost_subhead.js
beams/beams/doctype/cost_subhead/cost_subhead.py

- Add Custom button Update Budget Template in Cost Subhead.
- Added custom button Update Budget Template in Cost subhead for update cost subhead in Budget Template.
[Screencast from 25-02-25 11:15:15 AM IST.webm](https://github.com/user-attachments/assets/301fa643-d7e7-426a-94a7-961284ab5131)
No.

feat: Create Custom Button Update Budget Template in Cost Subhead

---

beams/beams/doctype/asset_bundle/asset_bundle.js
beams/beams/doctype/asset_bundle/asset_bundle.py
beams/beams/doctype/asset_return_check/asset_return_check.json
beams/beams/doctype/asset_return_check/asset_return_check.py
beams/beams/doctype/asset_return_checklist/asset_return_checklist.json
beams/beams/doctype/asset_return_checklist/asset_return_checklist.py
beams/beams/doctype/asset_return_checklist_template/asset_return_checklist_template.js
beams/beams/doctype/asset_return_checklist_template/asset_return_checklist_template.json
beams/beams/doctype/asset_return_checklist_template/asset_return_checklist_template.py
beams/beams/doctype/asset_return_checklist_template/test_asset_return_checklist_template.py
beams/beams/doctype/asset_transfer_request/asset_transfer_request.js
beams/beams/doctype/asset_transfer_request/asset_transfer_request.json
beams/beams/doctype/asset_transfer_request/asset_transfer_request.py

Child DocType: Asset Return Checklist
. DocType: Asset Return Checklist Template
. DocType: Asset Transfer Request
Fields:
Posting Date (Date) (Required, allow backdated but not future dates)
Posting Time (Time) (Required)
Asset Type (Select: "Single Asset" / "Bundle") (Required)
Bundle (Link/Asset Bundle) (Shown if Asset Type = "Bundle")
Assets (Asset Bundle Stock Item, fetch assets from Bundle if Asset Type = "Bundle")
Items (Table from Bundle for Stock Items) (Shown if Asset Type = "Bundle", fetch from Bundle if it contains Stock Items)
Asset Return Checklist Template (Link/Asset Return Checklist Template) (Allow selection on Submit)
Asset Return Checklist (Table/Asset Return Checklist) (Allow on Submit, auto-populate items from selected Template)
.Child DocType Created: Asset Return …

feat:TASK-2025-00194 Asset Transfer Request Doctype Created

---

beams/beams/doctype/outward_pass/outward_pass.js
beams/beams/doctype/outward_pass/outward_pass.json
beams/beams/doctype/outward_pass/outward_pass.py
beams/beams/report/employee_allocated_asset_report/employee_allocated_asset_report.js
beams/beams/report/employee_allocated_asset_report/employee_allocated_asset_report.json
beams/beams/report/employee_allocated_asset_report/employee_allocated_asset_report.py

Modify Outward Pass
- added Bundles (Tabe MultiSelect for Asset Bundle)
- added Assets (Table Multiselect for Assets)
- added Stock Items (Table/Stock Items table in Asset Bundle)
- Fixed Recursive Asset Fetching in bundle_asset_fetch by ensuring assets are correctly added.
-  Ensure Correct Asset Fetching and Merging in Outward Pass
- created Employee Allocated Asset Report
[Screencast from 25-02-25 03:04:30 PM IST.webm](https://github.com/user-attachments/assets/542c27c7-5db3-4a75-9139-3b56d6300ccd)
- Outward Pass
- Chrome
- Opera Mini
- Safari

feat:TASK-2025-00263 - Modify Outward Pass

---

beams/beams/doctype/employee_checkin_permission/employee_checkin_permission.js
beams/beams/doctype/employee_checkin_permission/employee_checkin_permission.json
beams/beams/doctype/employee_checkin_permission/employee_checkin_permission.py
beams/beams/doctype/employee_checkin_permission/test_employee_checkin_permission.py

Create doctype Employee Checkin Permission
- Chrome
- Opera Mini
- Safari

feat: Create doctype Employee Checkin Permission

---

beams/beams/custom_scripts/job_applicant/job_applicant.py

-Remove job applicant minimum experience validation in job portal
-No experience validation is required, even if the 'Minimum Experience Required' is set in the job requisition. Applicants should still be able to submit their application(ISS-2025-00042)
-Allowed applicants to submit even if minimum experience is required
[Screencast from 26-02-25 10:39:42 AM IST.webm](https://github.com/user-attachments/assets/ef5ae905-0e48-40c4-896d-f5d65eca6b4f)
-No. 

fix:Remove minimum experience validation for Job Applicant in Job Portal

---

beams/beams/doctype/asset_transfer_request/asset_transfer_request.py

Need to: Mark Assets in the request as In Transit When Asset Transfer Request is Approved and Uncheck it once it is Transferred.
Marked Assets in the request as In Transit When Asset Transfer Request is Approved and Unchecked it once it is Transferred.
[Screencast from 26-02-25 05:16:28 PM IST.webm](https://github.com/user-attachments/assets/f6333281-2878-4286-90be-b04e1d8a555c)
[Screencast from 26-02-25 05:20:40 PM IST.webm](https://github.com/user-attachments/assets/54ad27c8-f207-4683-8d69-6c3632280e01)
Asset Doctype
No. 

Feat:Mark Assets in the request as In Transit When Asset Transfer Request is Approved and Uncheck it once it is Transferred.

---

beams/beams/doctype/cost_subhead/cost_subhead.js
beams/beams/report/budget_comparison_report/budget_comparison_report.py

- Add Company filter in Cost Subhead.
- Applied company filter in Account of Cost Subhead.
No.

fix: Applied company filter in account of Cost subhead

---

beams/beams/custom_scripts/budget/budget.js
beams/beams/custom_scripts/budget/budget.py
beams/beams/doctype/budget_template/budget_template.json
beams/beams/doctype/division/division.json
beams/beams/doctype/region/region.json
beams/hooks.py
beams/setup.py

- Apply Company filters in division and region in Budget.
- Add company field in division and region
- Customize Budget doctype
- Calculate total amount based on budget amount.
- Update Budget Template doctype
- Applied Company filters in division and region in Budget.
- Added company field in division and region
- Customized Budget doctype
- Calculated total amount based on budget amount.
- Updated Budget Template doctype
[Screencast from 01-03-25 12:20:47 PM IST.webm](https://github.com/user-attachments/assets/e44de0bc-32f4-451f-bacc-ab6d933b0948)
No.

fix: Update Budget,Division and Region Doctype

---

beams/setup.py

Reorder Job Requisition fields
- Chrome
- Opera Mini
- Safari

feat: Reorder Job Requisition fields

---

beams/beams/doctype/budget_template/budget_template.js
beams/beams/doctype/revenue/revenue.js
beams/beams/doctype/revenue/revenue.json
beams/beams/doctype/revenue/revenue.py
beams/beams/doctype/revenue_account/revenue_account.json

- Customize Revenue and Revenue Account.
- Calculate Total Amount based on revenue amount.
- Calculate revenue amount based on monthly distribution.
- Apply company filter in Budget Template.
- Added custom fields in Revenue and Revenue Account.
- Calculated Total Amount based on revenue amount.
- Calculated revenue amount based on monthly distribution.
- Applied company filter in Budget Template.
No.

feat: Update Revenue Doctype

---

beams/beams/custom_scripts/budget/budget.js

- Update Department in Budget when the company is changed.
- Cleared Department in  Budget when the company is changed.
[Screencast from 01-03-25 03:14:48 PM IST.webm](https://github.com/user-attachments/assets/913ffa0a-da84-45d1-ac01-3cab17e11fb7)
No.

fix: Update Department in Budget when the company is changed

---

beams/beams/doctype/budget_template/budget_template.js
beams/beams/doctype/budget_template/budget_template.json

- Customize Budget Template.
- update department and division in budget template when the company is changed.
- Customized Budget Template Doctype.
- Updated department and division in budget template when the company is changed.
[Screencast from 01-03-25 03:53:07 PM IST.webm](https://github.com/user-attachments/assets/ca44f6ba-7142-46cb-9fb4-727e3f03eeb8)
No.

fix: Update Budget Template

---

beams/setup.py

Need to arrange field properly to look better
- Chrome
- Opera Mini
- Safari

fix: Rearrange fields in Job Requisition

---

beams/beams/doctype/cost_subhead/cost_subhead.json
beams/beams/report/budget_comparison_report/budget_comparison_report.js

- Remove account from Cost Subhead.
- Add Totals in Budget Comparison Report.
- Removed account from Cost Subhead.
- Added Totals in Budget Comparison Report.
[Screencast from 03-03-25 01:24:20 PM IST.webm](https://github.com/user-attachments/assets/b0796f15-3c4e-4c75-ad42-53f54a3cd283)
No.

feat: Added Totals In Budget Comparison Report

---

beams/beams/custom_scripts/job_applicant/job_applicant.py
beams/hooks.py
beams/www/job_application_form/index.html
beams/www/job_application_form/index.js

1. In Job Applicant,remove validation
2. validation for Applicant Name such that only characters are allowed.
3. resume is uploaded after double clicking the resume field make into one
1. Added validation on text field that manditory and characterOnly.
2. made the pdf upload corrected 
[Screencast from 03-03-25 03:57:24 PM IST.webm](https://github.com/user-attachments/assets/d34216c2-4d17-4ce5-82e9-9d74159abea3)
shots (optional)
job_application_form
No
- Chrome

Prevent Multiple Clicks in Resume Uploads in Job Application

---

beams/beams/custom_scripts/job_applicant/job_applicant.py
beams/hooks.py
beams/www/job_application_form/index.html
beams/www/job_application_form/index.js

Revert "Prevent Multiple Clicks in Resume Uploads in Job Application"

---

beams/beams/doctype/asset_bundle/asset_bundle.js

Remove Assets when Removing Corresponding Bundle
Removed Assets when Removing Corresponding Bundle
[Screencast from 04-03-25 11:00:43 AM IST.webm](https://github.com/user-attachments/assets/57b99b1e-6509-4c4d-a9a0-1f3e45d30890)
No

feat: Removed Assets when Removing Corresponding Bundle

---

beams/beams/custom_scripts/interview/interview.js
beams/beams/custom_scripts/job_applicant/job_applicant.py
beams/hooks.py
beams/www/job_application_form/index.html
beams/www/job_application_form/index.js

1. In Job Applicant,remove validation
2. validation for Applicant Name such that only characters are allowed.
3. resume is uploaded after double clicking the resume field make into one
4. Add validation to check if the entered interview time 
1. Added validation on text field that manditory and characterOnly.
2. made the pdf upload corrected
3. Added validation in Interview doctype in time fields
[Screencast from 03-03-25 03:57:24 PM IST.webm](https://github.com/user-attachments/assets/15ceac06-aee2-492f-a0ae-65808e80022a)
No
- Chrome

feat: added validation and prevent double click error in resume attactment

---

beams/beams/custom_scripts/interview_feedback/interview_feedback.py
beams/beams/doctype/applicant_interview_round/applicant_interview_round.json
beams/hooks.py

- Fetch Applicant Rating In Job Applicant from Interview Feedback.
- Add applicant rating field in Applicant Interview Round Child table.
- Fetches Applicant Rating In Job Applicant from Interview Feedback.
- Customized Applicant Interview Round.
[Screencast from 04-03-25 05:53:04 PM IST.webm](https://github.com/user-attachments/assets/04d0f03b-85a5-4d85-8d8a-d671f8515713)
No.

    TASK-2025-00292 : Fetch Applicant Rating In Job Applicant from Interview Feedback

---

beams/beams/doctype/finance_group/finance_group.json
beams/beams/report/budget_allocation/budget_allocation.js
beams/beams/report/budget_allocation/budget_allocation.json
beams/beams/report/budget_allocation/budget_allocation.py
beams/beams/report/budget_comparison_report/budget_comparison_report.js
beams/beams/report/budget_comparison_report/budget_comparison_report.py

Budget Allocation Report and Finance Group
No
- Chrome

feat: Budget Allocation Report and Finance Group

---

beams/beams/report/budget_allocation/budget_allocation.js
beams/beams/report/budget_comparison_report/budget_comparison_report.js
beams/setup.py

Filter for cost subhead in reports

feat: filter for cost subhead in reports

---

beams/beams/custom_scripts/interview/interview.py

This feature adds validation to the Interview doctype, ensuring that an interview can only be submitted if all listed interviewers have submitted feedback.
- The system retrieves all interviewers listed under the Interview Details child table.
- It checks whether each interviewer has submitted feedback in the Interview Feedback doctype (with docstatus = 1).
- If any interviewers have not submitted feedback, the system raises an error, listing the missing interviewers.
- This prevents interviews from being submitted with incomplete feedback.
Interview doctype.
No
- Chrome

ISS-2025-00081:Added validation for interviewers in Feedback submission

---

beams/beams/doctype/shift_swap_request/shift_swap_request.py

Modify shift swap logic to ensure only the requested date range is swapped without canceling the entire shift assignment.
Currently, when a shift swap is approved, the entire shift assignment for an employee is canceled, even if the swap affects only a single day. The new approach should:
-  Identify the affected shift period.
-   Split the shift assignment into separate records if necessary.
-   Ensure only the swapped date is modified.
- Instead of canceling the entire shift assignment, check if the shift spans multiple days.
- If the shift covers dates before and after the swap date, split it into multiple shift assignments.
- Create a new shift assignment only for the swapped date with the updated employee.
- Maintain the original shift assignments for unaffected dates.
shift swap …

fix: Preserve Original Shift Assignments During Shift Swap

---

beams/beams/custom_scripts/interview_feedback/interview_feedback.py

- Update Applicant Rating In Job Applicant.
- Updated Applicant Rating In Job Applicant.
No.

fix: Update Applicant Rating in Job Applicant

---

beams/beams/custom_scripts/employee/employee.js

- Syntax error in employee
- Unwanted code removed

fix : Syntax Error in employee

---

beams/beams/custom_scripts/employee_dashboard/employee_dashboard.py

-Fix issue when accessing Connection tab in Employee
-Resolved issue when accessing Connection tab in Employee
-Employee Doctype
-No

fix:Resolve error when clicking Connection tab in Employee

---

beams/beams/custom_scripts/employee/employee.js
beams/patches.txt
beams/patches/no_of_children_patch.py
beams/setup.py

- Add patches for field no_of_children in Employee
- Change company phone type as phone
- Get value of user in reports_to of Employee
- Patches added for no of children
- Company phone number set to field_type phone
- Taken user id from reports_to to approvers

fix : Issue fixing in Employee

---

beams/setup.py

Fix error in company no in employee
- Fix error in company no in employee
- change data type of company_number
- employee
- Chrome
- Opera Mini
- Safari

feat:change data type of company_number

---

beams/beams/doctype/division/division.js

- Apply company filter in department of division doctype.
- Added company filters in department of division doctype.
No.

feat: Added Department filter in Division Doctype.

---

beams/beams/custom_scripts/appraisal/appraisal.js
beams/beams/custom_scripts/appraisal/appraisal.py
beams/beams/doctype/category_details/category_details.json
beams/hooks.py

Add a button in Appraisal to assign tasks to list of Assessment Officers.
A button labelled Assessment Officers was added and on clicking this button task assignment to list of officers is triggered. Task  is assigned in sequential order.
Appraisal Doctype
No
- Chrome

TASK-2025-00308 feat: Notification sent for Asset Reservation

---

beams/beams/custom_scripts/appraisal/appraisal.js
beams/beams/custom_scripts/appraisal/appraisal.py
beams/beams/doctype/category_details/category_details.json
beams/hooks.py

Add a button in Appraisal to assign tasks to list of Assessment Officers.
A button labelled Assessment Officers was added and on clicking this button task assignment to list of officers is triggered. Task  is assigned in sequential order.
Appraisal Doctype
No
- Chrome

Assessment officers Task assignment triggered on button click.

---

beams/beams/custom_scripts/budget/budget.js
beams/beams/custom_scripts/budget/budget.py
beams/hooks.py
beams/setup.py

- Customize Budget Doctype.
- Fetch Budget Template items in to Budget Accounts,
- Customized Budget Doctype.
- Fetches Budget Template Items into Budget Accounts.
No.

feat: Update Budget Accounts

---

beams/beams/custom_scripts/budget/budget.py
beams/setup.py

Total Amount in Budget should be in company currency
Issue with calculatuon in budget

Budget custom

---

beams/setup.py

Need to  :
Add Budget Verifier,Budget Verifier Finance and Budget Approver roles 
Added  Budget Verifier,Budget Verifier Finance and Budget Approver roles through setup.py
No. 

Feat:Added new roles like Budget Verifier,Budget Verifier Finance and Budget Approver

---

.github/workflows/master.yml
beams/beams/custom_scripts/budget/budget.js
beams/beams/custom_scripts/budget/budget.py
beams/beams/custom_scripts/customer/customer.py
beams/beams/custom_scripts/lead/lead.js
beams/beams/custom_scripts/opportunity/opportunity.js
beams/beams/custom_scripts/quotation/quotation.js
beams/beams/custom_scripts/sales_invoice/sales_invoice.js
beams/beams/custom_scripts/sales_order/sales_order.js
beams/beams/doctype/budget_template/budget_template.json
beams/beams/doctype/division/division.js
beams/beams/doctype/division/division.json
beams/beams/doctype/division/division.py
beams/beams/doctype/finance_group/finance_group.js
beams/beams/doctype/finance_group/finance_group.json
beams/beams/doctype/finance_group/finance_group.py
beams/beams/doctype/finance_group/test_finance_group.py
beams/beams/report/budget_allocation/budget_allocation.js
beams/beams/report/budget_allocation/budget_allocation.py
beams/beams/report/budget_comparison_report/budget_comparison_report.js
beams/beams/report/budget_comparison_report/budget_comparison_report.py
beams/beams/report/detailed_budget_allocation_report/detailed_budget_allocation_report.js
beams/beams/report/detailed_budget_allocation_report/detailed_budget_allocation_report.json
beams/beams/report/detailed_budget_allocation_report/detailed_budget_allocation_report.py
beams/beams/report/detailed_budget_allocation_report/detailed_budget_allocation_report_old.py
beams/hooks.py
beams/patches.txt
beams/patches/update_budget_for_inr.py
beams/setup.py

Changes Made in the master branch needs to be merged into the develop branch
Fixed conflict in setup.py, all other changes are from master branch

Merge master branch changes into develop branch

---

beams/beams/doctype/required_manpower_details/required_manpower_details.json
beams/beams/doctype/required_manpower_details/required_manpower_details.py
beams/setup.py

1. Create a new child doctype Required Manpower Details
2. Under the Required Details section:
add:
- Required Manpower (Table/Required Manpower Details)
creted doctype and added it the project
No
- Chrome

feat: created required manpower child doctype and added to it in project

---

beams/setup.py

Issue Fixing
- Chrome
- Opera Mini
- Safari

fix: Issue Fix

---

beams/beams/custom_scripts/project/project.py
beams/beams/doctype/allocated_vehicle_details/allocated_vehicle_details.json
beams/beams/doctype/allocated_vehicle_details/allocated_vehicle_details.py
beams/beams/doctype/required_vehicle_details/required_vehicle_details.json
beams/beams/doctype/required_vehicle_details/required_vehicle_details.py
beams/beams/doctype/transportation_request/transportation_request.json
beams/beams/doctype/transportation_request/transportation_request.py
beams/setup.py

Modify the functinality in project to create Transportation request , and re-map transportation request to project
- Create a Child Doctype: Required Vehicle Details
- Modify Create → Transportation Request Button
Generate a Transportation Request based on Required Vehicle Details.
Map necessary details from Required Vehicle Details to Transportation Request.
- Create a Child Doctype: Allocated Vehicle Details
- Update Project's Allocated Details Section
- Add "Allocated Vehicles" (Table/Allocated Vehicle Details).
Automate Vehicle Allocation Update
- When Transportation Request & Vehicle Hire Details are approved, update Allocated Vehicle Details in the Project.
[Screencast from 20-03-25 09:42:00 AM IST.webm](https://github.com/user-attachments/assets/de9c3b6d-6ae4-4c79-b80b-3ceeb054000b) …

feat:Modify the functinality in project to create Transportation request

---

beams/beams/custom_scripts/payment_entry/payment_entry.js
beams/beams/custom_scripts/voucher_entry/voucher_entry.js
beams/beams/custom_scripts/voucher_entry/voucher_entry.py
beams/beams/doctype/batta_claim/batta_claim.json
beams/beams/doctype/petty_cash_request/petty_cash_request.js
beams/beams/doctype/petty_cash_request/petty_cash_request.json
beams/beams/doctype/petty_cash_request/petty_cash_request.py
beams/beams/doctype/petty_cash_request/test_petty_cash_request.py
beams/beams/doctype/stringer_bill/stringer_bill.js
beams/beams/doctype/stringer_bill/stringer_bill.json
beams/beams/doctype/stringer_bill_detail/stringer_bill_detail.json
beams/beams/doctype/stringer_type/stringer_type.json
beams/hooks.py
beams/setup.py

- Add Stringer Amount In Stringer Type Doctype.
- Add some fields in Stringer Bill Detail(Stringer Type,Stringer Amount)
- Rearrange fileds of Stringer Bill Detail.
- Customize Stringer Bill Detail.
- Calculate Stringer Amount on the basis of amount of Stringer type.
- Fetch Amount from Stringer Type.
- When selecting Supplier,fetch area from that supplier in stringer Bill.
- Add Area field in Supplier Doctype(when is_stringer ==1)
- Create Doctype Petty Cash Request(with fields Bureau,Requested Person,Requested Employee,Requested Amount,Mode Of Payment,Account)
- Add Custom Button Petty cash request in Voucher Entry.
- When click the button Petty cash Request,display pop up message for Petty Cash Request.
- Fetch Bureau,mode of Payment, and account from voucher entry in to popup.
- When …

feat: Update Accounts

---

beams/beams/doctype/revenue_budget/revenue_budget.js

Validation for Revenue Centre
Validated revenue centre
No

fix: Validate revenue centre

---

beams/beams/custom_scripts/training_program/training_program.js
beams/beams/custom_scripts/training_program/training_program.py
beams/hooks.py

Apply validation for phone number & Email in Training Program doctype
Applied validation for phone number & Email in Training Program doctype
[Screencast from 07-03-25 12:42:33 PM IST.webm](https://github.com/user-attachments/assets/9259d67f-571f-483b-9413-99294cf746c1)
- Chrome

feat: validation for email and contact number in training program doctype

---

beams/api/api.py

Need to create api 
1. Need to create api 
- here created the api for the get for filter to get list of employees belongs to specefic department
- listed the employees belongs to the department 
api
No. 
- Postman

TASK-2025-00438: Created the Api for get list employee

---

beams/beams/custom_scripts/voucher_entry/voucher_entry.py
beams/beams/doctype/petty_cash_request/petty_cash_request.js
beams/beams/doctype/petty_cash_request/petty_cash_request.json

- Update petty Cash request.
- Updated petty cash request doctype.
[Screencast from 21-03-25 04:06:24 PM IST.webm](https://github.com/user-attachments/assets/9dcb8479-53e4-461a-8943-39517e0855e6)
No.

fix: Update Petty Cash Request

---

beams/beams/doctype/stringer_bill/stringer_bill.json
beams/beams/doctype/stringer_bill/stringer_bill.py
beams/beams/doctype/stringer_bill_detail/stringer_bill_detail.json

- Update Stringer Bill doctype and Stringer Bill Detail.
- Update purchase Invoice Creation from Stringer Bill.
- Updated Stringer Bill Doctype and Stringer Bill Doctype.
- Updated amount in purchase invoice.
[Screencast from 21-03-25 05:51:25 PM IST.webm](https://github.com/user-attachments/assets/3720ee84-dfc2-4acb-a367-a616d278661c)
No.

fix: Update Stringer Bill Doctype

---

beams/beams/doctype/stringer_bill/stringer_bill.json
beams/beams/doctype/stringer_bill_detail/stringer_bill_detail.json

- Customize Stringer Bill Doctype
- Fetches Area and Bureau from Supplier.
No.

fix: Update Stringer Bill

---

beams/beams/doctype/batta_claim/batta_claim.js
beams/beams/doctype/batta_claim/batta_claim.json
beams/beams/doctype/batta_claim/batta_claim.py

Add configuration  for the availability of room.
Added acheck box Is Avail Room Rent to mark the availability of rooms.
Batta Claim
No
- Chrome

TASK-2025-00417:Add configuration  for the availability of room.

---

beams/beams/doctype/allocated_resource_detail/allocated_resource_detail.json

- Fields change to read only
- Add Two Fields(Assigned from,Assigned To)
- Fields changed to read only
- Added Two Fields(Assigned from,Assigned To)
No

feat: Fields change to read only 

---

beams/beams/doctype/batta_claim/batta_claim.json
beams/beams/doctype/batta_policy/batta_policy.json
beams/beams/doctype/work_detail/work_detail.json

--update Batta Claim doctype field
--change labels and descriptions in Batta Policy doctype
--add food allowance fields and total batta calculation in Work Detail  
--update Batta Claim doctype field
- Moved 'batta' field above 'food_allowance'  
- Hid 'batta_based_on' field  
- Renamed 'Total Daily Batta' to 'Total Batta'  
- Removed 'food_allowance' field  
--change labels and descriptions in Batta Policy doctype
-Fixed capitalization in 'Room Rent for Overnight Stay'  
- Fixed spacing in 'Daily Batta With Overnight Stay'  
- Corrected description: 'Travel 50 kms' → 'Travel 100 kms'  
- Standardized 'OverNight Stay' → 'Overnight Stay' 
--add food allowance fields and total batta calculation in Work Detail    
- Added fields for Breakfast, Lunch, and Dinner  
- Introduced Total Food …

    TASK-2025-00458:Update Batta Claim, Batta Policy, and Work Detail doctypes with field modifications

---

beams/setup.py

--Add field Department in voucher entry
Added Department in voucher entry
Voucher Entry
- Chrome
- Opera Mini
- Safari

feat: Add Department in voucher entry

---

beams/beams/custom_scripts/voucher_entry/voucher_entry.py

-auto-creation of petty cash request from the voucher entry is submitted state 
-auto-creation of petty cash request from the voucher entry is changed to  draft state 
[Screencast from 24-03-25 04:45:38 PM IST.webm](https://github.com/user-attachments/assets/0473afba-61df-4ee3-8deb-1a3687d075d8)
voucher entry and petty cash request doctype
No. 

TASK-2025-00461:fixed auto-creation of petty cash request

---

beams/beams/doctype/batta_claim/batta_claim.py

- Update Daily Batta with overnight stay calculation.
- Changed fieldname in Daily Batta with overnight stay calculation.
No.

fix: Update Batta Claim Calculation

---

beams/beams/doctype/batta_claim/batta_claim.py

- Update Batta Claim.
- Fixed the errors in converting total hours and total distance in to float.
[Screencast from 27-03-25 05:10:31 PM IST.webm](https://github.com/user-attachments/assets/c2da2a70-8ab4-4317-9532-1157016f395b)
No.

fix: Convert Total Hours and Total Distance into Float.

---

beams/setup.py

Need to : Add new roles.
Added new roles as Admin User ,Bureau User, Coordinating Editor, News Coordinator
No. 

Added new roles.

---

beams/beams/doctype/bureau_trip_sheet/bureau_trip_sheet.js
beams/beams/doctype/bureau_trip_sheet/bureau_trip_sheet.py

--Implement food allowance calculation based on travel conditions
--Add allowance calculation based on travel details
-->For batta allowance calculation based on travel conditions.
--------------------------------------------------------------------------------------------
1) Input Sanitization: Converts total_distance_travelled_km and total_hours to float values.
2) Fetch Policy Data: Retrieves the Batta Policy for the designation (Driver) and extracts allowance values.
3) Boolean Conversion: Converts is_travelling_outside_kerala and is_overnight_stay to boolean.
4) Allowance Calculation:
a) With Overnight Stay: Fetches outside_kerala__ or inside_kerala__ allowance.
b) Without Overnight Stay: If travel exceeds 100 km & 8 hours, fetches outside_kerala or inside_kerala allowance. …

Task 2025 00504: Bureau Trip Sheet calculation

---

beams/beams/doctype/allocated_vehicle_details/allocated_vehicle_details.json
beams/beams/doctype/required_vehicle_details/required_vehicle_details.json
beams/beams/doctype/transportation_request/transportation_request.json
beams/beams/doctype/transportation_request/transportation_request.py
beams/beams/doctype/vehicle_detail/vehicle_detail.json

Modify the vehicle request process
- In Project modify the vehicle requesting process 
- Remove  the allocated and hired fields and bring it in Allocated Vehicle Details table ,
- Change the datatype of required_vehicle_details in the text editor to small text in project 
- The vehicle is allocated. Bring the necessary details in the allocated vehicle details table like vehicle, vehicle details , no of travelers, allocated and hired checkbox, from and to
- modified Required Vehicle
[Screencast from 04-04-25 10:32:52 AM IST.webm](https://github.com/user-attachments/assets/7725c1ed-5042-459c-a5c7-1734744a5e79)
- Project 
- Transportation Request
- Chrome
- Opera Mini
- Safari

feat: TASK-2025-00522: Modify the vehicle request process

---

beams/www/job_application_upload/upload_doc.html

Added dynamic "Remove" button functionality to allow users to delete rows from a table and auto-update the serial numbers accordingly.
- Appended a "Remove" button to each new row created via the Add Row button.
- On clicking the "Remove" button, the row is deleted from the DOM.
- After deletion, the serial numbers (S.No) are recalculated and updated to maintain order.
- Ensured the functionality works seamlessly with multiple row additions and deletions.
[Screencast from 04-08-2025 02:52:41 PM.webm](https://github.com/user-attachments/assets/3e7f4e75-5f40-48e7-a4cd-edc20f98b133)
UI for table row actions
JavaScript DOM manipulation for dynamic row handling
- Chrome

feat: add remove row functionality to tables in job application form

---

beams/setup.py

fix custom field layout
- Updated field insertion order in setup.py for Allocated Manpower Detail
- Removed duplicate definition of Allocated Item Details to avoid redundancy
- added customfields asset location in project
- project
- Chrome
- Opera Mini
- Safari

fix:fix custom field layout

---

beams/beams/custom_scripts/job_applicant/job_applicant.js
beams/setup.py
beams/www/job_application_upload/upload_doc.html
beams/www/job_application_upload/upload_doc.js
beams/www/job_application_upload/upload_doc.py

--update Job Applicant form fields, layout, and added payslip upload
--Removed fields: Former Name/Maiden Name, Nationality, Residence Number, Email ID, Telephone No, Employee Code/No,  First Salary Drawn, Are You Willing to Travel?, In India, Abroad, State Restrictions, Period of Stay (From/To)
--Added Aadhar Number"
--Renamed "Last Salary Drawn" in Previous Employment History to "Last Salary CTC"
--Added provision to upload last 3 months' payslips
--Removed client-side validation for resume_attachment field.
--Validation for file extensions (pdf, doc, docx, xls, xlsx) is no longer required.
[Screencast from 09-04-25 11:58:12 AM IST.webm](https://github.com/user-attachments/assets/ab7c8594-d246-4b9d-bdbf-5d0b0f4fda13)
[Screencast from 09-04-25 12:00:43 PM …

    TASK-2025-00558:refactor Job Applicantion form fields and layout

---

beams/beams/custom_scripts/full_and_final_statement/full_and_final_statement.js
beams/beams/custom_scripts/full_and_final_statement/full_and_final_statement.py
beams/beams/doctype/full_and_final_bundle/full_and_final_bundle.json
beams/beams/doctype/full_and_final_bundle/full_and_final_bundle.py
beams/hooks.py
beams/setup.py

Need to: 
-  Create Child Table "Full and Final Bundle" with fields Asset Transfer Request , Asset Bundle , Date , Description
-  Customize Full and Final Statements
Add the Allocated Bundles (Table/Full and Final bundle)  Under Assets Allocated table.
- Fetch any Asset Bundles Currently in Ownership of the Employee when the employee is selected.
-  Created Child Table "Full and Final Bundle" with fields Asset Transfer Request , Asset Bundle , Date , Description
-  Customized Full and Final Statements
Added the Allocated Bundles (Table/Full and Final bundle)  Under Assets Allocated table.
- Fetched any Asset Bundles Currently in Ownership of the Employee when the employee is selected.
[Screencast from 11-04-25 11:49:32 AM IST.webm](https://github.com/user-attachments/assets/bdf630a2-e209-4 …

TASK-2025-00282:Customized Full and Final Statement.

---

beams/beams/custom_scripts/project/project.js
beams/beams/doctype/allocated_manpower_detail/allocated_manpower_detail.json
beams/beams/doctype/external_resource_request/external_resource_request.js
beams/beams/doctype/external_resources_detail/external_resources_detail.json
beams/beams/doctype/manpower_transaction_log/manpower_transaction_log.js
beams/beams/doctype/manpower_transaction_log/manpower_transaction_log.json
beams/beams/doctype/manpower_transaction_log/manpower_transaction_log.py
beams/beams/doctype/manpower_transaction_log/test_manpower_transaction_log.py
beams/setup.py

TASK-2025-00629
Add new field named designation in supplier doctype.
Change Hired Personnel field type in External Resources Detail Child Table and apply a filter to the 'Hired Personnel'
TASK-2025-00637
Add fields in Allocated Manpower detail child table (returned, returned date, returned reason)
Create manpower transaction log doctype
TASK-2025-00629
Supplier: Added a new field called Designation (Type: Link, Options: Designation).
External Resources Detail (Child Table): Changed the field type of 'Hired Personnel' to Link, with Options: Supplier.
External Resource Request : Applied filter to the 'Hired Personnel' field to filter suppliers based on the selected Designation.
TASK-2025-00637
Added fields in Allocated Manpower detail child table ( Return{check}, Returned Date(datetime), …

feat: TASK-2025-00629 update external_resource_request

---

beams/beams/doctype/batta_claim/batta_claim.py

- Update daily batta reference in journal entry accounts
- Updated daily batta reference in journal entry accounts
No.

fix: Updated daily batta reference in journal entry accounts

---

beams/beams/doctype/batta_claim/batta_claim.js
beams/beams/doctype/batta_claim/batta_claim.py

- Update travelled distance in food calculation and Daily batta without overnight stay
- Updated travelled distance in food calculation to be less than 100 km.
- Updated daily batta without overnight stay to apply for distances greater than or equal to 100 km.
No.

fix: Update travelled distance in food calculation and Daily batta without overnight stay

---

beams/beams/custom_scripts/attendance_request/attendance_request.py
beams/hooks.py

TASK-2025-00870 : make correction in date comparison
Removed date validation in Attendance Request as it is not needed currently; may consider adding it in the future if required.
- Chrome

fix: TASK-2025-00870 : remove date validation in attendance request

---

beams/beams/doctype/employee_travel_request/employee_travel_request.js
beams/beams/doctype/employee_travel_request/employee_travel_request.json
beams/beams/doctype/vehicle_allocation/vehicle_allocation.json
beams/beams/doctype/vehicle_allocation/vehicle_allocation.py

TASK-2025-00879 : In Employee Travel Request , create feature to assign vehicle and driver
In Employee Travel Request
1. Added field ' Is Vehicle Required ' and ' Number of Travellers '
2. If group trip: update number_of_travellers as per the count in the travellers table.
3. Added child table named "Vehicle Allocation" with fields
1. vehicle (Link)
      2. Driver (Link)
4. Applied filter in Employee with designation Driver
5. allowed vehicle allocation entries only after HOD approval and when a vehicle is actually needed
   
List out the areas affected by your code changes. (Employee Travel Request)
- Chrome

feat: TASK-2025-00879 create feature to assign vehicle and driver

---

beams/beams/doctype/fuel_card/fuel_card.json
beams/beams/doctype/fuel_card_log/fuel_card_log.js
beams/beams/doctype/fuel_card_log/fuel_card_log.json
beams/beams/doctype/fuel_card_log/fuel_card_log.py
beams/beams/doctype/fuel_card_log/test_fuel_card_log.py
beams/beams/doctype/owered_by/owered_by.json
beams/beams/doctype/owered_by/owered_by.py

created Fuel Card Log doctype and its functionalities
**created Fuel Card Log doctype 
Refactored Fuel Card DocType:**
-     Removed unused fields:
-      current_holder (Link → Employee), issued_to_current_holder_on (Date),recharge_history (Table → Recharge History), recharge_history (Table → Recharge History), column_break_nhyn (Layout field),Simplified the field_order and fields array to keep only relevant fields like card_no and provider.
These fields were likely moved or their logic shifted to the Fuel Card Log DocType, which now handles dynamic tracking of ownership and recharge history.
**Added two new child DocTypes:**
-     Owered By: Tracks the historical ownership of a fuel card.
-     Fuel Card Log: Manages fuel card assignment and recharge actions.
**Implemented a button "Set …

feat: TASK-2025-00878: Add ownership history and current holder logic in Fuel Card Log

---

beams/beams/custom_scripts/expense_claim/expense_claim.py
beams/beams/doctype/employee_travel_request/employee_travel_request.js
beams/beams/doctype/employee_travel_request/employee_travel_request.py
beams/hooks.py

Need to: 
- Create a button in employee travel request to claim expense 
- when clicked open popup with child table with fields :-
Expense Date (Date) 
Expense Claim Type (LINK )
Description (small text) 
Amount - (Currency)
- map the details to Expense claim doctype and notify admin 
- Created a Button in Employee Travel Request Doctype to  Expense Claim Doctype
- when clicked open popup with child table with fields :-
Expense Date (Date) 
Expense Claim Type (LINK )
Description (small text) 
Amount - (Currency)
- mapped the details to Expense claim doctype and notify admin Via ToDo and Email
[Screencast from 06-05-25 10:29:49 AM IST.webm](https://github.com/user-attachments/assets/3797e571-2792-4838-8287-e33f477d7a8e)
[Screencast from 06-05-25 10:30:39 AM …

TASK-2025-00880,TASK-2025-00900:Created a button in Employee Travel Request Doctype to Expense Claim Doctype

---

beams/beams/doctype/vehicle_incident_details/vehicle_incident_details.json
beams/beams/doctype/vehicle_incident_details/vehicle_incident_details.py
beams/beams/doctype/vehicle_incident_record/vehicle_incident_record.json

Create Child table Vehicle Incident Details and add it it to Vehicle Incident REcord doctype
Child table was created with following fields:
- Expense type (select)
- amount
- Is Payable (check)
Vehicle Incident Record doctype
No
- Chrome

TASK-2025-00903:Created child table Vehicle Incident Details

---

beams/beams/doctype/employee_travel_request/employee_travel_request.js

Need to: Create a button in Employee Travel Request to  Expense Claim Doctype when the trip is Unplanned.
Created a button in Employee Travel Request Doctype to Expense  Claim Doctype when the trip is Unplanned
[Screencast from 06-05-25 05:21:27 PM IST.webm](https://github.com/user-attachments/assets/98de7801-8d72-4555-85ae-5e5e59edd031)
Employee Travel Request Doctype
No

TASK-2025-00902:Created a button in Employee Travel Request Doctype to  Expense Claim Doctype when the trip is Unplanned.

---

beams/beams/doctype/employee_travel_request/employee_travel_request.py

Add logic to automatically create  Attendance Requests when an Employee Travel Request is approved.
Currently Attendance Request is created only for Requesting Employee.The employee listed as travellers (multiselect) should also request for Attendance Request.
Changes Made:
-     on_update_after_submit method added inside EmployeeTravelRequest DocType class.
-     Attendance creation is triggered only when workflow state is 'Approved'.
-     Validates that "Reason for Rejection" is not filled during approval.
-     Includes attendance requests for:
-         The requesting employee (requested_by)
-         All additional travellers listed under the child table.
-     Skips creation if overlapping attendance request already exists.
-     Attendance Requests are saved in Draft mode for …

feat:Attendance Request created for Travellers

---

beams/beams/doctype/employee_travel_request/employee_travel_request.js

TASK-2025-00947 : automatically fills the ' requested by '  field in employee travel request 
The system automatically fills the "Requested By" field with the employee’s name when the employee logs in and opens the form.
- Chrome

feat: TASK-2025-00947 automatically fills the requested by field in employee travel request

---

beams/beams/report/fuel_and_mileage_monitoring/fuel_and_mileage_monitoring.js
beams/beams/report/fuel_and_mileage_monitoring/fuel_and_mileage_monitoring.json
beams/beams/report/fuel_and_mileage_monitoring/fuel_and_mileage_monitoring.py

Added Fuel and Mileage Monitoring Report
- Implemented the "Fuel and Mileage Monitoring" report with filters for vehicle, driver, fuel consumed, and mileage.
- Added Python script to retrieve data from the "Trip Sheet" DocType based on filter conditions.
Trip sheet
- Chrome
- Opera Mini
- Safari

feat: TASK-2025-00949: Added Fuel and Mileage Monitoring Report

---

beams/beams/doctype/trip_sheet/trip_sheet.js
beams/beams/doctype/trip_sheet/trip_sheet.json
beams/beams/doctype/vehicle_incident_details/vehicle_incident_details.json
beams/beams/doctype/vehicle_inspection_details/vehicle_inspection_details.json
beams/beams/doctype/vehicle_inspection_details/vehicle_inspection_details.py
beams/beams/doctype/vehicle_safety_inspection/test_vehicle_safety_inspection.py
beams/beams/doctype/vehicle_safety_inspection/vehicle_safety_inspection.js
beams/beams/doctype/vehicle_safety_inspection/vehicle_safety_inspection.json
beams/beams/doctype/vehicle_safety_inspection/vehicle_safety_inspection.py

TASK-2025-00950:
- Created Vehicle Inspection Details child table
- Created 'Vehicle Safety Inspection' template with child table named Vehicle Inspection Details
- Added Vehicle Inspection Details child table and Vehicle Template fields in Trip sheet
- Added functionality to fetch Safety Inspection Checklist Template when Safety Inspection is ticked.
TASK-2025-00953:
- In Vehicle Incident Details , changed amount field type from float to currency
TASK-2025-00965:
- Added description details in vehicle incident record (Trip Sheet field)
List out the areas affected by your code changes. (Trip sheet, Vehicle incident Record, Vehicle incident details)
- Chrome

feat: TASK-2025-00950 create a safety inspection checklist in trip sheet

---

beams/beams/doctype/shift_swap_request/shift_swap_request.py

-Need to implement the shift swap request functionality for employees and automatically create corresponding shift assignments during the approval of the request.
- Need to fix the error while approving the shift swap request doctype 
1.  implemented the shift swap request functionality for employee and swaped employee and automatically created corresponding shift assignment 
- Updated the create_shift function to return the shift document instead of directly saving and submitting it.
- shift assignment is created based on the spliting shift assignment based on the shift swap request  
[Screencast from 12-05-25 04:45:20 PM IST.webm](https://github.com/user-attachments/assets/8a5560dc-cbcd-410b-ae65-f416f40a7410)
shift swap request and shift assignment doctype
No.

TASK-2025-00970: Implement  to change the logic of Shift Swap Request for employee

---

beams/beams/custom_scripts/appraisal/appraisal.js
beams/beams/custom_scripts/appraisal/appraisal.py

--Add category to appraisal and send assessment reminder notification
--Added category with remarks to Appraisal and send assessment reminder
--simplified by removing unused task assignment code
[Screencast from 13-05-25 02:22:30 PM IST.webm](https://github.com/user-attachments/assets/c45e1458-815c-459e-8f09-ecf3c29c1476)
--No

Refactor:send notification to assessment officer when category is added

---

beams/beams/custom_scripts/employee_checkin/employee_checkin.py
beams/hooks.py

--Implement active status update for HD Agent from  check-in
--Introduced set_hd_agent_active_status to update agent status using today's latest employee check-in
[Screencast from 15-05-25 01:38:29 PM IST.webm](https://github.com/user-attachments/assets/4aa4fbc2-bd3a-4596-9414-ab001ac174bd)
--No.

    TASK-2025-01009:Add logic to update HD Agent active status based on employee check-in

---

beams/beams/doctype/employee_travel_request/employee_travel_request.js
beams/beams/doctype/employee_travel_request/employee_travel_request.py

Need to: 
- Validate vehicle is allocated if is vehicle required checked before admin approval in Employee Travel Request doctype.
- Change the name Ticket Details Table name into Attachments Table Employee Travel Request doctype.
- Validated vehicle is allocated if is vehicle required checked before admin approval Employee Travel Request doctype.
- Changed the name Ticket Details Table name into Attachments Table in Employee Travel Request doctype.
[Screencast from 19-05-25 12:49:48 AM IST.webm](https://github.com/user-attachments/assets/2326a4d7-59df-4983-aa30-a1e65495a439)
[Screencast from 19-05-25 12:40:02 AM IST.webm](https://github.com/user-attachments/assets/40859cbb-7e2e-40e0-90c7-d090b41ed835)
Employee Travel Request doctype.
No. 

TASK-2025-01034:Validated vehicle is allocated if is vehicle required checked

---

beams/beams/doctype/fuel_card_log/fuel_card_log.js

Need to : Validate today's date for date field in fuel card log doctype
Validated today's date for date field in fuel card log doctype
[Screencast from 16-05-25 05:48:00 PM IST.webm](https://github.com/user-attachments/assets/c5652f3a-e348-4a7f-808b-cf9ff53ac469)
Fuel Card Log doctype
No. 

TASK-2025-01031:validated today's date for date field in fuel card log doctype

---

beams/beams/custom_scripts/asset/asset.py
beams/beams/custom_scripts/asset_movement/asset_movement.py
beams/beams/doctype/asset_location_details/asset_location_details.json
beams/beams/doctype/asset_location_details/asset_location_details.py
beams/beams/doctype/asset_location_log/asset_location_log.js
beams/beams/doctype/asset_location_log/asset_location_log.json
beams/beams/doctype/asset_location_log/asset_location_log.py
beams/beams/doctype/asset_location_log/test_asset_location_log.py
beams/beams/doctype/asset_transfer_request/asset_transfer_request.py
beams/beams/doctype/container/container.js
beams/beams/doctype/container/container.json
beams/beams/doctype/container/container.py
beams/beams/doctype/container/test_container.py
beams/beams/doctype/row/row.js
beams/beams/doctype/row/row.json
beams/beams/doctype/row/row.py
beams/beams/doctype/row/test_row.py
beams/beams/doctype/shelf/shelf.js
beams/beams/doctype/shelf/shelf.json
beams/beams/doctype/shelf/shelf.py
beams/beams/doctype/shelf/test_shelf.py
beams/hooks.py
beams/setup.py

This update introduces enhancements to asset location tracking , by capturing and maintaining the physical location (Room, Shelf, Row, Bin) of assets in both the Asset ,bundle and Asset Movement.
- created room, shelf, row, and container doctypes
- Added room, shelf, row, and bin fields to Asset and Asset Movement Item
- Auto-update asset location from Asset Movement on submission
- Log asset location changes via Asset Location Log
- Added location field to Asset Location Log and Details for better tracking
- Improved asset location updates in movements to handle empty fields
- Addressed asset, bundle  return logic to use the correct previous location with full details
[Screencast from 20-05-25 11:16:45 AM IST.webm](https://github.com/user-attachments/assets/96b8f62c-19d0-4adc-9bc9-9cfa93d …

feat:implemented Asset tracking and room allocation

---

beams/beams/doctype/employee_travel_request/employee_travel_request.py
beams/hooks.py

TASK-2025-01089 Permission query for employee travel request
Added Permission query in employee travel request (HOD can see Employee Travel Requests of employees in their department , 
Employee can see their own Employee Travel Requests)
Employee- HOD - Admin
[Screencast from 23-05-25 11:38:50 AM IST.webm](https://github.com/user-attachments/assets/ab6986ae-634c-4f68-ab90-c245c1d0e8ba)
- Chrome

TASK-2025-01089 Permission query for employee travel request

---

beams/beams/doctype/employee_travel_request/employee_travel_request.js
beams/beams/doctype/employee_travel_request/employee_travel_request.py

Create Journal Entry from Travel Request via dialog with background processing
- Added dialog in Employee Travel Request to input multiple travel expenses
-  creation now happens silently in the background
- Implemented server-side method to create Journal Entry based on selected Expense and Budget types
- Displays clickable link to created Journal Entry in a success message
- Handles validation and missing default account scenarios
[Screencast from 23-05-25 11:35:51 AM IST.webm](https://github.com/user-attachments/assets/ce29c990-ffa8-4ddd-b8fa-47cf2781898c)
JV
- Chrome
- Mozilla Firefox- YES
- Opera Mini
- Safari

feat: TASK-2025-01093 : Create Journal Entry from Travel Request via dialog

---

beams/beams/doctype/employee_travel_request/employee_travel_request.py

Need to: Fix the issue in odometer when automatically created trip sheet from employee travel request doctype
Fixed the issue in odometer when automatically created trip sheet from employee travel request doctype
Trip Sheet doctype
No. 

TASK-2025-01099:Fixed the issue in odometer when automatically created trip sheet from employee travel request doctype

---

beams/beams/custom_scripts/vehicle_dashboard/vehicle_dashboard.py
beams/hooks.py

Need to:Added connections in Vehicle doctype
Added connection in  Vehicle doctype for Vehicle Documents Log ,Vehicle Log and Delivery Trip 
Vehicle doctype
No

TASK-2025-01141:Added connections in Vehicle doctype

---

beams/beams/doctype/asset_transfer_request/asset_transfer_request.py

Add a validation for the location before transferring the asset in the Asset Transfer Request.
Validates that source and target locations are not the same before transferring assets.
- Chrome
- Opera Mini
- Safari

TASK-2025-01159 t : add validation for location in asset transfer request

---

beams/beams/report/employee_allocated_asset_report/employee_allocated_asset_report.py

Need to: Filter assets by custodian and sort by employee in ascending order in Employee Allocated Asset Report
Filtered assets by custodian and sorted by employee in ascending order in Employee Allocated Asset Report
Employee Allocated Asset Report
No. 

TASK-2025-01292:Filtered assets by custodian and sorted by employee in ascending order in  Employee Allocated Asset Report 
