efeone/beams

beams/hooks.py
beams/setup.py

-Add Custom Fields on Customer Doctype.
-"MSME Status" (Select/Options: MSME/Non-MSMSE)
-"Is Agent" (Checkbox)
-"Agent of" (Link/Customer/depends on Is Agent == True)
-Added Custom Fields on Customer Doctype.
-No

feat: Add Custom Fields on Customer Doctype

---

beams/setup.py

-Add Custom Fields on Sales Invoice DocType.
-  "Actual Customer" (Link/Customer)
- "Actual Customer Group" (Link/Customer Group)
- "Include in IBF" (Checkbox)
- "Is Barter Invoice" (Checkbox)
-Added Custom Fields on Sales Invoice DocType.

feat: add custom fields to Sales Invoice Doctype

---

beams/hooks.py
beams/public/js/sales_invoice.js

- Hide 'actual_customer' and 'actual_customer_group' fields by default on form load.
- Display 'actual_customer' field and clear its value if the selected customer is an agent.
- Populate 'actual_customer_group' based on the 'customer_group' of the selected 'actual_customer'.
- Hide 'actual_customer_group' if 'actual_customer' is not selected.
-Hid actual_customer and actual_customer_group fields by default on form load.
-Displayed actual_customer field and cleared its value if the selected customer was an agent.
-Populated actual_customer_group based on the customer_group of the selected actual_customer.
-Hid actual_customer_group if no actual_customer was selected.
-No

feat: Enhance Sales Invoice form behavior based on customer selection

---

beams/setup.py

- Custom fields Customer Purchase Reference ID and Is Barter (Checkbox) needed to be added to Quotation DocType.
- Added the fields to Quotation DocType.
-`beams/setup.py`
- No

feat: Add Custom fields on Quotation

---

beams/beams/custom_scripts/quotation/quotation.py
beams/hooks.py
beams/public/js/quotation.js

-Create sales invoice from quotation
-implement a new function make_sales_invoice to map and create a sales invoice from a quotation document.
-Created sales invoice from quotation
-implemented a new function make_sales_invoice to map and create a sales invoice from a quotation document.
-No

feat: Create Sales Invoice From Quotation

---

beams/beams/custom_scripts/sales_invoice/sales_invoice.py
beams/hooks.py
beams/public/js/sales_invoice.js
beams/setup.py

- Feature
- Automated  Include in IBF Field in Sales Invoice.
- Added validation for total amount in sales invoice and quotation.
- Introduced Reference Id field in Sales Invoice Doctype to implement validation.
- Added validation for the total amount in both the Sales Invoice and Quotation
- Implemented logic to automatically set the Include in IBF field based on the customer’s territory and the barter invoice status.
-`beams/hooks.py`
-`beams/public/js/sales_invoice.js`
-`beams/setup.py`
-`beams/beams/custom_scripts/sales_invoice/`
- No
- New Data
- No

feat: Implement Include in IBF conditions and validate amounts in Sales Invoice and Quotation

---

beams/setup.py

-Add Custom Fields on  Purchase Invoice Doctype.
-Barter Invoice(Checkbox)
 -Quotation Referance(Link/Quotation)
-Added Custom Fields on Purchase Invoice Doctype.
-No

feat: Added custom fields 'Barter Invoice' and 'Quotation Reference' to Purchase Invoice Doctype

---

beams/public/js/sales_invoice.js
beams/setup.py

-Add Custom Fields on Sales Invoice Doctype.
-"Actual Customer" (Link/Customer)
-"Actual Customer Group" (Link/Customer Group)
-"Include in IBF" (Checkbox/Read Only)
-"Is Barter Invoice" (Checkbox)
-"Quotation "(Link/Quotation)
-remove include in IBF conditions in sales invoice 
-Added Custom Fields on Sales Invoice Doctype.
-No

feat: Customize Sales Invoice DocType

---

beams/beams/custom_scripts/quotation/quotation.py
beams/public/js/quotation.js

-Create Button Purchase Invoice on Release Order.
-Fetch Quotation Reference to the Purchase Invoice.
-Display Purchase Invoice button if is_barter is Checked
- Created Button Purchase Invoice on Release Order.
- Fetched the Quotation Reference to the Purchase Invoice.
- Displayed Purchase invoice button only when the is_barter is Checked.
-No

feat: Create Purchase Invoice From Release Order

---

beams/setup.py

-Remove 'Agent Of' Field from Customer Doctype.
-The 'Agent Of' field has been removed from the Customer Doctype to streamline the form and eliminate unnecessary fields.
-No

fix: Remove Agent Of Field from Customer Doctype

---

beams/beams/custom_scripts/quotation/quotation.py
beams/setup.py

-Rename Quotation Reference To Quotation in Purchase Invoice Doctype.
The label "Quotation Reference" in the Purchase Invoice doctype is renamed to "Quotation"
-This change is reflected in the UI where the field appears.
-No

fix:Rename Quotation Reference to Quotation

---

beams/beams/custom_scripts/sales_invoice/sales_invoice.py
beams/hooks.py

- Feature
- Added Validation to ensure that total of amounts on sales invoices does not exceed the  total amount on Release Order
- Implemented a method to compare the sales invoice amount with the total amount of the associated Release Order.
- Display an error message if they do not match, preventing the invoice from being submitted.
[Screencast from 08-13-2024 11:35:34 AM.webm](https://github.com/user-attachments/assets/79fb8c53-c7f5-4a3c-873f-874bbbc2a6d3)
-`beams/beams/custom_scripts/sales_invoice/sales_invoice.py`
- New Data

feat: Validate Sales Invoice amounts based on Release Order

---

beams/public/js/sales_invoice.js

-Ensure that only non-agent customers are visible in the actual_customer field of the Sales Invoice doctype.
-Applied a filter to the actual_customer field in the Sales Invoice doctype to ensure that only non-agent customers (where is_agent is false) are displayed.
-This filter enhances data accuracy by preventing agent customers from being selected where only non-agent customers are relevant.
-yes.

feat:Apply Filters in Actual Customer

---

beams/public/js/sales_invoice.js
beams/setup.py

- Feature
-  Include in IBF checkbox in Sales Invoice is checked based on whether the customer is agent and the type of barter invoice
- Added Item Type in items child table quotation.
- An event listener is added to the customer field that activates when a user selects a customer from the dropdown.
- When a customer is selected, the system checks if that customer is an agent.
- If the is_barter_invoice field on Sales Invoice is not checked and customer is agent it will updates the include_in_ibf field   based on that.
- Added Item Type in items table in Quotation.
-`beams/public/js/sales_invoice.js`
- No
- New Data

fix: Update logic for include_in_ibf field based on customer and is_barter_invoice status

---

beams/setup.py

- Automatically set the 'Is Barter Invoice' checkbox to be checked in the Sales Invoice doctype whenever a Sales Invoice is created from a Release Order.
- Implemented logic to auto-check the 'Is Barter Invoice' field when a Sales Invoice is generated from a Release Order.
[Screencast from 13-08-24 03:19:08 PM IST.webm](https://github.com/user-attachments/assets/c2c955a3-9745-4a3f-b673-195c41a55e27)
- No
- Mozilla Firefox"

feat:Auto-check 'Is Barter Invoice' when Sales Invoice is created from Release Order

---

beams/beams/custom_scripts/quotation/quotation.py
beams/beams/custom_scripts/sales_invoice/sales_invoice.py
beams/hooks.py
beams/public/js/quotation.js

- if it is a barter, a validation is needed to ensure that the parties involved are common parties.
- When creating a Sales Invoice from a Release Order , validate that a Purchase Invoice has already been submitted against the common party.
- Warning message to enable common party in accounts settings while triggering is_barter checkbox in quotation.
- Common party link is created at the time of mapping to purchase invoice from quotation. 
- Alert message on creation of barter sales invoice without purchase invoice
[Screencast from 17-08-24 10:36:52 AM IST.webm](https://github.com/user-attachments/assets/c7928ad3-4460-4a7c-94b2-49beb25c8dd5)
-No

Validation of common party

---

beams/beams/doctype/adhoc_budget/adhoc_budget.js
beams/beams/doctype/adhoc_budget/adhoc_budget.json
beams/beams/doctype/adhoc_budget/adhoc_budget.py
beams/beams/doctype/adhoc_budget/test_adhoc_budget.py
beams/beams/doctype/budget_expense/budget_expense.json
beams/beams/doctype/budget_expense/budget_expense.py
beams/beams/doctype/budget_expense_type/budget_expense_type.js
beams/beams/doctype/budget_expense_type/budget_expense_type.json
beams/beams/doctype/budget_expense_type/budget_expense_type.py
beams/beams/doctype/budget_expense_type/test_budget_expense_type.py

-Create Doctype Adhoc Budget
-Created Adhoc Budget doctype for managing adhoc budgets with fields for expected revenue and total expenses.
- Added Budget Expense Type doctype to define various types of expenses.
- Implemented Budget Expense as a child table in Adhoc Budget for recording individual expenses.
-No

feat: Create Doctype Adhoc Budget

---

beams/beams/custom_scripts/quotation/quotation.py

-Fix the Missing Argument in Quotation.
Added Missing argument in Quotation .
-yes

fix: fix the missing argument

---

beams/beams/custom_scripts/quotation/quotation.py

- Remove unnecessary method
- Removed the method def  validate
[Screencast from 17-08-24 01:42:18 PM IST.webm](https://github.com/user-attachments/assets/bd04a84f-e1ac-4ba6-9718-2909052377e2)
-No

Issue beams

---

beams/fixtures/workflow_state.json

- Feature
- A Workflow has to be created for doct-ype Adhoc Budget.
- A field Remarks only visible for workflow state with docstatus == 1.
- Created workflow for Adhoc Budget and hide the field remarks for state with docstatus ==0 
[Screencast from 19-08-24 12:13:55 PM IST.webm](https://github.com/user-attachments/assets/0e3d1c7a-3533-406f-9c71-0a21f4f7912b)
-`beams/hooks.py`
-`beams/fixtures/`
- New Data

fix: Missing of a comma

---

beams/beams/custom_scripts/purchase_invoice/purchase_invoice.py
beams/hooks.py
beams/setup.py

- Feature
- Validation on amount(Purchase Amount=Quotation Amount)
-To automatically set the "Is Barter Invoice" checkbox in the Purchase Invoice doct-ype whenever a Purchase invoice is created from a Barter Release Order(Is Barter checked).
-Barter Invoice(Read Only)
-Quotation(Read Only)
-Albatros RO ID(Mandatory in Quotation) 
- Validated purchase amount == quotation amount before save
- Automated Barter invoice on basis of is_barter
[Screencast from 20-08-24 04:35:46 PM IST.webm](https://github.com/user-attachments/assets/d09a8e7e-9d4c-4567-acf3-026c00c45d33)
- `beams/hooks.py`
- `beams/setup.py`
- New Data

feat: Purchase Invoice Amount should be equal to Quotation Amount

---

beams/beams/doctype/additional_account_settings/additional_account_settings.js
beams/beams/doctype/additional_account_settings/additional_account_settings.json
beams/beams/doctype/additional_account_settings/additional_account_settings.py
beams/beams/doctype/additional_account_settings/test_additional_account_settings.py
beams/public/js/quotation.js

- Fix
- Feat
- The message is only shown on submit
- Created doctype additional account settings
- [Screencast from 21-08-24 10:59:08 AM IST.webm](https://github.com/user-attachments/assets/d439dfa9-c1ab-4b78-b732-ef209a81ac24)
- ![image](https://github.com/user-attachments/assets/a65aa529-f960-4d19-8e21-820caa5e8d60)
- Sales Invoice
- Additional Accounts Settings
- New Data

Quotation changes and additional acc settings

---

beams/beams/doctype/accounts/accounts.json
beams/beams/doctype/accounts/accounts.py
beams/beams/doctype/adhoc_budget/adhoc_budget.json
beams/beams/doctype/budget_expense_type/budget_expense_type.json

-Update Doctype Adhoc Budget
-Updated Budget Expense Type Doctype.
-Created Child table Accounts.
-Updated Adhoc Budget Doctype
-No

fix: Update  Adhoc Budget Doctype

---

beams/beams/custom_scripts/account/account.py
beams/hooks.py

-Automatically generate review ToDo for Accounts User on new Supplier creation
-Implemented automatic ToDo creation for Accounts User to review new Suppliers upon their creation.
-Supplier Doctype.
-User Notifications
-yes.

feat:Create ToDo for Accounts User on Supplier creation

---

beams/beams/doctype/adhoc_budget/adhoc_budget.js
beams/beams/doctype/adhoc_budget/adhoc_budget.json

-Set the Values in Adhoc Budget Doctype.
-The Total Budget Amount field is now set to read-only to prevent manual changes after it's calculated.
-The Total Budget Amount is automatically calculated based on the sum of the Budget Amount fields in the Budget Expense child table. This value is updated dynamically whenever the Budget Amount is modified.
-Posting Date is set to Today.
-Fetched Expected Start Date and Expected End Date from Project.
-The Expected Revenue Reached checkbox is automatically checked when the Expected Revenue is at least three times the Total Budget Amount and does not exceed the Adhoc Budget Revenue Expectation set in the Additional Account Settings. An introductory message is displayed to indicate whether the criteria have been met
[Screencast from 22-08-24 …

feat: Set the Values in  Adhoc Budget Doctype

---

beams/beams/custom_scripts/purchase_invoice/purchase_invoice.py
beams/beams/doctype/additional_account_settings/additional_account_settings.json
beams/public/js/sales_invoice.js
beams/setup.py

- Validate Quotation and Purchase Amount Based On Checkbox Equalize Purchase & Quotation Amount in Doc-type  Additional Account Settings
- Not saved issue in sales invoice on onload
-
- Validated Equalize through Checkbox
- Removed unwanted code in sales invoice and done through setup
[Screencast from 22-08-24 04:52:30 PM IST.webm](https://github.com/user-attachments/assets/aa18e1ca-c885-4a0f-b6c1-d859ee10ad09)
[Screencast from 22-08-24 04:55:58 PM IST.webm](https://github.com/user-attachments/assets/c5a1ad1e-fafe-4a89-a567-62594c3423ca)
-No

Sales beams

---

beams/beams/custom_scripts/sales_invoice/sales_invoice.py
beams/hooks.py

- Sales invoice less than quotation amount is saved
- it works on submit
- Sales invoice validation  is given on both limit which exceed and less.
- set to before save
[Screencast from 26-08-24 11:17:43 AM IST.webm](https://github.com/user-attachments/assets/7f2bd9a4-9352-43d3-8216-598d73a13c41)
-No

fix : Sales amount less than quotation amount cannot be saved

---

beams/setup.py

-Customize Supplier Doctype.
-Added Checkbox 'Is Stringer' 
-Added Link Field Bureau
-The Bureau field should be displayed when the supplier is a stringer.
-No

feat: Customize Supplier Doctype

---

beams/beams/custom_scripts/quotation/quotation.py
beams/fixtures/role.json
beams/hooks.py
beams/public/js/quotation.js
beams/setup.py

Feature Description.
- Add a Checkbox is_production_item in doctype item
- Create a Task to Production Manager when the release order with item that checkbox  is_production_item checked is submitted
Solution Description.
- Added Checkbox is_production_item
- A task is generated to the particular release order
Output. 
[Screencast from 27-08-24 03:09:16 PM IST.webm](https://github.com/user-attachments/assets/fbd9c9b1-1ff4-40a1-b51b-99d412d63fe7)
Is there any existing change.
No
Was the feature tested on the browsers.

feat : Task is created to production manager on release order

---

beams/fixtures/workflow.json

-Update Approval Workflow on Supplier and Accounts
-Added Reopen state to workflow.
-No

fix: Update Workflow

---

beams/beams/doctype/stringer_work_details/stringer_work_details.json
beams/beams/doctype/stringer_work_details/stringer_work_details.py
beams/hooks.py
beams/public/js/purchase_invoice.js
beams/setup.py

- Feature
-  This feature enhance the Purchase Invoice DocType with a new invoice type field, conditional filters, and a child table for   stringer work details.
- Added field Invoice Type to Purchase Invoice.
- Applied Item field filtering-Show only service items in the Item field when Invoice Type is "Stringer Bill."
- Supplier field filtering-Show only stringer suppliers in the Supplier field when Invoice Type is "Stringer Bill."
- Added Child table 'Stringer Work Details' in Purchase Invoice. 
- Bureau from the supplier fetched into the Stringer Work Details table based on whether the supplier is a stringer.
[Screencast from 08-28-2024 09:36:14 AM.webm](https://github.com/user-attachments/assets/f3387449-2cf5-410d-bd39-4365712e6768)
Purchase Invoice.
- New Data

feat: Customize Purchase Invoice

---

beams/fixtures/workflow_action_master.json
beams/fixtures/workflow_state.json
beams/hooks.py

- A Workflow has to be created for doctype Driver Batta Claim.
A workflow was created for the Driver Batta Claim doctype to manage the approval process and state transitions.
- Driver Batta Claim doctype
-No

feat: Create Approval workflow on Driver Batta Claim.

---

beams/beams/custom_scripts/quotation/quotation.py

- Fix
- Task is Created but not assigned to the user with role production manager 
- Assigned the task to the users with the role production manager
[Screencast from 28-08-24 04:42:37 PM IST.webm](https://github.com/user-attachments/assets/6fa7b145-19b4-4db7-8466-cfdb6e7ad1de)
-New Feature
- New Data

fix : Assigning of task is not working

---

beams/beams/doctype/beams_accounts_settings/beams_accounts_settings.json
beams/beams/doctype/beams_naming_rule/beams_naming_rule.json
beams/beams/doctype/beams_naming_rule/beams_naming_rule.py

Create  child table Beams Naming Rule.
Created child table Beams Naming Rule to Beams Accounts Settings.This Child table can be used to set naming series for any doctype.
-No

feat:Create child table Beams Naming Rule

---

beams/beams/doctype/sales_type/sales_type.js
beams/beams/doctype/sales_type/sales_type.json
beams/beams/doctype/sales_type/sales_type.py
beams/beams/doctype/sales_type/test_sales_type.py
beams/setup.py

-Rename Item Type to Sales Type and add 'Is Digital Sales' checkbox
-Created "Sales Type" by renaming "Item Type" and added 'Is Digital Sales' checkbox.
-no

fix:Rename Item Type Doctype To Sales Type

---

beams/beams/doctype/driver_batta_claim/driver_batta_claim.js
beams/beams/doctype/driver_batta_claim/driver_batta_claim.py
beams/public/js/purchase_invoice.js
beams/setup.py

- Feature
-  This feature Auto create Purchase Invoice when the Driver Batta Claim is Approved.
- Validate time fields and calculate hours based on it in Stringer Work Table in Purchase Invoice.
- Applied filters for Driver in Driver Batta Claim,
- Applied Validation that ensures that all rows in the 'stringer_work_details' table have the same date.
[Screencast from 08-30-2024 09:58:16 AM.webm](https://github.com/user-attachments/assets/1db7b2c7-3d58-4250-a7d2-2f6b86594e1a)
Purchase Invoice.
Driver Batta Claim.
- New Data

feat: Create Purchase Invoice on the Approval of Driver Batta Claim

---

beams/setup.py

-add 'Sales Type' field to Item doctype
-added 'Sales Type' field to Item doctype
-no

feat: Customize Item Type Doctype

---

beams/beams/doctype/driver_batta_claim/driver_batta_claim.json
beams/setup.py

- Feature
- Added checkbox "Budget Exceeded" on Material Request.
- Applied Naming Series for Driver Batta Claim.
Sales Order.
Driver Batta Claim.
- New Data

feat: Add checkbox Budget Exceeded on Material Request

---

beams/hooks.py
beams/public/js/sales_invoice.js
beams/public/js/sales_order.js
beams/setup.py

- Feature
- Add field Sales Type  in Sales Order & Sales Invoice.
- Applied filters for items of Sales Order and Sales Invoice.
[Screencast from 08-30-2024 12:31:03 PM.webm](https://github.com/user-attachments/assets/523b8dff-fa0e-41e7-a5af-71b86cb2b359)
Sales Invoice.
Sales Order.
- New Data

feat: Customize Sales Invoice & Sales Order

---

beams/beams/doctype/sales_type/sales_type.json
beams/setup.py

-Rename "Digital Sales" checkbox to "Is Time Sales
-## Solution description
-Renamed"Digital Sales" checkbox to "Is Time Sales
-Sales Type field has been removed from the child table because the field had already been created in the main doctype
-## Output
-no

fix:Rename to Sales Type, add checkbox

---

beams/beams/custom_scripts/quotation/quotation.py
beams/beams/custom_scripts/sales_invoice/sales_invoice.py
beams/beams/custom_scripts/sales_order/sales_order.py
beams/beams/doctype/beams_accounts_settings/beams_accounts_settings.js
beams/beams/doctype/beams_accounts_settings/beams_accounts_settings.py
beams/beams/doctype/beams_naming_rule/beams_naming_rule.json
beams/hooks.py

Add naming rule for Quotation,Sales Order and Sales Invoice through child table Beams naming rule.
Apply filters to doctype field of childtable Beams naming rule to list only  Quotation,Sales Order and Sales Invoice.
Applied  filters to doctype field of childtable Beams naming rule to list only  Quotation,Sales Order and Sales Invoice.
Defined naming series in child table Beams Naming Rule of Beams Account Settings doctype and  the rule is made applicable for naming Quotation,Sales Order and Sales Invoice.
-No

feat:Added naming rule for Quotation,Sales Order and Sales Invoice through child table

---

beams/beams/doctype/employee_advance_purpose/employee_advance_purpose.js
beams/beams/doctype/employee_advance_purpose/employee_advance_purpose.json
beams/beams/doctype/employee_advance_purpose/employee_advance_purpose.py
beams/beams/doctype/employee_advance_purpose/test_employee_advance_purpose.py
beams/setup.py

-Add "Employee Advance Purpose" Doctype and link field to "Employee Advance". Hide existing "Purpose" field in "Employee Advance".
-    Added a new "Employee Advance Purpose" Doctype with a "Purpose" field (Small Text).
-   Updated the "Employee Advance" Doctype to include a "Purpose" field (Link to "Employee Advance Purpose").
- Hid the existing "Purpose" field in the "Employee Advance" Doctype.
-yes.

feat:Create Employee Advance Purpose Doctype and update Employee Advance form

---

beams/public/js/purchase_invoice.js
beams/public/js/sales_invoice.js
beams/setup.py

- chore
- Removed space from selectbox Invoice Type in Purchase Invoice.
- Clear filters for Item table and Supplier field in Purchase Invoice when Invoice Type is General.
- Set 'include_in_ibf' field based on Sales Type, 'is_barter_invoice' and 'is_agent' in  Sales Invoice.
- Hid 'Is Subcontracted', Scan Barcode, Update Stock  fields in Sales Invoice.
[Screencast from 09-02-2024 02:23:12 PM.webm](https://github.com/user-attachments/assets/80a62b71-92ae-4081-94af-648af3ece09a)
[Screencast from 09-02-2024 02:25:29 PM.webm](https://github.com/user-attachments/assets/dc509897-9b29-4e7b-925e-bc19237c15e2)
Sales Invoice.
Purchase Invoice.
- New Data

fix: Update Purchase Invoice & Sales Invoice

---

beams/beams/custom_scripts/quotation/quotation.py
beams/public/js/quotation.js
beams/setup.py

Customise Purchase Order doctype by adding fields  Sales Type(Linked to Sales Type)and Purchase Order(Linked to Purchase Order).Display Purchase Order  only if Is Barter is checked.
Make Albatross RO ID imandatory only when  Is Time Sales  field of Sales Type is checked.
Purchase Order doctype is customised  by adding fields   Sales Type(Linked to Sales Type)and Purchase Order(Linked to Purchase Order). Order).Purchase Order is made visible only if Is Barter is checked.
Albatross RO ID is made mandatory only when  Is Time Sales  field of Sales Type is checked.
-No
-Mozilla

feat:Customised Purchase Order

---

beams/public/js/quotation.js

-Apply a filter to the items child table in the Quotation doctype so that only items matching the selected Sales Type are displayed
-Implemented a filter on the items child table based on the selected Sales Type in the Quotation doctype. This ensures that only      relevant items are shown according to the selected Sales Type
-Added functionality to clear the items child table whenever the Sales Type is updated to maintain data consistency and relevance.
[Screencast from 02-09-24 04:36:20 PM IST.webm](https://github.com/user-attachments/assets/e676ed8c-1ff9-4ba6-a01e-8f57cc34ab4c)
-no

feat:Filter and reset Quotation items by Sales Type

---

beams/beams/doctype/bureau/bureau.json

-Add 'Company' link field to Bureau doctype
-Added 'Company' link field to Bureau doctype.
-no

feat:Customize Bureau Doctype

---

beams/beams/doctype/adhoc_budget/adhoc_budget.js
beams/beams/doctype/adhoc_budget/adhoc_budget.json
beams/beams/doctype/adhoc_budget/adhoc_budget.py

-Add Company Field In Adhoc  Budget Doctype
-Apply Filters On Budget Expense Type based On Company.
-Added Company Field In Adhoc Budget Doctype
-Applied Filters On Budget Expense Type Based On Company.
-No
-Mozilla

fix: Apply Filters On Budget Expense Type Based On Comapany

---

beams/beams/doctype/stringer_type/stringer_type.json
beams/setup.py

- Hide the Series field in the Employee Advance doctype 
- Add a mandatory Purpose field in Employee Advance
- Set the String Type doctype as not submittable to prevent unnecessary submission workflow for this document type.
-Hid Series field in Employee Advance to simplify the form.
-Added mandatory Purpose field in Employee Advance
-Configured String Type doctype as not submittable to prevent submission errors.
-no

fix:Hide Series field, make Purpose mandatory in Employee Advance, and set String Type Doctype as not submittable

---

beams/beams/doctype/beams_accounts_settings/beams_accounts_settings.js
beams/beams/doctype/beams_accounts_settings/beams_accounts_settings.json

Add a new field Batta Claim Service Item in Beams Accounts Settings linked to item doctype and applied filter as maintain stock is false.
Applied filter to field Batta Claim Service Item in Beams Accounts Settings  as maintain stock is false. 
-No

feat: Added new field Batta Claim Service Item and applied fiter

---

beams/beams/doctype/stringer_bill/stringer_bill.js
beams/beams/doctype/stringer_bill/stringer_bill.py

- Feature
- This features checks whether the specified employee is on approved leave or not for each date in Stringer Bill Date Table.
- Applied filters for 'substituting for' field in Stringer Bill based on Bureau.
- Implemented method to validate employee leaves.
- Applied filters.
[Screencast from 09-09-2024 03:04:10 PM.webm](https://github.com/user-attachments/assets/9e118da1-b336-44de-b898-88348381dc39)
Stringer Bill.
- New Data

feat: Update Stringer Bill

---

beams/beams/doctype/beams_accounts_settings/beams_accounts_settings.json

-Include Batta Payable and Expense Account fields in Beams Account Settings
-Added fields for Batta Payable  and Batta Expense  accounts in Beams Account Settings.
-no

feat:Add Batta Payable and Expense Account fields to Beams Account Settings

---

beams/beams/doctype/batta_claim/batta_claim.js
beams/beams/doctype/batta_claim/batta_claim.json
beams/beams/doctype/work_detail/work_detail.json

- Added functionality to automatically sync the batta_type field between the parent Batta Claim doctype and the child Work Detail table.
- Improved field visibility and behavior based on the selected batta_type in Work Detail.
- Added logic to update the `batta_type` field in the child table when the parent `Batta Type` is changed.
- Set `batta_type` as a hidden and read-only field in the `Work Detail` doctype, ensuring it reflects the parent's value.
- Added necessary UI dependencies to display fields like `ot_hours` and `ot_batta` based on the `batta_type` being 'External.'
- Modified the Batta Claim doctype to include autonaming as 'BC-{YY}-{####}'.
[Screencast from 09-09-2024 04:18:52 PM.webm](https://github.com/user-attachments/assets/afee0961-6e3a-434d-8469-0518c6dfe8a1)
[Screencast …

feat : Sync across Batta Claim and Work Detail.

---

beams/beams/doctype/batta_claim/batta_claim.json
beams/beams/doctype/batta_claim_type/batta_claim_type.js
beams/beams/doctype/batta_claim_type/batta_claim_type.json
beams/beams/doctype/batta_claim_type/batta_claim_type.py
beams/beams/doctype/batta_claim_type/test_batta_claim_type.py
beams/beams/doctype/beams_accounts_settings/beams_accounts_settings.json

- Create Doctype Batta Claim Type.
- Add the doctype as link in Batta Claim
- Remove Batta Expense Account From Beams Account Settings
- Created Batta Claim Type
- Linked the batta claim type to the batta claim
- Removed the batta expense account field in beams account settings
Output

feat : Created doc-type Batta Claim Type

---

beams/beams/doctype/batta_claim/batta_claim.py
beams/beams/doctype/stringer_bill/stringer_bill.json

- Feature
- This feature Automatically create a Purchase Invoice when the  Batta Claim is approved, but only if the Batta Type is External.
- This feature Automatically create a Journal Entry when the  Batta Claim is approved, but only if the Batta Type is Internal.
- Fetch the bureau from the employee in the Stringer Bill when the Substituting for field is selected.
- Purchase Invoice
- Journal Entry
- Batta Claim.
- Purchase Invoice.
- Journal Entry
- New Data

fix: Update Journal Entry Creation

---

beams/beams/doctype/stringer_bill/stringer_bill.py

-Auto-Assign Cost Center to Purchase Invoice
-Auto-Assign Cost Center to Purchase Invoice
-no

fix: Update Cost Center

---

beams/beams/doctype/stringer_bill/stringer_bill.py

- This feature calculates total wage and no of days based on dates specified in child table in Stringer Bill
- Implemented a server side method to count no of days based on date specified in Stringer Bill Date table and calculate total wage  based on daily wage and no of days
-no

feat: Calculate total wage and no of days based on date in Stringer Bill

---

beams/beams/doctype/batta_claim/batta_claim.js
beams/beams/doctype/batta_claim/batta_claim.json
beams/beams/doctype/batta_claim/batta_claim.py

Update  Total daily batta field when  Batta field is changed.
Total Daily Batta is calculated based on days and Batta  and updated when either one is changed.
No

fix:Update Total daily batta field when Batta field is changed.

---

beams/beams/doctype/beams_accounts_settings/beams_accounts_settings.json

-Add Substitute Booking Settings and Work Settings Fields
-Added "Substitute Booking Settings" section.
- Added fields:
- Default Credit Account (Link to Accounts)
- Default Debit Account (Link to Accounts)
- Added "Batta Expense Account" field in Work Settings.
-no

Update Beams Account Settings

---

beams/beams/doctype/substitute_booking/substitute_booking.js
beams/beams/doctype/substitute_booking/substitute_booking.json
beams/beams/doctype/substitute_booking/substitute_booking.py
beams/beams/doctype/substitute_booking/test_substitute_booking.py
beams/beams/doctype/substitution_bill_date/substitution_bill_date.json
beams/beams/doctype/substitution_bill_date/substitution_bill_date.py
beams/setup.py

- Feat.
- Created DocType Substitute Booking 
- Made Invoice Type field read-only in Purchase Invoice.
Substitute Booking -Doctype
- New Data

feat: Create DocType Substitute Booking

---

beams/beams/custom_scripts/sales_invoice/sales_invoice.py
beams/beams/doctype/beams_accounts_settings/beams_accounts_settings.js
beams/beams/doctype/beams_accounts_settings/beams_accounts_settings.json
beams/fixtures/workflow.json
beams/hooks.py

-Need to add New Field in Beams Accounts Settings and  enabled print formats is attached in email in Sales Invoice doctype.
Added new field in Beams Accounts Settings 
Applied filter to enabled print formats in Beams Accounts Settings for attaching for sending email
updated the  Sales Invoice Approval Workflow  docstatus.
changed the controller event in hooks.
-Sales Invoice doctype

Added field in Beams Accounts Settings, enabled print format attachment in Sales Invoice emails 

---

beams/beams/doctype/batta_claim/batta_claim.py
beams/beams/doctype/beams_accounts_settings/beams_accounts_settings.js
beams/beams/doctype/beams_accounts_settings/beams_accounts_settings.json
beams/beams/doctype/stringer_bill/stringer_bill.js
beams/beams/doctype/stringer_bill/stringer_bill.json
beams/beams/doctype/stringer_bill/stringer_bill.py

Update Stringer Bill doctype.
The Stringer Bill doctype is updated with following features:
-      Stringer Type,Substituting For fields were  removed.
-       Daily Wage field was renamed as Stringer Amount.
-      Stringer Bill Date child table was removed.
-      Added  Field  Date(set Default=Today).
-      Added DateTime field 'On Air Date and Time'.
-      Added Field News Remarks(Small Text).
Updated Beams Account Settings:
                -Add Link Field Stringer Service Item(Options=Item Doctype)(Applied Filter Maintain Stock=0)
On creating Purchase Invoice up on the Approval Of Stringer Bill, Service Items was fetched from Stringer Service Item Of Beams Account Settings.
-No

fix:Updated Stringer Bill doctype

---

beams/beams/doctype/substitute_booking/substitute_booking.py

Need to create the Journal entry Automatically From the Approval of  Substitute Booking Doctype 
created the Journal entry Automatically From the Approval of  Substitute Booking Doctype .
New Feature
-No

feat: Created Journal Entry from Approval of Substitute Booking Doctype

---

beams/beams/doctype/substitute_booking/substitute_booking.js
beams/beams/doctype/substitute_booking/substitute_booking.json
beams/beams/doctype/substitute_booking/substitute_booking.py

- feat.
- Calculate no of days based on dates specified in Substitution Bill Date child table.
- Compute total wage based on daily wage and no of days in Substitute Booking doctype.
- fetch cost center associated with  bureau when bureau is selected.
- Validation for employee leave on dates specified in Substitution Bill Date child table.
[Screencast from 09-17-2024 12:54:36 PM.webm](https://github.com/user-attachments/assets/cdb86050-22c0-444a-924a-0501e5aaa0dc)
Substitute Booking.
- New Data

feat: Update Substitute Booking doctype

---

beams/beams/doctype/voucher_entry_type/voucher_entry_type.json
beams/setup.py

- fix
- Remove fields 'Description' and 'Attachment' from the doctype Voucher Entry Type.
- Add custom field 'cost center' in the doctype Journal Entry.
Journal Entry.
Voucher Entry Type

fix: Remove fields from doctype Voucher entry type

---

beams/hooks.py
beams/public/js/voucher_entry.js
beams/setup.py

- Feat
-Added a new custom field 'Bureau' to the Voucher Entry doctype and implemented logic to automatically populate the Cost Center and Company fields based on the selected Bureau.
Updated hooks.py to include 'voucher_entry.js' for Voucher Entry Doctype.
Added 'Bureau' custom field in Voucher Entry via setup.py.
Implemented client-side logic to fetch and set cost center and company based on Bureau selection.
- Voucher Entity Doctype.
- New Data

feat : Added field Bureau in Voucher Entry Doctype.

---

beams/beams/doctype/batta_claim/batta_claim.json
beams/beams/doctype/batta_claim/batta_claim.py
beams/setup.py

-Update Batta Claim Doctype.
-Added Field batta Claim Reference in both purchase invoice and journal entry.
-Added Purchase Invoice and journal entry connections in Batta Claim Doctype.
-No

feat: Add Connections In Batta Claim Doctype

---

beams/beams/doctype/albatross_settings/albatross_settings.js
beams/beams/doctype/albatross_settings/albatross_settings.json
beams/beams/doctype/albatross_settings/albatross_settings.py
beams/beams/doctype/albatross_settings/test_albatross_settings.py
beams/setup.py

Need to Add a new Custom Field 'Albatross Customer ID' to the Customer doctype .
also add a new Custom Fields  in Quotation doctype.
create a new single doctype Albatross settings need to filter where maintain stock is zero and Sales type is Time Sales.
Added ''Albatross Customer ID'' custom field in Customer via setup.py.
Added 'Region' custom field in Quotation via setup.py
Added  a new section break Albatross Details includes 'Albatross Invoice Number','Albatross Ref  Number','Client Name','Executive Name' custom fields in Quotation via setup.py. 
deleted Albatross RO ID custom field in Quotation  and added in section break Albatross Details .also is barter checkbox insert after the sale type field in via setup.py.
Created a single doctype Albatross settings with field  'Albatross …

feat:Created a doctype Albatross Settings and Customized Quotation nd Customer doctype

---

beams/beams/doctype/batta_claim/batta_claim.py
beams/beams/doctype/beams_accounts_settings/beams_accounts_settings.json

Issue Description:
- Total distance should automatically fetch through back-end
- Add Description to single sales checkbox in beams settings
Solution Description:
- Total distance automatically fetched from the child table workdetails
- Added Description to single sales checkbox in beams settings
Output
[Screencast from 19-09-24 12:31:22 PM IST.webm](https://github.com/user-attachments/assets/4b78fb57-8aaa-42d7-a634-16d732ff17e6)

fix : Total distance automatically fetch through backend

---

beams/fixtures/workflow.json
beams/hooks.py
beams/public/js/purchase_invoice_list.js
beams/public/js/sales_invoice_list.js

-Implemented custom status indicators in the Sales Invoice and Purchase Invoice  List Views based on both the status and workflow_state and need to ensure workflow state does not override the status in the list view.
Purchase Invoice  and Sales Invoice list view, particularly the display of invoices based on their status and workflow state.
Displayed  purchase invoice and sales invoice in list view based on the status and workflow state.
Ensured that the workflow state does not override the status in the list view when both are present.
Added  logic to display visual indicators for invoice status.
[Screencast from 20-09-24 01:29:45 PM IST.webm](https://github.com/user-attachments/assets/2dc75312-ef5a-4c1d-b06d-f6500c84566a)
new feature 
-No

feat: Added custom status indicators to Purchase Invoice and Sales Invoice List View.

---

beams/beams/doctype/batta_claim/batta_claim.js
beams/beams/doctype/work_detail/work_detail.json

-Add logic to populate  `origin` and `destination` fields in the `work_detail` child table from the parent form.
-Implemented logic to fill  `origin` and `destination` fields in the `work_detail` child table using parent form values.
-Corrected label casing for the `Destination` field in `work_detail`
[Screencast from 23-09-24 09:39:54 AM IST.webm](https://github.com/user-attachments/assets/8a52a03a-8aaf-4e4a-90d8-e649a3b8e724)
-no

fix:Update work_detail rows with parent values and fix label casing

---

beams/beams/doctype/beams_accounts_settings/beams_accounts_settings.json

-Reorganize field order in Beams Accounts Settings
-.Reordered fields to move `batta_payable_account` after `single_sales_invoice`.
-no

chore:Adjust field order in Beams Accounts Settings

---

beams/beams/doctype/stringer_bill/stringer_bill.py
beams/beams/doctype/substitute_booking/substitute_booking.json
beams/beams/doctype/substitute_booking/substitute_booking.py

-Implement the automatic creation of ToDo while creating the Stringer Bill and Substitute Booking.
-Make Substitute Booking   Doctype Submittable
-created ToDo while creating the stringer bill ,TodO Created to Account Manager
-created ToDo While Creating the Subtitute Booking , ToDo Created to Account Manager
-Modified the Substitute Booking  doctype to be submittable
stringer bill:
[Screencast from 23-09-24 04:59:32 PM IST.webm](https://github.com/user-attachments/assets/1fe70cb2-c553-4423-9e12-bed57406ec1e)
substitute Booking:
[Screencast from 23-09-24 05:02:43 PM IST.webm](https://github.com/user-attachments/assets/3dd9d785-f005-4bac-8abb-b7f577c8289c)
-New Feature
-No

feat:Created ToDo in Stringer Bill and Substitute booking

---

beams/setup.py

- Need to Fix the Alignment is_barter checkbox in quotation doctype.
added the section break insert after the is_barter checkbox  via setup.py 
-added the changes in setup.py
-No

fix: Fixed the alignment of is_barter checkbox in Quotation doctype

---

beams/beams/doctype/substitute_booking/substitute_booking.json
beams/beams/doctype/substitute_booking/substitute_booking.py
beams/setup.py

Create a field for Substitute Booking Reference in Journal Entry and with that  add connection from Substitute Booking to Journal Entry.
Created customised field Substitute Booking Reference in Journal Entry linked to Substitute Booking doctype.
The field was populated with  unique Id.Link was added from Substitute Booking to journal entry.
-No

feat:Added link from Substitute Booking to Journal Entry

---

beams/beams/doctype/batta_claim/batta_claim.js
beams/beams/doctype/batta_claim/batta_claim.json

Feature description
In Subsitute Booking doctype if employee is set then designation is fetched from Employee.The designation field is made editable.
Designation made editable. Fetch from expression  is removed from json file and is implemented through code.
Now one can edit designation as per his preference.
-No

chore:Made designation field editable

---

beams/beams/doctype/stringer_bill/stringer_bill.py
beams/beams/doctype/work_detail/work_detail.json

-Reorganize the field layout in the Work Detail Doctype to include new fields like batta_type and on_air_date.
-Update the rate in Purchase Invoice creation from total_wage to daily_wage for more accurate calculations.
-Reorganized fields in the Work Detail form
-Changed Purchase Invoice item rate calculation from total_wage to daily_wage for more precise billing.
-No

feat:Reorganize fields in Work Detail Doctype and update wage mapping in Purchase Invoice

---

beams/beams/custom_scripts/contract/contract.py

- Contract cannot approved if party type is not supplier
- Purchase Order creation checking done only on party type is supplier 
##Output

fix : Contract cannot be Approved when party type is not supplier

---

beams/beams/api/api.py

- Fix
- There is no need for tax template assignment in quotation API .
##Solution description
Removed tax template assignment.
Release Order.
- New Data

fix: Remove tax template assignment from quotation API

---

beams/public/js/contract.js

-Implemented to  Fix  issue where the Total Amount was not updating after row deletions service child table in Contract Doctype
Fixed issue where the Total amount was not updating after row  deletions in service child table in a Contract Doctype.
[Screencast from 26-09-24 03:11:36 PM IST.webm](https://github.com/user-attachments/assets/851b4e2b-9a59-4b73-9e6a-cf1a2b9711b2)
-fixed issue in the update total amount in Contract Doctype
-contract.js

fix:Fixed issue where the total amount was not update Contract doctype.

---

beams/beams/doctype/substitute_booking/substitute_booking.js

-Implemented to  Fix  issue where the   No of days and Total Wage was not updating after row deletions Substitute Bill Date  child table in  Substitute Booking Doctype
Fixed issue where the No of days and Total Wage was not updating after row  deletions in Substitute Bill Date child table in a Substitute Booking  Doctype.
[Screencast from 27-09-24 11:49:28 AM IST.webm](https://github.com/user-attachments/assets/d33389f5-6f08-4a10-b3b9-4fe25bad732e)
-fixed issue in the update No of days and Total Wage  in Substitute booking  Doctype
-Substitute Booking .js

fix:updated no_of_days and total_wage based on child table changes in Substitute Booking

---

beams/beams/custom_scripts/department/department.py
beams/beams/doctype/division/division.js
beams/beams/doctype/division/division.json
beams/beams/doctype/division/division.py
beams/beams/doctype/division/test_division.py

-Add Division Doctype
-Add mandatory 'Department' Link field to associate with the Department Doctype
-Implement 'Department Abbreviation' field (Data) to auto-fetch from the selected department
-Add mandatory 'Division' field (Data) for specifying division names
-Set Naming Series
-Added mandatory 'Department' Link field to associate with the Department Doctype
- Implemented 'Department Abbreviation' field (Data) to auto-fetch from the selected department
- Introduced mandatory 'Division' field (Data)
- Configured Naming Series as "Division-Department Abbreviation" 
- Added a docstring to describe the function purpose
-This filter enhances data accuracy by preventing agent customers from being selected where only non-agent customers are relevant.
-yes.

feat:Create Division Doctype

---

beams/beams/doctype/batta_claim/batta_claim.js
beams/beams/doctype/batta_claim/batta_claim.py

-Set Read Only to Batta claim fields based on checkbox of Batta Policy.
-Updated the Batta Claim form to dynamically set fields as read-only based on values from the "is_actual"     checkboxes in the Batta Policy.
-No

feat :  Added dynamic read-only field handling for Batta Claim form based on Batta Policy

---

beams/beams/doctype/job_description_template/job_description_template.js
beams/beams/doctype/job_description_template/job_description_template.json
beams/beams/doctype/job_description_template/job_description_template.py
beams/beams/doctype/job_description_template/test_job_description_template.py
beams/hooks.py
beams/public/js/job_requisition.js
beams/setup.py

-Need to create the Doctype Job Description Template and implement  dynamic filtering and data fetching for the Job Requisition 
doctype.
-Created  a new doctype Job Description Template with fields Job Description Template, Job Description and Designation.
-Added new field Job Description Template in Job Requisition doctype via setup.py.
-Applied  filter in field 'Job Description Template' by Designation in Job Requisition Doctype.
-Need to Map the  Job Description  in Job Description Template Doctype in to Job Requisition doctype.
-Configured Naming Series as  field name "Job Description Template" in Job Description Template
-Added a docstring to describe the function purpose in Job  Requisiton .js
-Added custom js job requisition.js via hooks.py
[Screencast from 02-10-24 02:45:05 PM …

feat: Created doctype Job Description Template

---

beams/beams/doctype/substitute_booking/substitute_booking.js
beams/beams/doctype/substitute_booking/substitute_booking.json
beams/beams/doctype/substitute_booking/substitute_booking.py

Add some logic to mark payment details before making journal entry.
- Added new fields Is Paid(checkbox) and Paid Amount.
- If Is Paid is checked,Paid Amount is populated with value fetched from  Total Wage.
- If unchecked a custom button labelled 'Make Payment' appears on approval of workflow.On action of this button payment is completed and Journal Entry is made.
-Task form UI, including the navbar where the timer is displayed.
-No

fix:Added payment details in Substitute Booking

---

beams/setup.py

-Customize the Doctype Sales Order and Quotation Item.
-Added fields to manage actual customer and customer groups for agent-linked invoices.
-Included a checkbox to indicate barter invoices.
-Linked reference_id to the Quotation for fetching related data.
-Actual Customer field is shown only if the selected customer is an agent.
-Actual Customer Group is fetched based on the selected actual customer.
-Added checkbox Include In IBF.
-No

feat : Add Custom Fields In Quotation Item and Sales Order

---

beams/beams/doctype/substitute_booking/substitute_booking.js

-    Need Disable the '+' icon in the Connections for  journal entry  substitute booking doctype.
-If the status is 'Approved', the '+' icon is disabled in Connections for journal entry in substitute booking doctype 
-Implemented logic to disable the '+' icon  via Substitute Booking doctype .
-Added a Comment to describe the code  purpose in  Substitute Booking doctype.js
[Screencast from 04-10-24 09:59:37 AM IST.webm](https://github.com/user-attachments/assets/2ad534f7-75b6-41e1-a91a-5dcad4d2d398)
New Feature
-No

 Hide '+' icon in Connections in Substitute Booking

---

beams/setup.py

- Fix
- There was a duplicate custom fields definition for "Job Requisition" in the setup.py file, which led to redundant code.
- Removed the duplicate get_job_requisition_custom_fields() function from setup.py, ensuring only one definition remains for the custom fields setup.
- `beams/setup.py`
- No
- New Data
- No

fix : Remove duplicate custom field definition.

---

beams/beams/custom_scripts/job_requisition/job_requisition.py
beams/hooks.py
beams/setup.py

- Feature
- Automatically create a Job Opening document when a Job Requisition is approved.
- Populate Job Opening fields with data from the approved Job Requisition.
**Fields** : 
1. Minimum Educational Qualification
2. Add Minimum Experience Required
3. No of Positions
4. Expected Compensation
5. Number of Days Off
6. Designation
7. Department
8. Employment Type
1. Trigger the creation of a Job Opening when the workflow state of a Job Requisition changes to "**Approved**."
2. Validate essential fields in the Job Requisition before creating the Job Opening.
3. Populate relevant fields from the Job Requisition into the Job Opening document.
4. Display a success message upon successful creation.
[Screencast from 10-07-2024 10:41:28 …

feat : Create Job Opening on the Approval of Job Requistion

---

beams/fixtures/workflow.json
beams/setup.py

-Enhance Job Requisition workflow with automated status updates
-Implemented automated status updates for Job Requisition workflow
- Set status to 'Pending' until CEO approval.
- Changed status to 'Open & Approved' upon CEO approval.
- Updated status to 'Rejected' if denied by CEO.
- Set status to 'On Hold' if placed on hold by CEO.
[Screencast from 07-10-24 01:27:13 PM IST.webm](https://github.com/user-attachments/assets/3c9bae85-adca-4752-81ce-8e44a6555cff)
-yes.

feat:Implement automated status management for Job Requisition workflow

---

beams/public/js/quotation.js

-Replace frappe.call with frappe.db.get_value to fetch sales_type in Quotation Item
-Updated item_code trigger in Quotation Item doctype to use frappe.db.get_value for a cleaner, promise-based approach.
-No

fix : Replace frappe.call with frappe.db.get_value to fetch sales_type in Quotation Item

---

beams/beams/custom_scripts/job_requisition/job_requisition.py
beams/hooks.py

- On cancel of job requisition change the status of job opening to closed and closed on to the current date
- Cancel action on job requisition then the corresponding job opening status is changed to closed 
-  job opening field closed on date set to current date

feat : Job opening is closed on cancel of job requsition

---

beams/public/js/job_requisition.js

- Fix
- The employee_left field in job requisition did not always filter employees with status "Left".
- Moved the set_query call to refresh event.
Job Requisition
- New Data

fix: Resolve inconsistent filter for employee_left field based on status

---

beams/beams/custom_scripts/journal_entry/journal_entry.py
beams/beams/doctype/substitute_booking/substitute_booking.js
beams/beams/doctype/substitute_booking/substitute_booking.py
beams/hooks.py
beams/setup.py

- Feature
When a substitute is assigned for an employee on a specific date, the button must display a filtered list of approved leaves.Also validate Duplicate assignment of substitutes.
- This pull request adds a custom button "Leave Application List" under the "View" dropdown in the "Substitute Booking"     form. 
- The button allows users to view approved leave applications based on dates specified in the child table. 
If no leave applications are found for the provided dates, an error message is displayed.
-  Also Journal Entry (that is created on approval of this Substitute Booking ) when cancelled updates Is Paid checkbox to    zero.
- Duplicate assignment of substitutes are validated.
/home/zakkiyath/Pictures/Screenshots/Screenshot from 2024-10-08 11-02-48.png
- `beams/setup.py`
- …

feat:Applied filter for Leave Application list.

---

beams/setup.py

-Move 'status' field configuration to property setter in Job Requisition
-Add new fields to Job Requisition for employee exit, staffing plan, and unplanned requests
-Removed 'status' field configuration from custom fields definition.
-Added property setter to make 'status' field read-only in the Job Requisition doctype.
-Added "Request For" field as a Select option with values: Employee Exit, Staffing Plan, and Unplanned.
- Introduced "Employees Who Left" as a Table MultiSelect, shown only when "Request For" is set to "Employee Exit."
- Added "Staffing Plan" Link field, displayed when "Request For" is set to "Staffing Plan."
- Included "Requested By" field after the Staffing Plan.
-no

chore:Set 'status' field in Job Requisition to read-only

---

beams/beams/doctype/division/division.json

-Update autoname format in Division doctype
- Changed autoname to "{division}-{department_abbreviation}" for improved naming clarity and consistency.
-yes.

fix:Update autoname format for Division doctype

---

beams/beams/doctype/educational_qualification/educational_qualification.js
beams/beams/doctype/educational_qualification/educational_qualification.json
beams/beams/doctype/educational_qualification/educational_qualification.py
beams/beams/doctype/educational_qualification/test_educational_qualification.py
beams/beams/doctype/license_type/license_type.js
beams/beams/doctype/license_type/license_type.json
beams/beams/doctype/license_type/license_type.py
beams/beams/doctype/license_type/test_license_type.py
beams/setup.py

Add Field 'License Type '(Data)
Naming series should be the License Type Name field.
Link it to Job requsition
-> Created  License Type doctype 
-> Linked it to the job requsition doctype's field License Type
-> Applied the Naming Series too
License Type field in job requsition is linked to the License doctype
No
Chrome

feat: Created a License Type doctype and linked to job requsition

---

beams/beams/doctype/local_enquiry_checklist/local_enquiry_checklist.json
beams/beams/doctype/local_enquiry_checklist/local_enquiry_checklist.py
beams/beams/doctype/local_enquiry_parameter/local_enquiry_parameter.js
beams/beams/doctype/local_enquiry_parameter/local_enquiry_parameter.json
beams/beams/doctype/local_enquiry_parameter/local_enquiry_parameter.py
beams/beams/doctype/local_enquiry_parameter/test_local_enquiry_parameter.py

- Need to create  Doctype Local Enquiry Parameter and Local Enquiry Checklist Child Table.
1. Created Doctype Local Enquiry Parameter 
- Parameter (Data,Mandatory)
- Added section break 'Applicable In'
- Job Applicant(Check)
- Added naming series as parameter(Field  name)
2. Created Child Doctype Local Enquiry Checklist
- Parameter(Link,options-Local Enquiry Parameter,Mandatory)
- Value(Data)
- Remarks(Data)
-New feature
-No

 Created Doctype Local enquiry Parameter and Local Enquiry Checklist Child Table

---

beams/beams/custom_scripts/job_requisition/job_requisition.py
beams/hooks.py
beams/public/js/job_requisition.js
beams/setup.py

1. Apply validation for 'Employees who Left field' in Job Requisition(in Server side and Client side).
2. Customise Job Requisition Doctype:Add fields in Job Requisition
- Location(Link,Options-Locations)
- Add Description for Skill Field-"Proficiency selected here is the minimum proficiency needed".
- Add description Number of days off in 30 days for No of Days off field.
Server-Side Validation Logic:
The employee_left field will be reset to an empty list to ensure the field is not populated in non-exit cases.
Client-side: When the request_for field is updated, the employee_left field is reset to an empty list.
New Fields Added:
- Location(Link,Options-Locations)
- Added Description for Skill Field-"Proficency selected here is the minimum proficency needed".
-  Added  description Number …

feat:Validated  'Employees who Left field' in Job Requisition

---

beams/public/js/job_requisition.js

- Fixed the Implementation of filter for Job Description Template in Job Requisition doctype
-  Need to Clears the Job Description Template field when the form is refreshed in Job Requistion doctype.
1. Changed the event for filter the job description template in the job Requisition Doctype
-  Sets a filter on the Job Description Template field based on the Designation in refresh event via job requisition.js
-   Clears the Job Description Template field when the form is refreshed via job requisition.js
2. Added a docstring to describe the function purpose in Job Requisiton .js
[Screencast from 14-10-24 12:02:44 PM IST.webm](https://github.com/user-attachments/assets/801f9017-b8d7-431e-91c9-8f2183ee4dd7)
[Screencast from 14-10-24 11:47:39 AM …

fix: Fixed the filter for Job Description Template in Job Requisition doctype

---

beams/setup.py

Make Educational Qualification field as MultiSelect
Rearrange child tables Skill Proficiency and Language Proficiency  in Job Applicant doctype
The field Educational Qualification is made as a multiselect field which has link with Educational Qualifications childtable.
-Task form UI, including the navbar where the timer is displayed.
-No

fix:Made Educational Qualification field as MultiSelect 

---

beams/beams/custom_scripts/sales_invoice/sales_invoice.py
beams/beams/doctype/batta_claim/batta_claim.js
beams/beams/doctype/batta_claim/batta_claim.json
beams/beams/doctype/batta_claim/batta_claim.py
beams/hooks.py
beams/public/js/sales_order.js

-Update Batta claim Doctype and sales order.
-Added validation for barter Sales Invoice to ensure corresponding Purchase Invoice exists
-Set batta to 0 upon changing batta_type in Batta Claim doctype
-Hide Employee name in batta claim when the batta type is external.
-Updated Overdue Invoice Alert in sales order.
-No

fix : Update Batta Claim and Sales Order

---

beams/beams/custom_scripts/job_applicant/job_applicant.py
beams/beams/doctype/local_enquiry_report/local_enquiry_report.js
beams/beams/doctype/local_enquiry_report/local_enquiry_report.json
beams/hooks.py

Feature
Restrict Job Applicant Visibility Using Permission Query Condition  
Only allow the interviewer to view and edit the job applicant , assigned to
Implemented the logic using permission query condition.
allowed only the job applicant to visible to interviewer that thay got assigned
beams/hooks.py
beams/beams/custom_scripts/job_applicant/
No
Existing Data
New Data
No

feat: Restrict Job Applicant Visibility

---

beams/beams/custom_scripts/customer_dashboard/customer_dashboard.py
beams/beams/custom_scripts/item_dashboard/item_dashboard.py
beams/beams/custom_scripts/sales_invoice_dashboard/sales_invoice_dashboard.py
beams/beams/custom_scripts/sales_order_dashboard/sales_order_dashboard.py
beams/beams/doctype/beams_accounts_settings/beams_accounts_settings.json
beams/beams/doctype/stringer_bill/stringer_bill.json
beams/beams/doctype/stringer_bill_detail/stringer_bill_detail.json
beams/beams/doctype/stringer_bill_detail/stringer_bill_detail.py
beams/beams/workspace/beams/beams.json
beams/hooks.py
beams/public/js/sales_invoice.js
beams/public/js/sales_order.js
beams/setup.py

-Update Accounts Module.
-Removed Item  Quick creation 
-Removed Dashboard Unnecessary Links in  item
-Removed  Grant Commission Field in item
-Changed Is Agent to Agency
-Removed Sale Team in Customer and All Delivery Note References
-Removed Support,Subscriptions,Delivery Note  and Allowed Items Connections from Customer
-Renamed Quotation to Release order
-Removed BOM,Product Bundle,Manufacture and Delivery Note connections from Item
-Set Include Item in Manufacturing to default 0
-Removed Inspection required before purchase in Item
-Hide Manufacturing TabBreak in item when the maintain stock is checked
-Added Accounts new doctypes to dashboard
-Added Stringer Bill Detail Child table in Stringer Bill
[Screencast from 17-10-24 10:17:24 AM …

fix : Update Accounts Module

---

beams/beams/custom_scripts/job_applicant/job_applicant.py
beams/hooks.py
beams/public/js/job_applicant.js

Add method to trigger creation of Local Enquiry Report from Job Applicant.
- Implemented a custom button in the refresh method of the Job Applicant form..The button triggers a backend method to create a Local Enquiry Report if it does not already exist.
-Task form UI, including the navbar where the timer is displayed.
-No

feat:Created a Local Enquiry Report from Job Applicant

---

beams/beams/custom_scripts/department/department.py
beams/beams/doctype/cost_category/cost_category.js
beams/beams/doctype/cost_category/cost_category.json
beams/beams/doctype/cost_category/cost_category.py
beams/beams/doctype/cost_category/test_cost_category.py
beams/beams/doctype/cost_subhead/cost_subhead.js
beams/beams/doctype/cost_subhead/cost_subhead.json
beams/beams/doctype/cost_subhead/cost_subhead.py
beams/beams/doctype/cost_subhead/test_cost_subhead.py
beams/hooks.py
beams/public/js/budget.js
beams/public/js/department.js
beams/setup.py

-Create Doctype Cost Subhead and Cost Category
-Update Budget
-Update Department Doctype
-Created Doctype Cost Suhead with fields cost subhead,department and Account.
-Added Cost Center Field in Department
-Applied filters in Cost center of department
-And also applied Validation in Cost center of department.
-Added department field in Budget.
-Fetched the department field based on  selecting cost center in budget.
-Created doctype cost category and added this field in to budget child table.
-Added Cost Subhead,cost category and cost description field in Budget Child table.
-Applied filters in cost subhead based on department in budget.
-Fetched account in budget child table from Cost Subhead.
[Screencast from 18-10-24 02:37:17 PM …

feat : Update Budget

---

beams/beams/doctype/expected_question_set_in_interview_round/expected_question_set_in_interview_round.json
beams/beams/doctype/expected_question_set_in_interview_round/expected_question_set_in_interview_round.py
beams/setup.py

-Introduce "Expected Question Set" Child Table In Interview Round and update related fields
-Created "Expected Question Set In Interview Round" child table with:
- "Question" (Small Text, Mandatory)
- "Weight" (Float)
- Enhanced "Expected Skill Set" in "Interview Round" by adding a "Weight" (Float) field.
- Integrated "Expected Question Set In Interview Round" as a child table in the "Interview Round" doctype.
-no

feat:Add Expected Question Set child table to Interview Round and enhance 

---

beams/beams/doctype/interview_rounds/interview_rounds.json
beams/beams/doctype/interview_rounds/interview_rounds.py
beams/setup.py

Add a multiselect field in Job Requisition.
Added child Interview Round(Link,option-Interview Round)
Add this child table in to Job Requisition as 'Interview Rounds'
This is a  Multi select field (Option-Interview Rounds)
Job Requisition.
- Chrome
- Opera Mini
- Safari

feat:Created Child table Interview rounds

---

beams/beams/doctype/interview_question_result/interview_question_result.json
beams/beams/doctype/interview_question_result/interview_question_result.py
beams/hooks.py
beams/public/js/interview_feedback.js
beams/setup.py

Feature
=>  Add new fields to Skill Assessment child table 
* Score(Float, Mandatory, In list view) 
* Remarks(Small Text) 
* Weight(Fetch from Expected Skill Set child table in interview round doctype)
=> Create child table - Interview Question Result 
* Fields are: 
* Question(Small Text, Mandatory, In list view),
* Weight(Fetch from Expected Question Set in interview round doctype)
* Answer(Small Text, Mandatory)
* Score(Float)
Created all the neccessary fields and child doctype .
updates the "Interview Feedback" form by populating the skill_assessment and interview_question_result tables with data fetched from the selected "Interview Round."
beams/beams/doctype/interview_question_result/__init__.py
beams/beams/doctype/interview_question_result/interview_question_result.json …

feat: added fields and created child doctype and fetched the data from interview round to interview feedback

---

beams/setup.py

Feature
Interview rounds field was placed inside a section break named Interview Details.
beams/setup.py
No
Existing Data
New Data
No

fix:Alignment of Job Requisition was done

---

beams/beams/doctype/local_enquiry_checklist/local_enquiry_checklist.json
beams/beams/doctype/local_enquiry_report/local_enquiry_report.json
beams/beams/doctype/local_enquiry_report/local_enquiry_report.py
beams/hooks.py

->Need to update the Local Enquiry Report 
- Need to Add the field in Local Enquiry Report
- Need to Add option in select field in Local Enquiry Report
- Need to add list view in a field in the Local enquiry checklist child table
-  need to set if the Expected Completion Date passed change the status in Local Enquiry Report.
1.  Added the fields
Enquiry Start Date(Date),
Enquiry Completion Date(Date) ,
Expected Completion Date(Date),
Enquiry Officer(Link, option-Employee)  in the Local Enquiry Report doctype
2. Added  new status 'Overdue' in status field(it is a select field) in the Local Enquiry Report doctype
3.  4.Added the list view for value field in Local enquiry checklist child table.
4.updated the status "open" to "overdue" in status field when enquiry_completion_date is after …

feat: Update Local Enquiry Report doctype

---

beams/beams/custom_scripts/job_requisition/job_requisition.py
beams/public/js/job_requisition.js

Feature
In Job Requisition doctype two buttons labelled Actions is seen.One of them should be  renamed as Create.
The secondary action button is renamed as Create. The primary action button which follows a workflow  is remained as such.
The create button has two dropdown:Create Job Opening and Associate Job Opening.when these buttons are clicked they are mapped to Job Opening and associated with Job OPening respectevely. 
beams/beams/custom_scripts/job_requsition/job_requsition
No
Existing Data
New Data
No

feat:Secondary action button in Job Requisition was recreated

---

beams/beams/custom_scripts/job_applicant/job_applicant.py
beams/public/js/job_applicant.js

- Feature
1. A button is added in the Job Applicant DocType to send a magic link via email.
2. This button triggers a confirmation dialog before proceeding. 
3. Once confirmed, the system sends an email to the applicant with the magic link.
**Button Addition:**  
Added a "Send Magic Link" button to the Job Applicant DocType.
**Confirmation Dialog:**  
Implemented a prompt to confirm before sending.
**Email with Magic Link:**  
Generates a tokenized link on confirmation, saving it in the applicant’s document and emailing it to the applicant.
[Screencast from 10-29-2024 11:25:38 AM.webm](https://github.com/user-attachments/assets/b60ce15f-47f0-45c3-a614-16fc47a9faa5)
[Screencast from 10-29-2024 11:24:57 AM.webm](https://github.com/user-attachments/assets/53b722bd-a3eb-47a2-a538-eba88b1713d7) …

feat : Add functionality to send magic link for document upload to job applicants.

---

beams/beams/custom_scripts/job_applicant/job_applicant.py
beams/beams/doctype/applicant_interview_round/applicant_interview_round.json
beams/beams/doctype/applicant_interview_round/applicant_interview_round.py
beams/hooks.py
beams/public/js/job_applicant.js
beams/setup.py

-Need to create child table  'Applicant Interview Round
-Need to Add field Applicant Interview Round in to Job Applicant doctype .
-implement to fetch  the interview rounds from the Job Requisition and in the Applicant Interview Round child table.
-Need Add the Field job opening
1. created child table  'Applicant Interview Round 
- Interview Round(Link, options: Interview Round)
- Interview Reference (Data)
- Interview Status (Data)
- create/view(button)
2 . Added the child table applicant interview round in job appilicant via setup.py
- added the section break via setup.py
- added the field interview rounds (table,option-applicant interview round) via setup.py
- also implemented that if the doctype job applicant doctype job title is selected and saved then only the
Applicant Interview …

feat: Created child doctype Applicant Interview Round

---

beams/beams/doctype/local_enquiry_report/local_enquiry_report.py
beams/beams/doctype/local_enquiry_report/local_enquiry_report_list.js
beams/hooks.py

- Feat
- Update Local Enquiry Report status to 'Overdue' when enquiry completion date exceeds expected completion date.
- Introduced a feature to enhance the Local Enquiry Report list view  with color-coded status indicators,
- Added functionality to update the status of Local Enquiry Report records to 'Overdue' based on the enquiry completion date and expected completion date.
- Added color-coded status indicators to the Local Enquiry Report list view.
- Local Enquiry Report-status updates for overdue reports
- Local Enquiry Report List View: Enhanced with color-coded indicators
No
Existing Data
New Data

feat: Set overdue status for Local Enquiry Reports(TASK-2024-00945)

---

beams/beams/doctype/local_enquiry_report/local_enquiry_report.json
beams/beams/doctype/local_enquiry_report/local_enquiry_report.py

Feature
Added validations in LocalEnquiryReport before the workfow submit for approval
Brougth Validation in LocalEnquiryReport for the necessary fields which are information_given_by and information_given_by_designation 
if it is not filled then msg will be printed that it is not filled .
After fields is filled then continue the process
No
Existing Data
New Data
No

TASK-2024-00932

---

beams/beams/doctype/beams_hr_settings/beams_hr_settings.js
beams/beams/doctype/beams_hr_settings/beams_hr_settings.json
beams/beams/doctype/beams_hr_settings/beams_hr_settings.py
beams/beams/doctype/beams_hr_settings/test_beams_hr_settings.py

- Feat
- a docype is needed to manage default configurations for HR Settings.
- Add read permission for "All" in Beams HR Settings.
- Remove the whitespace from label Admin Department
- Created doctype named 'Beams HR Settings' with fields Default Local Enquiry Duration ,Admin Department, Admin HOD,IT Department ,IT HOD 
- Add read permission for "All" in Beams HR Settings and removed the whitespace from label Admin Department.
- Beams HR Settings.
No

feat: Create doctype Beams HR Settings

---

beams/beams/doctype/job_proposal/job_proposal.js
beams/beams/doctype/job_proposal/job_proposal.json
beams/beams/doctype/job_proposal/job_proposal.py
beams/beams/doctype/job_proposal/test_job_proposal.py
beams/setup.py

Update Job Applicant with Department field and introduce Job Proposal doctype
- Added 'Department' field (Link to Department) in the Job Applicant doctype.
- Created a new  doctype 'Job Proposal' with the following fields:
- Job Applicant: Link (select from Job Applicant)
- Applicant Name: Data (Read-Only, auto-fetch from Job Applicant)
- Designation: Link (select from Designation, Read-Only, auto-fetch from Job Applicant)
- Department: Link (select from Department, Read-Only, auto-fetch from Job Applicant)
- Proposed CTC: Currency (mandatory field)
[Screencast from 04-11-24 04:43:29 PM IST.webm](https://github.com/user-attachments/assets/4a717e0c-bfdf-4477-8721-575b0a0ec0ac)
Job Applicant Doctype 
Job Proposal Doctype
no

TASK-2024-00986: Add Department field in Job Applicant and create Job Proposal doctype

---

beams/beams/custom_scripts/job_applicant/job_applicant.py
beams/beams/doctype/language_proficiency/language_proficiency.json
beams/beams/doctype/skill_proficiency/skill_proficiency.json
beams/setup.py

- fix.
- Removed Validation errors that occur unnecessarily when creating a Job Applicant without a linked Job Opening.
- Validation for location, qualifications, experience, and skills is applied only when these fields are specified in the Job Opening.
- Added checks to validate only filled fields in the Job Applicant against those in the Job Opening.
- Included error handling to avoid validation errors when creating a Job Applicant without a linked Job Opening.
- Made skill proficiency and language proficiency table not mandatory in Job Applicant.
- Made Skill and Proficiency fields in Skill proficiency table not mandatory
- Made Language field in Language proficiency table not mandatory.
[Screencast from 11-04-2024 04:06:42 PM.webm](https://github.com/user-attachments/assets/5240ad95-41 …

fix: improve Job Applicant validation based on Job Opening fields

---

beams/beams/report/budget_report/budget_report.py
beams/setup.py

-Add Custom Fields in Release Order and change the label of Cost Subhead in Budget.
-Add Local Enquiry Approved and Selected options in status of the Job Applicant.
-Added Is Agency,Actual Customer and Actual customer group custom fields in Release Order.
-Changed the label of Cost Sub Head in Budget Report and its child table.
-Added Local Enquiry Approved and Selected Options in status of the Job Applicant.
[Screencast from 05-11-24 01:45:14 PM IST.webm](https://github.com/user-attachments/assets/b2463a74-3e36-4bfc-ad55-ec0d160afdfa)
No.

fix : Added Custom Fields in Release Order and Changed the label of Cost Sub Head In Budget

---

beams/fixtures/workflow.json

-  Set to  enable status overriding  local enquiry report workflow
- Modify the allow edit  permissions to specify roles for different states
-Checked the `override_status` to 1 to enable status overriding.
- Changed `allow_edit` from "All" to "HR Manager" for the first state.
- Changed `allow_edit` from "HR Manager" to "Enquiry Manager" for the second state
local enquiry report doctype
no

fix:  TASK-2024-00946: updated the workflow in local enquiry report

---

beams/beams/custom_scripts/department/department.js
beams/beams/custom_scripts/department/department.py

Filtered the "Head of Department" field in Department to display only employees who have both the "HOD" and "Employee" roles in their respective department.
- Updated the get_hod_users function to join the tabHas Role table twice to ensure that only users who have both the "HOD" and "Employee" roles are included in the results.
- Adjusted the client-side code to handle the case where no users with the "HOD" role are found in the specified department
- Created two employees with the same department
- Assigned a user employee role only.
- Assigned another user both roles 'HOD' and 'Employee'
- ![image](https://github.com/user-attachments/assets/7a320aa0-9173-48ae-9b0f-9df7f2da2b9b)
- filtered "Head of Department" to show employees with both "HOD" and "Employee" roles.
- The "Head of …

TASK-2024-00890: Update filter applied for Head of Department in Department doctype

---

beams/beams/doctype/beams_hr_settings/beams_hr_settings.json
beams/beams/doctype/local_enquiry_report/local_enquiry_report.json
beams/beams/doctype/local_enquiry_report/local_enquiry_report.py

-Set Expected Completion Date on Enquiry Officer assignment
-Remove unused "column_break  from Beams HR Settings Doctype
-Removed unused "column_break_wgti" field from Beams HR Settings Doctype.
- On "Assign to Enquiry Officer" action, automatically set the Expected Completion Date in Local Enquiry Report by adding the Default Local Enquiry Duration (from Beams HR Settings) to the current date.
- Set Expected Completion Date field as read-only to prevent manual edits.
[Screencast from 05-11-24 03:20:02 PM IST.webm](https://github.com/user-attachments/assets/f44d09f1-3930-4256-9924-abf7b326fef1)
Beams HR Settings Doctype 
Local Enquiry Report Doctype
no

TASK-2024-00985:Set Expected Completion Date in Local Enquiry Report on Enquiry Officer assignment

---

beams/beams/doctype/local_enquiry_report/local_enquiry_report.js
beams/beams/doctype/local_enquiry_report/local_enquiry_report.py

-  The information_collected_by field  in Local Enquiry Report was previously being set to the current user every time the form loaded.
- The information_collected_by field in the Local Enquiry Report is now set to the current user only when the workflow state transitions to "Pending Approval."
- Local Enquiry is done by Assigned Enquiry Officer mentioned in Local Enquiry Report.
- The client-side code that previously set the information_collected_by field on form load was removed.
-  Instead, the field is now updated on the server-side during the validation phase of the Local Enquiry Report. When the workflow_state changes to "Pending Approval," the field is assigned the value of the current user 
- the information_collected_by field in Local Enquiry Report is assigned the id of Enquiry …

TASK-2024-00932: Set information_collected_by on Pending Approval of Local Enquiry Report

---

beams/setup.py

status options ("Pending,Open & Approved,Rejected,Filled,On Hold,Cancelled") should be added through Property Setter in Job Requisition.
Added required option in status field of job requisition using property setter.
Job Requisition.
No.

TASK-2024-00896: Added status options in Job Requisition through Property Setter

---

beams/beams/custom_scripts/interview/interview.js
beams/beams/custom_scripts/interview/interview.py
beams/beams/custom_scripts/interview_round/interview_round.py

- Questions should be fetched from interview round to Question assessment table in dialog
- Hide 'Submit feedback' Button
- Check exist of feedback and   fetch it while reloading the dialog button.
- Save,save and submit buttons should be shown in that dialog
- If an interview feedback is submitted for an interview hide dialog button.
- Questions automatically fetch from interview round to dialog box and can also additionally add.
- Hided Already existing submit feedback button from erp.
- Fetched the existing feedback once if it is in draft.
- Both Save and submit actions are available in dialog.
- Once the interview feedback for an interview is submitted then the dialog button is hided
[Screencast from 06-11-24 12:34:38 PM IST.webm](https://github.com/user-attachments/assets/bff71ca0-dbc …

fix : Existing Interview feedback fetched back

---

beams/beams/custom_scripts/job_applicant/job_applicant.js
beams/beams/custom_scripts/job_applicant/job_applicant.py
beams/beams/doctype/local_enquiry_checklist/local_enquiry_checklist.json
beams/beams/doctype/local_enquiry_report/local_enquiry_report.json

1.Make 'Enquiry Report' field optional  in Local Enquiry Report 
2.Need  to Implement the creation Button Local Enquiry Report in Job apaplicant 
1.Make 'Enquiry Report' field optional  in Local Enquiry Report 
-Removed  the mandatory in enquiry_report field(option-table) in local enquiry report.
-Removed  the mandatory in Parameter field(option-data) in  child table local enquiry checklist .
2.Need  to Implement the creation Button Local Enquiry Report in Job apaplicant 
-Added a check to call get_existing_local_enquiry_report and conditionally display the "Create" or "View" button for the Local     Enquiry Report.
-implement the logic that create button only when if not exists and if clicked the button alert message created and viewed from the button view buttonvia job applicant.py and …

 TASK-2024-00938:  Fixed the Creation of Local Enquiry Report From Job Applicant 

---

beams/beams/custom_scripts/job_applicant/job_applicant.js

-Create Custom Button Job Proposal in Job Applicant when the status is Selected.
-Created Job Proposal button in Job Applicant when the status is "Selected".
-when clicking button it should be redirected to Job Proposal Doctype.
-Button will only show to HR Manager Role.
-Ensure that the button only appears if there is no existing Job Proposal for the Job Applicant."
[Screencast from 06-11-24 03:04:46 PM IST.webm](https://github.com/user-attachments/assets/47b60aa8-e006-4bc2-bcdc-beaa5951b0c0)
[Screencast from 06-11-24 03:06:39 PM IST.webm](https://github.com/user-attachments/assets/bd29945b-1096-4af4-a344-2504bbd13708)
No.

    TASK-2024-00987 : Create Custom Button Job Proposal In Job Applicant when the status is Selected

---

beams/beams/custom_scripts/job_applicant/job_applicant.js
beams/setup.py

1 Need to Add new option in status field in job applicant
2.Need to create  custom button to set status as 'Training Completed' 
3.Need to Create the Custom Button to  Appointment Letter 
1 Added  option "Training Completed" in status field in job applicant via setup.py
2 implemented   custom button to set status as 'Training Completed' 
-when the status of job applicant "Accepted " created custom button 'Training Completed' 
3 Created the Custom Button to  Appointment Letter 
-Button will only  show to HR Manager
-If Job Applicant status is Training Completed, Once created remove the Button via job applicant.js 
[Screencast from 06-11-24 10:51:23 PM IST.webm](https://github.com/user-attachments/assets/83de88f3-d259-4bd8-aff8-08ef1b7c88f0)
job applicant 
No.

TASK-2024-00996: Created Custom Button to Create Appointment Letter

---

beams/beams/custom_scripts/job_applicant/job_applicant.py
beams/beams/doctype/beams_hr_settings/beams_hr_settings.json
beams/beams/doctype/job_proposal/job_proposal.json
beams/beams/doctype/job_proposal/job_proposal.py
beams/fixtures/workflow.json

- The on_update_after_submit method checks the workflow state, triggering the job offer creation if "Applicant Accepted."
- A new Job Offer document is created, pulling data from the Job Proposal.
- Beams HR Settings configures Admin HOD and IT HOD fields and provides notification templates for personalized messages.
- Notifications are assigned to Admin HOD and IT HOD with custom Jinja messages if both are defined.
- The HR Manager can amend the Job Proposal document and create a revised version, with an Amend button if not available.
[Screencast from 11-07-2024 09:59:21 AM.webm](https://github.com/user-attachments/assets/4125ed84-dc21-4d94-acbe-f9b829fed222)
[Screencast from 11-07-2024 09:23:21 AM.webm](https://github.com/user-attachments/assets/ef4f80b0-0e10-49be-a376-0c46b9ff136f) …

feat : Create ToDos for Admin and HR Departments upon Job Offer Creation

---

beams/beams/custom_scripts/job_applicant/job_applicant.js

1.Need to create custom button in job applicant doctype
2. optimize the code in job applicant doctype
3. implement  handling of "Local Enquiry Report" button creation and view logic
1 created custom button in  job applicant doctype
-created the custom button in set status group button 
-"Rejected" Button: Displays when the status is not "Rejected" or "Selected".
-"Hold" Button: Displays when the status is neither "Rejected" nor "Hold". 
-"Selected" Button: Displays only when the status is "Hold". via job applicant .js
2 optimized the code in job applicant doctype
-added the custom button in one function via job applicant .js
3 implemented  handling of "Local Enquiry Report" button creation and view logic
-Added frm.refresh() to ensure the form is properly updated after adding custom …

feat:  TASK-2024-00938:Added custum button depend on status updates

---

beams/beams/custom_scripts/sales_order/sales_order.py
beams/hooks.py
beams/setup.py

-Add Custom Fields in Quotation,Sales Order and Sales Invoice.
-Fetch region in Sales Order from Release Order.
-Added Region,Executive, and Executive Name fields in Quotation,Sales Order,and Sales Invoice.
-Updated Region in Sales Order from Release Order
[Screencast from 08-11-24 11:50:17 AM IST.webm](https://github.com/user-attachments/assets/99ef3529-3640-45a8-abb1-25f821d6ebb5)
No.

feat : Add Custom Fields in Quotation,Sales Order and Sales Invoice

---

beams/beams/doctype/beams_hr_settings/beams_hr_settings.json

Update the  sections for Admin and IT department notifications Beam HR settings Doctype.
Updated the sections for Admin and IT department notifications Beam HR settings Doctype.
- Removed the on tab break Department Settings and it's fields Admin Department,Admin HOD,IT Department and IT HOD
- Added the two section break 
- added new fields Responsible Employee(Link,option-Employee)in two section break 
[Screencast from 08-11-24 03:33:26 PM IST.webm](https://github.com/user-attachments/assets/ea2be76a-afe6-4e0f-8872-fab3ea793aa8)
Beam HR Settings doctype
No. 

fix:     TASK-2024-01023: Update Beams HR Settings Doctype

---

beams/setup.py

Clearly and coAdd a new tab to the Company DocType named Company Policy.
In this new tab, add a field:
    Company Policy: Text Editor.ncisely describe the feature.
New Tab Added:A new tab, Company Policy, has been added after the existing dashboard_tab in the Company 
DocType.
New Field:
A Text Editor field named Company Policy has been added to the Company Policy tab to allow users to input and f 
ormat the company’s policy text.
The company_policy_tab is a Tab Break field inserted after the dashboard_tab.
The company_policy field is a Text Editor field, designed for the company policy text, and is placed directly after the company_policy_tab
setup.py
- Chrome
- Mozilla …

    TASK-2024-01028:Added fields in custom doctype Company

---

beams/beams/doctype/company_policy_acceptance_log/company_policy_acceptance_log.js
beams/beams/doctype/company_policy_acceptance_log/company_policy_acceptance_log.json
beams/beams/doctype/company_policy_acceptance_log/company_policy_acceptance_log.py
beams/beams/doctype/company_policy_acceptance_log/test_company_policy_acceptance_log.py

- Create a doctype Company Policy Acceptance Log
- Validate the field Accept and Signature should be filled before submit
- Only the selected employee can only access submit
- Created doctype CPAL with field Employee , Department , Designation and Company
- Validated that the both field Read and Accept and Digital Sign should not be empty
- Only Employee selected in the field can submit the form 
[Screencast from 11-11-24 03:54:01 PM IST.webm](https://github.com/user-attachments/assets/f6e3c568-8c71-4f74-963c-5f135786134a)

TASK-2024-01027 : Created a doctype CPAL and validated

---

beams/beams/doctype/training_request/test_training_request.py
beams/beams/doctype/training_request/training_request.js
beams/beams/doctype/training_request/training_request.json
beams/beams/doctype/training_request/training_request.py

Create 'Training Request' doctype with fields
Added 'Training Request' doctype with the following fields:
- Employee (Link to Employee, mandatory)
- Posting Date (Date)
- Expected Training Completion Date (Date)
- Remarks (Small Text, mandatory)
- Training Requested by (Link to Employee)
- Training Requested By (Name, Data, Read-only, fetched from 'Training Requested by' field)
- Training Event (Link to Training Event, Read-only)
- Status (Select: Open, Training Scheduled, Training Completed)
No. 

    TASK-2024-01053:Create doctype Training Request

---

beams/beams/custom_scripts/job_applicant/job_applicant.js

Hide Interview Button in Job Applicant when the Job Applicant status is Training Completed.
Objective: The goal of this feature is to hide the "Interview" button on the Job Applicant form when the applicant's status is "Training Completed". This ensures that once an applicant has completed training, no further interviews can be scheduled for them.
Modified the handle_custom_buttons function to check if the applicant's status is "Training Completed".
If the status is "Training Completed", the "Interview" button is removed from the form using 
frm.remove_custom_button().
Job Applicant doctype.
No.
- Chrome

TASK-2024-01034:Removed custom button create interview when status is  Training  Completed

---

beams/beams/custom_scripts/interview/interview.js
beams/beams/custom_scripts/interview/interview.py
beams/beams/custom_scripts/interview_feedback/interview_feedback.py
beams/beams/custom_scripts/job_applicant/job_applicant.py
beams/beams/doctype/expected_question_set/expected_question_set.json
beams/hooks.py
beams/setup.py

Change status of Job Applicant to the following ones according to different interview stages
- Interview Scheduled(On Scheduling any of the interview listed in the Job Applicant)
- Interview Ongoing(On creation of any of the Interview Feedback creation linked to the Job Applicant)
- Interview Completed (On completion of all interview rounds in the Job Applicant - if the Interview Completed checkbox is checked for each interview round in the Applicant Interview Round table in Job Applicant)
Fixes:
- The interview document could not be submitted.
- Currently  Interview Completed checkbox in Applicant Interview Round child table is checked  when the interview document is created.
- Put fields Question and Weight in Expected Question Set table in Grid view.
- Set Job Applicant status to: …

feat: Change status of Job Applicant according to Interview stages

---

beams/setup.py

Add 'Training Request' link field in Training Event Employee child table
- Added a custom link field 'Training Request' to the Training Event Employee child table
- Links each employee entry in a training event to their associated training request
Training Event Doctype
No

    TASK-2024-01054:Add 'Training Request' link field to Training Event Employee table

---

beams/beams/doctype/company_policy_acceptance_log/company_policy_acceptance_log.json
beams/fixtures/workflow.json
beams/fixtures/workflow_state.json
beams/hooks.py

- This feature adds an additional state, "Applicant Rejected," to the job application workflow.
- the fields department,designation,Date of Joining from Employee in Company Acceptance Log should be get from employee selected in Company Policy Acceptance Log Doctype.
- Added the "Applicant Rejected" state to the job application workflow and configured a transition from "Approved" to "Applicant Rejected" for the HR Manager role.
- fetched department,designation,Date of Joining from Employee in Company Acceptance Log Doctype.
Job Proposal Workflow
Company Policy Acceptance Log Doctype

fix: Add Applicant Rejected state to job application workflow

---

beams/beams/custom_scripts/training_event/training_event.py
beams/beams/doctype/training_request/training_request.js
beams/hooks.py

-Add "Create Training Event"Custom button in Training Request
Set status of linked Training Requests based on Training Event status
- Added a new option "Training Event" in the "Create" button group of the Training Request doctype.
- Adds the employee from the Training Request to the Training Event Employee child table.
- Updates the Training Request status based on the Training Event status
- Ensured the "Create Training Event" option is accessible only to the HR Manager role.
[Screencast from 14-11-24 02:26:43 PM IST.webm](https://github.com/user-attachments/assets/fc44b41b-371a-4eed-94b2-c48b519d50ac)
[Screencast from 14-11-24 02:31:16 PM IST.webm](https://github.com/user-attachments/assets/a6a1ef9e-50d7-4cf8-936f-d5e9cc887b4f)
Training Request  Doctype
Training Event Doctype
No. 
- …

    TASK-2024-01055:Change status in Training Request and add Custom button to create Event

---

beams/beams/custom_scripts/training_event/training_event.js

-  Updated dialog in Training event.
- Changed Custom Button name 'Get Employees From' to 'Get Employees'.
- Implemented dialog with read-only fields to display selectable training requests.
- Removed Name Field in Dialog.
- Implemented check to prevent duplicate entries in the 'employees' child table when processing selected training requests.
[Screencast from 14-11-24 05:32:10 PM IST.webm](https://github.com/user-attachments/assets/1a808eb0-82ce-4201-8314-70e8d8b86e64)
No.

fix : Prevent duplicate entries in 'employees' child table for training requests

---

beams/beams/custom_scripts/employee_onboarding/employee_onboarding.js
beams/beams/custom_scripts/employee_onboarding/employee_onboarding.py
beams/hooks.py
beams/setup.py

Hide Employee Button in Employee onboarding doctype.
Hide Required for Employee Creation checkbox in Activities child table in Employee onboarding doctype.
Add a button labeled "Company Policy Acceptance Log" Under Create Group button in the Onboard Employee DocType.
Create it and show it in draft
Field visibility modifications in core DocType
Child table field adjustments:required for employee creation.
New button addition in the toolbar section:Comany Policy Acceptance Log.
Create Employee from Employee Onboarding is disabled.
When a Job Applicant is selected the Job Offer corresponding to the employee is fetched.Also the employee details of the 
employee(Department,Designation,Date of Joining,Employee Grade and Holiday List) are automatically populated.
Company Policy Acceptance Log …

feat:Added Custom Button to create CPAL from Employee Onboarding

---

beams/beams/doctype/beams_hr_settings/beams_hr_settings.json

- Add a new "Leave Settings" tab with the following fields:
- Penalty Leave Type: Link field to specify leave type for unplanned leaves
- Compensatory Leave Type: Link field for double-shift compensatory leaves
-Introduced a new tab for managing leave configurations:  
- Penalty Leave Type: For unplanned leaves  
- Compensatory Leave Type: For double-shift compensatory leaves  
- Enhanced layout using Tab Break and Column Break fields.  
- Provided descriptions for better clarity of the  fields.
Beams Hr Settings Doctype
No. If Yes, provide the appropriate explanation.

    TASK-2024-01087:Add Leave Settings tab in Beams Hr Settings

---

beams/beams/custom_scripts/training_event/training_event.js

- Remove unnecessary custom buttons on unsaved forms 
- 'Training Result' and 'Training Feedback' buttons are removed when the Training Event document is not submitted 
[Screencast from 16-11-24 10:00:16 AM IST.webm](https://github.com/user-attachments/assets/02c6e20c-06c4-4985-b704-7146114ec818)
No.

fix : Remove unnecessary custom buttons on unsaved forms

---

beams/beams/doctype/job_proposal/job_proposal.py
beams/setup.py

##Issue description
1.Need to Arrange the fields in the job offer doctype
2.implement to map the fields in  job offer from job proposal doctype 
1.Arranged the fields in the job offer doctype
-Placed Job Proposal and CTC field after field Job Applicant email Address.via setup.py
2.implemented to map the fields in  job offer from job proposal doctype 
-Fetched the content of Job Offer Terms and Terms and Condition from a linked job offer terms and Terms and Condition template
-Applied jinja template in terms and condition via job proposal.py
[Screencast from 16-11-24 10:23:36 AM IST.webm](https://github.com/user-attachments/assets/a7381912-974c-42d8-a996-c188fffc5cf8)
job proposal
job offer
No

TASK-2024-01080: maped the fields in job offer doctype

---

beams/beams/doctype/compensatory_leave_log/compensatory_leave_log.js
beams/beams/doctype/compensatory_leave_log/compensatory_leave_log.json
beams/beams/doctype/compensatory_leave_log/compensatory_leave_log.py
beams/beams/doctype/compensatory_leave_log/test_compensatory_leave_log.py

Add essential fields to the Compensatory Leave Log doctype to track employee compensatory leave details including employee information, date ranges, leave type, and leave allocation. Also implement naming series for the doctype.
Create doctype Compensatory Leave Log:
Add following fields :
Employee(Link, Employee, Mandatory), Start Date(Date), End Date(Date), Leave Type(Link, option-Leave Type),Leave Allocation(Link, option-Leave Allocation)
Set naming series for Compensatory Leave Log doctype.
Added the following fields to Compensatory Leave Log doctype:
-           Employee (Link)Link to Employee doctype,Mandatory field.
-           Employee Name(fetch from Employee)
-            Leave Type (Link),Link to Leave Type doctype
-           Leave Allocation (Link),Link to Leave Allocation …

feat:Created doctype Compensatory Leave Log

---

beams/beams/custom_scripts/employee/employee.js
beams/beams/custom_scripts/job_requisition/job_requisition.py

1.Need to hide event  button on Employee doctype before save
2. Need to change the alert message while creating the job opening from the job requisition doctype
1.implemented to hide the event button while before saving the employee doctype for hod user
-when hod user creating the event only show after saving via employee.py
2.changed the alert message while creating the job opening from the job requisition via job requisition.py
[Uploading Screencast from 18-11-24 12:25:35 PM IST.webm…]()
[Screencast from 18-11-24 12:44:46 PM IST.webm](https://github.com/user-attachments/assets/3c300e6c-a08d-4b79-9a4f-d6dcc8b5831e)
5e8b)
Employee
No

     TASK-2024-01031: hide event button on Employee doctype before save

---

beams/www/job_application_form/index.py

Ignore permissions on Job Applicant creation
No
- Chrome

fix: Ignore permissions on Job Applicant creation

---

beams/beams/custom_scripts/training_event/training_event.py
beams/hooks.py

1. implement to update the status of training request on cancellation of training event doctype
1.  Implemented to update the status of training request on cancel of training event doctype
- on cancel of  training event corresponding training request status become open only  for hr manager user via hooks.py 
and via training event.py
[Screencast from 19-11-24 03:19:12 PM IST.webm](https://github.com/user-attachments/assets/4b421da8-56f9-4e54-98cf-913d83ad4f24)
Training Event doctype
Training Request doctype
No.

TASK-2024-01055:Updated the Status of Training Request on cancel of Training event.

---

beams/beams/doctype/beams_hr_settings/beams_hr_settings.json
beams/beams/doctype/compensatory_leave_log/compensatory_leave_log.json

Reorganize the notification fields in the Beams HR Settings DocType to improve clarity, usability, and structure.
Employee field should be mandatory in Compensatory Leave Log doctype.
- Removed section break Notification to IT Department to Login Credentials
- Removed section break Notification to Admin Department to Create ID Card
- Updated descriptions and labels for better clarity:
a) notification_to_admin: Renamed to "Admin Notification Message" .
b)notification_to_it: Renamed to "IT Notification Message" and enhanced description.
- Made Employee field mandatory in Compensatory Leave Log doctype.
- Beams HR Settings DocType: Notification fields and layout.
No.

TASK-2024-00984: Reorganize notification fields in Beams HR Settings

---

beams/setup.py

-Need to change the Label on the field in job opening doctype
-Changed the Label name in a field  Minimum Educational Qualification  to Preferred Educational Qualification via setup.py
job opening
No. 

    TASK-2024-01132:  Changed the label on a field in the Job Opening doctype.

---

beams/beams/custom_scripts/employee_checkin/employee_checkin.py
beams/beams/custom_scripts/leave_allocation/leave_allocation.py

- Log should only create when the employee have ot shift
- On creation of leave allocation it checks whether it is created from employee checkout if yes log is created 
[Screencast from 25-11-24 11:47:48 AM IST.webm](https://github.com/user-attachments/assets/128bb602-af94-436a-9bca-d422740d51b1)

fix : Log should create only if the employee has shift assignment

---

beams/beams/custom_scripts/leave_application/leave_application.js
beams/beams/custom_scripts/leave_application/leave_application.py

1. Implement logic to  show or hide the 'medical_certificate' field based on leave type and duration 
2. implement  validation for medical certificate requirements for sick leave .
1.Implement logic to  show or hide the 'medical_certificate' field based on leave type and duration.
-implemented the logic that show or hide the 'medical_certificate' field based on leave type is is_sick_leave (checkbox) checked 
and the from_date and to_date duration check exceeds more than medical_leave_required field in leave type in leave application via leave application.js 
2.implemented  validation for medical certificate requirements for sick leave exceeding 2 days
-implemented the validation that if  is_sick_leave (checkbox) leave type and   exceeds more than medical_leave_required field in   leave …

 TASK-2024-01142:  Fixed the validation in leave application doctype

---

beams/beams/custom_scripts/employee/employee.py
beams/beams/doctype/beams_hr_settings/beams_hr_settings.json
beams/hooks.py
beams/setup.py

Add following fields:
Employee DocType:
Added a new field Leave Policy (Link, options: Leave Policy).
Beams HR Settings DocType:
Add a new field Default Leave Policy (Link, options: Leave Policy).
Add a new field Leave Period (Link, options: Leave Period).
Leave Policy Assignment:
A Leave Policy Assignment should be automatically created when an Employee is created.
The assignment will be based on the Default Leave Policy and Leave Period configured in the Beams HR Settings DocType.
The Leave Policy Assignment will be submitted automatically after creation.
This feature enhances the Employee and Beams HR Settings DocTypes by adding fields for leave policies and leave periods. It automatically assigns the correct leave policy and leave period to each newly created Employee based on the …

TASK-2024-01149:Leave Policy Assignment created and Submitted on creation of Employee.

---

beams/beams/custom_scripts/job_applicant/job_applicant.js

Hide "Interview" button for "Interview Completed" status  
Added "Interview Completed" to the conditions for removing the "Interview" button in Job Applicant.  
[Screencast from 26-11-24 03:03:58 PM IST.webm](https://github.com/user-attachments/assets/92228b05-dac2-4c69-930f-9aca9de79266)
Job Applicant Doctype
No. 

    TASK-2024-01151:Hide Interview button for 'Interview Completed' status

---

beams/beams/custom_scripts/leave_application/leave_application.js
beams/beams/custom_scripts/leave_application/leave_application.py

Validate Leave Application based on the threshold defined in leave type doctype for all leave type.Currently it works for casual leaves only.
Add Validation in Leave Application
Implement a validation in the Leave Application DocType to ensure the From Date is at least the specified number of days from the current date, as defined in the selected Leave Type.
Implemented a validation function in the backend to ensure that the from_date in the Leave Application is at least the configured minimum number of days from the current date.
[Screencast from 2024-11-26 12-42-07.webm](https://github.com/user-attachments/assets/a22d95a0-68fb-46fd-b9c1-da895344133a)
No. 
- Chrome

fix:Leave type validation for Casual Leave made general for all leave types.

---

beams/beams/custom_scripts/leave_application/leave_application.py
beams/setup.py

Add date and Signature field after family details child table(ESI tab) of  employee doctype .
Add fields date and Signature in employee.
Fix issue that if minimum advance days is not provided validation should be skipped.
A section break has been added after the family_details field .A Date field is added with the label "Date" after the section break.A column break field is placed after the date field.A signature field with the label "Signature" is added after the column break for user signature input.
In leave Application If min_advance_days in leave type is 0 or not set, no validation is skipped for the leave date.
Leave Application
Employee
- Chrome

feat:Added fields in employee doctype

---

beams/beams/doctype/employee_documents/employee_documents.json
beams/beams/doctype/employee_documents/employee_documents.py
beams/beams/doctype/maternity_leave_request/maternity_leave_request.json
beams/setup.py

- Create a new tab Document in Employee
- Create a child table Employee Documents and add to tab Document
- Add fields in Employee external work history in tab profile
- Created a new tab Document in doctype Employee
- Created a child table Employee Documents to attach the documents
- Add fields in Employee external work history

TASK-2024-01166:Created new tab and child table

---

beams/beams/doctype/provident_fund/provident_fund.json

- Need  To update the field alignments   in the Provident Fund doctype
-updated the field alignments in  the Provident Fund doctype
- Added these fields Date of Exit for previous member Id and  PPO Number(If pension payment order(PPO) issued for previous employment) in another column break 
- Added field Specially Abled  in another column break
provident doctype
no

TASK-2024-01152 : updated the Provident Fund doctype

---

beams/beams/doctype/compensatory_leave_log/compensatory_leave_log.py
beams/hooks.py
beams/setup.py

- This feature execute a scheduler job on daily to expire the leave allocation Get the Compensatory Leave Log ends on Yesterday If not a Leave Application Exists (for the Leave Type and the Yesterday included in the leave dates), then reduce a leave from the leave allocation linked to the Compensatory Leave Log.
- Add No of Children field in Employee doctype.
Created Scheduler Function:
-  Fetch all Compensatory Leave Logs with an end_date of yesterday.
-  Verify if a Leave Application exists for the corresponding employee, leave type, and if yesterday’s date is covered in the application period.
-  If no such leave application exists, reduce one day from the corresponding Leave Allocation.
-  Ensure leave balances do not fall below zero.
- Added No of Children field in Employee doctype. …

feat: Expire Compensatory Leave Allocation with in a 30 days

---

beams/beams/custom_scripts/leave_application/leave_application.py
beams/hooks.py

Add leave application validation for penalty leave balance
- Retrieve penalty leave type from Beams HR Settings.
- Compute the total allocated and used penalty leave for the employee.
- Posting date of the leave application must be after the dates of absence.
- Enforce 'Leave Without Pay' if no penalty leave balance is remaining.
- Prevent applying for non-penalty leave types when penalty leave balance is available.
- Provide clear error messages to enforce leave application rules
Implemented validation for leave application based on penalty leave balance
- Fetched penalty leave type from Beams HR Settings.
- Employees marked absent during the leave period must adhere to penalty leave type policies.
- Calculated total allocated and used penalty leave for the employee.
- Restricted …

feat : Employees marked absent during the leave period must adhere to penalty leave type policies

---

beams/beams/doctype/maternity_leave_request/maternity_leave_request.js
beams/beams/doctype/maternity_leave_request/maternity_leave_request.json
beams/beams/doctype/maternity_leave_request/maternity_leave_request.py

- Remove todo in maternity leave request for hod after  creating todo for hr
- Set the validation that the birth count should greater than 0 
- Set a validation that if the maternity leave type in beams hr settings is not configured alert
- Removed the todo after changing workflow status to pending hr approval from hod
- A validation is given that birth count cannot be 0 and material leave type field cant be empty
[Screencast from 29-11-24 12:13:01 PM IST.webm](https://github.com/user-attachments/assets/77233939-9d34-4997-824e-89d6c7271bfc)

fix : Removing todo and Adding some validation

---

beams/beams/custom_scripts/leave_application/leave_application.js
beams/beams/custom_scripts/leave_application/leave_application.py
beams/beams/doctype/provident_fund/provident_fund.js
beams/beams/doctype/provident_fund/provident_fund.json
beams/beams/doctype/provident_fund/provident_fund.py
beams/hooks.py
beams/setup.py

Add Employee details in Provident Fund doctype.
Validation fot Sick Leave Applications.
Added following fields to Provident Fund doctype.
-            employee_number
-             employee_name
-             department"
-             designation
-             cell_number
-             personal_email
-             company_email
-             user_id
-             name_of_father
-             gender
-            date_of_birth
-            permanent_address
-             current_address
- 
Fetch and auto-populate employee data in the Provident Fund doctype when employee is selected.
Medical Certificate attach field made mandatory if leave days exceeds than 2 days for sick leave type. 
[Screencast from 2024-12-02 09-53-38.webm](https://github.com/user-attachments/assets/652ec0a4-7d34-4cf3-84a …

feat:Added Employee details in Provident fund doctype

---

beams/beams/doctype/beams_hr_settings/beams_hr_settings.json

Added a new tab in Beams HR Settings under Shift Settings. The tab includes fields to configure shift publication and reminder settings:
- Shift Publisher Role: Link to role .
- Shift Publication Day: Select  field (Monday to Sunday).
- Send Shift Creation Reminder: Integer field,When Scheduling Reminder Need to be Sent (In days) description.
- Shift Creation Reminder Template: Link to an email template.
Add New Tab break in Beams HR Settings : Shift Settings
Shift Publisher Role : Link to Role 
Shift Publication Day : Select, Monday, Tuesday,.... Sunday 
Send Shift Creation Reminder : Int, Description- When Scheduling Reminder Need to be Sent (In days) 
Shift Creation Reminder Template: Link to Email Template
Added the fields as mentioned above.
Beams HR Settings.
No. 
- Chrome
- Mozilla …

feat:Added new tab shift settings in HR settings

---

beams/beams/doctype/provident_fund/provident_fund.json

Rearranged fields in Provident Fund.
Remove the Mandatory Requirement for Fields in the Previous Employment Details Tab.
Rearranged fields in Provident Fund.
Mandatory of fields in Details section under  Previous Employment Details Tab was removed.
No
- Chrome

fix:Made changes in Provident Fund

---

beams/beams/doctype/bank_details/bank_details.json
beams/beams/doctype/esi/esi.json
beams/beams/doctype/family_details/family_details.json

-Add column breaks and fetch functionality for employee-related doctype
- Added 'Column Break' fields to `Bank Details`, `ESI`, and `Family Details` doctypes for improved form structure.
- Implemented `fetch_from` for fields like `Name of Father`, `Name of Spouse`, and `Marital Status` in the `ESI` doctype to pull data from linked Employee records.
- Updated field order in `Bank Details` and `Family Details` doctypes for better data organization.
[Screencast from 02-12-24 03:07:02 PM IST.webm](https://github.com/user-attachments/assets/05feeca2-50bd-4f4c-ba9e-1939007bfa41)
No.

TASK-2024-01145_fix:Enhance form layout and data fetching in employee-related doctype

---

beams/beams/doctype/document_type/document_type.js
beams/beams/doctype/document_type/document_type.json
beams/beams/doctype/document_type/document_type.py
beams/beams/doctype/document_type/test_document_type.py
beams/beams/doctype/employee_documents/employee_documents.json

-Create Doctype Document Type
-## Solution description
Created "Document Type" Doctype with a "Document Type" field
Added "Document" field (Link to "Document Type") in Employee Documents child table.
Yes 

TASK-2024-01211:Create Doctype Document Type

---

beams/beams/doctype/beams_hr_settings/beams_hr_settings.json
beams/beams/doctype/beams_hr_settings/beams_hr_settings.py
beams/hooks.py
beams/setup.py

This feature introduces a system to send notifications (both email and in-app) to users responsible for publishing shifts. The notifications are triggered based on a configurable Shift Publication Day and Reminder Lead Time. Notifications are sent only when the Enable Shift Notification checkbox is selected in Beams HR Settings.
Create role 'Shift Publisher'.
Send Notification to Users with 'Shift Publisher' role on Shift Publication Day configured in Beams HR Settings and notification should be based on Email template configured in Shift Creation Reminder Template in Beams HR Settings
Configuration in Beams HR Settings:
Added the Enable Shift Notification checkbox t
fields:
Shift Publication Day: The day on which shifts are scheduled to be published.
Shift Publisher Role: Role of users …

feat:Created system and email notification to publish shifts.

---

beams/beams/doctype/shift_swap_request/shift_swap_request.py

Enables shift swapping between two employees upon approval of a "Shift Swap Request." This feature allows the cancellation of current shifts and creation of swapped assignments.
- Implemented the swap_shifts method to:
1.Fetch and cancel the existing Shift Assignment records for both employees.
2.Create and submit new Shift Assignment records with swapped details.
- Executed shift swap logic on approval of the Shift Swap Request
- Shift Assignment DocType: Existing records  are updated or canceled based on swap logic.
- Shift Swap Request workflow:  shift swap on approval state.

feat: Implement shift swap to update shift assignments on approval of shift swap request.

---

beams/beams/doctype/provident_fund/provident_fund.json

Fetch Email from the Preferred Email field of Employee.
Email is  now fetched from the Preferred Email field rather than Preferred Contact Email.
No.
- Chrome
mu

fix:Email field fetched from Prefered Email field of Employee doctype.

---

beams/beams/custom_scripts/job_applicant/job_applicant.js
beams/beams/doctype/esi/esi.json

-Modify button visibility based on specific statuses
- Removed "Local Enquiry Report" button for the following statuses: 'Document Uploaded', 'Open', 'Pending Document Upload', 'Shortlisted', 'Local Enquiry Approved', 'Selected', 'Local Enquiry Started', 'Local Enquiry Rejected', 'Local Enquiry Completed'.
- Removed "Interview" button for all statuses except 'Document Uploaded'.
- Updated permissions and fields for the "ESI" doctype, including removal of the "submit" permission and adjustments to "write" permissions.
##Post the output screenshots, if a UI is affected or added due to this feature.
[Screencast from 04-12-24 04:52:51 PM IST.webm](https://github.com/user-attachments/assets/abfa3d3c-1567-42e1-88fc-ae0e70b93432)
Yes . 

fix:Removed 'Local Enquiry Report' and 'Interview' buttons based on status

---

beams/beams/doctype/compensatory_leave_log/compensatory_leave_log.json
beams/beams/doctype/kyc_details/kyc_details.json
beams/beams/doctype/kyc_document/kyc_document.js
beams/beams/doctype/kyc_document/kyc_document.json
beams/beams/doctype/kyc_document/kyc_document.py
beams/beams/doctype/kyc_document/test_kyc_document.py

- Create doctype KYC Document and make KYC Document Type field  (of Provident Fund doctype) link to this doctype.
- Restrict Compensatory Leave Log creation from front end.
Create doctype KYC Document and add following field into it:
Document Type(Data)
add this doctype as Link field inside child table KYC Documents child table in Provident Fund Doctype
KYC Document(Link,option-KYC Document)
KYC Document Doctype has following  fields:
Document Type (Type: Data)
Document Name.
Changes in Provident Fund Doctype:
Child table KYC Details field  KYC Document Type field is made Link field  and linked to KYC Document doctype.
Name as on KYC Document  field value fetched from Document Name field of KYC Document.
User cannot create button checked to restrict document creation by user.
No. 
- …

TASK-2024-01221:Create doctype KYC Document

---

beams/setup.py

Set 'Stringer Type' field to follow 'Bureau'
Updated 'Stringer Type' field to appear after 'Bureau' in Employee doctype
No

fix:Change 'Stringer Type' field position to after 'Bureau'

---

beams/setup.py

Adjust field dependencies and positioning for leave Type
- Removed `is_sick_leave` field and adjusted dependencies accordingly.
- Updated the `is_proof_document` field to be positioned after `is_optional_leave` instead of `is_sick_leave`.
- Modified `medical_leave_required` field dependency to rely solely on `is_proof_document`.
No. 

feat:Update sick leave and proof document dependency logic

---

beams/beams/doctype/adhoc_budget/adhoc_budget.json
beams/www/job_application_upload/upload_doc.html
beams/www/job_application_upload/upload_doc.js
beams/www/job_application_upload/upload_doc.py

- Removed duplicate remarks field in the Adhoc Budget doctype to ensure clean data structure.
- Improved functionality in Job Application Upload by resolving issues and enhancing user experience.
- Implemented a conditional logic in the current_mobile_no, applicant_name, designation, email_id_1 fields to make it read only if value exists.
- Used ' ' fallback for None values.
- Added check boxes for selected fields for better user interaction.
- Addressed and fixed the issue with fetching and displaying dates in the doctype.
`Job Applicant From`
`Adhoc Budget`
No
- Chrome

fix : Updates Adhoc Budget Doctype and Job Application Upload Functionality.

---

beams/beams/doctype/performance_appraisal/performance_appraisal.js
beams/beams/doctype/performance_appraisal/performance_appraisal.json
beams/beams/doctype/performance_appraisal/performance_appraisal.py
beams/beams/doctype/performance_appraisal/test_performance_appraisal.py
beams/beams/doctype/shift_swap_request/shift_swap_request.js
beams/beams/doctype/shift_swap_request/shift_swap_request.py

Create doctype Performance Appraisal.
Create doctype Performance Appraisal and add following fields to it:
- Employee(Link,option-Employee)
- Name of Employee(Data,read-only,fetch from employee)
- Designation(Link,option-Designation,read-only)
- Department(Link,option-Department,read-only)
- Location(Link,option-Location)
- Date of Joining(Date)
- Mode of Employment(Link,option-Employment Type)
- Date of Last Promotion(Date)
- Appraisal Cycle(Link,option-Appraisal Cycle)
Created doctype Performance Appraisal with following fields.
No
- Chrome

TASK-2024-01234:Created doctype Performance Appraisal.

---

beams/beams/doctype/shift_swap_request/shift_swap_request.js
beams/beams/doctype/shift_swap_request/shift_swap_request.py

The Shift Swap Request Doctype requires validation for shift assignments and department matching between employees.
Populate employee field automatically when an employee logs in.
This feature enhances error messages for shift assignment and department validation in the Shift Swap Request form by converting employee references into clickable links. When an error occurs, users are now able to click on the employee name .
Added client script to populate employee when employeeis logged in.
- The has_valid_shift_assignment and employee_department validation checks have been enhanced to show error messages containing clickable links to the relevant Employee documents.
- The employee name is fetched from the Employee Doctype using frappe.db.get_value.
- If an error occurs, the employee name is …

fix:Added Employee link in shift assignment and department validation

---

beams/beams/custom_scripts/interview/interview.py
beams/hooks.py

Automate Status Updates Based On Interview Outcomes
Set to "Interview Completed" when all interviews were cleared.
Set to "Interview Ongoing" when any interview was rejected or pending.
[Screencast from 11-12-24 04:03:50 PM IST.webm](https://github.com/user-attachments/assets/6e1eb42c-94f2-4ba2-861f-763d4f0f38b8)
Interview Doctype 
Yes.

fix: Updated Job Applicant status based on interview outcomes

---

beams/beams/custom_scripts/job_applicant/job_applicant.js

- Enhance button visibility in Job Applicant form based on status
- Added additional statuses ('Accepted', 'Training Completed', 'Job Proposal Accepted', 'Job Proposal Created') to control button visibility.
- Removed 'Local Enquiry Report' and 'Interview' buttons for specific statuses, such as 'Document Uploaded'.
- Disabled 'View', 'Send Magic Link', 'Job Offer' buttons, and specific inner buttons for statuses like 'Accepted' and 'Training Completed',Interview Scheduled ,Local Enquiry Approved ,Selected,Job Proposal Created,Job Proposal Accepted
[Screencast from 11-12-24 03:05:44 PM IST.webm](https://github.com/user-attachments/assets/9ec95c62-fa6b-416f-b610-e6e123f94e57)
Job Applicant Doctype
Yes.

fix:updated Job Applicant form button visibility based on status

---

beams/beams/doctype/beams_hr_settings/beams_hr_settings.json
beams/beams/doctype/beams_hr_settings/beams_hr_settings.py
beams/hooks.py

This feature sends notifications to HR Managers to remind them to create appraisals for employees. It checks the configured appraisal creation period and enables reminders based on the Beams HR Settings.
- Add the following field into Beams HR Settings:
- Enable Appraisal Reminder(Checkbox)
- Appraisal Creation Period(int)-Description-Days to send Appraisal Reminder
- Send a reminder to the HR Manager to create appraisals for employees based on their joining date and the Appraisal Creation Period configured in Beams HR Settings.
- Reminder should send only if Enable Appraisal Reminder(Checkbox) is checked in Beams HR Settings.
- 
- Fetching HR settings and verifying the "Enable Appraisal Reminder" flag.
- Calculating the appraisal due date based on employee joining date and the configured …

TASK-2024-01233:Reminder to HR Manager to ensure employee appraisals are created  before the due date.

---

beams/beams/custom_scripts/leave_application/leave_application.py
beams/hooks.py
beams/setup.py

`Leave Application Doctype`
No
- Chrome

feat : Validate Leave Application during Notice Period

---

beams/beams/custom_scripts/employee/employee.py
beams/hooks.py

-  Set the relieving_date in the Employee doctype based on the resignation_letter_date and notice_number_of_days.
- Added logic to compute the relieving_date by adding the notice_number_of_days to the resignation_letter_date.
- Ensures the relieving_date is updated dynamically when both fields are provided.
`Employee Doctype`
No
- Chrome

feat : Set employee relieving date based on resignation letter date and notice period

---

beams/beams/custom_scripts/leave_application/leave_application.py
beams/beams/doctype/beams_hr_settings/beams_hr_settings.json
beams/setup.py

-Remove 'Penalty Leave Type' from Beams HR Settings
-Add 'Penalty Leave Type' to Employment Type Doctype
-Validate leave application for absent days with allocation check
-Make Posting Date field read-only in Leave Application"
-Removed 'Penalty Leave Type' from Beams HR Settings.
-Added 'Penalty Leave Type' field in Employment Type Doctype.
-Added validation in Leave Application for absent days and leave allocation.
-Set Posting Date field to read-only.
[Screencast from 19-12-24 09:37:28 AM IST.webm](https://github.com/user-attachments/assets/3acfad41-dad9-42e2-b367-42eed3770751)
[Screencast from 19-12-24 10:16:16 AM IST.webm](https://github.com/user-attachments/assets/a301b5bf-140e-4ceb-8a30-ac0cb0dbbd88)
[Screencast from 19-12-24 10:17:46 AM …

    TASK-2024-01099:Add validation in Leave Application

---

beams/setup.py

Add field 'Training Status' to Employee
Added 'Training Status' field to Employee doctype
No

feat:Add 'Training Status' field to Employee doctype

---

beams/beams/custom_scripts/attendance/attendance.py
beams/beams/doctype/beams_hr_settings/beams_hr_settings.json

- Add Absence Reminder Configuration to Beams HR Settings
- Introduced 'Absence Reminder Duration' field in Beams HR Settings to set the duration after which absence reminders are sent.
- Added 'Enable Absence Reminders' checkbox to enable or disable absence reminders.
- Updated 'send_absence_reminder' function to check the settings and send reminders only if enabled, based on the configured  reminder duration.
[Screencast from 24-12-24 05:01:59 PM IST.webm](https://github.com/user-attachments/assets/a9e9df36-bf59-4db6-967e-e01d908dc652)
[Screencast from 24-12-24 05:05:06 PM IST.webm](https://github.com/user-attachments/assets/425ed918-4fae-44f8-a24d-01b16cb4c59e)
-Leave Application Doctype 
-Beams HR Settings Doctype
-Yes . 

feat:Add Absence Reminder Configuration to Beams HR Settings

---

beams/beams/custom_scripts/job_requisition/job_requisition.js
beams/setup.py

Add child tables 'Department Rating Criteria' and 'Company Rating Criteria'(use the existing table 'Rating Criteria' table in Appraisal Template).
In Appraisal template doctype,add two child tables named as 'Department Rating Criteria' and 'Company Rating Criteria'(use the existing table 'Rating Criteria' table in Appraisal Template)
Appraisal Template doctype
No
- Chrome

TASK-2024-01315:Added child tables to Appraisal Template doctype

---

beams/setup.py

In Employee Feedback Rating child table
- Marks(float) and make  Rating field read-only
In Employee Performance feedback  doctype 
- Hide Total Score field
- Add Department Criteria and Company Criteria tables
- Add Total Score and Average Score fields under corresponding tables.
- In Employee Feedback Rating doctype, added field  Marks(float).
- Added  child tables  Department Criteria and Company Criteria(options  Employee Feedback Rating)
- Renamed feedback ratings table as Employee Criteria.
- Added Average Score and Total Score fields under each child table. 
Employee Performance Feedback doctype.
No. 
- Chrome

TASK-2024-01317,TASK-2024-01319 : Customised Employee Performance Feedback doctype

---

beams/beams/custom_scripts/appraisal/appraisal.js
beams/beams/custom_scripts/appraisal/appraisal.py
beams/hooks.py
beams/setup.py

1.  This feature generates an appraisal summary in the form of an HTML table, integrating employee feedback data for detailed performance insights.
2.  Introduced new custom fields for the Appraisal doctype to enhance summary display and functionality.
3.  Added property setters to hide specific fields and adjust labels for improved usability.
**1. Custom Fields:**
- Added a `Tab Break (appraisal_summary_tab_break)` and an `HTML field (appraisal_summary)` in the Appraisal doctype for appraisal summaries.
- Included fields like `label_for_department_kra` and `label_for_company_kra` to store combined values for department and company KRA. These fields allow aggregation of values from `department_rating_criteria` and `company_rating_criteria`respectively.
**2. Property Setters:**
- Hid …

feat : Add appraisal summary with employee feedback(TASK-2024-01320)

---

beams/beams/custom_scripts/appraisal/appraisal.js
beams/beams/custom_scripts/appraisal/appraisal.py

--Add One-to-One Meeting creation from Appraisal  
--Added a custom button "One to One Meeting" to the Appraisal form for submitted appraisals with feedback.
--Introduced `map_appraisal_to_event` to map appraisal details to a new Event.
--adds the employee and logged-in user as participants in the Event.
[Screencast from 02-01-25 10:00:44 AM IST.webm](https://github.com/user-attachments/assets/f7ce57db-249c-4bf6-aa1c-261fa33cb359)
--Appraisal Doctype
--Event Doctype
-- No.

TASK-2024-01321:Enable One-to-One Meeting creation from Appraisal

---

beams/beams/custom_scripts/appraisal/appraisal.js
beams/hooks.py
beams/setup.py

- Add a field mark in child table employee feedback rating and make rating field read only
- Add a button New feedback in appraisal, which get in to a dialog with feedback and employee , department and company criteria
- Bring a Validation that mark should be between 0-5 and button only visible to employee reports to
- Added a extra field mark in child table employee feedback rating that exist in employee performance feedback and made rating            as read only 
- Added a custom button in appraisal New feedback 
- On clicking the button a dialog is created with feedback , employee criteria , department criteria and company criteria
- An alert message is popped if mark is not between 0-5
-  The button is only visible for the employee reports to 
- [Screencast from 02-01-25 10:35:40 AM …

TASK-2024-01316 : Dialog button added in Appraisal

---

beams/beams/custom_scripts/appraisal/appraisal.js
beams/beams/custom_scripts/appraisal/appraisal.py
beams/beams/doctype/category/category.js
beams/beams/doctype/category/category.json
beams/beams/doctype/category/category.py
beams/beams/doctype/category/test_category.py
beams/beams/doctype/category_details/category_details.json
beams/beams/doctype/category_details/category_details.py
beams/setup.py

- Added functionality to manage categories in the Appraisal doctype.
- Implemented a dynamic "Add Category" button and dialog to add categories with remarks.
- Categories fetched from the Category master doctype are displayed in the Appraisal form.
- The `Appraisal` doctype now includes a child table `Category Details` to store linked categories and remarks.
- Categories from the `Category Master` doctype are displayed in alphabetical order within the Appraisal form's HTML table.
- Used `frappe.call` to fetch categories and their descriptions, rendering them in an HTML table.
- Implemented a dialog for adding categories, where users can link a category and add remarks.
- Integrated the logic to store the selected categories with remarks in the Appraisal's child table `category_details`. …

 feat : Add Category management functionality to Appraisal

---

beams/beams/custom_scripts/appraisal/appraisal.py
beams/setup.py

--Enhance Event and Appraisal doctypes with custom fields and mapping
--Introduced new fields in the Event doctype related to "One to One Meeting":
1.Contribution of Employee
2.     Areas of Improvement
3.   Training Needs
4.   Promotion Eligibility and Remarks
5.   Appraisal Reference field
--Added "Event Reference" field to Appraisal doctype.
--Expanded Event Category options to include "One to One Meeting.
--Implemented mapping to generate an Event from an Appraisal with cross-references.
--Adjusted property settings for Job Requisition 
[Screencast from 06-01-25 04:18:25 PM IST.webm](https://github.com/user-attachments/assets/4f609873-8b5a-48ad-943d-ea82a6c5d153)
[Screencast from 06-01-25 04:20:37 PM IST.webm](https://github.com/user-attachments/assets/2ea2b3d1-9339-4eba-9b84-119b3bcec …

TASK-2025-00001:Customize Event Doctype

---

beams/beams/custom_scripts/interview/interview.js
beams/beams/custom_scripts/job_applicant/job_applicant.js
beams/beams/custom_scripts/job_applicant/job_applicant.py
beams/hooks.py
beams/setup.py

In Job Applicant Doctype, 
Hide 'Resume Link' field and Add validation for 'Resume Attachment' field that only PDF format should be allowed
In Interview doctype,
Add the "view" group button for 'Job Applicant' and 'Resume'
In Job Applicant Doctype Hide the 'Resume Link' field and added validation for 'Resume Attachment' field that only PDF format should be allowed.
In Interview Doctype Created "View" group button that contains Job Applicant and Resume after the interview saved .. 
When 'job applicant' button is clicked,it should be redirected to Job Applicant's document and when 'Resume' button is clicked,it should be redirected to Job Applicant's document.
[Screencast from 09-01-25 10:23:36 AM IST.webm](https://github.com/user-attachments/assets/e97f6400-4efb-4ca6-ae1c-9562d34e5bc6) …

TASK-2025-00019:Validate the  Resume Attachment as PDF in Job Applicant Doctype

---

beams/beams/custom_scripts/appraisal/appraisal.js

- Change the arrangement of dialog as feedback last and all child table first
- Add goals field in child table employee criteria
- Make the dialog size extra large
- Except marks and feedback make all the fields of dialog as read only
- Remove add row option in child table of dialog
- Fetch data to department and company criteria from appraisal template
- Fetch data to employee criteria from appraisal_kra 
- Rearranged the dialog
- Added field to employee criteria of dialog - goals
- Set dialog size as extra large
- Setting All fields as read-only in child table except marks 
- Removed the add row option from the child table
- Fetched data to the child table of dialog from appraisal template and appraisal kra child table 
[Screencast from 09-01-25 09:31:06 AM …

feat : Fetched all data to the dialog from appraisal template

---

beams/beams/custom_scripts/appraisal/appraisal.js
beams/beams/doctype/beams_hr_settings/beams_hr_settings.json
beams/setup.py

--Updated Appraisal custom button logic and HR settings configuration
--Removed unnecessary button logic and adjusted conditions for the "One to One Meeting"
-- Updated property settings to reflect changes in template and feedback fields
--Added dependency logic for "absence_reminder_duration" to trigger only when "enable_absence_reminders" is enabled.  
[Screencast from 09-01-25 02:37:38 PM IST.webm](https://github.com/user-attachments/assets/e9c2515a-2eb2-4aff-ba5c-4ba97f01f382)
-- No. 

fix:Refactor Appraisal button logic and enhance HR settings

---

beams/beams/custom_scripts/appraisal/appraisal.js

- Bring a Validation that on submitting mark should not be empty
- Whenever a dialog without entering a mark is submitted a alert message is given
[Screencast from 10-01-25 09:09:22 AM IST.webm](https://github.com/user-attachments/assets/8297e081-d889-4a8a-b23a-40a9b345e78c)

fix : Bringing a validation that marks should not be empty

---

beams/beams/custom_scripts/appraisal/appraisal.js
beams/beams/custom_scripts/appraisal/appraisal.py
beams/hooks.py
beams/setup.py

- Fetches criteria data, calculates totals and averages in Self Appraisal.
- Added a new feature to automatically fetch relevant criteria data for appraisals, perform necessary calculations on totals and averages in Self Appraisal.
[Screencast from 01-10-2025 11:56:44 AM.webm](https://github.com/user-attachments/assets/e9a42f63-2bc6-449b-8ef3-aa4a97af3e31)
- `Appraisal Doctype`
- No
- Chrome

feat : Add functionality to fetch criteria data, calculate totals/averages in self appraisal.

---

beams/beams/custom_scripts/appraisal/appraisal.js
beams/beams/custom_scripts/appraisal/appraisal.py

The assignment to Assessment Officers was triggered when Create One to One  button was clicked.But now it is triggered when Officer adds a Category.
Remove Dashboard for KRA  in Appraisal doctype.
Assessment officer notification is triggered when Officer adds Category of the employee.
Triggering function when One to one is created is removed and was triggered when Category is added.
No.
- Chrome

fix:Assignment to Asessment officers triggered when Category is added  by officer

---

beams/beams/doctype/adhoc_budget/adhoc_budget.json
beams/beams/doctype/adhoc_budget/adhoc_budget.py

Add field in  Adhoc Budget DocType: Generates Revenue (a checkbox) .
Expected Revenue: This field is visible and required only if Generates Revenue is checked.
Validation should be added  as Expected Revenue cannot be less  than zero.
The Adhoc Budget DocType is modified by adding   field: Generates Revenue (a checkbox) .
Expected Revenue: This field is visible  only if Generates Revenue is checked.
Validation added as Expected Revenue cannot be less than zero.
The script will monitor changes to the Generates Revenue checkbox and toggle the visibility of the Expected Revenue field accordingly.
If Generates Revenue is checked, Expected Revenue becomes visible.
No. 
- Chrome

TASK-2025-00039:Modified doctype Adhoc Budget

---

beams/beams/doctype/project_expense_type/project_expense_type.json
beams/beams/doctype/project_expense_type/project_expense_type.py
beams/setup.py

Add  fields to the Project Doctype to manage program-specific details, including:
Added Program Details section to Project doctype
- Included new fields:
- Program: A Link field to associate the project with a 'Program Request'.
-Generates Revenue: A Read-Only checkbox, fetched from the associated program, indicating if the program generates revenue.
-Program Type: A Read-Only Link field, fetched from the associated program, to define the program type.
-Budget Expense Types: A MultiSelect table, linked to 'Project Expense Type', for selecting applicable expense types.
Created a child table for 'Project Expense Type
Project Doctype
No.

    TASK-2025-00037:Customize Project doctype

---

beams/beams/doctype/program_request/program_request.js
beams/beams/doctype/program_request/program_request.py

- Create a custom button create project in program request doctype , on approval
- Map the button to project doctype
- Once a project is created hide the button
- When the workflow state turn to approved a custom button Create Project is added
- On clicking the button a project is created with data in program request 
- Once a project exist against the program request the button is hide
[Screencast from 15-01-25 11:53:24 AM IST.webm](https://github.com/user-attachments/assets/2d84cdd8-54e4-453a-bfb5-42c25856ea4a)

TASK-2025-00038 : Created a project from program request

---

beams/beams/custom_scripts/project/project.js
beams/beams/custom_scripts/project/project.py
beams/hooks.py

-  Added a feature to create an Adhoc Budget from a Project, including mapping relevant fields and transferring selected budget expense types.
- Implemented the `create_adhoc_budget` function to map fields from the Project doctype to the Adhoc Budget doctype.
- For each selected expense type in the Project, a corresponding entry is added to the `Budget Expense` child table in the Adhoc Budget.
- Introduced a custom button on the Project form to trigger the creation of the Adhoc Budget.
[Screencast from 01-15-2025 01:01:06 PM.webm](https://github.com/user-attachments/assets/b222cde2-47d1-42ac-8d16-3fbaf0d72f21)
- `Project Doctype`
- `Adhoc Budget Doctype`
- No
- Chrome

feat : Add functionality to create Adhoc Budget from Project

---

beams/api/api.py
beams/setup.py

- Need to add custom fields in Customer Doctype
- Set mandatory on Region based on is agency checkbox.
- Added is editable checkbox in Customer
No.

feat: Customize Customer doctype

---

beams/beams/custom_scripts/appraisal/appraisal.js
beams/beams/custom_scripts/appraisal/appraisal.py
beams/hooks.py
beams/setup.py

Added functionality to calculate and set the category for an Appraisal based on the final_average_score.
-   get_category_based_on_marks:
Fetches the top category where appraisal_threshold is less than or equal to the given final_average_score.
Returns the name of the category.
-   set_category_based_on_marks:
Hooks into the Appraisal lifecycle using the method parameter (e.g., before_save).
Updates the category_based_on_marks field with the calculated category.
Appraisal DocType: Category assignment logic.
Appraisal Category DocType: Thresholds used for category calculation.
- Chrome
- …

feat: set Category on Appraisal doctype based on Final Average Score

---

beams/setup.py

Add  fields for Provident Fund and ESI in Payroll Settings
- Added 'Provident Fund' section with fields:
- Employer PF Contribution (Percent)
- PF Expense Account (Link)
- Added 'Employees State Insurance' section with fields:
- ESI Employer Contribution (Percent)
- ESI Expense Account (Link)
Payroll Settings Doctype
No

    TASK-2025-00041:customize Payroll Settings Doctype

---

beams/beams/custom_scripts/customer/customer.py
beams/hooks.py
beams/setup.py

- Set is_edited field to 0 after the document insertion
- Marks the document as edited if approved and modified after its creation date
- The is_edited field was set to 0 after the document was inserted.
- The document was marked as edited if it was approved and modified after its creation date.
No.

feat: Update the value of is_edited in Customer doctype

---

beams/beams/doctype/program_request/program_request.js
beams/beams/doctype/program_request/program_request.json
beams/beams/doctype/program_request/program_request.py

This feature ensures that the start date of a program request cannot be later than the end date
set Posting Date to read-only
- Implemented a validate_start_date_and_end_dates method within the ProgramRequest class.
- This method checks if the start_date is greater than the end_date.
- Program Request Document:
- Start and End date fields are now logically validated.
- Ensures no erroneous data is saved, enhancing the data consistency for program requests.
yes
- Chrome
- Mozilla Firefox- yes
- Opera Mini
- Safari

fix:add validation for start date

---

beams/beams/doctype/program_request/program_request.js
beams/beams/doctype/program_request/program_request.py
beams/setup.py

- Project now created from Program Request on approval of workflow.Button trigger was removed.
- Progam field was renamed as Program Request.
Program Request and Project doctype.
No
- Chrome

fix:Project Created from Program Request automatically

---

beams/beams/custom_scripts/budget/budget.js
beams/beams/custom_scripts/department/department.js
beams/beams/custom_scripts/department/department.py
beams/beams/doctype/division/division.js
beams/beams/doctype/division/division.json
beams/beams/doctype/division/division.py
beams/setup.py

- Customize Division Doctype
- Apply filters in Cost center of Division
- Customize Budget Doctype
- Calculate Budget Amount based on Monthly amount Distribution
- Remove cost center from department and its filters.
- Added Custom fields in Division Doctype
- Applied cost center filters in Division
- Added custom fields in Budget and its child table budget accounts
- Calculated budget amount based on monthly amount distribution
[Screencast from 18-01-25 12:05:19 PM IST.webm](https://github.com/user-attachments/assets/f5b38f68-4c3b-44de-9af9-741124c39dc1)
No.

feat: Update Budget Doctype

---

beams/beams/doctype/technical_support_request/technical_support_request.js
beams/beams/doctype/technical_support_request/technical_support_request.json
beams/beams/doctype/technical_support_request/technical_support_request.py
beams/beams/doctype/technical_support_request/test_technical_support_request.py

Need to:Create a DocType Technical Support Request
Created DocType Technical Support Request, fields are 
- Project (Link/Project)
- Bureau (Link/Fetch from Project)
- Posting Date (Date)
- Required From (Datetime)
- Required To (Datetime)
- Department (Link/Department)
- Designation (Link/Designation)
- Remarks (Small Text)
- Employee (Link/Employee/Filter by Department & Designation) and  the doctype is changed to submittable doctype.
[Screencast from 18-01-25 02:01:35 PM IST.webm](https://github.com/user-attachments/assets/c73efcf0-fdbb-4658-8618-5685c8bffcd4)
No

TASK-2025-00069:Created DocType Technical Support Request

---

beams/beams/doctype/program_request/program_request.json
beams/beams/doctype/program_request/program_request.py

- Add field bureau and project in program request
- Add Project Link in Program Request on creation of Project from Program Request's Approval
- Bring a validation that if a link exist then no project should create
- Added field bureau , project and budget in program request 
- Whenever a new project is created on approval of program request a link is attached in the field project.
- If a project link  already exist in the field project then no new project is created
[Screencast from 18-01-25 07:17:12 PM IST.webm](https://github.com/user-attachments/assets/a506a572-bbc3-491a-8c2b-a447d77c38ef)

TASK-2025-00063 : New fields in program request

---

beams/beams/doctype/external_resource_request/external_resource_request.js
beams/beams/doctype/external_resource_request/external_resource_request.json
beams/beams/doctype/external_resource_request/external_resource_request.py
beams/beams/doctype/external_resource_request/test_external_resource_request.py
beams/beams/doctype/external_resources_detail/external_resources_detail.json
beams/beams/doctype/external_resources_detail/external_resources_detail.py
beams/setup.py

Create 'External Resource Request' DocType and 'External Resources Detail' child table
- Created 'External Resource Request' DocType with the following fields:
- Project (Link/Project)
- Bureau (Link/Bureau, fetched from Project)
- Posting Date (Date)
- Required From (Datetime)
- Required To (Datetime)
- Required Resources (Table for 'External Resources Detail')
- Designed 'External Resources Detail' child table with fields:
- Designation (Link/Designation)
- Required From (Datetime)
- Required To (Datetime)
- Hired Personnel 
- Contact Number 
- Implemented auto-population of 'Required From' and 'Required To' fields in child table based on the main document's values, while keeping them editable.
- Set 'External Resource Request' DocType to be Submittable.
[Screencast from 18-01-25 …

    TASK-2025-00068:Create DocType External Resource Request

---

beams/beams/doctype/allocated_resource_detail/allocated_resource_detail.json
beams/beams/doctype/allocated_resource_detail/allocated_resource_detail.py
beams/setup.py

customized project doctype
- Create a **child table** called **Allocated Resource Detail** with fields for **Designation** (Link/Designation), **Assigned From** (Datetime), **Assigned To** (Datetime), and **Employee** (Link/Employee, filtered based on availability).  
- Add a field called **Allocated Resources** (Table/Allocated Resource Detail) to the program section, enabling detailed tracking of assigned resources.  
-  Include additional fields in the program section: **Bureau** (Link/Bureau, fetched from Program Request), **Estimated Budget** (Currency, fetched from Program Request), and **Approved Budget** (Currency).
project doctype
- Chrome
- Opera Mini
- Safari

feat:customize project doctype

---

beams/beams/custom_scripts/project/project.js
beams/beams/custom_scripts/project/project.py

-  Added a feature to create an Transporation Request from a Project, including mapping relevant fields.
- Implemented the `create_transportation_request` function to map fields from the Project doctype to the Transportation Request doctype.
- Introduced a custom button on the Project form to trigger the creation of the Transportation Request.
[Screencast from 01-21-2025 09:22:42 AM.webm](https://github.com/user-attachments/assets/a444b2f8-0953-44b5-ab77-4783792f80c4)
- `Project Doctype`
- `Transportation Request  Doctype`
- No
- Chrome

 feat :  Add functionality to create Transportation Request from Project

---

beams/beams/custom_scripts/project/project.js
beams/beams/custom_scripts/project/project.py
beams/beams/doctype/program_request/program_request.py
beams/beams/doctype/technical_support_request/technical_support_request.json

Add a button in Project to create a  Technical Support Request by taking values from a popup dialog box and create a Technical Support Request.
Add a Button "Technical Support Request" in "Create" group in Project
On click, Show a popup with the following fields:
- Requirements(Table with the below fields):
-- Department (Link/Department)
-- Designation (Link/Designation)
-- Remarks (Small Text)
Once the popup is submitted with values, create Technical Support Request with Each Lines of Table in Background,
- A new button "Technical Support Request" is added in the "Create" group within the Project module.
- Clicking this button opens a popup dialog.
- The popup contains a table with fields for Department, Designation, and Remarks.
- After submitting the form, a background process is …

feat:Created Technical Support Request from Project

---

beams/beams/doctype/equipment_hire_request/equipment_hire_request.js
beams/beams/doctype/equipment_hire_request/equipment_hire_request.json
beams/fixtures/workflow.json
beams/hooks.py

Added Equipment Hire Request workflow with states and transitions
Added workflow states and transitions for Equipment Request
Added 'Reason for Rejection' field and validation before rejection
Created Asset Movement on approval
[Screencast from 21-01-25 01:08:30 PM IST.webm](https://github.com/user-attachments/assets/7da2f581-4318-428c-b196-dbe54142a141)
[Screencast from 21-01-25 01:10:52 PM IST.webm](https://github.com/user-attachments/assets/1b9d03a6-2b38-49a9-843f-0890bedba3dd)
Equipment Hire Request Doctype
No

    TASK-2025-00080:Create Workflow for Equipment Request

---

beams/beams/doctype/required_hired_vehicle_detail/required_hired_vehicle_detail.json
beams/beams/doctype/transportation_request/transportation_request.json
beams/beams/doctype/vehicle_hire_request/vehicle_hire_request.py

Update No. of Hired Vehicles in Transportation Request on submission of Vehicle Hire Request.
- This update introduces logic to manage the no_of_hired_vehicles field in the linked Transportation Request document.
- On submitting a Vehicle Hire Request, the system will calculate the total number of vehicles from the required_vehicles child table and update the Transportation Request accordingly.
- On canceling a Vehicle Hire Request, the number of hired vehicles in the associated Transportation Request will be reset to 0.
Transportation Request.
No
- Chrome

TASK-2025-00089:Updated No of hired vehicles in Transportation Request

---

beams/beams/doctype/adhoc_budget/adhoc_budget.py

Update the approved budget in the associated Project when the Adhoc Budget workflow state is 'Approved'.
-  Verify the Adhoc Budget's `workflow_state` is 'Approved'.
-  Check if the associated Project exists in the database.
-  Fetch the Project document and ensure the `approved_budget` field is valid (default to 0 if None).
-  Add the Adhoc Budget's `total_budget_amount` to the Project's `approved_budget`.
-  Save the updated Project document and commit the changes to the database.
Project doctype,Adhoc Budget 
- Chrome
- Mozilla Firefox- yes 
- Opera Mini
- Safari

feat:Updating Budget in Project on Approval of Adhoc Budget

---

beams/beams/doctype/transportation_request/transportation_request.js
beams/beams/doctype/transportation_request/transportation_request.json
beams/beams/doctype/transportation_request/transportation_request.py

validation for Reason for Rejection is filled if the status is Rejected and vehicles child table set to editable when Pending Approval state
-  validation for Reason for Rejection is filled if the status is Rejected
- checked to allow on submit of vehicles in transportation request,allow_on_submit 
- vehicles child table set to editable  in transportation request
- Calculate the total number of rows in the "Vehicles" child table  and update the "No. of Own Vehicles" field  in the pending approval state too
transportation request and its doctype
- Chrome
- Opera Mini
- Safari

feat:validation for Reason for Rejection ,  vehicles child table set to editable 

---

beams/beams/report/budget_comparison_report/budget_comparison_report.js
beams/beams/report/budget_comparison_report/budget_comparison_report.json
beams/beams/report/budget_comparison_report/budget_comparison_report.py

- Create Budget Comparison Report
- Created Budget Comparison Report
No.

feat: Create Budget Comparison Report

---

beams/beams/doctype/award_record/award_record.js
beams/beams/doctype/beams_admin_settings/beams_admin_settings.js
beams/beams/doctype/beams_admin_settings/beams_admin_settings.json
beams/beams/doctype/beams_admin_settings/beams_admin_settings.py
beams/beams/doctype/beams_admin_settings/test_beams_admin_settings.py

[TASK-2025-00127] - Add a button in the Award Record to Create JV against the total amount in the Award Record
- created "BEAMS Admin Settings": with - Default Award Expense Account (Link/Account)* fields 
- .Add a "Create Journal Voucher" button to the **Award Record** DocType, visible when `total_amount` > 0.  
- fetch the **Default Award Expense Account** from the **BEAMS Admin Settings **
- Automatically create a **Journal Entry (JV)** with the fetched account as the debit account, a credit account from the **Award Record**, and the `total_amount`.  
- Award Record DocType
- BEAMS Admin Settings DocType
- Journal Entry DocType
- Chrome
- Opera Mini
- …

feat:Add a button in Award Record to Create JV against the total amont

---

beams/setup.py

Duplicate field issue during installation:
requested_by field in Job Requisition
Removed requested by custom field in job requisition in setup
setup.py
No
- Chrome
- Opera Mini
- Safari

fix: removed requested by custom field in job req

---

beams/beams/doctype/makeup_consumption_entry/makeup_consumption_entry.json
beams/beams/doctype/makeup_consumption_entry/makeup_consumption_entry.py

- Add a field stock entry in makeup consumption entry that link to corresponding stock entry
- On cancel of makeup consumption entry cancel the corresponding stock entry
- A new link field added and set as read only
- On submission of makeup consumption entry a stock entry is created and that is linked to the field
- On cancellation of makeup consumption entry the corresponding stock is cancelled
[Screencast from 24-01-25 10:36:33 AM IST.webm](https://github.com/user-attachments/assets/e9c47cac-1356-494f-9c70-819468bf410c)

TASK-2025-00098 : Cancellation of stock entry on cancel of makeup consumption entry

---

beams/beams/custom_scripts/budget/budget.js
beams/beams/doctype/budget_template/budget_template.js
beams/beams/doctype/budget_template/budget_template.json
beams/setup.py

- Customize Budget Template
- Apply filter in Budget template Item based on department
- Fetch Account from cost subhead in Budget Template
- Customized Budget Template
- Applied filters in BUdget Template
- Ferches Account from Cost subhead in Budget Template
[Screencast from 24-01-25 01:19:59 PM IST.webm](https://github.com/user-attachments/assets/054a15e1-9133-4da5-b0aa-7da06dc6ff55)
No.

feat: Update Budget Template and Budget

---

beams/beams/doctype/technical_request/technical_request.js
beams/beams/doctype/technical_request/technical_request.json
beams/beams/doctype/technical_request/technical_request.py

- validation for Technical Request
- Fetch Bureau  from project to Technical Request
- A validate method is implemented in the TechnicalRequest DocType to enforce validation logic whenever the document is saved.
- The solution adds client-side validation triggers for the required_from and required_to fields in the TechnicalRequest form.
-  Fetch Bureau  from project to Technical Request
- Technical Request
- Chrome
- Opera Mini
- Safari

feat:validation for Technical Request

---

beams/beams/doctype/inward_register/inward_register.js
beams/beams/doctype/inward_register/inward_register.json
beams/beams/doctype/inward_register/inward_register.py
beams/beams/doctype/inward_register/test_inward_register.py
beams/beams/doctype/visitor_type/test_visitor_type.py
beams/beams/doctype/visitor_type/visitor_type.js
beams/beams/doctype/visitor_type/visitor_type.json
beams/beams/doctype/visitor_type/visitor_type.py

Need to:Create Inward Register  DocType  and Visitor Type DocType
Created Inward Register  DocType  and Visitor Type DocType with fields:
Create Master DocType Visitor Type
- Visitor Type (Data) (Naming Series)
Create DocType Inward Register
- Vistor Type (Link/Visitor Type)*
- Vistor Name (Data)*
- Posting Date (Date)* Default Today
- Posting Time (Time)* Default Now
- Purpose of Visit (Small Text)*
- Received By (Link/Employee)*
- Vehicles Keys (check)
- Vehicle Key Remarks (Small Text/Mandatory depends on check)
No

TASK-2025-00144:Create DocType Inward Register

---

beams/beams/doctype/inward_register/inward_register.js
beams/beams/doctype/visitor_pass/test_visitor_pass.py
beams/beams/doctype/visitor_pass/visitor_pass.js
beams/beams/doctype/visitor_pass/visitor_pass.json
beams/beams/doctype/visitor_pass/visitor_pass.py

Created DocType Visitor Pass and its validation
- Created a **DocType "Visitor Pass"** with the following fields: **Inward Register** (Link/Inward Register, mandatory), **Issued Date** (Date, mandatory, default to Today), **Issued Time** (Time, mandatory, default to Now), **Issued To** (Data, fetch Visitor Name from Inward Register), **Expire on** (DateTime), **Returned Date** (Date), and **Returned Time** (Time). This DocType should be submittable.
- Validates that issued_date and expire_on are properly set and checks  if issued_date is not later than expire_on.
- Validates that issued_date and returned_date are properly set and checks if issued_date is not later than returned_date.
- Add a button in Inward Register to create a visitor pass
Visitor Pass Doctype
Mention Yes or No. If Yes, …

feat:TASK-2025-00146-Created DocType Visitor Pass and its validation

---

beams/beams/doctype/outward_register/outward_register.js
beams/beams/doctype/outward_register/outward_register.json
beams/beams/doctype/outward_register/outward_register.py
beams/beams/doctype/outward_register/test_outward_register.py

Need to:Create Outward Register Doctype
Created Outward Register Doctype with fields :
- Inward Register (Link/Inward Register)*
- Posting Date (Date)* Default Today
- Posting Time (Time)* Default Now
Fetch the below data from Inward Register
- Vistor Type (Select/ (Options))*
- Vistor Name (Data)*
- Purpose of Visit (Small Text)*
- Received By (Link/Employee)*
- Vehicles Keys Handover (check)
- Vehicle Key Remarks (Small Text/Mandatory depends on check)
[Screencast from 27-01-25 10:28:30 AM IST.webm](https://github.com/user-attachments/assets/065b02e4-e2c5-4c32-84df-843d6af1c4f1)
Outward Register Doctype
No.

TASK-2025-00145:Create Outward Register Doctype

---

beams/beams/custom_scripts/event/event.js
beams/beams/doctype/external_participants_detail/external_participants_detail.json
beams/beams/doctype/external_participants_detail/external_participants_detail.py
beams/beams/doctype/guest_appointment/guest_appointment.js
beams/setup.py

- Customize Event
- Create button to create guest appointment from event and event from guest appointment
- If a service unit already has a event then no other event should be created with same time period
- Added fields in event 
. Check box Assign service unit
. Meeting room - service unit
. Child table external participants
- Created button guest appointment in event doctype
- Created button event in guest appointment doctype
- Once a event is created against a service unit , when a another event of same service unit of same time period is created validation is triggered
- Filter is added to the field meeting room
[Screencast from 24-01-25 04:45:19 PM IST.webm](https://github.com/user-attachments/assets/7e634a7a-cc27-4e8b-9c7b-c76df49ec033)

TASK-2025-00153 : Customize event and create button

---

beams/beams/doctype/visitor_pass/visitor_pass.json
beams/beams/doctype/visitor_pass/visitor_pass.py

- Added Validation that Returned Date and Time is filled in before Status becomes Returned
- This solution addresses the requirement to ensure that the "Returned Date" and "Returned Time" fields are filled when the workflow state is transitioned to "Issued" in the "Visitor Pass" Doctype.
- A new method **validate_returned_date_and_returned_time**  was added to check the presence of the **returned_date** and  **returned_time** fields when the workflow_state is set to "Issued".
- Visitor Pass Doctype
- Chrome
- Opera Mini
- Safari

feat: TASK-2025-00147-Added Validation that Returned Date and Time is filled in before Status becomes Returned

---

beams/beams/doctype/cost_head/cost_head.js
beams/beams/doctype/cost_head/cost_head.json
beams/beams/doctype/cost_head/cost_head.py
beams/beams/doctype/cost_head/test_cost_head.py
beams/beams/doctype/cost_subhead/cost_subhead.json

New DocType Cost Head
Remove department field from Cost Subhead
Cost Head
DocType
- Cost Subhead
No
- Chrome
- Opera Mini
- Safari

feat: added cost head and modified cost subhead

---

beams/beams/custom_scripts/budget/budget.js
beams/beams/doctype/budget_template/budget_template.js
beams/beams/doctype/budget_template_item/budget_template_item.json
beams/setup.py

Cost Head in Items of Budget and Budget Template
Fetching Cost Head when selecting Budget template
Removing Department filter on cost subhead field in budget template
- Chrome
- Opera Mini
- Safari

feat: cost head in budget

---

beams/beams/custom_scripts/event/event.js
beams/beams/custom_scripts/event/event.py
beams/hooks.py
beams/setup.py

1.Need to create workflow for event doctype
2.Need to set status status as cancelled when it is rejected 
3.Need to Set the state as pending if there is a service unit selected in the event
4.Need to validate before approval that there is no event that is open with the same service unit in the same time
5.add  new field Reason for Rejection in event
6 .If a service unit already has a event then no other event should be created with same time period
1.created workflow for event doctype
-Draft, Pending (if only the event has a service unit),Approved (if only the event has a service unit) ,Rejected (if only the event has a service unit)
2.set the status as cancelled when it is rejected 
-when the workflow state rejected  need to set status become cancelled via event.py
3.Set the state as …

    TASK-2025-00154 : Created Workflow for Event doctype

---

beams/beams/custom_scripts/project/project.js
beams/beams/custom_scripts/project/project.py
beams/beams/doctype/adhoc_budget/adhoc_budget.json
beams/beams/doctype/required_items_detail/required_items_detail.json
beams/setup.py

- Make Approved Budget field in Project doctype read only.
- Make Generates Revenue field read only  in Adhoc Budget doctype.
- Create Button in Project to create Equipment Request.
The specified fields were made read only a button was created to create Equipment Request document.
Project doctype and Adhoc Budget doctype.
No
- Chrome

fix:Changes in Sprint Review

---

beams/beams/custom_scripts/salary_slip/salary_slip.py
beams/hooks.py

The feature creates a Journal Entry for Provident Fund (PF) deduction when a Salary Slip is submitted. 
1) Validation:
-Check for the "Provident Fund" deduction in the deductions child table of the Salary Slip.
2) Fetch Accounts:
-Retrieve the PF Expense Account from Payroll Settings.
-Fetch the PF Payable Account from the Salary Component for Provident Fund and ensure it matches the company.
3) Create Journal Entry:
-Instantiate a new Journal Entry with the following details:
Debit: PF Expense Account for the deducted amount.
Credit: PF Payable Account for the same amount.
-Link the Journal Entry to the Salary Slip.
4) Insert and Submit:
Save and submit the Journal Entry.
- Salary Slip Submission: Ensures PF deductions trigger Journal Entry …

feat: Create Journal Entry for Provident Fund (PF) deduction upon submission of Salary Slip

---

beams/beams/doctype/required_items_detail/required_items_detail.json

Change Required Item Detail Doctype fields to Mandatory
Required Item Detail Doctype fields change to Mandatory
No

 Required Item Detail Doctype fields change to Mandatory

---

beams/beams/doctype/equipment_hire_request/equipment_hire_request.js
beams/beams/doctype/equipment_hire_request/equipment_hire_request.json
beams/beams/doctype/equipment_hire_request/equipment_hire_request.py
beams/beams/doctype/required_hire_items_detail/required_hire_items_detail.json

Need to: Fix the issues in  Equipment Hire Request Doctype and Required Hire Items Detail Doctype
Fixed the issues in  Equipment Hire Request Doctype :
Fetched Bureau field from Project Doctype and validated that required_from and required_to
Required Hire Items Detail Doctype:
Item Field and Quantity Field can changed to Mandatory
Equipment Hire Request Doctype  and Required Hire Items Detail Doctype
No.

Fix:Fixed the issues in  Equipment Hire Request Doctype

---

beams/beams/custom_scripts/project/project.py
beams/hooks.py

Update related Program Request workflow state to 'Closed' when the Project status becomes 'Completed'.
This function, update_program_request_status_on_project_completion, is designed to update the workflow state of all related Program Requests to "Closed" when the status of a Project is updated to "Completed"
- Chrome
- Opera Mini
- Safari

feat:Update related Program Request workflow state to 'Closed' when the Project status becomes 'Completed'.

---

beams/beams/custom_scripts/project/project.py
beams/beams/doctype/adhoc_budget/adhoc_budget.js
beams/beams/doctype/adhoc_budget/adhoc_budget.py

1. Need add validation on the expected start date and expected end date 
2.  Need fetch the default  fiscal_year in adhoc budget from project 
3. need to update  total budget amount when removing a Budget Expense row in Adhoc Budget
4.  need to Validate 'expected_revenue' only when 'generates_revenue' is set in Adhoc Budget
1. added  validation on the expected start date and expected end date 
- validation applied  that expected end date should greater than expected start date via project.py
2.  fetched the default  fiscal_year in adhoc budget from project
- mapped the fiscal year from the project to adhoc budget as default via project.py
3.  updated   total budget amount when removing a Budget Expense row in Adhoc Budget
- updated the total budget amount  after deleting row from budget …

fix: applied validation and minor fixes in adhoc budget

---

beams/beams/doctype/visitor_pass/visitor_pass.json

Update 'Issued To' Field in Visitor Pass Doctype Fetch from Inward Register Doctype field 'Visitor Name' 
Updated 'Issued To' Field in Visitor Pass Doctype Fetch from Inward Register Doctype field 'Visitor Name'
No

Updated 'Issued To' Field in Visitor Pass Doctype Fetch from Inward Register field 'Visitor Name'

---

beams/beams/doctype/external_resource_request/external_resource_request.js
beams/beams/doctype/external_resource_request/external_resource_request.json
beams/beams/doctype/external_resource_request/external_resource_request.py

Need to: Fetch Bureau field from Project Doctype, Validate the required_from and required_to and Change some fields to mandatory in  External Resource Request Doctype" 
Fetched Bureau field from Project Doctype, Validated the required_from and required_to and Changed some fields to mandatory in  External Resource Request Doctype" 
External Resource Request Doctype
No. 

Fix:Validated the required _from and required_to in External Resource Request Doctype

---

beams/beams/custom_scripts/project/project.js
beams/beams/custom_scripts/project_dashboard/project_dashboard.py

Add a button to the 'Project' form to create an External Resource Request
✅ Creates a "External Resource Request" button inside the Project form.
✅ On Click, it opens a new External Resource Request form.
✅ Automatically fills in the Project and Bureau fields from the current Project document.
✅ Groups the button under the "Create" dropdown (optional).
✅ Add "External Resource Request"  into connection
Project and External Resource Request doctype
- Chrome
- Opera Mini
- Safari

feat:Add a button to the 'Project' form to create an External Resource Request

---

beams/beams/doctype/technical_request/technical_request.js

Need to: Create a Button External Resource Request in Technical Request Doctype
Created a Button External Resource Request in Technical Request Doctype when it is saved. 
[Screencast from 29-01-25 04:38:11 PM IST.webm](https://github.com/user-attachments/assets/6c6d8e2b-82ff-4ccb-83f1-d81dd1c4e73f)
Technical Request Doctype
No. 

Created a Button External Resource Request in Technical Request Doctype

---

beams/beams/custom_scripts/project/project.py
beams/hooks.py

1.Need to apply validation on the project when the employee is not assigned to multiple projects during the same time period.
Added validation to ensure an employee is not assigned to multiple projects during overlapping time periods.
via project.py 
[Screencast from 30-01-25 01:28:00 PM IST.webm](https://github.com/user-attachments/assets/c85b6aee-ce1f-4555-9fba-a1c407fa2531)
project doctype
no

feat: Applied validation for employee is not assigned to multiple projects

---

beams/beams/doctype/employee_travel_request/employee_travel_request.json
beams/beams/doctype/employee_travel_request/employee_travel_request.py
beams/beams/doctype/reference_document/reference_document.json

Add Validation in Employee Travel Request Doctype and Calculate Total Days 
Remove Mandatory field in Reference Document Doctype
Added Validation in Employee Travel Request Doctype and Calculate Total Days 
Total Days field change to Read Only in Employee Travel Request
Removed Mandatory field in Reference Document Doctype
No

 Add Validation in Employee Travel Request Doctype and Calculate Total Days

---

beams/beams/custom_scripts/salary_slip/salary_slip.py
beams/hooks.py

The feature creates a Journal Entry for Employee State Insurance (ESI) deduction when a Salary Slip is submitted. 
1) Validation:
-Check for the "Employee State Insurance (ESI)" deduction in the deductions child table of the Salary Slip.
2) Fetch Accounts:
-Retrieve the ESI Expense Account from Payroll Settings.
-Fetch the ESI Payable Account from the Employee State Insurance Salary Component for  and ensure it matches the   company.
3) Create Journal Entry:
-Instantiate a new Journal Entry with the following details:
Debit: ESI Expense Account for the deducted amount.
Credit:  ESI Payable Account for the same amount.
-Link the Journal Entry to the Salary Slip.
4) Insert and Submit:
Save and submit the Journal Entry.
- Salary Slip Submission: …

feat: Create Journal Entry for Employee State Insurance (ESI) deduction upon submission of Salary Slip

---

beams/beams/doctype/equipment_hire_request/equipment_hire_request.js
beams/beams/doctype/equipment_hire_request/equipment_hire_request.json
beams/beams/doctype/equipment_request/equipment_request.js
beams/beams/doctype/equipment_request/equipment_request.json
beams/setup.py

✅ Create approval workflow for Equipment Request
✅ Automatically generates an Asset Movement upon approval
✅ Validate the reason for rejection before submission
✅ Equipment Request workflow is implemented
✅ Approval automatically creates Asset Movement
✅ Rejection requires a reason
[Screencast from 31-01-25 11:28:53 AM IST.webm](https://github.com/user-attachments/assets/3cb07d0a-0d6b-4da7-886e-4b5d44c3ed40)
✅ Equipment Request Doctype 
✅  No.
✅ Mozilla Firefox

feat:Create Workflow for Equipment Request

---

beams/beams/doctype/vehicle_documents/vehicle_documents.json
beams/setup.py

Hide Insurance Details Section Break, Add  Fields ' Reference No, Remarks'  in Vehicle Documents Doctype
Hided Insurance Details Section Break, Added  Fields ' Reference No, Remarks'  in Vehicle Documents Doctype
No

 Hided Insurance Details Section Break, Added Fields in Vehicle Documents Doctype

---

beams/beams/doctype/required_hired_vehicle_detail/required_hired_vehicle_detail.json

Remove License Plate field from Required Hired Vehicle Detail
Removed License Plate field from Required Hired Vehicle Detail
No

 Removed License Plate field from Required Hired Vehicle Detail Doctype

---

beams/beams/custom_scripts/employee_checkin/employee_checkin.py

Fix the issue where employees with double shift assignment are unable to check out due to the missing "Compensatory Leave Type" configuration in Beams HR Settings. 
Added a check to allow employees to check out even if the "Compensatory Leave Type" is not set.
If the setting is missing, the function simply returns instead of blocking check-out.
Employee check-in/check-out process
Beams HR Settings 
- Chrome
- Opera Mini
- Safari

fix: fix check-out failure due to missing Compensatory Leave Type in Beams HR Settings

---

beams/beams/doctype/inward_register/inward_register.js
beams/beams/doctype/inward_register/inward_register.py
beams/beams/doctype/outward_register/outward_register.js
beams/beams/doctype/outward_register/outward_register.py
beams/beams/doctype/transportation_request/transportation_request.js
beams/beams/doctype/transportation_request/transportation_request.py
beams/beams/doctype/trip_sheet/trip_sheet.js
beams/beams/doctype/trip_sheet/trip_sheet.json
beams/beams/doctype/trip_sheet/trip_sheet.py
beams/beams/doctype/vehicle_incident_record/vehicle_incident_record.js
beams/beams/doctype/vehicle_incident_record/vehicle_incident_record.json
beams/beams/doctype/vehicle_incident_record/vehicle_incident_record.py

Need to: 
Validate the posting date fields in Vehicle Incident Record Doctype, Trip Sheet Doctype and Inward Register Doctype,Outward Register Doctype and Transportation Request Doctype.
Change the Vehicle Incident Record Doctype like add Driver field.
Validate the posting date fields in Vehicle Incident Record Doctype, Trip Sheet Doctype and Inward Register Doctype,   Outward Register Doctype and Transportation Request Doctype.
Change the Vehicle Incident Record Doctype like add Driver field.
Vehicle Incident Record Doctype, Trip Sheet Doctype and Inward Register Doctype.
No. 

Fix:Validated the posting date fields

---

beams/beams/doctype/award_expense_detail/award_expense_detail.json
beams/beams/doctype/award_record/award_record.js
beams/beams/doctype/award_record/award_record.json
beams/beams/doctype/award_record/award_record.py
beams/beams/doctype/equipment_hire_request/equipment_hire_request.js
beams/beams/doctype/equipment_hire_request/equipment_hire_request.json
beams/beams/doctype/equipment_hire_request/equipment_hire_request.py
beams/beams/doctype/equipment_request/equipment_request.js
beams/beams/doctype/equipment_request/equipment_request.py
beams/beams/doctype/guest_appointment/guest_appointment.js
beams/beams/doctype/guest_appointment/guest_appointment.py

validation for posting date
added posting date validation in equipment_hire_request,equipment_request,guest_appointment
- equipment hire request
- equipment request 
- guest appointment
- Chrome
- Opera Mini
- Safari

feat:validation for posting date

---

beams/setup.py

Add field for Department Head Name in Department
Add field department and hide field 'resume link' in Interview doctype.
Added required fields in Interview and Department doctype.
- Chrome
- Opera Mini
- Safari

fix: Update inteview and department doctype

---

beams/beams/custom_scripts/project/project.js
beams/beams/custom_scripts/project/project.py
beams/beams/doctype/adhoc_budget/adhoc_budget.json
beams/beams/doctype/employees/employees.json
beams/beams/doctype/employees/employees.py
beams/beams/doctype/equipment_acquiral_request/equipment_acquiral_request.js
beams/beams/doctype/equipment_acquiral_request/equipment_acquiral_request.json
beams/beams/doctype/equipment_acquiral_request/equipment_acquiral_request.py
beams/beams/doctype/equipment_acquiral_request/test_equipment_acquiral_request.py
beams/beams/doctype/equipment_request/equipment_request.js
beams/beams/doctype/equipment_request/equipment_request.py
beams/beams/doctype/external_resource_request/external_resource_request.js
beams/beams/doctype/external_resource_request/external_resource_request.py
beams/beams/doctype/program_request/program_request.json
beams/beams/doctype/required_items_detail/required_items_detail.json
beams/beams/doctype/technical_request/technical_request.js
beams/beams/doctype/technical_request/technical_request.json
beams/beams/doctype/technical_request/technical_request.py
beams/setup.py

- Created a popup in Project that takes inputs to create Technical Request  including no of employees and the technical document created  allows selection from a filtered list based on department and designation and the selection is limitted by the number of employees  specified in the popup.
- Removed assigning Equipments functionality from Project.
Fetched Remarks,Description and expected revenue from Program Request in project.
Created External Resource Request from Technical Request and populated its child table required resources. 
Technical Request
Equipment Acquiral Request.
External Resource  Request.
Program Request.
Project.
No
- Chrome

feat:Added no of in  employees in Technical Request

---

beams/beams/doctype/employee_travel_request/employee_travel_request.json

Need to: 
- Hide the Reason for Rejection field based on workflow state in Employee Travel  Request Doctype.
- Change to Batta Policy field to Read Only 
- Add the description for Mark Attendance Check Box
- Hide the Reason for Rejection field based on workflow state in Employee Travel  Request Doctype.
- Changed to Batta Policy field to Read Only 
-  Added the description for Mark Attendance Check Box
[Screencast from 04-02-25 10:13:46 AM IST.webm](https://github.com/user-attachments/assets/f29f1088-e3cf-4379-af4a-9920010a14ef)
Employee Travel  Request Doctype.
No. 

Fix:Hide the Reason for Rejection field based on workflow state in Employee Travel  Request Doctype

---

beams/beams/custom_scripts/budget/budget.js

- Set Budget Template in Budget based on division.
- Set Budget Template in Budget based on division.
[Screencast from 04-02-25 01:42:32 PM IST.webm](https://github.com/user-attachments/assets/3b5d0301-3c25-4904-aa1b-bf520dba2d0a)
No.

feat:Set Budget Template in Budget

---

beams/beams/custom_scripts/interview/interview.js

Real-time validation is added to the score field in the feedback dialog to ensure that users cannot enter a score greater than 10.
The score field is validated instantly as the user types, showing an error if it exceeds 10.
- Added an event listener for the score field in the feedback dialog.
- When a score is entered, the script checks if it exceeds the maximum limit of 10. If so, an error message is shown to the user.
- This change ensures that the score validation happens immediately when the user inputs a value, rather than waiting until submission.
[Screencast from 02-04-2025 11:50:56 AM.webm](https://github.com/user-attachments/assets/75f74aff-3afa-4e31-8aa9-a0515a234511)
Interview feedback dialog

fix: Add validation for score field in Interview Feedback dialog

---

beams/setup.py

Need to: Customize Purchase Order Doctype. Add following fields in PO Item Table:-
Under References:
- Reference DocType (Link/DocType)
- Reference Document (Dynamic Link/Reference DocType)
Customized Purchase Order Doctype.  Added following fields in Purchase Order  Item Table:-
Under References:
- Reference DocType (Link/DocType)
- Reference Document (Dynamic Link/Reference DocType)
[Screencast from 04-02-25 01:14:22 PM IST.webm](https://github.com/user-attachments/assets/f39d01dd-89d6-4dd8-84ce-17116be5f7ba)
Purchase Order Doctype
No. 

TASK-2025-00173:Customized Purchase Order Doctype

---

beams/beams/doctype/equipment_request/equipment_request.json
beams/beams/doctype/equipment_request/equipment_request.py

Need to: Hide the Reason for Rejection field based on workflow state in Equipment Request Doctype
Hide the Reason for Rejection field based on workflow state in Equipment Request Doctype
[Screencast from 04-02-25 03:43:38 PM IST.webm](https://github.com/user-attachments/assets/6d0238fd-8ef3-49f0-a5a3-badea566cd95)
Equipment Request Doctype
No.

Fix:Hide the Reason for Rejection field based on workflow state in Equipment Request Doctype

---

beams/beams/custom_scripts/interview/interview.py
beams/hooks.py

Restricts interview visibility for users with the "Interviewer" role to only those interviews they are assigned to
- Modified the get_permission_query_conditions method to ensure that only users with the "Interviewer" role can see interviews where they are assigned as an interviewer.
- The query checks the Interview Details table to match the logged-in user with the interviewer field.
- Administrators have unrestricted access to all interviews.
- Interview DocType permissions
- Interview Details table functionality for filtering interviews by interviewer
- Chrome
- Opera Mini
- Safari

fix: Restrict interview visibility to assigned interviewers only

---

beams/beams/custom_scripts/project/project.js
beams/beams/custom_scripts/project/project.py
beams/beams/doctype/equipment_request/equipment_request.js

-  Add Button  in Project to create equipment request which will open a popup with table for entering data:-
- When an item is selected in the table, available qty should be fetched in required qty can be entered.
- Upon primary action of popup, create equipment request
When Equipment Request button is clicked a popup dialog box appears.This has item field that shows filtered list of items in a particular Bureau.Available quantity is fetched by checking availability of the item.
validation logic for the "Required From" and "Required To" fields in the Equipment Request popup.
Upon Submission Equipment Request is created.
No
- Chrome

TASK-2025-00172:Equipment Request created from Project

---

beams/setup.py

The Employee DocType already has the field "His/Her Name". Since the same label was used when  Are You Related to Employee(checkbox) was checked, it caused an error.
Renamed the duplicate "His/Her Name" field to "Related Employee Name" when Are You Related to Employee(checkbox) was checked 
Employee

fix: Update field label from His/Her Name to Related Employee Name

---

beams/beams/custom_scripts/item/item.py
beams/hooks.py
beams/setup.py

Customize Item Group:-
- Hireable (check, set only once, fetch from parent item group (fetch only if empty))
Customize Item:-
- Hireable (check, fetch from item group, set only once)
- Service Item (Link, Item)
If an item is created with Hireable checked, create a service item with the same details and set it in the original item
Customized Item Group (added field hireable)
Customized Item (added field hireable and service item)
Created a service item with the same details and set it in the original item when an item created with hireable checked
Item Group
Item

feat:create a service item with the same details and set it in the original item

---

beams/beams/doctype/equipment_acquiral_request/equipment_acquiral_request.js
beams/beams/doctype/equipment_acquiral_request/equipment_acquiral_request.json
beams/beams/doctype/equipment_acquiral_request/equipment_acquiral_request.py
beams/beams/doctype/equipment_request/equipment_request.js
beams/beams/doctype/equipment_request/equipment_request.py
beams/beams/doctype/required_acquiral_items_detail/required_acquiral_items_detail.json
beams/beams/doctype/required_acquiral_items_detail/required_acquiral_items_detail.py
beams/beams/doctype/required_items_detail/required_items_detail.json
beams/setup.py

Need to: 
- Create Purchase Order Button from Equipment Acquiral Request Doctype  to Purchase Order Doctype.
Showed a dialog box, Items in the form is displayed in the dialog box. Everything editable. on      Primary action, create Purchase Order with the Corresponding Item Row reference in the PO Item Table
- Maps fields from the Equipment Request doctype to the Equipment Acquiral Request doctype.
- Create new Role "Budget User".
- Created Purchase Order Button from Equipment Acquiral Request Doctype  to Purchase Order Doctype.
Show a dialog box, Items in the form is displayed in the dialog box. Everything editable. on Primary action, create    Purchase Order with the Corresponding Item Row reference in the PO Item Table
- Maps fields from the Equipment Request doctype to the Equipment …

Feat:Created Purchase Order Button from Equipment Acquiral Request Doctype  to Purchase Order Doctype

---

beams/beams/custom_scripts/budget/budget.js
beams/beams/doctype/rejection_feedback/rejection_feedback.json
beams/beams/doctype/rejection_feedback/rejection_feedback.py
beams/setup.py

- Add Child table Rejection Feedback in Budget Doctype
- Added Rejection Feedback in Budget Doctype
[Screencast from 06-02-25 11:29:03 AM IST.webm](https://github.com/user-attachments/assets/b399c73d-6232-41ce-93a2-5c352d753c89)
No.

feat: Added child table Rejection Feedback in Budget

---

beams/beams/custom_scripts/budget/budget.js
beams/beams/doctype/rejection_feedback/rejection_feedback.json

-Add User Fullname in Rejection Feedback
-Added User Fullname in Rejection Feedback.
No.

fix: Added User Fullname in Rejection Feedback

---

beams/beams/doctype/award_record/award_record.js
beams/beams/doctype/award_record/award_record.py
beams/beams/doctype/employee_travel_request/employee_travel_request.json

Add travel request button for 'nominated' and 'applied' workflow states in Award record doctype.
Add dynamic link child table to employee travel request doctype.
Map from award record to employee travel request doctype.
Added travel request button for 'nominated' and 'applied' workflow states in Award record doctype.
Added dynamic link child table to employee travel request doctype.
Mapped from award record to employee travel request doctype.
List out the areas affected by your code changes.( award record, employee travel request doctype)

feat:mapping from award record to employee travel request

---

beams/beams/custom_scripts/leave_application/leave_application.js

The issue was that the Medical Certificate field in Leave Application was being shown for all leave applications where is_proof_document(checkbox) was enabled in the Leave Type, regardless of whether the leave duration exceeded the Medical Leave Required value configured in the Leave Type. The check for leave duration was not correctly ensuring that the Medical Certificate field would appear only when the leave duration was greater than the Medical Leave Required value.
Refactored validation logic for Medical certificate field.
Ensured proper field visibility based on leave type and leave duration.
[Screencast from 02-07-2025 11:20:10 AM.webm](https://github.com/user-attachments/assets/d7135140-aed0-4291-9b6f-87012e5abed1)
Leave Application form …

Refactor: Improve Leave Application script with medical certificate validation and date checks

---

beams/beams/doctype/external_resource_request/external_resource_request.js

Need to: Remove the purchase invoice button in External Resource Request Doctype
Removed the purchase invoice button in External Resource Request Doctype.
No.

Fix:Removed the purchase invoice button in External Resource Request Doctype

---

beams/beams/doctype/employee_travel_request/employee_travel_request.js
beams/beams/doctype/employee_travel_request/employee_travel_request.json
beams/beams/doctype/employee_travel_request/employee_travel_request.py

add validation for end date in the Employee Travel Request
add validation for end date in the Employee Travel Request
Collapsible set true in section break in Employee Travel Request
Employee Travel Request
- Chrome
- Opera Mini
- Safari

feat: add validation for end date in  Employee Travel Request

---

beams/beams/custom_scripts/purchase_order/purchase_order.py
beams/beams/doctype/equipment_acquiral_request/equipment_acquiral_request.js
beams/beams/doctype/equipment_acquiral_request/equipment_acquiral_request.json
beams/beams/doctype/required_items_detail/required_items_detail.json
beams/hooks.py

1.Need link the Purchase Order Items to Required Acquiral Items with reference fields in Equipment Acquiral Request child table.
2.Need to update  of Purchase Order fulfillment, update Acquired Qty qty in the corresponding Equipment Acquiral Request and Issued Qty in corresponding Equipment Request doctype
3. Need to Add new field in  Equipment Acquiral Request  doctype 
4. Need to add  'allow_on_submit' for issued_quantity field in Required Items Detail
1.linked the Purchase Order Items to Required Acquiral Items with reference fields in Equipment Acquiral Request child table.
- linked the Equipment Acquiral Request  item with Corresponding Item Row reference in the PO Item Table
- linked  Equipment Acquiral Request   service item Corresponding Item Row reference in the  service PO Item …

TASK-2025-00174: Modified Equipment Acquiral Request

---

beams/beams/custom_scripts/project/project.js
beams/beams/custom_scripts/project/project.py
beams/beams/doctype/equipment_request/equipment_request.js
beams/beams/doctype/required_items_detail/required_items_detail.json

Modify filtering of item by considering location as the attribute instead of Bureau in Required Item Detail child table.
From Project create Equipment Request button when clicked shows a popup dialog box   Available quantity in require items detail child table  is auto fetched when an item is selected.But the filtering was based on Bureau defined in the Project.Now it is modified as filtering is done based on Location of item.
Project doctype.
Equipment Request doctype.
No
- Chrome

fix:Available quantity fetched  from filtered list of items based on location.

---

beams/beams/custom_scripts/purchase_order/purchase_order.py

Need add  logic for updating the issue quantity in equipment request 
updated the logic of code for update the issue quantity in equipment request doctype
- Instead of saving child rows in loop, Save the parent doc  after required actions
[Screencast from 10-02-25 05:36:08 PM IST.webm](https://github.com/user-attachments/assets/1dc292c3-ac28-44c6-8770-f953e4af4e9e)
equipment request
No. 

fix: updated  logic for the issue quantity in equipment request 

---

beams/beams/doctype/technical_request/technical_request.js

Add validation for 'external resource request ' button in technical request doctype
Added validation for 'external resource request ' button in technical request doctype ( shows 'external resource request ' button only when workflow state is approved) 
List out the areas affected by your code changes. (technical request doctype)

feat:add validation for external resource request button in technical request doctype

---

beams/beams/doctype/equipment_request/equipment_request.js
beams/beams/doctype/equipment_request/equipment_request.py
beams/beams/doctype/required_items_detail/required_items_detail.json

Create Asset Movement Button should map details for asset movement against the asset of the selected item
Created Asset Movement Button should map details for asset movement against the asset of the selected item
[Screencast from 12-02-25 11:38:00 AM IST.webm](https://github.com/user-attachments/assets/b2d95aee-f806-4145-b1a0-d774f2ba2969)
Asset Movement
No

feat:  Created Asset Movement Button should map details for asset movement against the asset of the selected item

---

beams/beams/doctype/equipment_request/equipment_request.js

- add validation for button Equipment Acquiral Request
- add validation for button Equipment Acquiral Request in Equipment  Request 
- button is only visible when the document's workflow state is "Approved".
Equipment  Request 
- Chrome
- Mozilla Firefox-yes 
- Opera Mini
- Safari

feat:add validation for button Equipment Acquiral Request

---

beams/beams/custom_scripts/purchase_order/purchase_order.py
beams/beams/doctype/required_items_detail/required_items_detail.json

1.Need to add  new field in the child table  Required Items Detail doctype
1. Need to  update the value in to acquired quantity in Equipment Request doctype 
1. Added the field called Acquired quantity in the child table Required Items Detail doctype 
2. change updation  of value issue quantity in to the acquired quantity when purchase order is submitted in equipment request
[Screencast from 13-02-25 10:17:30 AM IST.webm](https://github.com/user-attachments/assets/e94a5032-0bdd-4b53-825c-188d28986b70)
Equipment Request and Equipment Acquiral Request Doctype
No

fix: updated Equipment Request field from issued quantity to acquired quantity

---

beams/beams/custom_scripts/asset_movement/asset_movement.js
beams/beams/custom_scripts/asset_movement/asset_movement.py
beams/beams/doctype/equipment_request/equipment_request.js
beams/beams/doctype/equipment_request/equipment_request.py
beams/hooks.py

Issued Qty will be updated once asset movement is submitted
Issued Qty updated once asset movement is submitted
[Screencast from 12-02-25 04:52:26 PM IST.webm](https://github.com/user-attachments/assets/fcd15a53-b48e-4b2b-9b54-6b79463ef4f2)
Equipment Request
No

feat: Issued Qty updated once asset movement is submitted

---

beams/beams/custom_scripts/project/project.js
beams/beams/doctype/employee_travel_request/employee_travel_request.json
beams/beams/doctype/transportation_request/transportation_request.json
beams/setup.py

Nedd to: 
- Arrange the button on group button in project.
-  Add search fields in Transportation Request Doctype and Travel Request Doctype
-  Change the field name of Requirements fields in Project Doctype.
-  Arrange the button on group button in Project Doctype.
-  Add search fields in Transportation Request Doctype and Travel Request Doctype.
-  Change the field name of Requirements fields in Project Doctype.
- Project Doctype
- Transportation Request Doctype
- Travel Request Doctype.
No. 

Fix:Arranged the buttons on group button in Project Doctype

---

beams/beams/custom_scripts/budget/budget.js
beams/beams/doctype/budget_template/budget_template.js
beams/beams/doctype/budget_template/budget_template.json
beams/beams/doctype/budget_template/budget_template.py
beams/beams/doctype/budget_template_item/budget_template_item.json
beams/beams/doctype/cost_subhead/cost_subhead.js
beams/beams/doctype/cost_subhead/cost_subhead.json
beams/patches.txt
beams/patches/update_account.py
beams/setup.py

- Customize Cost Subhead doctype and Budget Template.
- Apply company filter in Budget Template field of Budget.
- Apply filter in Account field of Cost Subhead.
- Fetch account in Budget template based on selected company.
- Customized Cost Subhead doctype and Budget Template.
- Applied company filter in Budget Template field of Budget.
- Applied filter in Account field of Cost Subhead.
- Fetches account in Budget template based on selected company.
- Set account as read only in both budget and Budget template child table.
[Screencast from 13-02-25 03:02:31 PM IST.webm](https://github.com/user-attachments/assets/212851c7-349b-424f-a59d-4202f62afa08)
No.

feat: Update Cost Subhead and Budget Template

---

beams/beams/doctype/technical_request/technical_request.json

Change Required Employee Field editable in Technical Request Doctype when workflow state Pending Approval
Required Employee Field editable in Technical Request Doctype when workflow state Pending Approval
No

fix: Required Employee Field editable in Technical Request Doctype

---

beams/setup.py

Customize Asset Category doctype.
Add field Parent Asset Category
Customized Asset category doctype ( Added new field named Parent Asset category) 
List out the areas affected by your code changes. ( Asset category doctype)

feat: customize asset category doctype

---

beams/beams/doctype/asset_auditing/asset_auditing.js
beams/beams/doctype/asset_auditing/asset_auditing.json
beams/beams/doctype/asset_auditing/asset_auditing.py
beams/beams/doctype/asset_auditing/test_asset_auditing.py
beams/beams/doctype/attachments_detail/attachments_detail.json
beams/beams/doctype/attachments_detail/attachments_detail.py

Create Doctype Asset Auditing with custom fields,Validate attach 3 photos before submit
Employee field fetch when select an Asset
Created Doctype Asset Auditing with custom fields,Validated attach 3 photos before submit
Employee field fetched when select an Asset
No

TASK-2025-00196: Created Doctype Asset Auditing with custom fields

---

beams/setup.py

customize asset doctype
- add fields in asset 
- Field Name - In Transit, Warranty Reference No ,Warranty Till
asset doctype
- Chrome
- Mozilla Firefox -yes
- Opera Mini
- Safari

feat:customize asset doctype

---

beams/beams/custom_scripts/appraisal/appraisal.js
beams/beams/custom_scripts/appraisal/appraisal.py
beams/setup.py

✅ Implement logic to display "View Event" button if an existing event is linked to the Appraisal.
✅ "Remove 'Event Reference' field from appraisal form
✅ Add "View Event" button to Appraisal form when an event is linked.
✅ Removed 'Event Reference' field from appraisal form
[Screencast from 18-02-25 11:08:25 AM IST.webm](https://github.com/user-attachments/assets/812506b1-e5e9-420c-b070-ba8d0756d45b)
✅ No. 
✅ Mozilla Firefox

    ISS-2025-00029:Refactor One-to-One Meeting button and add event reference

---

beams/beams/custom_scripts/appraisal/appraisal.py
beams/beams/custom_scripts/employee_checkin/employee_checkin.py

1. When Employees working on a double shift and checking out lack the necessary permissions to create or update their leave allocation, preventing the compensatory leave from being granted.
2. When attempting to save an Appraisal document, a TimestampMismatchError was raised. The error message indicated that the document had been modified after it was loaded into memory:
- Added ignore_permissions flag while saving Leave Allocation to prevent PermissionError.
- Update only the specific field (final_average_score) directly in the database using frappe.db.set_value, thereby bypassing the full document save and its timestamp check.
- Employee Checkin-processing
- Leave …

fix: handle permission issue for Leave Allocation update

---

beams/beams/doctype/asset_auditing/asset_auditing.js
beams/beams/doctype/asset_auditing/asset_auditing.json
beams/beams/doctype/asset_auditing/asset_auditing.py

- added Posting Date to Asset Auditing doctype
- added Posting Date to Asset Auditing doctype
- add validation for posting date
- fetch location from asset
Asset Auditing
- Chrome
- Opera Mini
- Safari

feat:add Posting Date to Asset Auditing doctype

---

beams/beams/custom_scripts/job_requisition/job_requisition.js

-Remove employee_left filter to reflect recent change
-Employee status has to be marked as left in order to to select the employee in Job Requisition. Remove the filter status=left in Job Requisition (issue id----- [ISS-2025-00031] )
-Removed employee_left filter as it's no longer required
Job Requisition Doctype
- No.

Refactor:Remove unnecessary employee_left filter query

---

beams/beams/report/damage_history_report_for_assets/damage_history_report_for_assets.js
beams/beams/report/damage_history_report_for_assets/damage_history_report_for_assets.json
beams/beams/report/damage_history_report_for_assets/damage_history_report_for_assets.py

Created a Damage History Report for Assets
- Asset details such as location, assigned employee, and audit records.
- Repair details like description, cost, failure date, and repair status.
- Filters to refine results based on asset, location, audit ID, employee, repair ID, and repair status.
- A structured approach to merging audit and repair data, ensuring comprehensive asset tracking.
[Screencast from 19-02-25 10:24:30 AM IST.webm](https://github.com/user-attachments/assets/bd2c12a0-7311-4e20-8453-fa1e0f162741)
Damage History Report for Assets  report
- Chrome
- Opera Mini
- Safari

feat:Created a Damage History Report for Assets

---

beams/beams/custom_scripts/job_requisition/job_requisition.py

-Job Requisition is not auto setting in Job Opening([ISS-2025-00033])
-Assigned Job Requisition in Job Opening
-No.

fix:Set Job Requisition in Job Opening

---

beams/setup.py

This feature improves field behavior and permissions in the Job Requisition DocType by making certain fields mandatory or optional based on user roles and adjusting user permissions.
->The following changes were applied to the Job Requisition DocType:
Field Requirement Changes:
-     no_of_positions → Made Optional
-     expected_compensation → Made Optional, with a default value of 0.0
-     department → Made Mandatory
Dynamic Field Visibility & Mandatory Conditions:
-  expected_compensation:Mandatory only for HR Managers
Permission Changes:
- employee_left → Ignore User Permissions (Accessible to all users)
- requested_by → Ignore User Permissions (Accessible to all users)
Post the output screenshots, if a UI is affected or added due to this …

fix: Update fields in Job Requisition

---

beams/beams/doctype/shift_swap_request/shift_swap_request.py
beams/setup.py

Shift Assignments were not swapped upon approval of shift swap request.
- Chrome
- Opera Mini
- Safari

fix: Ensure shift assignment is swapped upon approval of shift swap request

---

beams/beams/doctype/beams_admin_settings/beams_admin_settings.json
beams/beams/doctype/beams_admin_settings/beams_admin_settings.py
beams/hooks.py

Configure Reminders for Asset Auditing in BEAMS Admin Settings and Send Notification.
If Asset Auditing Notification is checked ,Send Notification to users with "IT" role and Current asset owner
Modify BEAMS Admin Settings:
Added field named  "Asset Auditing Notification" (Check)
Added field named  "Notify After (Days)" (Int) (Display and Mandatory Depends on Asset Auditing Notification check)
Added field named  "Asset Auditing Notification Template" (Link/Email Template) (Display and Mandatory Depends on Asset Auditing Notification check)
If Asset Auditing Notification is checked in BEAMS Admin Settings, send notification based on the configuration. Send Notification to users with "Technical Store Head" role and Current asset owner
List out the areas affected by your code changes.(BEAMS …

feat: send asset auditing notification to Technical Store Head and Asset owner

---

beams/patches.txt
beams/patches/set_account_in_cost_subhead.py
beams/patches/set_company_in_budget_template.py

- Add patches to set company in Budget Template.
- Added patches to set company in Budget Template.
No.

feat: Add Patches to set company in Budget Template

---

beams/beams/custom_scripts/employee_onboarding/employee_onboarding.js
beams/beams/custom_scripts/employee_onboarding/employee_onboarding.py

-Exclude job applicants linked to employees or onboarding  
- Implemented a server-side function to fetch job applicants linked to employees or ongoing onboarding.  
- Updated form script to exclude these applicants from the selection dropdown.  
- Ensures that only unassigned job applicants can be chosen in Employee Onboarding.
No.

feat:Exclude job applicants already linked to an employee or onboarding

---

beams/beams/custom_scripts/budget/budget.js
beams/beams/doctype/division/division.json
beams/beams/doctype/revenue/revenue.js
beams/beams/doctype/revenue/revenue.json
beams/beams/doctype/revenue_category/revenue_category.js
beams/beams/doctype/revenue_category/revenue_category.json
beams/beams/doctype/revenue_category/revenue_category.py
beams/beams/doctype/revenue_category/test_revenue_category.py
beams/beams/doctype/revenue_group/revenue_group.js
beams/beams/doctype/revenue_group/revenue_group.json
beams/beams/doctype/revenue_group/revenue_group.py
beams/beams/doctype/revenue_group/test_revenue_group.py
beams/beams/doctype/revenue_template/revenue_template.js
beams/beams/doctype/revenue_template/revenue_template.json
beams/beams/doctype/revenue_template/revenue_template.py
beams/beams/doctype/revenue_template/test_revenue_template.py
beams/beams/doctype/revenue_template_item/revenue_template_item.json
beams/beams/doctype/revenue_template_item/revenue_template_item.py

- Create Revenue ,Revenue Template,Revenue Group and Revenue Category Doctypes.
- Create Child tables Revenue Account and Revenue Template Item.
- Add Region field in Division Doctype.
- Fetch Region in Budget from division.
- Fetch revenue accounts values when selecting revenue template in Revenue.
- Created Revenue ,Revenue Template,Revenue Group and Revenue Category Doctypes.
- Created Child tables Revenue Account and Revenue Template Item.
- Added Region field in Division Doctype.
- Fetches Region in Budget from division.
- Fetches revenue accounts values when selecting revenue template in Revenue.
[Screencast from 21-02-25 01:08:28 PM IST.webm](https://github.com/user-attachments/assets/1438eec6-dbf5-4ef2-a9b4-f6c0450f508c)
[Screencast from 21-02-25 01:12:05 PM …

feat: Create Revenue and Revenue Template doctype

---

beams/beams/custom_scripts/job_applicant/job_applicant.js
beams/beams/custom_scripts/job_applicant/job_applicant.py

-Update resume attachment validation to allow multiple file formats  
-Allow DOC file upload for resume attachment  
-Applicants should be able to upload files such as PDF, Excel, Word, etc.[ISS-2025-00042]
Updated both client-side and server-side validation to permit PDF, DOC, , XLS, and XLSX file formats for resume attachments.  
[Screencast from 24-02-25 01:21:53 PM IST.webm](https://github.com/user-attachments/assets/cf4958a7-d78f-42ae-856b-f65e341c5dee)
-Job Application Doctype
-Yes 

fix: Update resume attachment validation to allow multiple formats

---

beams/setup.py
beams/www/job_portal/job.html

-Added "No of Positions" field to Job doctype and displayed it in job portal  
-Applicants should be able to see the number of vacancies available(ISS-2025-00042)
- Added "no_of_positions" field (Int) after employment_type in Job Opening doctype 
- Updated job.html to show openings 
[Screencast from 24-02-25 03:53:13 PM IST.webm](https://github.com/user-attachments/assets/f8d840fa-454a-49ec-b311-5a9cc94158e9)
-Yes 

feat:Add No of Positions field to Job Opening doctype and job portal

---

beams/beams/custom_scripts/asset/asset.py
beams/beams/doctype/beams_admin_settings/beams_admin_settings.json
beams/hooks.py
beams/setup.py

-Need to Add fields Beams Admin Settings
-Need To Add Fields  Item 
- Send Notifications for Asset Auditing as set in BEAMS Admin Settings, overrided by individual settings in Items
-Added fields are  in beams admin settings  doctype
fields are asset_audit_notification (check),notifcation_frequency(Select),notification_template(Link),start_notification_from(Select)
-Add fields in item doctype
fields are asset_audit_notification (check),notifcation_frequency(Select),notification_template(Link),start_notification_from(Select
-Implement asset notification system with item-specific and default beam admin  settings
-Notification  sented the basics of notifcation_frequency(Select) and start_notification_from(select)
[Screencast from 25-02-25 02:37:10 PM …

    TASK-2025-00254 :Asset Auditing Periodic Notification

---

beams/beams/custom_scripts/training_event/training_event.js

Auto Fetch Trainer Name,Trainer Email,Supplier,Contact Number form Training program in training event
When Training Program is selected following fields are populated.
- Trainer Name 
- Trainer Email
- Supplier
- Contact Number
No
- Chrome

fix:Auto Fetch data  from Training program in training event

---

beams/beams/doctype/asset_return_checklist_template/asset_return_checklist_template.json
beams/beams/doctype/asset_transfer_request/asset_transfer_request.json
beams/beams/doctype/asset_transfer_request/asset_transfer_request.py
beams/beams/doctype/beams_admin_settings/beams_admin_settings.json
beams/setup.py

Need to: 
- Create Asset Movements and Stock Entries at the "Transfer" Action when moving from Approved to Transferred.
-  Add to Naming Series in Asset Return Checklist Template doctype.
-  Add "Asset Transfer Warehouse" field in Beams Admin Settings Doctype.
- Create Role Technical Store Head through Setup.py
- When Workflow Sate of Asset Transfer Request is Transferred, display the fields Asset Return Checklist Template and     Asset Return Checklist and make it mandatory to be filled in before Return Action.
-  Created Asset Movements and Stock Entries at the "Transfer" Action when moving from Approved to Transferred.
-  Added to Naming Series in Asset Return Checklist Template doctype.
-  Added "Asset Transfer Warehouse" field in Beams Admin Settings Doctype.
- Created  Role …

TASK-2025-00197:Created Asset Movements and Stock Entries at the "Transfer" Action when moving from Approved to Transferred.

---

beams/beams/doctype/asset_bundle/asset_bundle.js
beams/beams/doctype/asset_bundle/asset_bundle.py

- Assets and Asset Bundles that are already in an Asset Bundle cannot be selected in another
- Apply filters to the following fields:
Asset
Assets
Bundles
- Assets and Asset Bundles that are already part of an Asset Bundle cannot be selected for another
- Applied filters 
[Screencast from 27-02-25 10:50:23 AM IST.webm](https://github.com/user-attachments/assets/8a3f7556-ec65-4b1e-8ad3-91eb11c9ad0f)
No

feat: TASK-2025-00273 Applied Filter to Assets and Bundles in asset Bundle Doctype

---

beams/beams/custom_scripts/asset_movement/asset_movement.py
beams/hooks.py
beams/setup.py

Send notification to custodian for asset movement
Added new user id field and custodian field in asset movement doctype.
Setup notification (email notification &system notification) to new custodian when an asset movement  submitted.
- Chrome

feat: Notification to Custodian for Asset Movement

---

beams/beams/doctype/employee_checkin_permission/employee_checkin_permission.json

- Fetch Shift start time & shift end time from shift type
- Add fields Expected Arrival Time & Expected Leaving  Time based on Log Type
- Add field Reports To
- Chrome
- Opera Mini
- Safari

feat: Customize Employee Checkin Permission doctype

---

beams/beams/doctype/asset_transfer_request/asset_transfer_request.json
beams/beams/doctype/asset_transfer_request/asset_transfer_request.py
beams/beams/doctype/asset_transfer_request/test_asset_transfer_request.py

Need to: 
-  Validate Received By field In Asset Transfer Request Doctype.
- Create a Stock Entry Field in Asset Transfer Request Doctype.
- To ensure that a Stock Entry and Asset Movement are created only once,  need to perform a check before creating a  new stock entry and Asset movement.
-  Validated Received By field In Asset Transfer Request Doctype.
-  Created a Stock Entry Field in Asset Transfer Request Doctype.
-  Ensured that a Stock Entry and Asset Movement are created only once,  need to perform a check before creating a  new stock entry and Asset movement.
[Screencast from 28-02-25 01:50:54 PM IST.webm](https://github.com/user-attachments/assets/4ae4842d-2d57-4cf9-96b2-553b4f8bf36c)
Asset Transfer Request Doctype 
No. 

feat:Validated Received By field In Asset Transfer Request Doctype

---

beams/beams/doctype/security_patrol_log/security_patrol_log.json

Add a new field 'full name' in security patrol log doctype
Added  new field 'full name' in security patrol log doctype
List out the areas affected by your code changes. ( security patrol log doctype)
- Chrome
- Opera Mini
- Safari

feat:add full name field in security patrol log doctype

---

beams/beams/doctype/asset_bundle/asset_bundle.py

Need to Prevent updating an Asset Bundle if it is currently in a  non Returned Asset Transfer Request
- Need to Prevent updating an Asset Bundle if it is currently in a non Returned Asset Transfer Request
validation  applied non returned asset bundle asset transfer request only update the  returned asset transfer request via asset bundle.py
[Uploading Screencast from 28-02-25 10:29:40 AM IST.webm…]()
asset bundle and asset transfer request doctype
No 

TASK-2025-00252 : Prevents updating an Asset Bundle if it is currently in a  non Returned Asset Transfer Request

---

beams/beams/doctype/employee_checkin_permission/employee_checkin_permission.json
beams/setup.py

The 'Minimum Experience Required' field should be relocated from the 'Education and Qualification Details' section into Work Details section
The 'Relieving Date' should be displayed for the employee selected when the 'Request For' is set to 'Employee Replacement
'Minimum Experience Required' field  relocated from the 'Education and Qualification Details' section into Work Details section
Added field Relieving Date that is set when request for is Employee Replacement.
No
- Chrome

feat:Added field Relieving Date in Job Requisition

---

beams/beams/doctype/equipment_request/equipment_request.json
beams/beams/doctype/equipment_request/equipment_request.py

- Add field Priority in Equipment Request Doctype
- Create Asset Reservation Log once the document is submitted if the Request is for a future date (Required From > Current Datetime)
- Added field Priority in Equipment Request Doctype
- Created Asset Reservation Log once the document is submitted if the Request is for a future date (Required From > Current Datetime)
[Screencast from 01-03-25 12:54:36 PM IST.webm](https://github.com/user-attachments/assets/c932252c-4604-47ea-bfc5-0e789081494f)
Asset Reservation Log
No

feat: TASK-2025-00281 Created Asset Reservation Log once the equipment request is submitted

---

beams/beams/doctype/asset_return_checklist/asset_return_checklist.json
beams/beams/doctype/asset_transfer_request/asset_transfer_request.py

- Modify Asset Return Checklist Table in Asset Transfer Request and Added the Assets and items in the Asset Return   Checklist
-  Checkboxes: Returned, Consumed, Damaged, Missing/Lost, Reassigned
Remarks (Small Text, mandatory for Damaged & Missing/Lost)
Automated Checklist Population:
-  When the status is Transferred, the checklist auto-fills with Assets, Items, and Template Items
Workflow Validation
/home/avishna/Videos/Screencasts/Screencast from 01-03-25 01:06:16 PM IST.webm
/home/avishna/Videos/Screencasts/Screencast from 01-03-25 01:08:31 PM IST.webm
- Asset Return Checklist
- Chrome
- Opera Mini
- Safari

feat: TASK-2025-00271 - added the Assets and items in the Asset Return Checklist

---

beams/beams/custom_scripts/job_applicant/job_applicant.js
beams/beams/custom_scripts/job_applicant/job_applicant.py

Add the 'Copy to Clipboard' functionality for magic link in Job Applicant
Added 'Copy to Clipboard' functionality for magic link in Job Applicant
[Screencast from 15-01-25 04:01:33 PM IST.webm](https://github.com/user-attachments/assets/38a6ea67-c588-48b3-a8fd-b540f68a5e3a)
In Job Applicant doctype while clicking the "send magic link" button that magic link is copied to the Clipboard 
No

TASK-2025-00019:Added Copy to Clipboard functionality for magic link in Job Applicant

---

beams/beams/custom_scripts/budget/budget.js
beams/beams/doctype/budget_template/budget_template.js
beams/setup.py

- Remove column break in Budget
- Add confirmation message in Budget Account.
- Removed column break in Budget.
- Added confirmation message in Budget.
No.

fix: Remove Column Break In Budget

---

beams/beams/custom_scripts/attendance/attendance.py
beams/beams/doctype/beams_hr_settings/beams_hr_settings.json

- Need to change the code logic for email template  and improve notification  handling change .
- Need to add the fields in the beams hr settings also change the allignment and description of fields 
- changed the code logic for email template  and improve notification  handling change .
- change the hard coding email template  to default .
- added the fields in beams hr settings Absence Reminder Template(link-email template),Leave Application Reminder Duration(int)
-Leave Application Template(link-email template),changed the description on Absence Reminder Duration
-notification sent for reporter where employee have absence without leave application it is sended based on  Absence Reminder Template(link-email template), and Absence Reminder Duration 
-notification sent employee for …

fix: absence reminder logic to use email templates and improve notifcation handling

---

beams/beams/custom_scripts/job_requisition/job_requisition.js
beams/beams/custom_scripts/job_requisition/job_requisition.py
beams/hooks.py

Validate Expected By field in Job Requisition such that only future dates can be selected.
Validation added as only future dateds are selected.
Job Requisition.
No
- Chrome

feat:Added Validation for Expected By field in Job Requisition

---

beams/beams/custom_scripts/job_requisition/job_requisition.py
beams/setup.py

- Added a new fields in job requisition and that field is should be traversed to Job Opening.doctype
- changed the label names in the job applicant  doctype
1. added field Publish on Job Opening   permlevel is setted to hr manager and ceo in job requistion doctype traversed in to job opening 
2. changed the label names in job applicant fields are Willing to Work in the Selected Location?,Can i take Reference Now?,Agency Details  (if temporary or contractual)"
[Screencast from 03-03-25 01:55:28 PM IST.webm](https://github.com/user-attachments/assets/7649941f-af71-42c5-812e-bdd791d15621)
[Screencast from 03-03-25 02:00:12 PM IST.webm](https://github.com/user-attachments/assets/bd2b55db-ce5e-4c48-a1c9-31d10541b94c)
job applicant,  job requsition and job opening doctype
No. 

 TASK-2025-00289 : Added the fields in job requistion

---

beams/beams/custom_scripts/asset/asset.py
beams/beams/doctype/asset_bundle/asset_bundle.js
beams/beams/doctype/asset_bundle/asset_bundle.json
beams/beams/doctype/asset_bundle/asset_bundle.py
beams/beams/doctype/asset_transfer_request/asset_transfer_request.js
beams/beams/doctype/asset_transfer_request/asset_transfer_request.json
beams/hooks.py
beams/setup.py

- Implement Adding Assets and Bundles using QR Code
- Automated QR Code Generation
- The function generate_asset_qr is triggered when an asset is created.
- It checks if a QR code already exists; if not, it generates a new one.
- QR Code Scanning for Asset Bundle:
- Implemented a QR scanner in asset_bundle.js to scan asset QR codes and add them to the asset bundle.
-  Scanned assets are validated before being added to prevent duplicates.
-  Updated Hooks (hooks.py)
- Registered generate_asset_qr on after_insert and generate_asset_details_qr on on_submit for the Asset DocType.
- Modified Asset Bundle Doctype (asset_bundle.json)
-  Added a new field scan_qr_code to facilitate scanning directly from the Asset Bundle form.
- asset
- asset bundle
Mention Yes or No. If Yes, provide the …

feat:     TASK-2025-00251-Implement Adding Assets and Bundles using QR Code in asset bundle

---

beams/beams/custom_scripts/job_requisition/job_requisition.js
beams/beams/custom_scripts/job_requisition/job_requisition.py
beams/setup.py

- Hide field department and remove mandatory
- Fetch the request by department to the job opening department
- Set No of positions as 1 and read only on requested for is for employee replacement
- Set License type as Mandatory
- Rearrange the field Is shift Work Needed
- Create Job opening connection in Job requisition
- The field department set as hidden and removed mandatory
- Department field in job opening is fetched from the department of employee selected in requested by
- No of positions is set as 1 and read only on loading the page with Employee replacement 
- License type set as mandatory
- Is Shift Work Needed
- Job opening connection is set job requisition
[Screencast from 02-03-25 09:16:10 PM IST.webm](https://github.com/user-attachments/assets/c671e69c-6f72-4c99-9f3b-1c76d80e2 …

fix : Issue fixing

---

beams/beams/custom_scripts/job_applicant/job_applicant.js
beams/hooks.py

- Create/View button in Job Applicant should only create once documents are uploaded
- Hooks are a mess
- Disabled suspicious validation for now
- Added a check for status in Job Applicant for the button
- Reordered Document Events Hooks
- Job Applicant
- Inteview
No
- Chrome - Yes
- Opera Mini
- Safari

fix: create/view button in job applicant and hooks

---

beams/beams/report/budget_comparison_report/budget_comparison_report.js
beams/beams/report/budget_comparison_report/budget_comparison_report.py

- Add Cost Head,Cost Subhead and Cost Category In Budget Comparison Report.
- Added Cost Head,Cost Subhead and Cost Category In Budget Comparison Report.
- Added cost Head,cost subhead,cost category filters in report.
[Screencast from 04-03-25 09:43:40 AM IST.webm](https://github.com/user-attachments/assets/8454cfa6-eacc-48b1-abf5-046d4b4f8628)
No.

feat: Update Budget Comparison Report

---

beams/beams/doctype/asset_transfer_request/asset_transfer_request.js
beams/beams/doctype/vehicle_incident_record/vehicle_incident_record.js
beams/beams/doctype/vehicle_incident_record/vehicle_incident_record.py

Add Validation for future dates on offense date in Vehicle Incident Record.
Apply filter for transferred assets in asset transfer request doctype
Added Validation for future dates on offense date in Vehicle Incident Record.
Applied filter for transferred assets in asset transfer request doctype
List out the areas affected by your code changes.( vehicle incident record and asset transfer request doctype)
- Chrome
- Opera Mini
- Safari

fix: validation for offense date in vehicle incident record , and filter for transferred asset in asset transfer request doctype

---

beams/beams/doctype/required_items_detail/required_items_detail.json
beams/beams/doctype/transportation_request/transportation_request.json

Issued Quantity in Equipment Request change to read only
Reason for rejection change to read only in Transportation Request
Issued Quantity in Equipment Request changed to read only
Reason for rejection change to read only in Transportation Request
No.of travallers default set to one
No

fix: Fields changed to Read only

---

beams/beams/doctype/local_enquiry_report/local_enquiry_report.json
beams/setup.py

- Remove permlevel for experience field in Job Applicant
- Add 'In Years' to field Label 'Experience'
- Put is_work_shift_needed checkbox  before travel_required checkbox in Job Requisition
- Put title for Local Enquiry Report
Job Applicant-permlevel
Job Requisition-field arrangement
- Chrome
- Opera Mini
- Safari

fix: Remove permlevel for experience field in Job Applicant

---

beams/beams/custom_scripts/interview/interview.py
beams/hooks.py

- Updates the Job Applicant's applicant_interview_rounds table when a new Interview is created
-  **Ensures Automatic Update**: Updates the `applicant_interview_rounds` table in the **Job Applicant** Doctype when a new **Interview** is created.  
-  **Checks for Linked Job Applicant**: If the Interview is not linked to a **Job Applicant**, the function exits early.  
-  **Prevents Duplicate Rounds**: Fetches existing interview rounds and skips adding if the round already exists.  
-  **Appends New Interview Round**: Adds the new **interview round** and its **status** to the Job Applicant’s record.  
-  **Saves Changes**: Updates the Job Applicant document while **ignoring permission restrictions**.
[Screencast from 04-03-25 01:21:17 PM …

feat: TASK-2025-00299 - Updates the Job Applicant's applicant_interview_rounds table when a new Interview is created

---

beams/beams/custom_scripts/interview/interview.js
beams/beams/custom_scripts/interview/interview.py
beams/beams/doctype/interview_question_result/interview_question_result.json
beams/hooks.py
beams/setup.py

Added a field for Job Applicant Email id in Interview doctype & made it hidden.
Hidden  'Mark as Accepted' message that appears after submitting interview.
Modified Score field as Score (Out of 10) in feedback dialog box.
Interview doctype
Job Applicant doctype
No
- Chrome

TASK-2025-00291:Override Interview class to hide a message.

---

beams/beams/custom_scripts/budget/budget.js
beams/beams/doctype/finance_group/finance_group.js
beams/beams/doctype/finance_group/finance_group.json
beams/beams/doctype/finance_group/finance_group.py
beams/beams/doctype/finance_group/test_finance_group.py
beams/setup.py

- Create doctype Finance group.
- Add Finance group in Department and Budget.
- Created Finance Group doctype.
- Added Finance Group In budget and department.
No.

feat: Create Doctype Finance Group

---

beams/beams/custom_scripts/interview/interview.js
beams/beams/custom_scripts/interview_feedback/interview_feedback.py

-Add validation for questions table 
- Validate that the score in the `questions` table is between 0 and 10.  
- Ensure `rating` is calculated as `score / 10`, similar to `skill_assessment`.  
- Raise an error if an invalid score is entered.  
-Interview Doctype
-Interview Feedback Doctype
-No.

    TASK-2025-00309:validation for Question Assessment in Interview Feedback

---

beams/beams/custom_scripts/attendance_request/attendance_request.py
beams/hooks.py

Need a validation for the to_date in attendance request doctype
- applied validation that if to_date is cannot be future date always today or before 
Attendence regularisation doectype
No.

TASK-2025-00313:validation for to_date in the Attendance Request doctype

---

beams/setup.py

customized Shift Assignment doctype
Add field user id in Shift Assignment
Shift Assignment
- Chrome
- Opera Mini
- Safari

feat:customized Shift Assignment doctype

---

beams/beams/custom_scripts/employee/employee.py
beams/hooks.py

This Feature validates Offer Date and Confirmation Date such that both these field cannot past date values and also offer date cannot be after Confirmation Date.
Server-side validation to the Employee doctype, ensuring:
-Offer Date must be a future date.
-Confirmation Date must be a future date.
- Confirmation Date must be after Offer Date.
This prevents incorrect or past dates from being saved, ensuring data consistency.
Employee doctype.
No
- Chrome

feat:Added validation for Offer Dates.

---

beams/beams/doctype/shift_swap_request/shift_swap_request.json

make posting field read only to prevent entering future dates
shift swap request
- Chrome
- Opera Mini
- Safari

feat: make posting date read only in shift swap request

---

beams/beams/custom_scripts/employee_onboarding/employee_onboarding.js
beams/beams/custom_scripts/employee_onboarding/employee_onboarding.py

-Incorrect filter on Employee onboarding
-exclude active employees with onboarding from job applicant field
-Updated filtering logic to exclude job applicants who are linked to active employees and have an Employee Onboarding record.
-Ensured that other job applicants remain visible in the dropdown.
-No

feat:Exclude active employees with onboarding from job applicant field

---

beams/beams/custom_scripts/job_offer/job_offer.js
beams/beams/custom_scripts/job_offer/job_offer.py
beams/hooks.py

- Need to apply validation on the field ctc in the job offer doctype
-Applied validation on the field ctc where cannot be save a  Negative Value in job offer doctype via hooks.py and job offer.py job offer.js
job offer doctype
No. 

    TASK-2025-00331:Validation in ctc in the job offer doctype

---

beams/beams/custom_scripts/training_feedback/training_feedback.js
beams/hooks.py

Apply filter in Training feedback
- When the Training Event is Cleared
- The Employee filter is reset (shows all employees).
- The Employee field is cleared to avoid invalid selections.
- When a Training Event is Selected
- The script fetches employee records from the selected Training Event using frappe.db.get_doc().
- Extract the Employee IDs from the child table (employees).
- A filter is applied to show only those employees in the dropdown.
[Screencast from 07-03-25 12:39:41 PM IST.webm](https://github.com/user-attachments/assets/97eba90e-cbb3-4566-9ae8-0e446f3e44d5)
put screenshots (optional)
- Chrome
- Opera Mini
- Safari

feat:     TASK-2025-00330 - Apply filter in Training feedback

---

beams/beams/doctype/shift_swap_request/shift_swap_request.py
beams/setup.py

- Instead of cancelling the already existing shift assignment and creating new , Just change the date in existing shift assignment
- Create new shift assignment for swapped days 
- Check all 3 cases that 
^ Swapped dates between the original start date and end date
^ Swapped start date == Original start date 
^ Swapped end date == Original end date 
- Instead of cancelling the date is changed to particular period
- New shift assignment created for swapped period
- All 3 cases are done 
[Screencast from 10-03-25 10:08:14 AM IST.webm](https://github.com/user-attachments/assets/f9ac4a42-53ae-46ed-9b5c-9f0b18ffefe3)

fix : Instead of cancelling the shift assignment change in exist

---

beams/beams/custom_scripts/job_applicant/job_applicant.js

Update interview status options
Show 'Send Magic Link' button after Pending document upload
Job Applicant Doctype
Yes 

fix:Refactor status options by removing 'Pending Document Upload

---

beams/beams/custom_scripts/employee/employee.js
beams/beams/custom_scripts/training_event/training_event.js

Need to arrange the button in create group button in the employee doctype
Need hide the get employees button when the event status become completed the in the Training Event doctype 
1. Arranged the button group button create  order the event button is first and Training event in secound . via employee.js 
2. hidden the get employees button inthe training event . if the event status become completed then the get employees button is hidden via training event.js
[Screencast from 10-03-25 04:12:22 PM IST.webm](https://github.com/user-attachments/assets/ecff4764-eb6f-471e-b54f-bb0d979314e8)
employee and training event doctype
No

TASK-2025-00335:Hide the button when status become completed in Training Event doctype

---

beams/beams/custom_scripts/customer/customer.py
beams/beams/custom_scripts/lead/lead.js
beams/beams/custom_scripts/opportunity/opportunity.js
beams/beams/custom_scripts/sales_invoice/sales_invoice.js
beams/beams/custom_scripts/sales_order/sales_order.js
beams/hooks.py
beams/setup.py

- Hide Custom Buttons from Opportunity except customer.
- Prevent Duplicate Customer Creation
- Customize Release Order Doctype.
- Change label of Item Code to Service Item in Release Order
- Customize Quotation Item Child table.
- Hide Custom Buttons from Sales Order.
- Customize Sales Order doctype.
- Hide Custom buttons from Sales Invoice.
- Hide Add to prospect button from Lead.
- Custom buttons were hidden from the Opportunity doctype except for the Customer button.
- Duplicate customer creation was prevented.
- The Release Order doctype was customized.
- The label of Item Code was changed to Service Item in the Release Order doctype.
- The Quotation Item child table was customized.
- Custom buttons were hidden from the Sales Order doctype.
- The Sales Order doctype was customized.
- …

fix: Hide Custom Buttons from sales order,sales invoice and Opportunity

---

beams/beams/custom_scripts/quotation/quotation.js

-Set Executive field if user has Employee role
-Assign the "executive" field if it is empty
-Fetch the Employee name based on the logged-in user.
-Ensure the user has the "Employee" role before fetching
[Screencast from 12-03-25 09:58:18 AM IST.webm](https://github.com/user-attachments/assets/777ca529-bbbb-4c39-9fa2-b7c4782dffc9)
[Screencast from 12-03-25 10:00:39 AM IST.webm](https://github.com/user-attachments/assets/635d9b6c-bc21-473b-a424-0b804ed7730d)
-Release Order
- No. 

    TASK-2025-00346:Fetch and set Executive field for Employee users in Release Order

---

beams/beams/custom_scripts/lead/lead.js

Remove the  prospect dialog box that appears when Oppurtunity created from Lead.
The default button was removed and added a new button under Create group in Led that maps to Oppurtunity.
Lead doctype.
No
- Chrome

feat:Remove prospect dialog box that appears when Oppurtunity created from Lead.

---

beams/beams/doctype/local_enquiry_report/local_enquiry_report.py

1.need to currently the status of Local Enquiry Report become overdue even if enquiry completion date does not exceed expected completion date
1. change the logic that status become not be overdue even without exceeds the enquiry_completion_date than the expected_completion_date
- status become overdue when only the enquiry_completion_date exceeds the expected_completion_date
[Screencast from 12-03-25 03:04:37 PM IST.webm](https://github.com/user-attachments/assets/9a439ca6-7e13-4958-99c0-eaa0cbfa4121)
[Uploading Screencast from 12-03-25 03:09:01 PM IST.webm…]()
local enquiry report
No

    TASK-2025-00338: changed logic for update status for local enquiry report

---

beams/beams/custom_scripts/quotation/quotation.js
beams/setup.py

Customise Release Order Doctype
- Fetch Region In relase Order when selecting customer..
- Hide Coupon Code field in Release Order.
Release Order.
- Chrome
- Mozilla Firefox -Yes
- Opera Mini
- Safari

feat:Customise Release Order Doctype

---

beams/beams/custom_scripts/appraisal/appraisal.js

Hide the "New Feedback" button for the employee being appraised in the Appraisal form. Only other users should be able to see the button.
- Fetched the logged-in user’s linked Employee record.
- Checked if the logged-in user is the same as the employee in the Appraisal form.
- Added the "New Feedback" button only if the logged-in user is not the appraised employee.
- An appraisal is created for employee Diya
- when the Employee Diya logged-in,she cannot see New Feedback button
Appraisal form UI
User session handling (to determine the logged-in employee)
Button visibility logic
- Chrome
- Opera Mini
- Safari

Refactor: Simplified logic to conditionally display the 'New Feedback' button in Appraisal

---

beams/beams/custom_scripts/quotation/quotation.js

fixed syntax error in Release Order
- JavaScript uses && instead of and for logical operations.
- Release Order
- Chrome
- Opera Mini
- Safari

fix:fixed syntax error in Release Order

---

beams/beams/custom_scripts/budget/budget.js
beams/beams/doctype/budget_template/budget_template.json
beams/beams/doctype/division/division.js
beams/beams/doctype/division/division.json
beams/beams/doctype/division/division.py

- Remove division head,division head user,cost center and region from division doctype.
- Add fields in Budget Template doctype.
- Fetch cost center and region from selected budget template in Budget.
- Removed division head,division head user,cost center and region from division doctype.
- Added fields in Budget Template doctype.
- Fetches cost center and region from selected budget template in Budget.
No.

feat: Update Division and Budget Template Doctype

---

beams/beams/custom_scripts/appraisal/appraisal.js
beams/beams/custom_scripts/appraisal_template/appraisal_template.js
beams/beams/custom_scripts/job_offer/job_offer.js
beams/beams/custom_scripts/job_offer/job_offer.py
beams/hooks.py
beams/setup.py

1. need to hide the fields in child table  fielld names employee feedback rating appraisal template  doctype
2. need to add list view for the child table  field names employee feedback rating appraisal doctype 
3.need to arrange the field order in employee feedback rating child table 
4. Need to validate the ctc field not negative value in job offer doctype
1.hid the fields in child table  field names employee feedback rating appraisal template  doctype
- hidden the fields marks and rating the company_rating_criteria ,department_rating_criteria, rating_criteria  in the appraisal doctype via appraisal_template .js and hooks.py
2. added add list view for the child table  field names employee feedback rating appraisal doctype 
-added list view  for the fields marks and rating the …

TASK-2025-00345: hidden the child table fields in appraisal template

---

beams/beams/custom_scripts/budget/budget.js
beams/beams/doctype/budget_template/budget_template.json

- Add confirmation message in Budget when changing budget template.
- Remove Budget set code from Budget.
- Added confirmation message in Budget when changing budget template.
[Screencast from 13-03-25 04:42:17 PM IST.webm](https://github.com/user-attachments/assets/14dc2dc8-b28a-4097-b23a-a01373724296)
No.

fix: Add Confirmation Message In Budget.

---

beams/beams/custom_scripts/budget/budget.py
beams/beams/report/detailed_budget_allocation_report/detailed_budget_allocation_report.py
beams/hooks.py
beams/setup.py

Showing non-INR budget amounts in INR in a separate field.
Added the required fields and set the converted amount in the new field
Company, Budget Accounts—Customization
Noo
- Chrome : Yes
- Opera Mini
- Safari

Budget currency conversion

---

beams/beams/custom_scripts/budget/budget.js

- Show/hide budget account fields based on user roles (HOD & HR Manager)
- Displayed Budget account child tables based on user roles(HOD & HR Manager)
[Screencast from 17-03-25 10:40:28 AM IST.webm](https://github.com/user-attachments/assets/81f8ee73-5b67-468d-96f6-bb7e9629f4b8)
No.

feat: Show/hide budget account child tables based on user roles (HOD & HR Manager)

---

beams/beams/doctype/technical_request/technical_request.json

Change Required Employee field to not editable when workflow state goes to Approved
Changed Required Employee field to not editable when workflow state goes to Approved
No

TASK-2025-00377: Changed Required Employee field to not editable

---

beams/setup.py

- Update label of budget accounts.
- Changed Budget Accounts label to Budget Accounts(HR Overheads)
No.

fix: Changed label of Budget Accounts in Budget

---

beams/beams/doctype/employee_travel_request/employee_travel_request.py
beams/beams/doctype/equipment_acquiral_request/equipment_acquiral_request.py
beams/beams/doctype/equipment_request/equipment_request.py
beams/beams/doctype/technical_request/technical_request.py
beams/beams/doctype/transportation_request/transportation_request.py

Validate the Reason for Rejection is not filled in when approving and it is filled in when rejecting wherever necessary in BEAMS
The method checks if the document's workflow state is set to "Approved" and if the field reason_for_rejection is filled.
If both conditions are true, the system raises an error using frappe.throw(), preventing the document from being approved while a rejection reason exists.
- Chrome

feat: validation for 'reason for rejection' in all doctypes

---

beams/setup.py

wrong currency appearing in Approved Budget field of Project
- wrong currency is updated in the approved budget field  in project doctype
- removed option for currency field approved budget and estimated_budget
[Screencast from 17-03-25 01:57:00 PM IST.webm](https://github.com/user-attachments/assets/239f6fc1-bdb4-4515-afa8-299931cb5e7b)
Project
No

    TASK-2025-00376: fixed  wrong currency in the field in the project doctype

---

beams/beams/doctype/external_resource_request/external_resource_request.js

Create Service Purchase order from External Resource Request.
Added a button in External Resource Request to  Create Service Purchase Order and on action of this button    dialog box appears and on submission of this popup Service Purchase Order is created.
External Resource Request
Purchase Order 
No
- Chrome

TASK-2025-00381:Created Service Purchase Order from External Resource Request

---

beams/beams/custom_scripts/asset_movement/asset_movement.py
beams/beams/custom_scripts/project/project.js
beams/beams/custom_scripts/purchase_order/purchase_order.py
beams/setup.py

- added Required Items child table  in Project
- added Required Items child table  in Project
- The "Item" field in the dialog only shows items that are listed in the required_items table
- Add a table in Project to Required Items in Project. (Use the same table as in the equipment request.)
- Only items from required_items are selectable.
- Once an item is selected, it will no longer be available in the dropdown.
- If an item is removed from the table, it becomes available again.
- update Required Items Detail in project when Purchase Order and asset movement is submitted
- changed issued quantity and acquired quantity
[Screencast from 18-03-25 11:40:46 AM IST.webm](https://github.com/user-attachments/assets/3de3dd24-0b28-4cd3-b490-6a01101daac4)
[Screencast from 17-03-25 01:40:44 PM …

feat:     TASK-2025-00382 - added Required Items in Project

---

beams/beams/custom_scripts/project/project.py
beams/beams/doctype/technical_request/technical_request.js
beams/beams/doctype/technical_request/technical_request.json
beams/beams/doctype/technical_request/technical_request.py
beams/beams/doctype/technical_request_details/technical_request_details.json
beams/beams/doctype/technical_request_details/technical_request_details.py

Feature Description:
- Modify the doctype Technical Request 
- Create a Chid table technical request details and add to technical request
- Fetch the pop up child table in project to the new child table added in technical request
- According to the no of employees duplicate the row in technical request
- Employees can be assigned only  by respective department head
- Approve and Reject can be done When all row of employee is assigned
- Give filter to employee field
Solution Description:
- Modified Technical Request
- Created Child table and Added to Doctype
- Fetched the pop up child table with duplication to the new child table 
- Employee row can only assigned or changed by respective hod
- Approve or reject can be done once all employees are assigned
- Filter for employee 
Output: …

TASK-2025-00383

---

beams/beams/doctype/revenue_account/revenue_account.json
beams/beams/doctype/revenue_budget/revenue_budget.js
beams/beams/doctype/revenue_budget/revenue_budget.json
beams/beams/doctype/revenue_budget/revenue_budget.py
beams/beams/doctype/revenue_budget/test_revenue_budget.py
beams/beams/doctype/revenue_centre/revenue_centre.js
beams/beams/doctype/revenue_centre/revenue_centre.json
beams/beams/doctype/revenue_centre/revenue_centre.py
beams/beams/doctype/revenue_centre/test_revenue_centre.py

- Update Revenue Doctype.
- Renamed Revenue Doctype in to Revenue Budget.
- Customized Revenue Account child table.
- Created master doctype Revenue Centre.
- Applied filter in account of revenue budget based on company.
No.

feat: update Revenue Budget doctype

---

beams/beams/custom_scripts/project/project.js

Need to Hide the Asset Movement Button in the Required Items child table in project doctype
This function hides the asset_movement button in the required_items child table by dynamically updating its hidden property and refreshing the grid to apply the change
- Chrome

fix: hide asset movement button in project

---

beams/beams/doctype/program_request/program_request.js
beams/beams/doctype/program_request/program_request.py

Need to: Fix the type error issue when Generates Revenue is checked in Program Request Doctype
Fixed the type error issue when Generates Revenue is checked in Program Request Doctype
[Screencast from 20-03-25 10:12:58 AM IST.webm](https://github.com/user-attachments/assets/e96577ce-55fb-4fa8-8a2c-4aedeb0cbb94)
Program Request Doctype
No. 

Fixed the type error issue when Generates Revenue is checked in Program Request Doctype

---

beams/beams/doctype/equipment_acquiral_request/equipment_acquiral_request.js

- If none of the item in required item child table has service item in doctype equipment acquiral request then show no service item in create button 
- If any of them has only fetch the service item 
- if quantity and acquired quantity of all rows are equal then hide the button create 
- If all row.item has no service item then shows no service item'
- If any of them has it fetches the service item 
- If all row.quantity and acquired quantity is same then no need of button create 
[Screencast from 19-03-25 04:09:40 PM IST.webm](https://github.com/user-attachments/assets/18a4f732-220a-4c4b-a158-260e479122a6)

TASK-2025-00405 : Hide service item table if there is no service item in item

---

beams/beams/doctype/batta_claim/batta_claim.js

Restrict selection of Origin and Destination in Work Detail if not set in Batta Claim.
Disabled Origin and Destination in Work Detail until they are not set in Batta Claim
Yes 

    TASK-2025-00419:Restrict selection of Origin and Destination in Work Detail if not set in Batta Claim.

---

beams/beams/doctype/batta_claim/batta_claim.js

Need to: Fix the issue "No of Days is not reflecting when Batta Type is External in Batta Claim".
Fixed the issue "No of Days is not reflecting when Batta Type is External in Batta Claim".
[Screencast from 20-03-25 02:10:35 PM IST.webm](https://github.com/user-attachments/assets/84751f0f-53c9-490c-9217-c99a4b68d0f4)
Batta Claim Doctype
Yes 

TASK-2025-00420: Fixed the issue "No of Days is not reflecting when Batta Type is External in Batta Claim".

---

beams/beams/doctype/batta_claim/batta_claim.py

Fixed incorrect journal entry postings for Expense and Payable accounts in Batta Claim Approval.
- Expense account now records the amount in credit.
- Payable account now records the amount in debit.
- remove party and party type from expense account
- created a batta claim and Approved it
- ![image](https://github.com/user-attachments/assets/49003fa3-21cb-48b6-9811-01ac748d8a42)
-Creation of Journal Entry on the approval of batta claim
Journal Entry creation from batta claim Approval
- Chrome
- Opera Mini
- Safari

fix: Correct Debit/Credit Entries for Expense & Payable Accounts

---

beams/beams/custom_scripts/voucher_entry_type/voucher_entry_type.py
beams/beams/doctype/batta_claim/batta_claim.json
beams/hooks.py
beams/setup.py

Restrict Multiple Accounts selection for a Single Company in Voucher Entry Type.
This update ensures that a company in Voucher Entry can have multiple accounts, but the same account cannot be assigned more than once to the same company.
Added validation function:
-     Uses a dictionary to track accounts for each company.
-     Throws an error if the same account is added twice for the same company.
Updated hooks.py to call this function during validation.
Voucher Entry Type
No
- Chrome

TASK-2025-00422:Validated multiple account selection for the same company.

---

beams/beams/doctype/employee_travel_request/employee_travel_request.js
beams/beams/doctype/employee_travel_request/employee_travel_request.py
beams/beams/doctype/transportation_request/transportation_request.json

1. make the field mandatory  field in  Transportation Request  doctype
2.  Need Validate "Expected Check-in Time"and "Expected Check-out Time" in Employee Travel Request doctype
3. Total Days has to be one if travel ends in the same day
1. make mandatory  field Requirements  in transportation request doctype
2. validated the   "Expected Check-in Time"and "Expected Check-out Time" in Employee Travel Request doctype
if the expected checkout time is less than Expected Check-in Time in employee travel request doctype
3. Total Days has to be one if travel ends in the same day
- if start_date and end_date are in same day make the total days  become one 
- and if the start_date and end_date are removed the referesh the field total days (read only) in employee traavel request doctype
[Screencast …

fix: Validated the expected checkin time and expected checkout time in employee travel request

---

beams/beams/doctype/department_cost_center/department_cost_center.json
beams/beams/doctype/department_cost_center/department_cost_center.py
beams/beams/overrides/queries.py
beams/hooks.py
beams/setup.py

This feature enhances the cost center search function by applying user-based filtering. It ensures that users only see cost centers they are permitted to access based on their assigned Bureau or Department.
- The feature follows the user permission structure in Frappe to restrict cost center selection:
- If a user has permissions for a Bureau, fetches cost centers linked to the Bureau.
- If no Bureau permissions exist, fetches cost centers linked to the user's permitted Departments. 
- A SQL query dynamically filters cost centers based on user permissions, ensuring only relevant records are shown.
- Implemented a Frappe whitelist function get_cost_center_list to filter cost centers dynamically. 
- Retrieves user permissions for Bureau or Department from User Permission.
- Uses Bureau …

feat: cost center filter

---

beams/beams/custom_scripts/voucher_entry/voucher_entry.js
beams/beams/custom_scripts/voucher_entry/voucher_entry.py
beams/beams/doctype/petty_cash_request/petty_cash_request.js
beams/beams/doctype/petty_cash_request/petty_cash_request.json

Add a field named "Reason" in the Petty Cash Request dialog in Voucher Entry and in the Petty Cash Request DocType. Ensure that its value is fetched from the dialog into the Petty Cash Request DocType.
Additionally, apply validation for the Requested Amount in this dialog, and implement the same validation in the Petty Cash Request DocType.
Added the requested fields and Applied validation
Added field Reason in Petty Cash Request dialog
Validation for Requested Amount field in Petty Cash Request dialog
Created Petty Cash Request document up on the submission of dialog and ensured that all values are fetched from the dialog into the Petty Cash Request DocType.
Validation for Requested Amount field in Petty Cash Request doctype
Petty Cash Request …

fix: Customize petty cash request doctype & dialog

---

beams/beams/doctype/employee_travel_request/employee_travel_request.py

Fix TypeError & Optimize Date Handling in total_days_calculate
- Fixed TypeError by properly handling both str and datetime objects.
- Ensured start_date and end_date are converted correctly to date format.
- Improved readability and efficiency of date calculations.
- Guaranteed total_days is always at least 1, even for same-day travel.
Employee Travel Request
- Chrome
- Mozilla Firefox -yes
- Opera Mini
- Safari

fix: TASK-2025-00473: Fix TypeError & Optimize Date Handling in total_days_calculate

---

beams/beams/doctype/bureau_trip_sheet/bureau_trip_sheet.js
beams/beams/doctype/bureau_trip_sheet/bureau_trip_sheet.json
beams/beams/doctype/bureau_trip_sheet/bureau_trip_sheet.py
beams/beams/doctype/bureau_trip_sheet/test_bureau_trip_sheet.py
beams/beams/doctype/trip_details/trip_details.json
beams/beams/doctype/trip_details/trip_details.py
beams/setup.py

--create Create Doctype for Bureau Trip Sheet
--Create Trip Details Child table 
--Add OT Batta field with dependency on is_transporter
--Added Bureau Trip Sheet Doctype 
--Trip Details child table 
--OT Batta field conditional on is_transporter
--Update Bureau Trip Sheet with supplier filtering, list view, and standard filter enhancements
-- No. If Yes, provide the appropriate explanation.

feat:Create Doctype for Bureau Trip Sheet

---

beams/setup.py

Make Total Amount field read only in Voucher Entry
Made Total Amount field read only in Voucher Entry
Voucher Entry
- Chrome
- Opera Mini
- Safari

feat: Make Total Amount field read only in Voucher Entry

---

beams/beams/doctype/employee_travel_request/employee_travel_request.js
beams/beams/doctype/employee_travel_request/employee_travel_request.py

- Trigger total_days_calculate on end_date change
**Trigger total_days_calculate on end_date change**  
- Added `end_date` event to call `total_days_calculate`.  
- Ensures `total_days` updates dynamically when `end_date` is modified.  
- Improves user experience by recalculating travel days in real-time.
[Screencast from 25-03-25 02:20:47 PM IST.webm](https://github.com/user-attachments/assets/52da6aa1-e232-4fbf-bba5-f0aad9e8805a)
- Employee Travel Request
- Chrome
- Opera Mini
- Safari

feat:Trigger total_days_calculate on end_date change

---

beams/patches.txt
beams/patches/delete_employee_fields.py

This patch removes the "bureau" field from the Employee doctype by deleting the associated custom field entry in the database.
The field "bureau" was identified as obsolete and is no longer required in the Employee doctype.
The patch ensures database cleanup to prevent unnecessary data clutter.
The following script will execute during migration:
-     It iterates over a list of fields to be removed.
-     It checks if the field exists in the Custom Field table.
-     If it exists, it deletes the field and commits the changes to the database.
Employee doctype
No
- Chrome

Remove Bureau field from Employee with help of patches.

---

beams/api/api.py

This update ensures that logged-in users can view all employees in their department, bypassing role-based permission restrictions.
Replaced frappe.db.get_list() with frappe.get_all() to bypass permission restrictions.
Employee retrieval logic in get_employees() function.
Backend API behavior for fetching employees within a department.
No.

fix: Bypass Permission Restrictions for Employee Retrieval

---

beams/beams/doctype/bureau_trip_sheet/bureau_trip_sheet.js
beams/beams/doctype/bureau_trip_sheet/bureau_trip_sheet.py

--correct total_hours calculation in Bureau Trip Sheet
--Renamed variable in bureau_trip_sheet.js for consistency.
--Converted total_hours to float in bureau_trip_sheet.py
[Screencast from 27-03-25 10:20:29 AM IST.webm](https://github.com/user-attachments/assets/779a9dda-723b-4ba1-a7fc-930e426e0178)
--Bureau Trip Sheet Doctype
--No. 

refactor: total_hours calculation in Bureau Trip Sheet

---

beams/api/api.py

Added an API to fetch the shift details of an employee for a specific date.
- Uses get_shifts from HRMS to fetch shift details.
- Filters shift assignments based on the provided employee ID and date.
- Implemented get_employee_shift(employee, date) API.
- Accepts employee (ID) and date (YYYY-MM-DD).
- Calls get_shifts with the given parameters.
- Returns the shift details if found, else an empty list.
- API implementation in beams/api/api.py
- Integration with get_shifts from hrms/api/roster.py
No.

feat: Add API to fetch employee shift for a specific date

---

beams/beams/report/detailed_budget_allocation_report/detailed_budget_allocation_report.js
beams/beams/report/detailed_budget_allocation_report/detailed_budget_allocation_report.json
beams/beams/report/detailed_budget_allocation_report/detailed_budget_allocation_report.py

Need to show budget dimensions in the Detailed Budget Allocation Report by user choice
Added a checkbox "Budget Amount Only" which, when unchecked, will show the details of Budget in extra columns
Report
- Detailed Budget Allocation Report
No
- Chrome - Yes
- Opera Mini
- Safari

feat: added option to show budget dimensions

---

beams/beams/doctype/batta_claim/batta_claim.js
beams/beams/doctype/batta_claim/batta_claim.json
beams/beams/doctype/batta_claim/batta_claim.py

- Update Batta Calculation.
- Updated Batta Calculation.
- Set Default Batta Type as Internal.
[Screencast from 27-03-25 03:00:55 PM IST.webm](https://github.com/user-attachments/assets/01744dc7-2760-4e64-abe6-578c9e69d78f)
No.

fix: Update Batta Calculation

---

beams/beams/custom_scripts/voucher_entry/voucher_entry.js

- Update Requested amount in Petty cash Request.
- Set Requested amount as read only in petty cash request.
- Update Requested amount in Petty cash Request.
[Screencast from 28-03-25 12:28:00 PM IST.webm](https://github.com/user-attachments/assets/75358c22-03a2-4edb-bcf8-519f5e3c3ab1)
No.

fix: Update Requested amount in Petty cash request

---

beams/beams/doctype/external_resource_request/external_resource_request.py
beams/beams/doctype/required_manpower_details/required_manpower_details.json
beams/beams/doctype/technical_request/technical_request.py

When a Technical Request is approved, the " Required Manpower Details" table in project should be updated with the "Allocated" field ticked.
When an External Resource Request is approved, the "Required Manpower Details" table in project should be updated with the "Hired" field ticked.
Make the "Allocated" and "Hired" fields read-only.
1.technical_request.py : The update_allocated_field function updates the "Allocated" field in the Project doctype when a Technical Request is approved. It checks for matching designation, required_from, and required_to between the Technical Request’s required_employees and the Project’s required_manpower_details table. If a match is found, it marks the corresponding row as allocated and saves the project. 
2. external_resource_request.py: The …

feat:Automated Allocation for Manpower Details TASK-2025-00506

---

beams/beams/custom_scripts/project/project.js
beams/beams/custom_scripts/project/project.py
beams/hooks.py

- Validate Required To must be greater than Required from fields
- Required From and Required To dates in the Required Manpower Details child table stay within the range of the Expected 
Start Date and Expected End Date of the project.
-  Validated Required To must be greater than Required from fields
- Validated Required From and Required To dates in the Required Manpower Details child table stay within the range of the
Expected  Start Date and Expected End Date

feat:TASK-2025-00530: Date validation for Required Manpower Detail

---

beams/beams/doctype/program_request/program_request.json
beams/beams/doctype/required_manpower_details/required_manpower_details.json
beams/beams/doctype/technical_request/technical_request.js
beams/setup.py

- When coming from a project to a technical request, make the custom fields  change to read-only
- Modify the No of Employees field name in the Required Manpower Details
- Modify fieldtype of dates in Project(Expected start date,Expected end date),Program Request(start date, end date)
- Changed some fields to only when coming from the project to the technical request 
- Modified the No of Employees field name in the Required Manpower Details
- Modified fieldtype of dates in Project,Program Request
No

feat: TASK-2025-00541:  Modified Technical request

---

beams/beams/custom_scripts/asset_movement/asset_movement.py
beams/beams/custom_scripts/project/project.js
beams/beams/custom_scripts/purchase_order/purchase_order.py
beams/beams/doctype/equipment_request/equipment_request.json
beams/beams/doctype/required_items_table/required_items_table.json
beams/beams/doctype/required_items_table/required_items_table.py
beams/setup.py

Modify the existing process of equipment request
Project: Remove existing table in the Required Items field, add a new table with required fields.
Equipment Request: Map Expected Start Date and Expected End Date from project to equipment request.
Project: Previous table in the required items field moved into  Allocated Resource Details field and update the values of the table (issued quantity , acquired quantity)
In project added new table named Required Items Table.
beams/setup.py : In project added new table named 'Required Items Table' and moved position of 'Required Items Detail table'
equipment_request.json: In equipment request change 'required from' , 'required to' field type from datetime into date.
project.js: Mapped Expected Start Date and Expected End Date from project to …

feat: modify the process of equipment request

---

beams/beams/doctype/external_resource_request/external_resource_request.py

In allocated manpower details put hired tick mark only to the exact hired person ,not for everyone with the same designation.
Added condition ensures that only the exact hired person is marked, not everyone with the same designation.
- Chrome

feat: changes in allocated manpower details

---

beams/beams/doctype/revenue_account/revenue_account.json
beams/beams/doctype/revenue_budget/revenue_budget.js
beams/beams/doctype/revenue_budget/revenue_budget.json
beams/beams/doctype/revenue_budget/revenue_budget.py
beams/beams/doctype/revenue_centre/revenue_centre.js
beams/beams/doctype/revenue_centre/revenue_centre.json
beams/beams/doctype/revenue_template/revenue_template.json
beams/beams/doctype/revenue_template_item/revenue_template_item.json

- Customize Revenue Budget,Revenue Template and Revenue Centre doctype.
- Customize Revenue Account and Revenue Template Item child table.
- Apply filter revenue category and company in Revenue template of Revenue Budget.
- Fetch Revenue template in Revenue Budget based on Revenue category and company.
- Apply filter account type = Income Account in account of Revenue Centre doctype.
- Convert revenue amaounts for non INR companies.
- Customized Revenue Budget,Revenue Template and Revenue Centre doctype.
- Customized Revenue Account and Revenue Template Item child table.
- Applied filter revenue category and company in Revenue template of Revenue Budget.
- Fetches Revenue template in Revenue Budget based on Revenue category and company.
- Applied filter account type = Income Account in …

feat: Update Revenue Budget and Revenue Template

---

beams/beams/doctype/shift_swap_request/shift_swap_request.json

- Add fields to fetch shift details in Shift Swap Request
- Added "shift" field to fetch the default shift of the requesting employee.
- Added "swapped_employee_shift" field to fetch the default shift of the swap target.
- Helps in displaying both employees' shifts clearly on the form.
[Screencast from 08-04-25 01:18:15 PM IST.webm](https://github.com/user-attachments/assets/9dace04a-503f-4f62-bce7-90cac3f50d5b)
- Shift Swap Request Doctype
- No

feat:Add fields to fetch default shift of both employees in shift swap request

---

beams/setup.py

--clean up and restructure Job Applicant custom fields
--Removed unused fields: period of stay, residence numbers, and salary-related fields
-- Reorganized section and column breaks for better UI flow
--Updated field insert positions to reflect new layout structure
--Moved 'Address of Employer' and related fields for improved logical grouping
--Job Applicant Doctype
-- No

 TASK-2025-00577:Restructure Job Applicant custom fields

---

beams/beams/custom_scripts/project/project.py
beams/hooks.py

Remove date validation for required manpower details in project
Removed date validation for required manpower details in project .
('Required From' and 'Required To' dates in the Required Manpower Details child table against the project's Expected Start Date and Expected End Date)
Reason: The current situation does not require it, but it may be included in the future if client request it.
- Chrome

fix:remove date validation for required manpower details

---

beams/beams/custom_scripts/project/project.js
beams/beams/custom_scripts/project/project.py

When location not given in Project  fetch from Beams Admin Settings.
The code now checks if Asset Location field in Project has value,if it has fetch assets that matches with the location else fetch location from Beams Admin Settings(Default Asset Location).
Project doctype
Equipment Request doctype.
No
- Chrome

Fix:Default asset location fetched only if not given in Project.

---

beams/beams/doctype/equipment_request/equipment_request.json

- Add Requested By field to Equipment Request with default set to current user
- Introduced a new field requested_by in the Equipment Request DocType.
- The field is a Link to the User doctype.
- It uses the default value __user, so the field automatically captures the current logged-in user.
- Equipment Request
- Chrome
- Opera Mini
- Safari

feat:Add Requested By field to Equipment Request with default set to current user

---

beams/api/api.py

Need an API to get all data in a document unrestricted.
Carried over get_doc api from IDMS
No

feat: get doc api

---

beams/beams/doctype/allocated_manpower_detail/allocated_manpower_detail.json
beams/beams/doctype/external_resource_request/external_resource_request.py
beams/beams/doctype/technical_request/technical_request.py

Change hired and allocated checkbox into select field
Created Status field (select) with options allocated and hired
- Chrome

feat: changed hired and allocated checkbox to select field

---

beams/beams/custom_scripts/project/project.py
beams/hooks.py

Need to: 
- Add validation for assigning same employee to same project
- Disallow creation of Technical Request after employee assignment
- Added validation for assigning same employee to same project
- Disallowed creation of Technical Request after employee assignment
[Screencast from 22-04-25 11:03:04 AM IST.webm](https://github.com/user-attachments/assets/45904ae3-78de-48ce-940b-878f4b199de0)
[Screencast from 22-04-25 11:00:52 AM IST.webm](https://github.com/user-attachments/assets/62564697-de97-4c08-b2a4-1d27104d34d5)
Project Doctype
No

fix:Added validation for assigning same employee to same project and disallowed creation after employee assignment

---

beams/beams/doctype/transportation_request/transportation_request.py
beams/beams/doctype/visitor_log/test_visitor_log.py
beams/beams/doctype/visitor_log/visitor_log.js
beams/beams/doctype/visitor_log/visitor_log.json
beams/beams/doctype/visitor_log/visitor_log.py

TASK-2025-00711:
Prevent data clearing in project when creating additional transportation request
TASK-2025-00713:
Create new dotype Vistor Log
Now able to create multiple transportation request.
Prevented data clearance from allocated vehicle details when new allocation is made
Updated code , updates vehicle allocation in a project document by retrieving existing vehicle details, updating or adding new vehicles from transportation request
TASK-2025-00713: Created new dotype Vistor Log with fields (visitor_name, contact_number, purpose_of_visit, purpose, person_visited, in_time, out_time, visitor_type, pass_issued , identification)
TASK-2025-00713:
- Chrome

feat: TASK-2025-00711 prevent data clearing in project when creating additional transportation request

---

beams/beams/doctype/external_vehicle_details/external_vehicle_details.js
beams/beams/doctype/external_vehicle_details/external_vehicle_details.json
beams/beams/doctype/external_vehicle_details/external_vehicle_details.py
beams/beams/doctype/external_vehicle_details/test_external_vehicle_details.py
beams/beams/doctype/vehicle_hire_request/vehicle_hire_request.py
beams/beams/doctype/vehicle_key_log/test_vehicle_key_log.py
beams/beams/doctype/vehicle_key_log/vehicle_key_log.js
beams/beams/doctype/vehicle_key_log/vehicle_key_log.json
beams/beams/doctype/vehicle_key_log/vehicle_key_log.py

- created External Vehicle Details and Vehicle Key Log doctype
- Generate External Vehicle Details records from the Vehicle Hire Request child table
- created External Vehicle Details and Vehicle Key Log doctype
- Added a new function generate_external_vehicle_details_from_hire_request inside the Vehicle Hire Request DocType.
- This function automatically creates External Vehicle Details records for each vehicle listed in the Vehicle Hire Request's child table (Required Hired Vehicle Detail).
- It copies key information like project, transportation request, required date, vehicle number, vehicle type, and route details (from and to) into a new External Vehicle Details document.
- Set the default returned status to "No" and linked the purpose field dynamically to the project by mentioning …

feat:created External Vehicle Details and Vehicle Key Log doctype

---

beams/beams/doctype/inward_register/inward_register.py
beams/beams/doctype/visitor_log/visitor_log.json

When submitting an Inward Register, Map fields ( Courier Service to Courier Service, Received By to Recipient, Purpose of Visit to Description)
Correct field name (in time & out time) in visitor log.
When submitting an Inward Register, 
created a Courier Log and maped the following fields from the Inward Register to the Courier Log: Courier Service to Courier Service, Received By to Recipient, and Purpose of Visit to Description.
In visitor log doctype corrected  field name of in time and out time (in_time to in time and out_time to out time)
- Chrome

feat: TASK-2025-00764 mapping from inward register to courier log

---

beams/beams/custom_scripts/project/project.py
beams/hooks.py

Need to:
- Add validation for assigning same vehicle to same project.
- Disallow creation of Transportation Request after Vehicle assignment.
- Allow creation of Transportation Request  when new vehicle required details requirement is given.
- Added validation for assigning same vehicle to same project.
- Disallowed creation of Transportation Request after Vehicle assignment.
- Allowed creation of Transportation Request  when new vehicle required details requirement is given.
[Screencast from 25-04-25 11:14:03 AM IST.webm](https://github.com/user-attachments/assets/96849f16-13ad-4830-b05d-6127efb7cc9b)
[Screencast from 25-04-25 11:15:52 AM IST.webm](https://github.com/user-attachments/assets/0c6de7f2-59bd-4cb5-8b2c-f720450496ba)
[Screencast from 25-04-25 11:16:47 AM …

fix:Added validation for assigning same vehicle to same project and disallowed creation after vehicle assignment

---

beams/beams/custom_scripts/project/project.js
beams/beams/doctype/equipment_transaction_log/equipment_transaction_log.js
beams/beams/doctype/equipment_transaction_log/equipment_transaction_log.json
beams/beams/doctype/equipment_transaction_log/equipment_transaction_log.py
beams/beams/doctype/equipment_transaction_log/test_equipment_transaction_log.py
beams/beams/doctype/required_items_detail/required_items_detail.json

TASK-2025-00821 create equipment transaction log doctype with required fields.
Add fields in Required Items detail child table and hide these fields in project.
Created Equipment Transaction Log doctype:
fields: Project, Equipment Request , Equipment Acquiral Request , Location , Expected Start Date , Expected End Date , Bureau , Item Log Details (table)
Added fields in Required Items Detail child table:
fields: Return Date , Returned , Returned Reason , Return (button)
Hided these fields in project (Return Date, Returned & Returned Reason)
- Chrome

feat: TASK-2025-00821 create equipment transaction log

---

beams/beams/doctype/equipment_request/equipment_request.py

Add validation to map only items with acquired_qty > 0 in equipment acquiral request
-  prevent items with no remaining quantity to be mapped.
- Solution: Added a conditional check (if acquired_qty > 0) before appending the item to the required_items child table in the Equipment Acquiral Request mapping function.
[Screencast from 29-04-25 12:57:13 PM IST.webm](https://github.com/user-attachments/assets/902465da-ac98-4f97-abaa-6fd2e74d3eb8)
- Equipment Acquiral Request
- Chrome
- Mozilla Firefox - YES
- Opera Mini
- Safari

feat: TASK-2025-00790 :Add validation to map only items with acquired_qty > 0 in equipment acquiral request

---

beams/beams/doctype/asset_auditing/asset_auditing.json
beams/beams/doctype/employee_travel_request/employee_travel_request.py

- handle datetime object type for start_date and end_date in travel days calculation
- add description to Asset Photos table in Asset Auditing Doctype
- Previously, the `total_days_calculate` method assumed `start_date` and `end_date` were strings and used `datetime.strptime`, which caused a `TypeError` when these fields were already `datetime` objects.
- This fix ensures type checking before parsing—if the fields are already `datetime`, they are used as-is; otherwise, they are parsed from strings. This prevents runtime errors during validation or submission of the Employee Travel Request document.
- Added a field description to the "Asset Photos" table in the Asset Auditing Doctype to inform users that a minimum of 3 photos must be uploaded. This enhances clarity and helps enforce data …

fix:TASK-2025-00817: handle datetime object type for start_date and end_date in travel days calculation

---

beams/beams/doctype/patrol_log_template/patrol_log_template.js
beams/beams/doctype/patrol_log_template/patrol_log_template.json
beams/beams/doctype/patrol_log_template/patrol_log_template.py
beams/beams/doctype/patrol_log_template/test_patrol_log_template.py
beams/beams/doctype/security_patrol_log/security_patrol_log.js
beams/beams/doctype/security_patrol_log/security_patrol_log.json

TASK-2025-00819 , create patrol log template with required fields 
(When a Patrol Template is selected in the Security Patrol Log form, fetches the corresponding Patrol Log Template record)
Created Patrol log template with  fields Template name and patrol log , 
Added field named patrol log template in security patrol log doctype .
( When a Patrol Template is selected in the Security Patrol Log form, fetches the corresponding Patrol Log Template record, copies its child table entries into the Security Patrol Log's patrol_log child table, and refreshes the field to display the updated entries.)
List out the areas affected by your code changes.(security patrol log)
- Chrome

feat: TASK-2025-00819 create patrol log template

---

beams/beams/doctype/inward_register/inward_register.json
beams/beams/doctype/inward_register/inward_register.py
beams/beams/doctype/visit_request/test_visit_request.py
beams/beams/doctype/visit_request/visit_request.js
beams/beams/doctype/visit_request/visit_request.json
beams/beams/doctype/visit_request/visit_request.py

Created a new Visit Request form to manage approval  for  Ex Employees.
Fields include:
Visitor Type
Contact Number
Purpose of Visit
Person to Meet
Request Date
Visit Date
Approval Status (Pending, Approved, Rejected)
Approver (Employee)
Visitor Name and Visit Date are mandatory.
The system will check the Inward Register to verify if an entry exists with the same visitor name and visit date.
If no matching record is found in the Inward Register, an error will be thrown.
Visit Request doctype
Inward Register doctype
No
- Chrome

feat:Created doctype Visit Request

---

beams/beams/custom_scripts/asset_movement/asset_movement.py
beams/beams/doctype/equipment_request/equipment_request.py

Map items with count > 0 in Asset Movement and log each item in a separate Asset Reservation
**- Asset Movement Mapping Enhancement**
- Updated the map_asset_movement function to skip items where the count is missing or <= 0.
- Ensures only valid asset quantities are considered for asset selection and movement.
- Replaced frappe.throw with return to avoid errors when reference_name is missing in Asset Movement, ensuring smoother processing.
**- Asset Reservation Log Logic Refactor**
- Instead of aggregating all required items into a single Asset Reservation Log, each required item creates an individual log entry.
-  added a check to ensure the item exists before creating a log to prevent unexpected errors.
**- Improved Error Handling in update_issued_quantity Hook**
- Instead of throwing …

feat:Map items with count > 0 in Asset Movement and log each item in a separate Asset Reservation

---

beams/beams/custom_scripts/project/project.js
beams/beams/custom_scripts/project/project.py
beams/beams/doctype/equipment_transaction_log/equipment_transaction_log.json
beams/beams/doctype/required_items_detail/required_items_detail.json
beams/hooks.py

TASK-2025-00826:
Update the Equipment Transaction Log doctype whenever there is any update in the Allocated items Detail field in the Project.
In project (Allocated Item Details field) added a popup when the Return button is clicked, allowing the user to enter the Returned Date and Return Reason and returned count.
Updated the corresponding values in the Equipment Transaction Log child table with the data from the popup.
TASK-2025-00857:
In Equipment Transaction Log display the count of returned equipment and mention that count in returned reason.
When the project is completed or cancelled, updated the 'Returned Count' and 'Returned Reason' fields accordingly.
- Chrome
- …

feat: TASK-2025-00826 Maintain Equipment transaction log , TASK-2025-00857

---

beams/setup.py

Need to fix the rearrange the fields in the job requisition dotype
need to fix the mandatory error of department in the job requisition doctype
fixed the arrangement fields in job requisition  re order the fields in the job requisition doctype in via setup.py 
fixed the mandatory error in department and designation in job requisition doctype and designation
change the department field in to not hidden in the job requisition doctype
removed unnecessary code fro the setup.py
[Screencast from 03-05-25 03:28:03 PM IST.webm](https://github.com/user-attachments/assets/ad7a0331-b7a3-440b-9a7d-0a490f8f1ead)
job requisition doctype
No. 

TASK-2025-00867: Need to Rearrange the fields in the job requisition doctype

---

beams/beams/doctype/vehicle_incident_record/vehicle_incident_record.json
beams/beams/doctype/vehicle_incident_record/vehicle_incident_record.py

Added server-side validation logic in the Vehicle Incident Record DocType to ensure that:
-    Added fields Trip Start Date and Trip End Date 
-  Fetch values in these fields from Trip Sheet.
-     The Offense Date and Time is not set in the future.
-     The Offense Date falls between the Trip Start Date and Trip End Date.
-Fetched values fromfor start and End dates when a Trip Sheet is selected.
Converted offense_date_and_time to a datetime object using frappe.utils.get_datetime() before performing comparisons.
Validated that:
-         Offense Date and Time is not in the future.
-         Offense Date falls within the Trip Start Date and Trip End Date.
Vehicle Incident Record doctype.
No
- Chrome

feat:Added validation for offense dates

---

beams/beams/doctype/trip_details/trip_details.json
beams/beams/doctype/trip_details/trip_details.py
beams/beams/doctype/trip_sheet/trip_sheet.json

Modified the flow of Trip Sheet
**Created a new child DocType named Trip Details with fields:**
-         departure (Data), destination (Data),  time (Time Duration), remark (Small Text)
-         Linked this child table to the Trip Sheet DocType using a Table field (trip_details), enabling detailed tracking of multiple legs or events within a trip.
**Renamed/Updated Fields for Clarity:**
-     Changed label of clean_vehicle checkbox from "Clean Vehicle" to "Is Cleaned" for consistency with naming conventions.
-     Updated fuel_consumed field label to "Fuel Consumed (Ltr)" for unit clarity.
-     Updated mileage field label to "Mileage (Km/Ltr)" to make the measurement unit explicit.
**Removed Redundant Fields:**
-     Removed departure_location and destination_location Link fields …

feat: TASK-2025-00883: Modified the flow of Trip Sheet

---

beams/beams/doctype/employee_travel_request/employee_travel_request.js
beams/beams/doctype/employee_travel_request/employee_travel_request.py

Fix issue in calculating Total Days in Employee Travel Request.
Removed Duplicate code and used frm.call to call the back-end method from client side.
Employee Travel Request.
No
- Chrome

fix:Fixed issue in calculating Total Days in Employee Travel Request

---

beams/beams/doctype/employee_travel_request/employee_travel_request.js

Implemented a client-side filter to exclude the employee selected in the requested_by field from the options available in the travellers multi-select field in the Employee Travel Request form.
To ensure that the person requesting the travel is not accidentally added as a traveller, maintaining data consistency and avoiding redundancy.
Added a client script to dynamically filter out the selected requested_by employee from the travellers field.
Triggered the filter on:
-     onload
-     requested_by field change
When a user selects or changes the requested_by field the script filters out that employee from the list of travellers.
Employee Travel Request
No
- Chrome

TASK-2025-00894:Applied filter for travellers multiselect field

---

beams/beams/doctype/trip_details/trip_details.json
beams/beams/doctype/trip_sheet/trip_sheet.js
beams/beams/doctype/trip_sheet/trip_sheet.py

- auto-set driver from logged-in user & calculate trip hours
- ' **Driver Auto-Assignmen**t:
- ' On Trip Sheet load, the driver field is auto-populated by tracing:
- ' current user → corresponding Employee → matching Driver.
- ' **Trip Hours Calculation**:
- ' Added from_time, to_time, hrs, and distance_traveled fields in Trip Details.
- ' Total hours (hrs) are calculated based on the time difference.
- ' **Validation**:
- ' Ensures to_time is after from_time. If not, throws a validation error.
- ' **Client-Side Updates**:
- ' Triggers calculate_hours when from_time or to_time changes
- ' in the Trip Details child table.
[Screencast from 06-05-25 12:31:46 PM IST.webm](https://github.com/user-attachments/assets/feecddd6-6b95-4f89-aeec-ed436b41fb1c)
- Tripsheet
Mention Yes or No. If Yes, …

feat: TASK-2025-00896: auto-set driver from logged-in user & calculate trip hours

---

beams/beams/doctype/fuel_card_log/fuel_card_log.js
beams/beams/doctype/fuel_card_log/fuel_card_log.json
beams/beams/doctype/ownered_by/ownered_by.json
beams/beams/doctype/ownered_by/ownered_by.py

- Rename child table Owered By to Ownered By in Fuel Card Log
- Renamed fieldname from `owered_by` to `ownered_by` in the Fuel Card Log DocType JSON.
- Updated JS file (fuel_card_log.js) to reference the correct field name `ownered_by`.
- Changed button labels:
• "Set Current Ownership" → "Ownership Transaction"
• "Set Recharge History" → "Recharge"
- Grouped both actions under the "Add" dropdown (matching standard UI dropdown style).
- Removed obsolete DocType files for `Owered By`:
• __init__.py
• owered_by.json
• owered_by.py
- Fuel Card Log
- Chrome
- Mozilla Firefox- YES
- Opera Mini
- Safari

feat: TASK-2025-00897: Rename child table Owered By to Ownered By in Fuel Card Log

---

beams/beams/doctype/employee_travel_request/employee_travel_request.js
beams/beams/doctype/trip_sheet/trip_sheet.js
beams/beams/doctype/trip_sheet/trip_sheet.py
beams/beams/doctype/vehicle_allocation/vehicle_allocation.json

1. Vehicle Allocation doctype: changed options of driver field in to 'driver'
2. Employee travel request: removed filter of driver by designation
3. Employee travel request: corrected  number of employee's count in ' number of travellers field'
4. Trip sheet: Applied a filter in the Travel Requests field to list only those Employee Travel Requests where the driver in the Vehicle Allocation child table matches the driver in the current Trip Sheet
List out the areas affected by your code changes.(Employee travel request, trip sheet)
- Chrome

feat: TASK-2025-00881 : filter employee travel request by driver in trip sheet

---

beams/beams/doctype/employee_travel_request/employee_travel_request.js

Skip traveller and mode of travel filters for Admin role in Employee Travel Request
- This update enhances the user experience for admin by conditionally disabling filters in the Employee Travel Request form based on user role:
-     apply_travellers_filter(frm) is now skipped when the logged-in user has the "Admin" role. 
-     set_mode_of_travel_filter(frm) is also bypassed for Admins, allowing them to view all mode_of_travel options without restriction.
- This ensures that policy-based filters do not constrain Admin users, while regular users continue to receive filtered options based on the selected batta_policy.
[Screencast from 07-05-25 02:29:31 PM IST.webm](https://github.com/user-attachments/assets/3f380a0e-b76f-438b-84a9-cece4af1dcc8)
- Employee Travel Request
Mention Yes or No. …

feat:TASK-2025-00904: Bypass filters for Admin in Employee Travel Request

---

beams/beams/doctype/employee_travel_request/employee_travel_request.js
beams/beams/doctype/employee_travel_request/employee_travel_request.json
beams/beams/doctype/traveller/traveller.json
beams/beams/doctype/trip_sheet/trip_sheet.js

To allow selection of other employees (besides the one set in requested_by)
- Automatically filter out the employee set as requested_by from being selected again in the travellers field (which uses the Table MultiSelect fieldtype).
- Allow all other employees to be selectable.
**1. Refactored filter logic:**
-     Moved the call to apply_travellers_filter(frm) outside the admin role check and directly into the requested_by handler, ensuring the filter is always applied regardless of user role.
- Allow users to see all employees (beyond their user permission restrictions) when selecting from the travellers field.
- Moved the 'travel_requests' set_query function under the refresh event to avoid redundancy.
- Ensured driver-specific filtering for travel requests is correctly handled. …

feat: TASK-2025-00918: Exclude requested_by from travellers and allow all employees selection

---

beams/beams/doctype/employee_travel_request/employee_travel_request.js

Prevent duplicate driver and vehicle selection in Vehicle Allocation child table.
- Dynamic filtering of `driver` and `vehicle` fields to exclude already selected values in other rows.
- Filters applied in real-time when:
- A new row is added
- A value is selected/changed in an existing row
- Logic only activates when:
- `is_vehicle_required` is checked
- `workflow_state` is "Approved by HOD"
Employee Travel Request.
No
- Chrome

feat: prevent duplicate driver and vehicle selection in Vehicle Allocation child table.

---

beams/beams/doctype/employee_travel_request/employee_travel_request.js

TASK-2025-00908: fix issue in employee travel request
Fix the issue of showing number of travellers field with value 0 when 'is unplanned' ticked and 'end date' entered.
1. Resolved the issue of showing ' number of travellers ' field with value 0 when 'is unplanned' ticked and 'end date' entered. 
2. Set number of travellers default value as 1
- Chrome

fix: TASK-2025-00908: fix issue in employee travel request

---

beams/beams/doctype/employee_travel_request/employee_travel_request.js
beams/beams/doctype/employee_travel_request/employee_travel_request.json
beams/beams/doctype/employee_travel_request/employee_travel_request.py
beams/setup.py

Need to: 
- Create Expense Claim connection from Employee Travel Request doctype to Expense Claim doctype.
- Remove the workflow condition , because of  Expense Claim button is visible if trip is unplanned
- Created Expense Claim connection from Employee Travel Request doctype to Expense Claim doctype .
- Removed the workflow condition , because of  Expense Claim button is visible if trip is unplanned.
[Screencast from 07-05-25 04:38:47 PM IST.webm](https://github.com/user-attachments/assets/4c6788c8-cf87-4412-8ff0-f4eb7b6ae282)
Employee Travel Request doctype and Expense Claim doctype
No

feat:Created Expense Claim connection from Employee Travel Request doctype to Expense Claim doctype

---

beams/beams/doctype/trip_sheet/trip_sheet.js
beams/beams/doctype/trip_sheet/trip_sheet.py
beams/beams/doctype/vehicle_incident_record/vehicle_incident_record.json

- Validate trip times and odometer fields; update driver_name field in Vehicle Incident Record
**Trip Sheet JS (trip_sheet.js):**
- Added validation to ensure 'from_time' and 'to_time' in Trip Details are within the trip's starting and ending datetime range.
- Invalid entries are reset with a user message.
- Clears 'hrs' field if time fields are cleared.
- Triggers hour recalculation after changes.
**Trip Sheet Python (trip_sheet.py):**
- Skips odometer reading validation if 'initial_odometer_reading' or 'final_odometer_reading' is missing.
**Vehicle Incident Record (vehicle_incident_record.json):**
- Removed 'reqd: 1' from 'driver_name', making it optional but still read-only.
- Allows saving record without requiring driver name.
- Trip Sheet
- Vehicle Incident Record
- Chrome
- Mozilla …

feat:Validate trip times and odometer fields

---

beams/beams/custom_scripts/appraisal/appraisal.js
beams/beams/custom_scripts/appraisal/appraisal.py
beams/setup.py

--add confirmation dialog before sending notification and assigning tasks
-- removed legacy task assignment logic and replaced it with email notification for assessment officer review
--Add confirmation dialog before sending notification and assigning tasks in Appraisal
--Removed assessment officers table
--add assessment officer filed  employee Doctype
[Screencast from 08-05-25 01:20:42 PM IST.webm](https://github.com/user-attachments/assets/d2da66ea-f9ec-4e49-a6c2-d11ff20a9c88)
--Appraisal Doctype
--No

 TASK-2025-00907:Send appraisal review notification to assessment officer

---

beams/beams/doctype/trip_sheet/trip_sheet.js
beams/beams/doctype/trip_sheet/trip_sheet.py

Need to: Correct the issue for odometer value reading in Trip Sheet when vehicle is selected
Ensures  the odometer reading is correctly set when vehicle is selected before saving the Trip Sheet.
[Screencast from 13-05-25 11:49:46 AM IST.webm](https://github.com/user-attachments/assets/7bf35644-2955-44db-aa3b-691d85b31deb)
Trip Sheet doctype
No. 

fix:Corrected odometer value reading in Trip Sheet when vehicle is selected

---

beams/beams/doctype/outward_pass/outward_pass.json
beams/beams/workspace/security/security.json

- Created workspace for security
- Created workspace for security
- Field: Employee in Charge
-     Removed the "unique": 1 constraint.
-     Field is still required ("reqd": 1) and of type Link to the Employee DocType.
- workspace
- Outer pass
- Chrome
- Mozilla Firefox -Yes
- Opera Mini
- Safari

feat:Created workspace for security

---

beams/beams/doctype/bureau_trip_sheet/bureau_trip_sheet.js

--Fix batta calculation timing by increasing setTimeout delay
--Fixed the  batta calculation delay by increasing setTimeout from 30ms to 200ms to ensure proper data loading
[Screencast from 14-05-25 11:41:06 AM IST.webm](https://github.com/user-attachments/assets/de54ec61-53ba-4d56-9c0d-198e65c06e09)
--No.

    TASK-2025-00989:Fix batta calculation timing by increasing setTimeout delay

---

beams/beams/doctype/patrol_log_detail/patrol_log_detail.json
beams/beams/doctype/security_patrol_log/security_patrol_log.js
beams/setup.py

- auto-set employee for security role and add checked field to patrol log
- **Auto-set Employee Field:**
- When a user with the "Security" role logs in and opens the Security Patrol Log, the employee field is now automatically set based on the logged-in user's linked Employee record.
- **Clear patrol log on template removal:**
-  If the patrol_template field is cleared, the patrol_log child table will now be cleared as well, ensuring no outdated entries remain.
- **New Field in Patrol Log Detail:**
- A new "Checked" (Check field) has been added to the Patrol Log Detail child table, and it is shown in the list view .
- **Role Update:**
- Added the "Security" role to the get_beams_roles() list to ensure role-based access.
[Screencast from 14-05-25 01:09:33 PM …

feat:auto-set employee for security role and add checked field to patrol log

---

beams/beams/doctype/guest_appointment/guest_appointment.js
beams/beams/doctype/guest_appointment/guest_appointment.py

TASK-2025-01003 : When guest appointment is approved then show button to create Event
- Rearranged ' Event ' button in the Guest Appointment appears only when the guest appointment is approved.
- Mapped from guest appointment to Inward register : Appointment Date to Visit Date, and Visitor Type as Guest
- Chrome

feat: TASK-2025-01003 show button to create event when guest appointment approved

---

beams/beams/custom_scripts/material_request/material_request.py

TASK-2025-01018 send notification to admin upon creation of material request
Added admin to the recipients in material request email notification
- Chrome

feat: TASK-2025-01018 send notification to admin upon creation of material request

---

beams/beams/doctype/inward_register/inward_register.js
beams/beams/doctype/inward_register/inward_register.json

TASK-2025-00994
1. Added mandatory to 'Received by' field in inward register 
2. Added search fields (Visitor type, visitor name and visit date) in inward register
3. Added a button to create 'courier log' in inward register
TASK-2025-00997
1. Hided visitor pass and courier log button in inward register for security
TASK-2025-01004
1. Mapped details from Inward Register to Courier log
- Visitor Name to sender, 
- Received By to Recipient, 
- Courier Service to Courier Service, 
- Visit Date to Date, 
- Purpose of Visit to Description
List out the areas affected by your code changes.(Inward Register, Courier Log)
- Chrome

feat: TASK-2025-00994 enable creating courier log from inward register

---

beams/beams/doctype/batta_claim/batta_claim.js

In batta claim now the date can be edited . after editing the total betta is fetching
In batta claim when we created a claim it cannot be edited . if it is edited total batta will turn to zero. now it is fixed
-New feature
-No
- Chrome

Fix Batta Claim date editing problem

---

beams/beams/doctype/attachment_detail/attachment_detail.json
beams/beams/doctype/attachment_detail/attachment_detail.py
beams/beams/doctype/employee_travel_request/employee_travel_request.js
beams/beams/doctype/employee_travel_request/employee_travel_request.json
beams/beams/doctype/ticket_detail/ticket_detail.json
beams/beams/doctype/ticket_detail/ticket_detail.py

Need to: Create Attachments Table in Employee Travel Request doctype when the employee travel request is unplanned and workflow state is "Approved by HOD"
Created Attachments Table in Employee Travel Request doctype  to manage Ticket and Accommodation Arrangements with the fields Attach , Document name and Remarks.
Employee Travel Request doctype
No. 

feat:Created Attachments Table in Employee Travel Request doctype

---

beams/beams/custom_scripts/vehicle/vehicle.js
beams/hooks.py

- Add custom button in Vehicle form to create new Vehicle Safety Inspection
- Added a custom button to the Vehicle form that allows users to create a new Vehicle Safety Inspection document.
- The button appears only when viewing an existing Vehicle (not on new unsaved forms) and automatically links the new inspection to the current Vehicle.
- Vehicle Safety Inspection
- Vehicle 
- Chrome
- Opera Mini
- Safari

feat:add button to create Vehicle Safety Inspection

---

beams/beams/doctype/beams_admin_settings/beams_admin_settings.json
beams/beams/doctype/vehicle_incident_record/vehicle_incident_record.py

Auto-create Journal Entry for employee-payable vehicle incidents
- Added 'default employee payable account' to BEAMS Admin Settings
- Implemented `create_journal_entry_for_payable_items` in Vehicle Incident Record
- Creates Journal Entry when `is_employee_payable` is checked
- Links created Journal Entry to child row
- Displays success message on creation
- Triggered JE creation on `on_update` if workflow_state == 'Approved'
[Screencast from 17-05-25 02:47:46 PM IST.webm](https://github.com/user-attachments/assets/6a03b10a-1030-475b-80c2-d90cd4360fe1)
- JE
- Chrome
- Mozilla Firefox - Yes 
- Opera Mini
- Safari

feat:Auto-create Journal Entry for employee-payable vehicle incident

---

beams/beams/doctype/employee_travel_request/employee_travel_request.py
beams/beams/doctype/trip_sheet/trip_sheet.py
beams/beams/doctype/vehicle_incident_record/vehicle_incident_record.py

feat: Auto-create Trip Sheets on ETR approval and validate odometer on Trip Sheet submit
- Moved final odometer validation logic from `validate` to `on_submit` in Trip Sheet to enforce check only on submission.
Checked  if any Trip Sheet exists already linked to this Employee Travel Request.
If such a Trip Sheet exists, then:
For each vehicle in the Employee Travel Request:
If that specific vehicle doesn’t already have a Trip Sheet linked to this Employee Travel Request → Create a new Trip Sheet for it.
If no Trip Sheet at all exists for this Employee Travel Request:
Then, create a Trip Sheet for every vehicle in the request.
[Screencast from 19-05-25 01:37:29 PM IST.webm](https://github.com/user-attachments/assets/fea3c8e1-9f4e-49d8-beaa-4a54301e76aa)
- tripsheet
Mention Yes or No. If …

feat:Auto-create Trip Sheets on ETR approval 

---

beams/beams/custom_scripts/hd_ticket/hd_ticket.js

--hide fields for non-Agent users on HD Ticket load
--When the form loads (onload), the function checks if the user has the role Agent.
--If the user is not an Agent, it hides all fields except:
subject
raised_by
description
[Screencast from 17-05-25 11:25:49 PM IST.webm](https://github.com/user-attachments/assets/83ce1414-68ef-43c2-97f4-58e8dc96378a)
--No. 

    TASK-2025-01036:hide fields for non-Agent users on HD Ticket load

---

beams/beams/doctype/employee_travel_request/employee_travel_request.js

TASK-2025-01061 allow only the admin to see the journal entry button
Restricted the visibility of the Journal Entry button to the admin, it should not be visible to other users
Admin
HOD
- Chrome

feat: TASK-2025-01061 allow only the admin to see the journal entry button

---

beams/beams/custom_scripts/material_request/material_request.js
beams/hooks.py
beams/setup.py

TASK-2025-01064 mark requested person id in material request
- Added a field named ' Requested By' in material request
- Automatically sets the "requested_by" field in the Material Request form to the current user's associated Employee record when the form loads
- Chrome

feat: TASK-2025-01064 mark requested person id in material request

---

beams/beams/doctype/employee_travel_request/employee_travel_request.js
beams/beams/doctype/employee_travel_request/employee_travel_request.json
beams/setup.py

TASK-2025-01065 Add connections in Employee Travel Request for journal entry, trip sheet.
- Added a field named 'employee_travel_request ' in journal entry and mapped value to this field
- Changed is_vehicle_required label to vehicle_required in Employee Travel Request
- Added connections in Employee Travel Request for journal entry, trip sheet
- Chrome
- Opera Mini
- Safari

feat: TASK-2025-01065 add connections in employee travel request

---

beams/beams/doctype/trip_sheet/trip_sheet.js
beams/beams/doctype/trip_sheet/trip_sheet.json
beams/beams/doctype/trip_sheet/trip_sheet.py
beams/beams/doctype/vehicle_incident_record/vehicle_incident_record.json
beams/beams/doctype/vehicle_incident_record/vehicle_incident_record.py

Use Date instead of Datetime for trip and incident date validations
- Changed 'starting_date_and_time' and 'ending_date_and_time' to Date fields in Trip Sheet
- Changed 'trip_start_date' and 'trip_end_date' to Date fields in Vehicle Incident Record
- Updated related validations to compare only dates
- Replaced frappe.set_route with frappe.new_doc since saving is not required during mapping.
- Simplified vehicle incident creation logic to return initial values without inserting
[Screencast from 16-05-25 03:57:28 PM IST.webm](https://github.com/user-attachments/assets/ad79d429-1c6c-4c30-b2c6-e7428a3cd605)
- Tripsheet
- Vehicle Incident Record
- Chrome
- Mozilla Firefox - YES
- Opera Mini
- Safari

feat:Use Date instead of Datetime for trip and incident date validations

---

beams/beams/custom_scripts/hd_ticket/hd_ticket.js
beams/beams/custom_scripts/hd_ticket/hd_ticket.py
beams/hooks.py
beams/setup.py

Assign tickets to only Active Agents.
When a ticket is created assign ticket to only Agents who are Active.
HD Ticket doctype
No
- Chrome

TASK-2025-01006:Assign ticket to active Agents

---

beams/beams/doctype/trip_sheet/trip_sheet.js

Need to:Fix the odometer issue in trip sheet doctype ie, two vehicle functions defined inside the js file so fetching of initial odometer is not working 
Fixed the odometer issue in trip sheet doctype ie,  Replaced existing vehicle field function in Trip Sheet to ensure correct fetching of initial odometer
[Screencast from 21-05-25 12:29:47 PM IST.webm](https://github.com/user-attachments/assets/c7877550-d596-4d1f-93e2-2620408fd364)
Trip sheet doctype
No.

fix:fixed the odometer issue in trip sheet doctype

---

beams/beams/doctype/employee_travel_request/employee_travel_request.py
beams/beams/doctype/trip_sheet/trip_sheet.json

TASK-2025-01078 for automatically created trip sheet bring safety inspection template
Rearranged position of field named 'remarks' in trip sheet
Added a feature to bring the safety inspection template of the vehicle into the automatically created trip sheet.
- Chrome
- Opera Mini
- Safari

feat: TASK-2025-01078 for automatically created trip sheet bring safety insepection template

---

beams/beams/doctype/vehicle_incident_record/vehicle_incident_record.json

Need to: Add vehicle field in vehicle incident record doctype and when create vehicle incident record doctype  from trip sheet doctype then map  the vehicle name of that trip sheet
Added vehicle field in vehicle incident record doctype and when create vehicle incident record doctype  from trip sheet doctype then mapped  the vehicle name of that trip sheet
[Screencast from 22-05-25 11:30:17 AM IST.webm](https://github.com/user-attachments/assets/4e9c3de4-0cca-4d2e-974c-ae4fb762a75a)
Vehicle incident record doctype
No. 

feat:Added vehicle field in vehicle incident record doctye

---

beams/beams/doctype/asset_auditing/asset_auditing.js
beams/beams/doctype/asset_auditing/asset_auditing.json

- Rearrange ' Has Damage ' field position.
- Added field named ' Employee name ', ' Scan QR Code '
- When a QR code is scanned, it fills the Asset field with the corresponding Asset ID
List out the areas affected by your code changes.(Asset auditing)
- Chrome
- Opera Mini
- Safari

TASK-2025-01097 add ability to scan qrcode for asset in asset auditing

---

beams/beams/doctype/employee_travel_request/employee_travel_request.js
beams/beams/doctype/employee_travel_request/employee_travel_request.py

TASK-2025-01109 : correct the popup table with proper fields and journal entry creation
Added and removed fields in the popup table
Added field named Mode of Payment in the popup
Edited creating journal entry in the draft state based on the details in the popup 
Resolved issues in the journal entry 
List out the areas affected by your code changes.( Journal entry)
- Chrome

TASK-2025-01109 : correction in journel entry

---

beams/beams/doctype/employee_travel_request/employee_travel_request.py
beams/beams/doctype/employee_travel_request/expense_claim.html

Show total claimed and sanctioned amount in expense claim summary
- Added logic in Python to calculate total claimed amount and total sanctioned amount
- Updated HTML template to display both totals in the final row
- Added fallback message if no expense claims are found
- removed unused variable {% set has_expenses = True %}
Employee Travel Request
- Chrome
- Opera Mini
- Safari

feat: TASK-2025-01128: add total claimed and sanctioned amount to expense summary

---

beams/beams/custom_scripts/driver_dashboard/driver_dashboard.py
beams/beams/doctype/trip_sheet/trip_sheet.json
beams/hooks.py

Added connection in Trip Sheet doctype and Driver doctype for Vehicle Incident Record doctype
Trip Sheet doctype
Driver doctype
No. 

TASK-2025-01147:Added connections in Trip Sheet doctype and Driver doctype

---

beams/beams/doctype/employee_travel_request/employee_travel_request.js
beams/beams/doctype/employee_travel_request/employee_travel_request.json
beams/beams/doctype/employee_travel_request/employee_travel_request.py
beams/beams/doctype/journal_entry_expenses/journal_entry_expenses.json
beams/beams/doctype/journal_entry_expenses/journal_entry_expenses.py
beams/setup.py

TASK-2025-01105 : create a table to store journal entry details in employee travel  request
- Edited employee travel request field in journal entry 
- Changed posting date value from expense date in to current date in journal entry
- Created new doctype : Journal Entry Expenses (child table)
- Added a field (Journal Entry Expenses Table) for child table in Employee Travel Request
- Journal entries created from an Employee Travel Request were added as new rows in the Journal Entry Expenses Table
List out the areas affected by your code changes. (employee travel request)
- Chrome

TASK-2025-01105 : create a table to store journal entry details in employee travel  request

---

beams/hooks.py

- ensure QR code is generated for all assets created from Purchase Receipt
- Fixed QR code generation issue for multiple assets from Purchase Receipt by moving generate_asset_qr from after_insert to on_submit. This ensures QR codes are consistently generated for all assets upon submission, regardless of quantity.
Asset
- Chrome
- Opera Mini
- Safari

feat: TASK-2025-01156: ensure QR code is generated for all assets created from Purchase Receipt

---

beams/hooks.py

Need to: Fix the issue in validation for assigning same employee to same project
Fixed the issue in validation for assigning same employee to same project
Technical Request doctype
No.

fix:Fixed the issue in validation for assigning same employee to same project

---

beams/beams/doctype/beams_admin_settings/beams_admin_settings.json
beams/beams/doctype/makeup_consumption_entry/makeup_consumption_entry.js
beams/beams/doctype/required_items_detail/required_items_detail.json
beams/setup.py

Apply filter item_code in makeup consumption entry
Remove the Asset Movement button from the Required Items Detail child table
- Added field named '  Is Makeup Item' in Item
- Added field named ' Item Group' in BEAMS admin settings
- Makeup Consumption Entry : Applied Filter on the item_code field to list only items from the selected item group with is_makeup_item checked
- Removed the Asset Movement button from the Required Items Detail child table because it is not used for asset movement; we are using another button for that
- Chrome
- Opera Mini
- Safari

TASK-2025-01185 : filter item_code in makeup consumption entry

---

beams/beams/doctype/asset_transfer_request/asset_transfer_request.py

Need to:Create Stock Entry when  workflow state is Returned in  Asset Transfer Request doctype
Created Stock Entry when  workflow state is Returned in  Asset Transfer Request doctype
[Screencast from 04-06-25 03:25:30 PM IST.webm](https://github.com/user-attachments/assets/f573e49d-153a-47dc-befd-1ed2e555c8b2)
[Screencast from 04-06-25 03:35:48 PM IST.webm](https://github.com/user-attachments/assets/9c4564c4-84db-4517-985b-2f14dacdf1a0)
[Screencast from 04-06-25 03:38:49 PM IST.webm](https://github.com/user-attachments/assets/032b83f2-45da-4062-a9ea-e6a8d7b33e9b)
Asset Transfer Request doctype
No. 

TASK-2025-01200:Created Stock Entry when  workflow state is Returned in  Asset Transfer Request doctype

---

beams/beams/doctype/asset_bundle/asset_bundle.py

regenerate asset bundle QR code on every save
Moved QR code generation from after insert to before save to ensure updated assets, bundles, or stock items are 
reflected in the QR. Prevents stale QR data when modifying existing Asset Bundles.
Asset Bundle
- Chrome
- Opera Mini
- Safari

feat: TASK-2025-01205: regenerate asset bundle QR code on every save

---

beams/beams/custom_scripts/asset/asset.js
beams/beams/custom_scripts/asset_movement/asset_movement.js
beams/beams/doctype/container/container.json
beams/beams/doctype/row/row.json
beams/beams/doctype/shelf/shelf.json
beams/hooks.py

TASK-2025-01218 :
Added fields in Shelf , Row , and Bin doctypes.
In the Asset doctype and in the child table of the Asset Movement doctype, filters are applied so that the Shelf field shows only shelves linked to the selected Room, the Row field shows only rows under the selected Shelf, and the Bin field shows only bins under the selected Row
TASK-2025-01219:
Dynamically hides or shows the Room, Shelf, Row, and Bin fields in the Asset Movement Item child table based on the selected purpose in the Asset Movement. If purpose = "Issue", those fields are hidden; otherwise, they remain visible.
TASK-2025-01218
[Screencast from 05-06-25 01:20:12 PM IST.webm](https://github.com/user-attachments/assets/444f7d01-a95c-4877-8219-0423376b27cf)
[Screencast from 05-06-25 01:23:17 PM …

TASK-2025-01218 : Add filter for shelf,row and bin in assets and asset movement

---

beams/beams/doctype/bureau_trip_details/bureau_trip_details.json
beams/beams/doctype/bureau_trip_details/bureau_trip_details.py
beams/beams/doctype/bureau_trip_sheet/bureau_trip_sheet.js
beams/beams/doctype/bureau_trip_sheet/bureau_trip_sheet.json
beams/beams/doctype/bureau_trip_sheet/bureau_trip_sheet.py

- create child table Bureau Trip Details.
- Update bureau trip sheet calculation.
- Created child table Bureau Trip Details and added this in Bureau Trip Sheet.
- Fixed issues in bureau trip sheet calculation.
No.

feat: Create child table Bureau Trip Details for Bureau Trip Sheet
